---
title: "Justin talk"
author: "grady"
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tribalism

- the belief system that perpetuates violence.
- part of culture, history.  
- limitations: cannot solve everything.  Some practical aspects can be improved.
- contact does not work completely.
- not all disinformation: the groups have been attacking each other.
- team and winning (psychological payoff)
- being realistic: these interventions do not replace all the history.
    - length of conflict.  Farmer-pastoralists have fairly recent conflict.
- what if the conflict is over morality?  
- Land resource has high potential to be corrected.  Working together is good for everybody.  The selfishness/violence of the past resists that universally better outcome.  In reality, everyone is better off sharing.
    - it's a prisoner's dilemma, not a game where mutually defecting is good.
- cooperation is a group property -- emergeny property of the group.
- it pays to defect: what is the defection rate?  Must look at groups.