---
title: "Promoting Peace Amidst Group Conflict: An Intergroup Contact Field Experiment in Nigeria - Introduction"
author: "Christopher Grady, Rebecca Wolfe, Danjuma Dawop, and Lisa Inks"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
    pandoc_args:
    - -M
    - secPrefix=\S
    template: ../utils/bowersarticletemplate.latex
  word_document: default
csl: ../utils/american-political-science-review.csl
bibliography: ../utils/cdg_references.bib
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="footnotesize",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132,
  out.width='.9\\textwidth',
  message=FALSE,
  comment=NA)

options(SweaveHooks=list(fig=function(){
			   par(mar=c(3.5, 3, 1.1, 0),
			       pty="s",
			       mgp=c(1.5,0.5,0),
			       oma=c(0,0,0,0))},
			 echo=function(){options(continue=" ") ##Don't show "+" prompts,
			 options(prompt=" ")
			 }),
	digits=4,
	scipen=8,
	width=132
	)
```

<!--
# Thinking

Option1 : zoom in  (current)
- nigeria example
- what accounts for difference?
- intergroup conflict as bargaining failure.




Option2: zoom out first
- intergroup conflict bad; no consistent way to prevent it.
- intergroup conflict as bargaining failure. 


**Intro**

Need to explain why I am doing things more than tell people details of what I am doing.  Only provide broad strokes for what I did.

Field experiment papers often take a couple paragraphs talking about the field experiment, but I don't want to.

*******
-->
## Introduction

<!--chris: New first paragraph about intergroup conflict generally.-->

Violent conflicts are one of most crucial phenomena for humans to overcome.  As of 2018, violent conflicts caused 2 million deaths since the year 2000 [@ucdp], were responsible for forcibly displacing over 70 million people from their homes [@unhcr2019], , threatened food supplies in numerous countries [@verwimp2012food], and extracted a psychological toll on participants and victims (chris: cite Schomerus and Rigterink from ISA Toronto?).  Despite extensive research, violent conflict is still common and methods to prevent violent conflict between groups are elusive.  

<!--The two perspectives: Psych and IR.   What psych brings: a variety of non-material factors that contribute to group violence, including: group identity; economic/other threat; prejudice and emotions; personality/social dominance orientation. Ways to influence those contributors, like intergroup contact (Allport 1954; Scacco and Warren 2018; Paluck 2009), expert appeals (Chang and Peisakhin 2018), resource competition [chris: realistic group conflict theory?], and perspective-taking (Simonovits et al. 2018). -->

There exists two main perspectives about group conflict.  One perspective, coming from psychology, identifies group conflict as a problem of emotion and group identity.  This perspective emphasizes things like perceived threat [@riek2006threat; @stephan2011threat], anger and aggression [@Claassen2014group; @deWall2011aggression; @halperin2011emotional; @schaller2008intergroup], ethnic or religious hatred [@staub2001ethnopolitical; @cikara2014their; @Petersen2002understanding], perceptual biases [@ward1997naive; @duncan1976differential; @hewstone1990ultimate], and dehumanization [@haslam2014dehumanization; @kteily2016they] as the drivers of group violence.  This perspective points to intergroup contact [@Allport1954; @Scacco2018; @Paluck2009), perspective-taking [@Simonovits2018], and expert appeals [@Chang2018] to reduce violent conflict.

<!--    - emotion and affect (chris: here also include prejudice, aggression, threat/fear, evolution, personality) [@Claassen2014group; Mackie, Devos, and Smith 2000; Tausch et al. 2011; @deWall2011aggression; @mcDonald2012maleWarrior] 
    - group identity (chris: here also include dehumanization, ethnic/religious hatred, morals/values), aggression [], threat of material deprivation, [@Claassen2014group; chris: relative deprivation theory; @Petersen2002understanding; @scheff2002emotions];-->

<!--What IR brings: a model that explicates the characteristics of violent conflict.  Intergroup conflict as a bargaining problem [@fearon1995rationalist; @fearon1994ethnic; @powell2006war].  Points to trust/costly signals and to bargaining range / perceived benefits and costs of conflict. [@rohner2013war; @kydd2000trust; chris: need something about bargaining range/].-->

The second perspective, coming from international relations, identifies group conflict as a bargaining problem [@fearon1995rationalist; @fearon1994ethnic; @powell2006war].  Two groups want some resource -- land, power, etc -- and must decide how to distribute that resource.  Violent conflict occurs when one or both sides expect their utility from fighting to be higher than their utility from bargaining.  This perspective emphasizes two factors: (1) the _bargaining range_ (i.e. the number of bargained outcomes preferable to fighting) [@colgan2015revolution; @lake2003international] and (2) _trust_ that the other side will honor bargained agreements [@reed2016bargaining; @powell2006war; @kydd2000trust].  This perspective points to third party mediation [@kydd2006when; @doyle2000international; @fearon1998commitment] and *costly signals of trustworthiness/reputations for trustworthiness* [@kydd2000trust; @rohner2013war] to reduce violent conflict.^[Note to lab: Two psych-oriented theories are similar to formal theory of conflict.  (1) Realistic group conflict theory from Campbell 1965: group conflict because groups compete for resources and have "incompatible goals".  (2) Nisbett and Cohen 1996 about a reputation for toughness.  I am not sure if I should bring those ]
<!--You have a nice office with a standing desk and other stuff; I want it.  Give it to me.
No.
Give it to me or I will do everything in my power to prevent you from getting tenure.
Whoa, don't do that.  Look, I won't give you my office, but if you don't try to prevent me from getting tenure I will buy you a standing desk.
Deal.-->

<!--Merging IR with psych: Model from IR that structures basic problem; portable and clear.  Other factors only relevant insofar as they affect the fundamental characteristics of the problem (bargaining range and trust).  From psych, the factors that affect trust and perception of behaviors that signal trust; the non-material costs and benefits that change the bargaining range.  

IR tells us this is a bargaining situation.  Psych tells us what makes that bargaining more/less difficult. -->
<!--
The psychological perspective and the international relations perspective each make valuable contributions to the study of group conflict.  The IR perspective provides a model that elucides the fundamental causes of group conflict: few agreements acceptable to both sides and low trust that the other side will honor those agreements.  It is portable, clear, and provides a basis to think about the way in which other factors affect group conflict.  The psychological perspective provides details about those other factors.  Dehumanization and emotions like anger provide non-material costs to bargained compromises that limit the number of mutually acceptable bargained agreements; perceptual biases prevent costly signals of trustworthiness from being perceived as such by the other side.

**OR**-->

The psychological perspective and the international relations perspective each make valuable contributions to the study of group conflict, but each is incomplete without the other.  The IR perspective provides a model that elucides the fundamental causes of group conflict: few agreements acceptable to both sides and low trust that the other side will honor those agreements.  It is portable, parsimonious, and provides a basis to understand how other factors affect group conflict by influencing the bargaining range or the formation of intergroup trust.  The IR perspective, however, does not always consider the myriad non-material factors that influence bargaining ranges or trust formation. ^[chris note: This sentence does not feel right.  Would like advice.]

The psychological perspective provides details about those other factors.  The acceptable bargaining range is affected by outgroup dehumanization and hatred.  Those factors provide non-material costs to bargained compromises that limit the number of compromises preferable to fighting.  The formation of intergroup trust is affected by perceptual biases that distort outgroup behavior.  Perceptual biases prevent one side's costly signals of trustworthiness from being perceived as such by the other side.  The psychological perspective, however, does not have a unified model of conflict to formalize how these various factors affect violent conflict.  <!--I used "passive voice" in this paragraph because the link back to the previous sentences (bargaining range and trustworthiness) are being acted on, not acting themselves.  They need to come first to link the previous sentences to these sentences, but they are not active. -->

**OR**

The psychological perspective and the international relations perspective each make valuable contributions to the study of group conflict, but each is incomplete without the other.  The IR perspective provides a model that elucides the fundamental cause of violent group conflict: bargaining failure.  It is portable, parsimonious, and provides a basis to understand how other factors increase or decrease the likelihood of violent conflict.  The IR perspective, however, does not always consider the psychological factors that make bargaining more or less difficult.  The psychological perspective theorizes about the psychological factors that influence group conflict, like emotion and perceptual biases.  It does not, however, provide a model of group conflict from which psychological factors can be understood.

These perspectives work together to provide a more complete understanding of group conflict.^[I don't like this sentence.  Would it be better as "...work together to provide a model of group conflict and understanding of how psychological factors work within that model."?]  Violent group conflict occurs when two groups fail to bargain, and bargaining fails when there are few agreements acceptable to both sides and low trust that the other side will honor their agreements.  The number of agreements acceptable to both sides depends on psychological factors like outgroup dehumanization and hatred; those factors provide non-material costs to bargained compromises that limit the number of compromises preferable to fighting.  The formation of intergroup trust is affected by perceptual biases that distort outgroup behavior; perceptual biases prevent one side's costly signals of trustworthiness from being perceived as such by the other side.  In short, the IR perspective tells us group conflict is a bargaining problem and the psychological perspective tells us what makes that bargaining more or less difficult.

In short, the IR perspective tells us group conflict is a bargaining problem where bargaining fails due to lack of acceptable agreements and lack of trust; the psychological perspective tells us that emotions and perceptual baises make bargaining more difficult.

<!-- Intergroup cooperation for material benefit is primary method that addresses issues relevant to conflict.  Should increase trust by providing structured interactions where group members cooperate for a common goal: group A's actions towards the common goal help group B, and vice versa.  Costly signal.  Something about working together for material benefit.

Decrease benefits of conflict because not feeling justified in harming outgroup; decreases costs of peace because not deriving self-esteem from feelings of moral superiority.

Diffuse to others through social norms and vicarious contact.-->

Synthesizing these perspectives, we argue that cooperative intergroup contact can reduce group conflict by increasing the bargaining range and building intergroup trust.  Cooperative contact -- interactions in which both groups cooperate to fulfill joint goals -- humanizes the outgroup, promotes positive affect towards outgroup members, dispels stereotypes/misperceptions that drive perceptual biases, and provides opportunities for unequivocal signals of trustworthiness.  Humanizing the outgroup and promoting positive affect increase the bargaining range by reducing the psychological costs of bargaining with the other side.  Cooperative contact can also demonstrate to groups the material benefits of cooperation, increasing the expected utility of peace.  Correcting perceptual biases and providing opportunities for costly signals helps foster intergroup trust and ensures each side that the other will honor bargained agreements.  What's more, cooperative contact for some group members can diffuse throughout the entire group through the process of indirect contact (knowledge of friendships between ingroup and outgroup members) and changes to social norms.^[This paragraph is not right yet and, anticipating changes, I have not added the citations.]  

<!-- We conducted a contact-based field experiment;  -->
To test the ability of cooperative contact to reduce violent conflict, we conducted a field experiment with conflicting farmer and pastoralist communities in Nigeria.  More than an occupational difference, farmers who cultivate crops and pastoralists who graze cattle define a major social cleavage in many parts of the world.  These groups conflict over land rights, which define both of their livelihoods.  Farmer-pastoralist conflict has escalated througout the Sahel in recent years, and nowhere more than in Nigeria.  The most recent conflict escalation has caused 7,000 deaths in the past five years, displaced hundreds of thousands of people from their homes, and costs $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria]<!--don't need to cite news articles like this. you can give an address / identifier / link /etc in a footnote -->.

We randomly assigned communities with ongoing farmer-pastoralist violence to receive a contact-based intervention or serve as a control group.  The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.^[The communities built boreholes, market stalls, primary health care facilities, etc.]  The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.  To measure the effects of the intervention, we conducted pre- and post-intervention surveys, a post-intervention natural public goods behavioral game,[^PGG] and twelve months of systematic observations in markets and social events during the intervention.

[^PGG]: In a public goods game (PGG), research subjects are given money and told they can keep the money or donate it to a public fund.  Money donated to the public fund is multiplied by some amount and then shared with all subjects.  Our PGG is _natural_ because it was conducted in a natural setting, rather than a lab.  The funding for the PGG came from the National Science Foundation under Grant No. 1656871.

<!-- Findings. -->

We find that the program increased intergroup contact, intergroup trust, and perceptions of physical security.  We see signs of the positive effects in fieldwork as well as in data -- in one of the treatment sites, farmers defended pastoralists from a group of anti-pastoralist vigilantes, rather than assist the vigilantes in removing the pastoralists and claiming their land.  Our results also show that the intervention affected communities as a whole, not just community members directly involved in the intergroup contact.  Individuals who directly engaged in intergroup contact changed the most positively from baseline to endline, but we also observe positive spillovers of trust to group members for whom we did not exogenously increase intergroup contact.

<!--Say implications for: (1) multi-method data evaluation of intergroup contact in conflict setting-->

This study expands our knowledge about group conflict in several ways.  First, this study synthesizes psychological and rationalist explanations for violent group conflict, demonstrating how the two perspectives complement each other.  Rationalist explanations teach that group conflict is a bargaining problem and violence is caused by incompatible incentives and mistrust; psychological explanations teach that emotions and group biases cause violent group conflict.  We synthesize these perspectives to explain how psychological factors affect intergroup bargaining and increase or decrease the likelihood of successful bargaining.

Second, this study teaches us about the capacity of intergroup contact to improve intergroup relations and reduce conflict.  Peacebuilding organizations implement numerous contact-based interventions in violent contexts each year [@ditlmann2017addressing], but its efficacy to improve intergroup attitudes amid real-world conflict is an open question [@paluck2017contact; @ditlmann2017addressing].  To our knowledge this is the first field experimental test of a contact-based intervention implemented during an active conflict.  The results suggest that contact-based peacebuilding programs can effectively improve relationships between conflicting groups and is especially relevant to conflict resolution in the cases of intergroup and intercommunal conflicts.

<!--(3) social institutions constraining behavior, intergroup bargaining. Should I also add (5) spillover of effects and social norms/vicarious learning?  Literature about informal structures solving collective action problems.  Some places have formal institutions, some places have do not.  Those places develop informal structures.  This program showed how informal structures can develop through repeated intergroup interaction.-->

Third, we contribute to the literature about informal structures, such as social norms, in solving collective action problems.  In some contexts, formal institutions ensure collective action by punishing groups and individuals who "defect" on agreements.  In many contexts, such as rural Nigeria, no formal institutions exist to encourage such behavior and so groups in those contexts develop informal structures to achieve collective action [@ostrom2000collective].  This intervention showed how informal structures governing interactions between groups can develop through repeated intergroup interaction.  Our intervention only engaged a small percentage of each community, yet its effects diffused to other community members.  Creating informal structures that diffuse the effects of contact are a way of scaling up peacebuilding interventions.^[chris: this paragraph is too long and not focused enough.  Would appreciate comments.]

<!--Sedentary and nomadic peoples; Fulani getting cleansed -->

Fourth, this paper teaches us about settling disputes between sedentary peoples and nomadic peoples.  Violent conflict between settled peoples and nomadic peoples is on the rise throughout Africa [@hrc2018farmer; @kuusaana2015land; @mwamfupe2015persistence].  This study focuses on the Fulani, the largest semi-nomadic people on Earth [@fulanisize2017].  Their way of life makes them targets for violence throughout Africa.  Along with this conflict in Nigeria, Fulani in Mali have been the targets of violence so severe that researchers at Armed Conflict Location & Event Data Project called it "ethnic cleansing" [@economist2019militias].  Understanding how to prevent violent conflict between Fulani and settled peoples can help prevent violence that targets other nomadic and semi-nomadic peoples, such as the Tuaregs in West Africa, Uyghurs in Central Asia, Kochi in Afghanistan, and Khoisan of Southern Africa.  Preventing such violence could help preserve a dying way of life.

<!--Fourth, this paper teaches us about bottom-up interventions to encourage peace between groups.  Most interventions use top-down approach.  Bottom-up approach can support top-down or be effective on its own. chris: do I even want to include this? -->

<!--Roadmap.

In the next section we provide a theoretical framework for how and why opposing groups struggle to solve their disagreements through bargaining and negotiation, and argue that cooperative contact can help these groups resolve disagreements by improving intergroup trust.  We then discuss Nigeria's farmer-pastoralist conflict, our experimental intervention, and two designs to evaluate the effect of the intervention.  Last we present the results of the study and conclude by discussing their implications for intergroup contact and group conflict. 
-->




<!--

IR Perspective on conflict and cooperation.
  - bargaining; commitment problem; trust

Psych Perspective on conflict and cooperation: has looked at many factors that contribute to conflict.
  - competition as inevitable consequence of groups (social ID theory, minimal group paradigm)
  - realistic group conflict theory: inevitable as groups fight over resources
  - contact theory: prejudice caused by stereotypes/information (original), anxiety (newer), lack of empathy (newer), perceived threat (newer).  Prejudice could cause conflict.  Need cooperative contact with superordinate goals

Why psych needs IR
  - IR/Formal Models show us the relevant characteristics of the situation.
  - Key is trust.  Intervention needs to build trust.
  - Other factors, such as affect, empathy, or social distance are important only insofar as they influence trust.
  - ALSO: must have a bargaining range == outcomes each side prefers to fighting.

Why IR needs psych
  - Psych knows a lot about psychological basis for trust.  Things that affect building trust: biased perceptions of behavior.
  - ALSO: non-material costs and benefits that change the bargaining range.
-->


*******************

<!--

To understand what causes some groups to engage in violent conflict while others maintain peaceful relations, we join many conflict scholars in conceptualizing group conflict as a bargaining failure [@fearon1995rationalist; @fearon1994ethnic; @powell2006war].  In the bargaining framework, both groups want some resource -- land, power, etc -- and must decide how to distribute that resource.  The groups can either bargain and split the resource or groups can fight to claim all of the resource.  Fighting is costly, so both groups are better off finding a bargained solution than fighting.  Though both groups materially benefit from a bargained peace, many peace negotiations fail.  The literature points to a lack of intergroup trust as the primary obstacle to peace: bargaining fails if neither group trusts the other side to be truthful or to honor bargained agreements [@rohner2013war; @kydd2000trust].  Without a reason to trust each other, groups are likely to fight despite the costs to both sides.

A number of psychological phenomena complicate trust-building between opposing groups.  First, these groups hold biased perceptions of their own behavior and the behavior of the other side [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Groups perceive their own belligerent actions as defensive and justified, and perceive the defensive actions of the other side as belligerent and gratuitous.  These perceptual biases create and reinforce outgroup mistrust and other negative stereotypes [@hewstone1990ultimate].  Second, groups in conflict derive psychological benefits from feelings of moral superiority over the outgroup [@tajfel1979integrative; @fein1997prejudice; @cikara2013their].  These feelings of moral superiority add costs to improving attitudes about the outgroup and to cooperating with the outgroup.  These two psychological phenomena sabotage intergroup bargaining by causing the groups to have inaccurate beliefs about each other and by limiting peace agreements acceptable to both sides.

Groups in conflict have few natural opportunities to build trust and many to degrade it.  We argue that cooperative intergroup contact provides opportunities to build intergroup trust and can improve the prospects for peaceful negotiation.  Directly, cooperative face-to-face contact provides groups the opportunity to send costly signals about their trustworthiness and preference for peace [@kydd2000trust; @lupia1998democratic; @rohner2013war; @bohnet1999social].  Indirectly, cooperative contact ameliorates the psychological biases that breed mistrust by reducing the anxiety felt from intergroup interaction [@lee2001mere; @page2008little], increasing empathy for members of the other group [@pettigrew2008does; @broockman2016durably], and providing information about the other group that replaces negative stereotypes [@allport1954prejudice; @pettigrew2008does].  Cooperative contact can also demonstrate to groups the material benefits of cooperation [@sherif1958superordinate; @gaertner2000reducing] and can form a superordinate identity that encompasses both groups [@gaertner2014reducing].  Cooperative contact for some group members can diffuse throughout the entire group through the process of indirect contact (knowledge of friendships between ingroup and outgroup members) and changes to social norms [@sen2007emergence; @paolini2004; @yablon2012we; @crisp2009imagined].

To determine if cooperative contact improves intergroup attitudes, we conducted a field experiment with conflicting farmer and pastoralist communities in Nigeria.  More than an occupational difference, farmers who cultivate crops and pastoralists who graze cattle define a major social cleavage in many parts of the world.  These groups conflict over land rights, which define both of their livelihoods.  Farmer-pastoralist conflict has escalated througout the Sahel in recent years, and nowhere more than in Nigeria.  The most recent conflict escalation has caused 7,000 deaths in the past five years, displaced hundreds of thousands of people from their homes, and costs $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria]

We randomly assigned communities with ongoing farmer-pastoralist violence to receive a contact-based peacebuilding intervention or serve as a control group.  The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.^[The communities built boreholes, market stalls, primary health care facilities, etc.]  The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.  To measure the effects of the intervention, we conducted pre- and post-intervention surveys, a post-intervention natural public goods behavioral game,[^PGG] and twelve months of systematic observations in markets and social events during the intervention.

[^PGG]: In a public goods game (PGG), research subjects are given money and told they can keep the money or donate it to a public fund.  Money donated to the public fund is multiplied by some amount and then shared with all subjects.  Our PGG is _natural_ because it was conducted in a natural setting, rather than a lab.  The funding for the PGG came from the National Science Foundation under Grant No. 1656871.

We find that the program increased intergroup trust, intergroup contact, and perceptions of physical security.  We see signs of the positive effects in fieldwork as well as in data -- in one of the treatment sites, farmers defended pastoralists from a group of anti-pastoralist vigilantes, rather than assist the vigilantes in removing the pastoralists and claiming their land.  Our results also show that the intervention affected communities as a whole, not just community members directly involved in the intergroup contact.  Individuals who directly engaged in intergroup contact changed the most positively from baseline to endline, but we also observe positive spillovers of trust to group members for whom we did not exogenously increase intergroup contact.

This study expands our knowledge about intergroup conflict in several ways.  First, this study teaches us about the capacity of intergroup contact to improve intergroup relations and reduce conflict.  Peacebuilding organizations implement numerous contact-based interventions in violent contexts each year [@ditlmann2017addressing], but its efficacy to improve intergroup attitudes amid real-world conflict is an open question [@paluck2017contact; @ditlmann2017addressing].  To our knowledge this is the first field experimental test of a contact-based intervention implemented during an active conflict.  Each of the groups in our study were part of an active conflict, with members of each side being killed within one year of the intervention's onset.  We evaluated the program's effects on both attitudinal and behavioral outcomes.  The results suggest that contact-based peacebuilding programs can effectively improve relationships between conflicting groups and is especially relevant to conflict resolution in the cases of intergroup and intercommunal conflicts.

Second, we contribute to the literature about informal structures, such as social norms, in solving collective action problems.  In some contexts, formal institutions ensure collective action by punishing groups and individuals who "defect" on agreements.  In many contexts, such as rural Nigeria, no formal institutions exist to encourage such behavior and so groups in those contexts develop informal structures to achieve collective action [@ostrom2000collective].  This peacebuilding intervention showed how informal structures governing interactions between groups can develop through repeated intergroup interaction.  Creating informal structures that diffuse the effects of contact are a way of scaling up peacebuilding interventions.

Third, this paper teaches us about settling disputes between sedentary peoples and nomadic peoples.  Violent conflict between settled peoples and nomadic peoples is on the rise throughout Africa [@hrc2018farmer; @kuusaana2015land; @mwamfupe2015persistence].  This study focuses on the Fulani, the largest semi-nomadic people on Earth [@fulanisize2017].  Their way of life makes them targets for violence throughout Africa.  Along with this conflict in Nigeria, Fulani in Mali have been the targets of violence so severe that researchers at Armed Conflict Location & Event Data Project called it "ethnic cleansing" [@economist2019militias].  Understanding how to prevent violent conflict between Fulani and settled peoples can help prevent violence that targets other nomadic and semi-nomadic peoples, such as the Tuaregs in West Africa, Uyghurs in Central Asia, Kochi in Afghanistan, and Khoisan of Southern Africa.  Preventing such violence could help preserve a dying way of life.

In the next section we provide a theoretical framework for how and why opposing groups struggle to solve their disagreements through bargaining and negotiation, and argue that cooperative contact can help these groups resolve disagreements by improving intergroup trust.  We then discuss Nigeria's farmer-pastoralist conflict, our experimental intervention, and two designs to evaluate the effect of the intervention.  Last we present the results of the study and conclude by discussing their implications for intergroup contact and group conflict. 

<!--chris: I want to add something about how incorporating psychological theories of human behavior into rationalist frameworks of phenomena like conflict provides a better understanding of human behavior. -->

<!--
## Old

## Motivating Example: Story about burnt down village/bad outcomes, then story about village defending pastoralists.

In Nigeria's Middlebelt, intergroup conflict between sedentary farmers and semi-nomadic pastoralists is causing dire consequences: 7,000 deaths in the past five years, 300,000 internally displaces peoples from their homes in 2018, and $13 billion of lost economic productivity annually [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria].  Since the most recent conflict escalation began in 2014, groups of anti-pastoralist vigilantes have mobilized to prevent pastoralists from encroaching on land claimed by farmers [@duru2018court; @mcdonnel2017graze].  These groups, dubbed the "livestock guard", ransack pastoralist settlements and violently drive pastoralists from their homes, often with the assistance of the local farming community.  Likewise, pastoralist groups enact vigilante justice, raiding and burning down farming villages seen to encroach on land claimed by pastoralists.

Though farmer-pastoralist conflict is widespread, mass violence between these groups has not broken out in all Middlebelt communities, and some farmers and pastoralists even defend each other.  When a group of livestock guard came for one pastoralist settlement, the neighboring farming village arrested them to protect the pastoralists.  After the arrest, farmers and pastoralists convened to decide what should be done with the prisoners.  They agreed that the group of livestock guard should not be punished, but should be disarmed and released home -- a proposition proposed by _the pastoralists_.  These same farmers and pastoralists had struggled with conflict, and people on both sides had died in past violence over farmland and grazing land.  But their recent disagreements had not escalated to the point that each side wanted the other removed by any means necessary.  The groups had created structures and relationships that allowed them to settle disputes, and the same structures and relationships allowed them to reach a solution about the livestock guard.

Why were some farmer and pastoralist groups able to keep peace whereas others were consumed by the escalating conflict?  Why were some communities able to overcome their disagreements whereas others were destroyed by them?  

 -->

****************


<!--
## Quotes From Articles

"The problem is bigger than mandates and resources. Above all, it has to do with two strategic choices the UN frequently makes: first, to work with national elites to stop violence from the top down and, second, to push for quick elections as a way to consolidate the peace. The standard UN approach to ending wars is to host large, costly conferences in order to strike agreements between governments and rebel leaders and then organize a national vote and declare victory. Both tendencies are based on faulty assumptions."

The weakness of the top-down approach is that warfare is often the result of not just national or international competition but local competition, too. In many conflict zones, the fight is over such issues as land, water, livestock, and low-level traditional and administrative power.

**Consider the island of Idjwi, in Lake Kivu in eastern Congo. Since war broke out in Congo in 1996, a conflict that has killed anywhere from two million to five million people, Idjwi has avoided the brunt of the violence, even as other islands in nearby lakes have not. Idjwi has all the same factors that have fueled fighting around it: a geostrategic location, mineral resources, ethnic tensions, a lack of state authority, extreme poverty, disputes over land and traditional power. But the island’s residents, including the poorest and least powerful, have set up various grass-roots organizations—religious networks, women’s associations, youth groups, and so on—to help resolve disputes. They also draw on strong traditional beliefs—for example, forming blood pacts through which different families promise never to hurt one another. They have worked to foster what they call a “culture of peace.”**

The UN currently views such bottom-up peace-building efforts as a sideshow. Instead, it should see them as an essential complement to its current top-down efforts to stop fighting.

"bottom-up strategies that [let] the people themselves determine how best to promote peace."

[@autesserre2017international]

"international enforcement can help solve commitment and cooperation problems by imposing order or by directly implement- ing peace agreements or raising the costs of defection from them. Long-term trusteeship may be required to overcome deep distrust and powerful incentives to defect from the peace. As in prisoner's dilemma and mixed motive games (Axelrod and Keohane 1985; Oye 1985), deep hostility, multiple factions, or lack of coherent leadership may complicate the achievement of self-enforcing cooperation. Conscious direction by an impartial agent to guarantee the functions of effec- tive sovereignty become necessary, [@doyle2000international]


@kydd2000trust: opportunity for costly signaling allows groups to build trust and cooperate.  @ostrom2000collective, @Axelrod: conditional cooperators. Need to forgive.

@ostrom2000collective: "if there is a noisy signal about a player’s type that is at least more accurate than random, trustworthy types will survive as a substantial proportion of the population. Noisy signals may result from seeing one another, face-to-face communication, and various mechanisms that humans have designed to monitor each other’s behavior"
"evidence has accumulated that externally imposed rules tend to “crowd out” endogenous cooperative behavior (Frey, 1994)"
"These studies typically find that **a social norm**, especially in a setting where there is communication
between the parties, can work as well or nearly as well at generating cooperative
behavior as an externally imposed set of rules and system of monitoring and
sanctioning." @rohner2013war also says that coercive peace policies do not have enduring effects. @beardsley2008agreement says peacekeeping only works short-term.
@rohner2013war: lack of trust causes civil conflict.  Intergroup trust increases intergroup trade, which increases costs of conflict.


UN peacekeeping not successful at ending _ongoing_ conflicts, but are successful at post-conflict stuff. [@gilligan2008interventions; @doyle2006making]. @bratt1996assessing also questions effectiveness at conflict resolution.  @beardsley2008agreement shows mediation works short-term but not long-term.

@di2017effectiveness good summary of peacekeeping stuff.

@grieg2008they about mediation.
@regan2002third questions effectiveness of international intervention overall.

Studies have not, however, shown how intergroup bargaining is made more difficult by the cognitive and motivational biases of two opposing groups; nor has it shown how those groups can overcome their biases to reduce conflict. 
-->

<!--
chris: biased perceptions.
Once conflict between two groups begins, the
violence escalation cycle is triggered. Group A
experiences Group B’s retaliation, which causes
Group A’s members to have high levels of
aggressive affect, to perceive Group B as hostile
and aggressive, and to experience heightened
arousal. These internal states cause members of Group A to act impulsively on their immediate
appraisal of Group B as hostile and threatening.
Group B then experiences the impulsively aggressive
act from Group A, which sets in motion
the same set of internal states and appraisal
and decision processes that result in an even
more aggressive retaliation (see Figure 2). Both
groups will trade increasingly aggressive retaliations
back and forth, which can result in the
widespread destruction of human life and property.
[@deWall2011aggression]


In most such cases,
members of conflicting societies or groups view the conflict through a unidimensional,
biased lens and therefore perceive the other group’s actions
as unjust, unfair, and incompatible with acceptable norms (White, 1970).
Often these perceptions are amplified by blindness to the previous wrongdoings
of one’s own group, which are considered by the opponents to
be the reasons for their current actions or statements (Bar-Tal & Halperin,
2010).
Given these biased appraisals, it is not surprising that intergroup anger
is a pivotal emotion in every conflict
[@halperin2011emotional]

-->

<!--
This approach to intergroup relations (Brewer, 1979; LeVine & Campbell,
1972; Sherif, 1966) assumes that group conflicts are rational in the
sense that groups have incompatible goals and compete for scarce resources.
[@hewstone2011social]
-->

<!--
FROM LITTLE AND ZEITZOFF: " psychological explanations posit that political violence is primarily driven by emotional or identity
grievances, ethnic or religious hatred, or in defense of sacred values (Atran 2006; Bar-Tal 2001; Cheung-Blunden and Blunden 2008; Nisbett and Cohen 1996; Petersen 2002; Scheff and Retzinger 2002.).
-->






# References