---
title: "Promoting Peace Amidst Group Conflict: An Intergroup Contact Field Experiment in Nigeria - Theory"
author: "Christopher Grady, Rebecca Wolfe, Danjuma Dawop, and Lisa Inks"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  word_document: default
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
    pandoc_args:
    - -M
    - secPrefix=\S
    template: ../utils/bowersarticletemplate.latex
csl: ../utils/american-political-science-review.csl
bibliography: ../utils/cdg_references.bib
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="footnotesize",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132,
  out.width='.9\\textwidth',
  message=FALSE,
  comment=NA)

options(SweaveHooks=list(fig=function(){
			   par(mar=c(3.5, 3, 1.1, 0),
			       pty="s",
			       mgp=c(1.5,0.5,0),
			       oma=c(0,0,0,0))},
			 echo=function(){options(continue=" ") ##Don't show "+" prompts,
			 options(prompt=" ")
			 }),
	digits=4,
	scipen=8,
	width=132
	)
```

# Theory

## Intergroup Conflict as a Bargaining Problem
<!--Typical solutions strive to solve intergroup bargaining problem.  Information and comittment problems.  Define these problems.  Bigger versions of "Intergroup conflict is often conceptualized as a bargaining problem" and "How can groups in conflict escape this spiral of distrust and conflict?" paragraphs from intro.-->

Intergroup conflict is most often conceptualized as a bargaining problem [@fearon1994ethnic; @powell2006war], and most solutions to reducing intergroup conflict strive to help the groups overcome barriers to bargaining [@di2017effectiveness; chris: this cite is just for peacekeeping/intervention].  Intergroup conflict is a bargaining problem because both groups want some resource -- land, power, etc -- but cannot reach an agreement about how to distribute that resource peacefully.  Because fighting is costly, the groups are better off reaching a bargained compromise than fighting.  However, two problems prevent successful bargaining: information problems and commitment problems [@fearon1995rationalist].  Groups are less likely to successfully bargain without (1) accurate information about each other's strengths and preferences, and/or (2) assurance that each side will abide by its agreements.  

An _information problem_ arises when neither group possesses accurate information about the other.  In this situation, both groups have an incentive to deceive the other to achieve an advantageous bargaining outcome.  Groups have an incentive to portray themselves as stronger, more willing to fight, and less willing to make concessions than they truly are [@fearon1995rationalist]. This causes bargaining failures because neither group knows what agreements the other side is willing to accept or what their side should receive from bargaining.  A _commitment problem_ arises when neither group can credibly commit to honor bargained agreements.  For example, if bargaining power shifts after the agreement, one side will have an incentive to renege on the status quo agreement to achieve a better agreement.  This causes bargaining failures because neither group will commit to agreements today that they believe will be broken tomorrow.  Without the ability to commit to agreements, bargaining will not be successful.[chris: maybe revise this paragraph so the second part (commitment problems) is structurally parallel to the first part (information problems).]

Groups in conflict overcome information and commitment problems in two main ways.  The first way is through third-parties.  Third parties can solve information problems by mediating disputes, providing accurate information to both sides [@kydd2006can].  Third parties can also solve commitment problems by intervening to punish defection from agreements.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1995rationalist].

The second way groups solve information and commitment problems is through reputations for trustworthiness [@kydd2000trust].  Reputations for trustworthiness are how groups bargain in the absence of formal enforcement mechanisms like third parties [@ostrom2003trust].  Reputations encourage bargaining because future bargaining depends on groups trusting each other to abide by agreements, and groups with reputations for defection are unlikely to attract other trustworthy partners or elicit trusting behavior from partners [@ostrom2003trust; @kydd2000trust].  Cultivating a reputation as a trustworthy partner in previous interactions gives a bargaining partner confidence that you are trustworthy in the present interaction.[^reputation]<!--chris: not talking about information problems at all, really...maybe ask ekrem? -->

[^reputation]: The reputation argument is generally mobilized for contexts in which many groups observe the behavior of many other groups.  In those contexts a good reputation assists in obtaining _other_ cooperative partners.  In our case, there are two main sides forming perceptions about the reputation of each other.  In this context, a good reputation assists in obtaining cooperative behavior in the future from the same partner.  This two player context is similar to @kydd2000trust.

## The Persistence of Intergroup Conflict

If we know how to resolve intergroup conflict, why does conflict persist?  First, it is not possible for third parties to mediate or intervene into every conflict.  Sometimes no third party is willing or able to become involved [@fey2010shuttle, p.530], and sometimes the conflict is too decentralized for a third party to effectively mediate or intervene.  This situation is common for internal conflicts in weak states, where conflicts are diffuse and the state lacks the capacity to mediate or intervene into the conflict.  Second, third party mediation and intervention are not effective in all contexts [@beardsley2008agreement; @beber2012international; @weinstein2005autonomous; @autesserre2017international].

Where third parties cannot effectively intervene, conflicting groups could negotiate based on reputation, but groups in conflict are unlikely to have positive reputations in each other's eyes.  Groups in conflict dehumanize the outgroup [@haslam2014dehumanization; @leyens2007infra; @opotow1990moral; @bandura1999moral], view the outgroup as innately immoral [@weisel2015ingroup; @parker2013lessons; @brewer1999ingroupOutgroup, p.435], do not naturally feel empathy for outgroup members [@gutsell2010empathy], are unlikely to forgive outgroup transgression; @tam2007impact], and believe outgroup members to be untrustworthy and dishonest [@levine1972ethnocentrism; @eidelson2003dangerous].  These psychological mechanisms introduce significant friction in the ability of groups to build trusting relationships and significantly restrain opportunities through which trust could be built.<!--chris: could remove everything after first sentence and merge with next paragraph. -->

<!-- Formerly a new section called something like "Animosity and Intergroup Conflict" or "Group Biases and Conflict" -->
<!--How conflict makes intergroup bargaining more difficult.  (1) Low trust due to history of noncooperation & violence.  (2) Disagree about fairness of proposed deal == Disagree about current power / Disagree about which side transgressed and needs to make amends / Disagree about who is likely to hurt more from conflict today/become stronger tomorrow (p.24 of Ross_Ward_1995-NaiveRealism).  (3) internal evaluations and social evaluations == get psychological and social payoffs from beating other side, psychological and social costs from cooperation.  (4) Biased processing of outgroup behavior.  (5) over-generalizing of outgroup. From intro: "Second, groups over-generalize negative behaviors of outgroup members as representative of the entire outgroup and under-generalize positive behaviors as exceptional to the outgroup [@hewstone1990ultimate].  These over and under-generalizations create and reinforce negative outgroup stereotypes."

(A) Biased perceptions: (1) Low trust, (2) perceive fair deals to be unfair.  This is due to (4) perceive outgroup as more threatening/less trustworthy/more in need of making amends.  And due to (5) over-generalizing of outgroup.
(B) Internal Evaluations/non-material payoffs: (3) psychological benefits to beating other side/costs to cooperating with other side, (3) Social benefits to fighting other side / costs to cooperating with other side.  

CHRIS: "Internal Evaluations", "disagreement about fairness of a deal" do not inhibit trust, only biased perceptions of actions and over-generalizing inhibit trust.  Internal evals and disagree about deal fairness make bargaining more difficult but do not work through trust. 

1) Via social/psychological mechanisms which increase costs of cooperation and benefits of defection (1a personal, 1b social, 1c constraining leaders)

2) Prevents accurate interpretations of signals. Blocks the pipes (which is the second part)

First, conflicting groups hold biased perceptions of their own behavior and the behavior of the other side [@ward1997naive].  Groups perceive their own belligerent actions as defensive and justified, and perceive the defensive actions of the other side as belligerent and gratuitous.  These perceptual biases create and reinforce negative outgroup stereotypes [@hewstone1990ultimate].  Second, groups in conflict derive psychological benefits from feelings of moral superiority over the outgroup.  These feelings of moral superiority add costs to improving attitudes about the outgroup and to cooperating with the outgroup.  Together these two psychological mechanisms sabotage intergroup bargaining by causing the groups to have inaccurate beliefs about each other and limiting peace agreements acceptable to both sides.-->

These psychological mechanisms prevents peaceful resolution of conflict in two main ways.  First, they bias each group's perception of the other side's behavior and preferences.  Second, they increase the costs of cooperation and the benefits of defection.  These two psychologicla mechanisms, biased perceptions and feelings of moral superiority create and reinforce negative outgroup stereotypes and prevent each side from accurately interpreting the other side's signals.<!--chris: previous sentence too long --> 

First, and most obviously, animosity directly exacerbates bargaining problems <!-- (1) less trust == higher information and comittment problems.-->.  Mutual distrust creates information and commitment problems.  Animosity also changes the payoff that each group receives from peace and war through non-material rewards and costs, called internal evaluations [@ostrom2003trust].<!--(2) internal evalutions: "animosity may change each group's preferences for peace and war", adding psych value to fighting.  (3) internal evaluations: gains from intergroup differentiation and feelings of superiority.  (4) internal evaluations due to social benefits/domestic audience costs -->  Second, animosity biases perceptions of ingroup and outgroup behavior and preferences.  These biases increase the likelihood that each group misperceives the other side's intentions and prevents groups from developing reputations for trustworthiness. <!--(5) biased info processing, increases likelihood of misperceptions of outgroup type. -->

<!--ekrem: i think you mean: animosity reduces the level of trust among groups, and thus directly exacerbate both information and commitment problems they face.  the way you currently say it sounds more like commitment problems are more likely to occur when the gorups can't commit to each other.  the more likely to occur part should be changed with exacerate/deepen/increases the bite or something like that -->

Intergroup animosity prevents peace by directly exacerbating informtion and commitment problems.  First, information and commitment problems are more likely to occur because groups are less likely to trust information they receive from the other side or any peace commitment they get from the other side.  Second, animosity may change each groups preferences for peace and war.  Individual group members might receive psychological benefits from "beating" the other side and from social differentiation with the outgroup [@wood2000attitude].  Many groups define "us" by positive differences with a "them", and an individual can derive self-esteem from positively comparing their group identity to a rival group [@tajfel1981groups; @brewer1999ingroupOutgroup].  When group members derive self-esteem from feeling superior to an outgroup, group members may reject actions that recognize the outgroup as equals and rhetoric about group similarity due to cognitive dissonance.  With these internal evaluations of peace and war, any outcome in which the other side achieves _any_ utility could be viewed as a loss.  Groups that see the other side as immoral may even receive some internal benefit from _harming_ the outgroup [@weisel2015ingroup].

<!--Ekrem: #2 is about psychological modification of payoffs (which increases mistrust, because we now like defecting more and cooperating less).  what is #1 about? the biases which don't let us update properly? if so say so, that's a good one -->

Along with psychological benefits, group members may receive social benefits for strong anti-outgroup stances and social sanctioning for cooperative behavior.  The utility a group members gets for attitudes and behaviors depends largely on how those attitudes and behaviors are received by their ingroup [@wood2000attitude].  If group members perceive outgroup animosity as socially desirable, they may profess attitudes and engage in behaviors that signal outgroup animosity.  These social _benefits_ also entail reciprocal social _costs_ that constrain the actions of group members and group leaders.  Individuals who cooperate with the outgroup, as opposed to taking a hard stance against the other side's perceived transgressions, might be accused of betraying the outgroup for cooperating [@dreu2010social].  Individuals in these groups might not engage in ingroup policing, a strong, costly signal to the other side that your group will uphold its peace agreements [@fearon1996explaining].  While cooperation and ingroup policing might be punished, aggressive actions may be seen as righteous self-defense of the ingroup and rewarded.

Leaders are also constrained by animosity among their group.  Groups are known to punish leaders for cooperating or compromising with the outgroup [@fearon1994domestic], so the set of peace agreements available to the leader of one group is likely unacceptable to the other.<!--chris: domestic audience costs-->.  Leaders of hostile groups also cannot credibly commit to keep their group members in check, as some subgroups may feel confident enough to disobey agreements made by group leaders.  Due to increased (1) likelihood of information and commitment problems, (2) internal psychological evaluations that favor competition over cooperation, and (3) social sanctioning for group members and leaders perceived as betraying the ingroup, animosity reduces the likelihood of successful bargaining and makes violent conflict more likely.<!--chris: need better discussion of internal evaluations -->

Animosity also sabotages peace in indirect, pernicious ways.  Indirectly, intergroup animosity biases interpretations of ingroup and outgroup behavior and prevents accurate perceptions about the attitudes and preferences of the outgroup.  Ingroups will perceive their own belligerent actions as defensive and justified, and are more likely to perceive outgroup actions as aggressive, negatively motivated, and unjustified [@hewstone1990ultimate; @amir1969contact; @hunter1991intergroup chris: also cite confirmation bias, anchoring bias].  <!--If groups want to dislike each other, they will. Klein and Kunda, brewer1991/1999 -->  The perceived negative behavior may be seen as _defining_ the group, whereas any perceived positive behavior may be seen as the _exception_ to the group [@allison1985group; @pettigrew1979ultimate].  Even positive intergroup interactions may be re-interpreted as negative to avoid cognitive dissonance [@festinger1962cognitiveDissonance; @gubler2013humanizing; @paolini2010negative].  Interpreting interactions negatively saps the power of each group to reassure the other with costly signals of willingness to cooperate in future interactions [@kydd2000trust, @rohner2013war].  It also adds to information problems as groups will hold inaccurate views about each other's willingness to cooperate and likelihood of upholding agreements.  As @axelrod1980effective shows, perceived untrustworthy behavior by one side often begets a cycle of mistrust.

<!--reputation as a mean of overcoming comittment problems when there is no third party.  How prejudice and biased interpretations of behavior prevent reputations from forming, even when both groups are the "complier" type. 

chris: need examples like "defensive action may be construed as offensive action."  And "Accidents or actions that incidentally injure may be construed as intentional or intentionally injuring."  What matters is the perception of the action!  Framing matters (Tversky and Kahneman) and we frame things in ours heads.  Ross_Ward_1995.  -->

The indirect effect of animosity on intergroup bargaining poses a major obstacle to groups overcoming bargaining problems through trustworthy reputations.  Groups tend to ascribe negative traits to the outgroup, and also tend to remember negative events that corroborate their negative beliefs [@tajfel1981groups, @brewer1999ingroupOutgroup; @klein1992motivated; @brewer1991social].  Groups in conflict are given many events to justify their negative perceptions.  Initial negative perceptions, and the biased interpretations they beget, make it very difficult for a group to develop a positive reputation with a group they are in conflict with, even when both groups are motivated to end the conflict.  This bias likely pushes each group's perception of the other side's willingness to make peace further from their true willingness to make peace and so reputations hinder, rather than aid, intergroup bargaining processes.

Reputations for trustworthiness are also hampered by a lack of opportunities for groups to observe each others behavior and update perceptions of the outgroup's trustworthiness.  Compounding that problem, few of the outgroup's interactions will be with groups that are relevant for predicting the outgroup's behavior towards the ingroup, providing fewer opportunities for updating.  This means that the main opportunity to observe outgroup behavior and learn their reputation is the ingroup's own interactions with the outgroup.  For groups in conflict, these opportunities are likely rare and almost always adversarial.
<!--
(This also means that the outgroup has less incentive to cooperate with your ingroup because they are less likely to be punished for defecting in a world where reputation is built off of _experienced_ interactions, rather than previous _observed_ interactions. [chris: Scott Page's coursera on overcoming collective action problems cites a model where the more people who can see your interaction the more incentive you have to cooperate.].  Not sure this is relevant.) <!--Mediation can also be good when the groups are likely to say inflammatory things to each other.  Going through a mediator prevents that. chris: don't remember the citation, and this belongs in a diff section. -->

<!--Reputations are most useful when (1) when each group knows its behavior will be viewed by many other groups and (2) a group's reputation can be gleaned from observing the other side's interactions with many other groups.  Unlike trade situations, groups in conflict  are unlikely to have a -->

## Peacebuilding Interventions to Improve Intergroup Attitudes

<!--intergroup contact.  Define what it is, when it should work.  Then talk about mechanisms: enhance knowledge/increase trust/reduce stereptypes, reduce threat/anxiety, increase empathy, expand ingroup, etc..

Two ways cooperative contact helps reduce conflict.  (1) Increases trust directly, (2) decreases biased information processing.-->

The problems of negative intergroup attitudes suggests that improving those attitudes could lead to peace-promoting behaviors and reduce conflict.  One approach to improving intergroup attitudes comes from intergroup contact theory [@allport1954prejudice].  Intergroup contact theory hypothesizes that intergroup relations can be improved through interactions in which group members (1) cooperate (2) with equal status (3) to achieve shared goals (4) with the support of elites.[^otherContact].  Improving relations -- especially improving trust -- can help groups overcome bargaining problems and reduce the likelihood of violence.

<!--chris: moved from intro -->The effectiveness of intergroup contact has been demonstrated in a variety of contexts and using a variety of methodological approaches [@paluck2017contact; @pettigrew2006meta].  Notably, intergroup contacted programs improved relations between white people and black people in the U.S. South Africa, and Norway [@marmaros2006friendships; @burns2015interaction; @finseraas2017does], Jews and Arabs [@yablon2012we; @ditlmann2016can], and Hindus and Muslims in India [@barnhardt2009near].  In Nigeria, a recent study found that intergroup contact between Muslims and Christians decreased discrimination relative to a group that experienced _intragroup_ contact, suggesting that intergroup contact can work by countering the adverse effects of ingroup-only experiences [@scacco2018nigeria].

Intergroup contact is proposed to affect a myriad of intergroup attitudes.  Here we focus on six: (1) increased trust, (2) reduced anxiety and threat, (3) reduced social distance (4) expansion of ingroup to include the former outgroup, and (5) perceptions of material benefit from cooperation.

[^otherContact]: Under other conditions -- incidental contact, intergroup competition, interactions in which one group has power over the other, elite disapproval of intergroup contact -- the structure of the contact may _not_ improve relations [@enos2014causal; @forbes1997ethnic]<!--hhabyarimana et al 2007; vanhanen 1999-->.]

Intergroup contact gives groups an opportunity to learn about each other and update opinions based on personal experience.  This updating can increase trust and decrease feelings of threat and anxiety [@hewstone2006intergroup; @page2008little].  Intergroup trust increases because contact gives groups the opportunity to signal trustworthiness and preferences for cooperation to the other group [@kydd2000trust, @rohner2013war].  Threat and anxiety reduce as familiarity with outgroup members increases.   Feelings of threat and anxiety often arise from fear of the unknown, and through intergroup contact the two groups to get to know each other.

Intergroup contact can show the groups how their values and interests align, making the groups feel closer.  The increased closeness can manifest as reduced social distance and even a new collective identification that includes both groups.  Groups in conflict often use the outgroup to define the ingroup -- the outgroup's _bad_ness helps define the ingroup's _good_ness [@tajfel1981groups; @allport1954prejudice; @brewer1999ingroupOutgroup].  Contact can make salient many similarities between the groups, reducing feelings of social distance and even helping to craft a joint identity that encompasses both groups [@gaertner2014reducing].

Intergroup contact can also show the groups how their material status benefits from cooperation.  Group animosity often arises due to the competition for resources that both groups claim or desire [@sherif1958superordinate].  Intergroup contact to achieve a goal that benefits both groups (1) alleviates material deprivation and (2) associates intergroup cooperation with positive material outcomes.  By cooperating for joint benefit in the present groups can see how cooperative behavior in the future will benefit both groups.

Contact-based interventions can also assist third-party mediation or intervention.  Helps mediation because the conflicting groups are more likely to update perceptions based on mediated information.  Helps intervention because the groups are still able to commit to agreements without the threat of punishment.

<!--
Intergroup contact has been shown to foster intergroup trust, even between groups with a recent history of violence .   Paragraph about knowledge -- specifically trustworthiness.  Bring in costly signals here.
Could improve reputations/remove stereotypes.  Increase perception of trustworthiness/intergroup trust.  Contact gives opportunity for costly signals.  Reputations will help groups overcome information and commitment problems.  Groups trust information they get from the other group.  Groups trust the other group to abide by agreements because they believe the other group is also motivated by peace.  Costly signals: gives each group the opportunity to give strong costly signals about a group's reputation and the "group type" as a conditional complier: we will honor our agreements if you honor yours.    Structured intergroup contact provides opportunities for these signals.  When the contact is group-to-group, trustworthy behavior by the outgroup is immediately known by several ingroup members.  

Paragraph about emotional reactions. Specifically, empathy and threat. Could change emotional reactions to the group, either by increasing feelings of empathy or decreasing feelings of threat.  ^[though in cases of active conflict this might exacerbate rather than solve conflict (information about reduced outgroup threat == higher chance of my group winning).]  Seeing the other side's argument, seeing their motivations. Increase empathy helps interpret information in non-biased way. [Chris: cite literature on empathy making me interpret information about other people more accurately.  Kertzer?]

Paragraph about reconceptualizing the outgroup.  Could cause groups to reconceptualize their ingroup to include the former outgroup.  Seeing our two groups as one, seeing our incentives as aligned.  

Paragraph about materal benefit / realistic group conflict theory. Other perspectives focus on the achievement of a joint goal that shows both groups they are _materially_ better off [superordinate goal/RGCT].  The intergroup contact to focus on superordinate goals so the groups can see how intergroup cooperation benefits both sides materially [@sherif1958superordinate].  Sees how _both groups_ have a self-interested incentive to cooperate with peace agreements.  Groups work together to gain more material resources, improves us now, makes me think working together in the _future_ would be good. Realistic Group Conflict Theory -- resource competition causes conflict, and intergroup relations improved when the groups work together to improve material status of both groups.

*******

Could create cognitive dissonance that allows individuals to re-evaluate their beliefs [@gubler].

Can give group members interactions that reduce perceptual biases.  And about perceptual fairness/unbiasedness: we will interpret things you do fairly and we will interpret things we do fairly (i.e. we will not think everything we do is justified and everything you do is unjustified).  

Groups wondering which type the other group is and making decisions based on that perception.  If other group will cooperate, we should cooperate.  If other group defects, we should defect.  Groups can learn how each other will respond to big interactions by how they respond to smaller interactions.  

When groups are in conflict, most incidental intergroup contact will be highly adversarial.

Ingroup identification does not necessitate outgroup hate [@allport1954prejudice; @brewer1999ingroupOutgroup; @halevy2008group].
--->


<!--Things From Peacebuilding But Not Contact Necessarily-->
<!--
Other components of peacebuilding interventions can 

Create norms against violence, or connect existing norms to the outgroup by humanizing the outgroup.

Could improve dispute resolution and reduce conflict over resources.  Encourage sharing resources _or_ separation of resources.  Mediation training -- help community leaders resolve disputes.

Can give group members the capacity to affect conflict.
-->
<!--
Can encourage ingroup policing [@ditlmann2017addressing; @Fearon1996].  Ingroup policing works because we cannot do things if our community dislikes those things.  Decrease negative affect allows leaders to credibly commit entire group to peace.  Encourage ingroup policing.  
-->
<!--
**Summary paragraph**

Contact-based peacebuilding programs can reduce conflict by focusing on both the immediate economic concerns contributing to conflict (superordinate goals?) and the psychological attitudes contributing to conflict. Bottom-up psychological reconciliation programs should work for the types of conflicts for which international intervention is rarely used and is unlikely to be successful.  Persistent intergroup conflict that plagues many countries.  Low-level conflict before it builds to large-scale conflict.  There are XX conflicts of this type accounting for XX deaths each year.-->
<!--
## Why Peacebuilding Could Fail

Yet peacebuilding generally, and intergroup contact specifically, may not work in contexts of ongoing violence.  Many top-down attempts to solve bargaining problems with a strong external actor (through mediation and intervention) are ineffective while conflict is going on and only effective at maintaining peace once the formal conflict has ended.  Likewise, psychological reconciliation may prevent resumption of conflict but requires conflict to already be resolved [@bar2000intractable].  Active conflict produces many grievances and high prejudice; cognitive dissonance causes backlash for the most prejudiced people [@festinger1962cognitiveDissonance; @gubler2011diss].  Negative contact experiences reinforce negative stereotypes [@paolini2010negative]. Motivated reasoning for attitudes towards others [@klein1992motivated].  If you don't want to like someone, you will find a reason not to.  Many reasons contact may not work in this context.

Intergroup conflict is commitment problem solved by strong third party [@fearon1994ethnic; @powell2006war] and bottom-up programs do not provide a strong third party that can enforce commitments.  Psychological reconciliation is not how we've thought of solving commitment problems between conflicting groups or improving reputations.  Can psych reconciliation improve reputations in contexts of ongoing violence?  

Underlying cause of conflict still present.  Groups still engage in competition for resources, which breeds conflict [@campbell1965ethno; @Sherif1988robbersCave].

The intergroup animosity comes from real conflict, not the type of prejudice that Allport and others theorized about.  Through contact, you might learn that the other group _does_ favor itself.  Contact might show you that the other group _will_ defect on agreements.

Few norms against prejudice, possibly group norms that support this particular intergroup prejudice.  If intergroup contact works by activating "norms against prejudice", unlikely to work here.

Intergroup contact may only reduce prejudice from high-status group to low-status group.

Relative deprivation theory: the groups still see the other as responsible for ingroup deprivations.
-->
<!--
## Hypotheses

We have several hypotheses about the way that contact-based peacebuilding programs can improve intergroup relations.  We add distinctions demarcating families of hypotheses, and we define a family of hypotheses as the set of hypotheses that would help make one decision or answer one question.  If a set of hypotheses are part of one family we will adjust the p-values within those families following the False Discovery Rate (FDR) method.

- $\mathbf{H_0}:$ **The treatment will increase information about city rates among treatment households vs. control households.** (Confirmatory)
    - The information campaign will increase the amount of information individuals have about the most important citizen-facing services that are under the purview of Zomba City Council, the relationship between city rates and these services, the existence of the ability to make payment through bank transfers, and the existence of a municipal tax forgiveness plan.


- $\mathbf{H_0}:$ **The treatment will increase information about city rates among treatment households vs. control households.** (Confirmatory)
    - The information campaign will increase the amount of information individuals have about the most important citizen-facing services that are under the purview of Zomba City Council, the relationship between city rates and these services, the existence of the ability to make payment through bank transfers, and the existence of a municipal tax forgiveness plan.

  - $\mathbf{H_1}:$ **The treatment will increase the intent to formalize among treatment households vs. control households.** (Confirmatory - Formalization Hypotheses Family)

-->


# References

<!--

# Other Stuff

**Solving Bargaining Problems section**
[chris: formerly had bigger discussions of mediation and intervention.]

[^bargainChange]: Commitment problems occur for many reasons.  A prominent reason is shifts in power between the bargaining groups.  Power between the groups can shift due to factors that affect each group's preferences and capabilities. Internally, one group may grow in power or size, one group may disarm before the other, the groups may have factions that reject the agreement, the groups may change leaders, or group members attitudes may change for other reasons.  Externally, the groups may gain or lose de facto or de jure state support, other external actors may switch allegiances, or some other shock may change each group's power relative to the other [@fearon2004civil; @reed2016bargaining].  Anything that will change group power in the future can cause commitment problems in the present.[chris: maybe I do not need this footnote now.]

"Groups in conflict overcome information and commitment problems in several ways.  

The two principal ways that groups overcome information problems are (i) fighting and (ii) third-party mediation.  Through fighting, the groups directly observe each others capacity and willingness to fight [@smith2003mediation].  Through mediation, the groups receive accurate information about each other from a third-party [@ott1972mediation; @kydd2006can; @beber2012international].

The two principal ways that groups overcome commitment problems are through (i) intervention by strong third parties that add large costs to reneging on agreements, and (ii) reputations for trustworthiness.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1998commitment; @powell2006war; @doyle2000international].  Likewise, groups have less incentive to defect on agreements if defection affects a group's reputation.  Future bargaining depends on groups trusting each other to abide by agreements, and groups with reputations for defection are unlikely to attract other trustworthy partners or elicit trusting behavior from partners [@ostrom2003trust; @kydd2000trust; @rohner2013war].  With these incentives for cooperation, the groups can bargain in good faith knowing that the other will abide by its word.[^reputation]"

"If we know how to resolve intergroup conflict, why does conflict persist?  Issues of bias prevent mediation from solving information problems.  Issues of capacity and motivation prevent intervention from solving commitment problems, and psychological biases prevent reputations from solving commitment problems.

Mediation and intervention are dogged by two issues of motivation.  First, mediators are often motivated for peace.  This motivation implies that mediators provide information that is biased towards encouraging the groups to negotiate a peace agreement.  For mediators to reduce information problems, groups engaged in bargaining must believe that mediators provide accurate, unbiased information.  Since both groups know that mediators are biased towards peace, mediators do not solve information problems and may not help groups achieve peace [@smith2003mediation; @kydd2006can; @fey2010shuttle].  This same argument prevents mediators who are biased for or against disputants from solving information problems [@kydd2006can].[^mediation]

Second, international actors may lack the motivation to mediate or to intervene into the conflict, even if one group reneges on its agreement.  Intervention is costly and many international actors either cannot credibly commit to intervene into many conflicts or have no interest in intervening into many conflicts [@kydd2006can; @fey2010shuttle; @beber2012international].  This lack of motivation is especially relevant for intergroup conflict between groups within a state.  Most international actors and strong third parties lack an incentive to intervene into intrastate intergroup conflicts, and these disputes tend to take place within states that lack the capacity to compel both sides themselves.  Since intervention is costly, strong third parties have an incentive to intervene only _after_ fighting escalates, so intervention will generally not be used to prevent conflict from escalating or to reduce the persistent, smaller-scale violence that plague many countries.  Where external actors are motivated to intervene, intervention is a short-term peace solution and its effects do not endure with the departure of the external actor [@rohner2013war; @beardsley2008agreement; @weinstein2005autonomous].  Once the external actor leaves, the groups' commitment problem returns: with no one to punish defection, the groups have no reason to trust each other."

[^mediation]: Whether mediation is benefited from biased or unbiased information is still a matter of debate.  Some scholars believe bias improves mediation.  The primary mechanisms proposed are that biased mediators are more likely to have relevant private information [@savun2008information] and that a biased mediator who tells his _favored_ group to compromise will be heeded [@kydd2003side; @svensson2009brings].  We tend to side with @beber2012international, @rauchhaus2006mediation, @crescenzi2011supply, and @kydd2006can and believe that unbiased mediation improves mediation outcomes.  @kydd2006can and @beber2012international provide compelling theoretical arguments: effective mediators must be both unbiased and motivated, but that motivation and bias often overlap.  We are also amenable to the argument of @fey2010shuttle that mediator success actually has less to do with information provision and more with agenda setting, offering carrots/threatening sticks, and serving as a back channel.



In this case, bias for or against one side of the conflict can increase the effectiveness of intervention [@kydd2003side; @regan2002third] because it provides motivation for the international community to intervene in the conflict.

"In many conflicts, the conflicting groups are not united and therefore it is not clear who is involved in bargaining and who the external actor should punish if one side defects."
-->


<!--

**About Reputation**
Commitment problems are problems of trust.  The trust can be through a third party or between the groups directly.

Reputations for trustworthiness are how groups overcome bargaining problems in the absence of formal enforcement mechanisms [@ostrom2000collective; @kydd2000trust, @rohner2013war; @ostrom2003trust].  Mutual trust overcomes bargaining problems because information and commitment problems are both, at their heart, problems of trust.  For information problems, groups do not trust the information they receive from the other side.  For commitment problems, groups do not trust the other side to abide by its agreements.  Cultivating a reputation as a trustworthy partner in previous interactions gives a bargaining partner confidence that you are trustworthy in the present interaction.


*******

**Thoughts about trust**

@ostrom2003trust ch.2 discusses how reciprocity, reputation, and trust help overcome selfish behavior that leads to pareto-inferior outcomes;  players achieve self-enforcing equilibria by comitting themselves to punishing noncooperators to deter noncooperation; repeated games & uncertainty about player types increases cooperation; face to face interaction increases cooperation bcuz increases trust, also could add subjective value to payoff structure, gives group ID, reinforces normes, not because players realize optimal strategies and not from non-face-to-face promises.  People seek to improve values they find important.  People use heuristics; people use internal evaluations that add or subtract from objective payoffs (+ for feeling good, - for being a sucker);    ch.12 discusses how trust is minimal in situations where reputations for trust cannot be established.  @hardin2003 ch.3 gaming trust -- concept of mutual trust: trust based on long-term interaction between two parties.  Thick trust: diverse layers of interaction; interactions in one layer influence interactions in another; repeated relationships and 3rd party relationships. @hardin2002trustAndTrustworthiness talks about being trustworthy. @kydd2003 and costly signals of trustworthiness. Trust and Reciprocity 2003 ch.15 - knowledge of the other, repeated interactions, and strong possibility of future interactions predict trustworthy and trusting relationships.-->

<!--
**Thoughts about intergroup prejudice**
@tam2007 intergroup prejudice = less likely to forgive, and forgiveness is a key to intergroup cooperation [@axelrod1980effective].  Prejudiced groups cannot put previous transgressions behind them.  @gutsell2010empathy people do not naturally feel empathy for outgroup members. 

Conflicting groups dehumanize the outgroup, meaning that they do not acknowledge the outgroup as fully human [@haslam2014dehumanization; @leyens2007infra; @opotow1990moral; @bandura1999moral].  Dehumanized groups are deemed unworthy of moral considerations; they do not deserve empathy, compassion, or fair treatment.  Along with not extending morality to outgroup members, ingroups often view of the outgroup themselves as immoral -- a group without values who cannot be trusted due to their innate moral deficiencies [@weisel2015ingroup; @parker2013lessons; @brewer1999ingroupOutgroup, p.435].

Wood's 2000 review of persuasion gave two additional functions of attitudes that apply to intergroup attitudes: self-concept and social adjustment [@wood2000attitude].  Self-concept refers to an individual's identity.  If an individual's identity is strongly related to ingroup superiority, she may not want to have better attitudes about the outgroup.  Social adjustment refers to an individual's desire to obtain social rewards.  If an individual's group opposes the outgroup and sanctions those who do not oppose the outgroup, she also has a strong reason to maintain negative outgroup attitudes.

***********

# Moved from Intro

When both groups desire some valuable $X$ they must come to an agreement about the division of $X$ based on the existing strategic situation.  In dynamic settings where the strategic situation is unstable, groups cannot credibly commit to abide by their agrements; when the situation changes, one group will have an incentive to renege on the deal.  Bargaining breaks down because both sides know that neither can credibly commit to any bargaining agreement.  In the absence of a bargained solution groups use violence to settle disputes over $X$.  In this view, the solution to intergroup violence is a strong neutral third-party to solve the comittment problem by compelling each side to honor bargaining agreements.  This is an example of institutions constraining behavior.<!--Possibly next paragraph talks about government intervention over land use to compel each side.  But government is weak and unable to compel each sides; and pastoralists view the government as very partial to the farmers. -->
<!--
Intergroup violence is also considered a product of intergroup prejudice and dehumanization ^[cite: humanizing the outgroup stuff, @halperin2011emotional; also cite: tajfel, ].  Chris: argument.  In this view, the solution to intergroup violence is to reduce prejudice and humanize the outgroup; provide superordinate goals that show groups the benefit of working together.  

Even some proponents of the psychological perspective doubt the ability of intergroup contact to reduce violent conflict [@gubler; @saguy2011tension; others.]
-->

<!-- 
Models say intergroup bargaining should work.  Groups should be able to form reputations for trustworthiness.  Groups are not doing so.
Negative affect makes it difficult to develop intergroup trust.
intergroup contact can increase trust even when groups don't like each other.



The story is "Theoretical models of conflict say that groups should be able to solve their problems through bargaining.  When external actors are not present to guarantee bargained agreements, groups use trust.  But it's hard for groups who don't like each other to develop trust.  Cooperative contact can build trust even in these contexts."

The only thing we do not specifically measure is "these groups don't like each other".  I don't think readers will reject the idea that these groups dislike each other.

The lack of effect on intergroup cohesion, which you cited above, is not a problem for this "trust" theory.  No increase on cohesion means the groups are not seeing themselves as more similar.  The trust theory would not say that these groups would see themselves as more similar.

@ichheiser1949misunderstanding: In this monograph supplement certain implicit assumptions which may distort the analysis of human relationships are discussed. Sources of misinterpretations include: (1) a tendency to over-estimate the unity of personality. (2) emphasis in our culture on success and failure, (3) stereotyped classifications, (4) lack of awareness of the limits of insight, and (5) a tendency to overestimate the role of personal and to underestimate the role of situational factors.

@liberman2004name: PD as community game vs wall street game.
@ward1997naive: People assume that they are rational.  We thus assume other rational people will share our views. We assume other people deviate either because (1) they don't have the right information, or (2) they are lazy/stupid, or (3) they are biased.  Biased assimilation of information: Historf and Cantril 1954 about sports fans, and Lord et al 1979 about political issues.  Don't forget Gaines & Kuklinski Same Facts Different Interpretations.  Anyone disagreeing with my side is obviously biased and lacks objectivity.  Vallone et al 1985 Israel-Arab conflict.  Partisans think their own side, and the other side, is more consistent/homogenous.  p.23 Keltner and Robinson 1993 - reducing misperceptions about other's construals/beliefs leads opposite sides to view each other more favorably & encourages search for agreement.  ME: We want to make allies! p. 23-24: egocentrism and naive realism creates barriers to negotiation and dispute resolution.
Difficulty of negotiation: (1) different construal of conflict history and who is to blame/the aggressor, (2) different construal of actions as hostile or defensive, (3) different construals of future gains in strength and trustworthiness of the groups.  Disputants disagree about proposals they give both parties what they need and deserve.  Disagreements about the proposal further heightens enmity and distrust (p.24).  Reactive devaluation: If the other side proposed it, it isn't that great of a deal; we value things we do not have over things we do have.  p.29: perception of self-other similarity can promote conflict resolution.
Chris: overestimate their own strength.
-->

<!-- EKREM STUFF:
Ekrem: "I am a proponent of highlighting how contact can complement our existing tools both by using it when intervention is not possible and also by using it when it is possible to make it work better."
"suppose I succeeded in this intervention and there is no animosity or information problems.  YET these groups still have conflicting incentives.  Third-party intervention can solve that, this intervention did not."
Earlier Ekrem: "(1) it's not clear how mediation could even function when parties to the conflict are not reasonably organized, but instead conflict is communal / dispersed. so here we could lean more heavily on bottoms-up stuff.  (2) in situations where mediation should work, bottoms-up is still good, because one way bottoms-up solves our problems is by removing frictions which sort of prevent rational belief updating and proper learning from data. so bottoms-up should make mediation more likely to be effective."-->

<!--Ekrem: I think you can make this part leaner and meaner by imposing a structure where you say

Animosity increases problems via 2 main channels

1) Via social/psychological mechanisms which increase costs of cooperation and benefits of defection (1a personal, 1b social, 1c constraining leaders)

2) Prevents accurate interpretations of signals. Blocks the pipes (which is the second part) -->
