---
title: "Promoting Peace Amidst Escalating Conflict: An Intergroup Contact Field Experiment in Nigeria - Context"
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--
Comes after theory.  Intervention Details moved to design.

## Context Outline

- distirbution of the lands: map that shows the regions: Fulani region, farmer region
- The setting: rural, economic
- the background: these populations used to get along, but population booms and climate change reduce land:people ratio
- The conflict: escalating, burnt village/livestock guard, expulsion
-->

## Context

Farmer-pastoralist conflict in Nigeria's Middle Belt provides a context to learn about intergroup conflict.  Nigeria’s Middle Belt divides the country between north and south, and houses a blend of various ethnic groups, with no clear majority. The south comprises primarily Christian farmers from various ethnic groups, while Muslims from the Hausa and Fulani ethnic groups — including the mostly Fulani pastoralists — dominate the north of the country. These religious, ethnic, and occupational identities intersect and create deep fault lines between communities.   Historically, these communities interacted through trade and shared access to land.  However, in recent years, interconnected factors have made these interactions more contentious.  The Middle Belt has been stressed by climate change, population booms, migration, and government policies perceived to favor some groups over others.  These stressors have sparked violent conflict between farmers and pastoralists in recent years.

Climate change contributes to the conflict in two ways.  First, changing climate has reduced available water sources and land conducive to farming or grazing.  As the Sahara expands southward [@thomas2018sahara] and water sources dry [@okpara2015conflict], farmers and pastoralists have to share fewer resources.  Second, changing climate pushes more pastoralists southward into the Middle Belt.^[In addition to the role of resource scarcity, @hoffman2004role also suggests that southward transhumance by Tuareg groups pushes Fulani pastoralists further south.]  Their southward migration of pastoralists who formerly resided in northern Nigeria causes even more demand for land and water as those resources are becoming scarce.

Land scarcity is exacerbated by Nigeria's population boom.  Nigeria's population increased from 73 million people in 1980 to an estimated 200 million people in 2019.  The rapidly growing population means increased demand for farming and grazing land, simultaneous with the decreasing supply of farming and grazing land.  The dual pressures of increasing demand and decreasing supply have fueled farmer-pastoralist conflict in recent years [@unah2018nigeria].  Sharing land is easier when people are scarce and land is plentiful; it is not so easy when land is scarce and people are plentiful.

Land scarcity and new migrants jeopardize traditional agreements that have managed farmer-pastoralist interactions for decades.  Farmers and pastoralists residing in Nigeria's Middle Belt developed agreements about seasonal land sharing, exchanges for crop residue and animal manure, compensation for damage to crops by livestock, and other arrangements that helped them share resources and avoid conflict.  As land scarcity increased, these traditional agreements were increasingly broken [@cotula2004land; @kuusaana2015land].  These agreements were also less likely to be implemented by the pastoralists migrating into the Middle Belt, who were unaware of these agreements and not involved in forging them.  Their use of land beyond these traditional agreements has further ignited tensions.

Grievances related to access land and water points are compounded by government policies perceived to favor farmers.  Land privatization enacted in recent decades encouraged farmers to plant crops that occupy land continunously, like orchards, and effectively nullified farmer-pastoralist land sharing agreements [@basset2009mobile].  Official cattle routes and reserves for moving herds are rarely enforced by the government, leading farmers to plant crops in once-protected areas, which further limits pastoralists’ available grazing space.  The “indigene versus settler” policy limits land ownership and other rights, including political representation, to certain ethnic groups in each state [@nigeria2014freedom].  Certain communities -- often pastoralists, who are seen as “settlers” -- are denied the right to run for public office, limiting the incorporation of their views into local policies.   

Compounding matters, the government of Benue State enacted an anti–open grazing law in November 2017, sparking more violence because many pastoralists reasonably viewed the law as biased against their way of life.  Benue mobilized state-sanctioned vigilante groups called "livestock guard" to enforce the law, but the livestock guard have sometimes sought out pastoralists, rather than guard farmland.[chris: @duru2018court benue police arresting livestock guard and benue courts releasing the guard; cite other news articles about livestock guard]

These factors -- climate change, increasing population, migration, and government policy -- have broken the agreements that previously governed interactions between farmers and pastoralists.  These factors have challenged the interdependence among the groups and the benefits and costs of reaching agreements.  As farmers in Nigeria began to raise their own livestock [@hoffmann2004role], the need for manure from pastoralists decreases.  As governments allocate private property to settled people, pastoralists increasingly destroy crops when using ancestral grazing routes.  And as demand for agriculture products rise, prices for crop destruction must increase to account for lost revenue.  These changes could seem like "defecting" on previous agreements, suggesting to each side that the other is untrustworthy.  Perceived untrustworthy behavior begets a cycle of distrust, culminating in the violent farmer-pastoralist conflict of recent years.

<!--The conflict is primarily _economic_ in nature -- groups fighting for land rights, with goals that are mainly local and territorial.  But these conflicts are exacerbated by ethnic and religious differences.-->

This persistent violence continues to have debilitating effects on Nigerians and the economy. First, it has taken many lives. In 2013 alone, Plateau, Kaduna, Nasarawa, and Benue states registered more than 100 incidents of violent conflict, accounting for more than 1,050 deaths (Mercy Corps 2018). The more recent violence left 300,000 displaced [@nyt2018nigeria] and more than 1,476 dead in 2018 [@council2019nigeria]. The Middle Belt is considered Nigeria’s “food basket” and is central to key value chains throughout the country, including beef, dairy, and cash crops such as cassava. This violence has impeded food production and threatens to create a food shortage [@frontera2018nigeria]. Before the latest surge in violence, the conflict was costing the Nigerian economy $13.7 billion a year [@mcdougal2015effect].  As one reporter noted, "The countryside is littered with the charred ruins of homes, schools, police stations, mosques and churches." [@mcdonnel2017graze].

Farmer-pastoralist conflict in the Middle Belt is not dissimilar from current and past conflicts in other parts of the world.  Throughout Sahel -- farmer-pastoralist clashes are a persistent problem throughout the Sahel and savannah areas of Africa, including Mali, the Ivory Coast (Bassett 1988, 2009), Niger (Thebaud and Batterbury 2001), and Ghana (Tonah 2002).  Farmer-pastoralist clashes are destabilizing to these countries politically, socially, and economically.  In South Sudan, Myanmar, Bosnia.  "Range wars" between farmers and ranchers in 19th and early 20th century American West.  Can learn about intergroup conflict generally from farmer-pastoralist conflict in Nigeria's Middle Belt.  These conflicts are primarily rural and the state does not project power to these areas.  It is often viewed as biased for or against one group.

## Intervention

The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.  It started with a series of community meetings, beginning with separate farmer and pastoralist meetings that built up to joint decision-making meetings with the two groups together.  Each joint project committee included an even number of farmers and pastoralists, as well as women and youth representatives, and totaled between 12 and 15 members. Each committee received two grants, one for quick-impact projects, of approximately \$2,000, and one for joint projects, of approximately \$25,000.

The quick-impact projects were conceived as a trust-building initiative, intended to let community members see that cooperation was possible. Projects, managed by both farmers and pastoralists, included hand pumps, construction or rehabilitation of market stalls and schools, rehabilitation of health centers, and construction of fences along grazing routes to protect farmlands. The joint economic development projects aimed to address an underlying issue related to the conflict: sharing of resources that impact livelihoods. Pollution of water, affecting both farming and livestock, was the primary issue people raised. As a result, each site received a new borehole well, with farmer and pastoralist youth helping to construct the wells.  

The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.

These projects were designed with the conditions of Contact Theory in mind.  Groups (1) cooperated with (2) equal status to achieve (3) shared goals with (4) support of local authorities.  These projects were meant to help the groups solve some underlying resource problems that drove conflict.  Collectively, these project give groups the opportunity so send costly signals about their willingness to cooperate [@kydd2000trust, @rohner2013war].

Will these cooperative interactions allow each group to trust the other?


*******

<!--
# Scacco

-->