---
title: "Intergroup Contact Amidst Escalating Conflict - Theory"
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Thinking

Big framing points/3 pills:

- Contact theory can be effective even if economic incentives opposed
- Contact theory can be effective even amidst an escalating conflict
- Most benefit to direct personal contact, but benefits diffuse to ingroup members with no personal contact.

## Theory Outline

Some studies suggest that contact in these contexts might increase prejudice.   [Chris: Ryan Enos, Gubler, negative contact guy].  Can direct intergroup contact overcome conflict and economic factors to reduce prejudice in places most in need of prejudice reduction?

Gaunt et al - Motivated Reasoning and the Attribution of Emotions to Ingroup and Outgroup
Dhont et al - https://pdfs.semanticscholar.org/76f8/74c6fcc7067332f42ef4848f5878a184c152.pdf

Sidanius and Pratto 1999/2001 - social dominance theory

Violence requires justifying why the violence was okay.  Strong motivation to maintain negative attitudes.

Enos - contact increasing prejudice.



## Theory


*******

<!--
# Scacco

-->