---
title: "z_b_introOld"
author: "Grady"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Old again

# Thinking

Big framing points:

- Contact theory can be effective at reducing real world conflict.
- Contact increases intergroup trust, which allows groups to bargain even in the absence of external costs of breaking agreements.

Intergroup conflict is often characterized as a bargaining failure<!--Prisoner's Dilemma?-->.  Both groups would benefit from compromise, but negotiations break down and conflict ensues because neither group trusts the other to abide by their agreements.  The proposed solutions are coercive institutions that prevent groups from defecting on bargained agreements.  However, coercive power cannot reach many group conflicts.  We propose intergroup contact as an alternative to coercive institutions.  Coercive institutions substitute for intergroup trust, but intergroup contact can foster intergroup trust directly by creating situations in which groups can signal their trustworthiness.  Intergroup trust allows groups to bargain even in the absence of coercive institutions.

Theory sections tend to summarize a literature and then apply it to new area.

# Outline/Presentation intro slide

- Intergroup conflict as commitment problem, solved by institution that can enforce commitments [@fearon; @powell]
- Institutions that constrain behavior cannot always be present
- Intergroup trust serves as social institution that solves commitment problem
- Intergroup contact creates intergroup trust

# Theory (12-20 para)

Two big theoretical literatures on intergroup conflict.  One sees intergroup conflict as bargaining problem.  The other sees intergroup prejudice as a prejudice problem.

Intergroup conflict is often considered the result of bargaining failures.  Groups have disagreements, but through bargaining they should be reach a compromise that prevents conflict.  Neither group _wants_ conflict because conflict is very costly for both groups.  Groups fail to reach bargaining agreements primarily due to comittment problems -- neither group trusts that other group will honor comittments [@fearon; @powell].  Groups cannot be trusted to commit to agreements for a variety of reasons.

[^bargainFail:] Other reasons are incorrect information.

The solution to the comittment problem are institutions or external actors that punish defection from agreements.

These institutions cannot always be present.  State power does not reach everywhere.  No neutral/trusted arbitrator.  Enforcement expensive.  Need something that functions like police but without police walking around punishing everyone

These institutions substitute for intergroup trust.  We can bargain without external enforcement if we trust each other to uphold agreements.  Bargaining allows groups to reach a non-violent outcome.

## Intergroup Contact

Intergroup contact creates social institutions that affect/constrain behavior. Intergroup contact theory: Intergroup cooperation to achieve common goals in an equal status context with the support of authorities reduces prejudice [@allport1954prejudice]
- Shown effective in many contexts [@pettigrew2006meta]
- Intergroup contact produces trust via opportunities for costly signaling(<!--through ingroup policing?)--> and increased likelihood that defections from agreement will become public and therefore punished.


**It could convince the groups that cooperation is good**/**It could decrease the social benefits of conflict**
Changing the game: [c,c] payoffs higher than [c,d or d,d] payoffs.  Before contact, could get social benefits to defecting and social costs to cooperating, so cooperating was not in anyone's interest.  After contact, social benefits from cooperating and social costs to defecting. Or something like that.

If groups hate each other, maybe social benefits to attacking the other group.  Feels justified.  If groups don't hate so much, maybe social costs instead.

** It could convince the groups that the other side will cooperate**
Allows costly signaling that my groups type is conditional complier, not defector.  Increases trust that other group will cooperate.  Increase opportunities for group reputations to increase.  In game theory terms, direct reciprocity.

**It could increase the acceptable bargaining space**
Before, both groups would only accept agreements where they got 75% or more, so there was no agreement space.
This is more a story about perceived strength: why would I only accept bargaining where I would receive 75%+ if I thought the alternative to bargaining was you beating me and taking 100%?




**Alternative Mechanisms of Intergroup Contact**
Generalized trust -- no increase to "people of other religions/ethnicities"
Decreased threat -- nope
Ingroup increases to include other group -- intergroup cohesion does not seem to increase.  Probably not that ingroup norms being extended to outgroup.
incresed empathy -- no questions address this, or intergroup cohesion 2?
Perceived benefits of cooperation -- maybe?  But contact does not increase this.

**Limitations**
Most effective for small, cohesive ingroups.

### Optimist Camp: 5 para

Intergroup contact.  Realistic group conflict theory (functional interdepence between groups to reduce conflict.  Achieve a series of superordinate goals that neither group can achieve alone).



### Pessimist Camp: 5 para

This is a comittment problem.  Neither group can commit to cooperating, and each group only wants to cooperate if the other cooperates.  Solution is to impose high cost for defecting, usually through some third actor.


### Synthesize: 4 para

Comittment problem is a trust problem.  Interventions that increase intergroup trust should ameliorate comittment problems.

Trust can increase a two ways.  Group _leaders_ increase trust that the leader will punish defecting ingroup members.  Group members increase trust that outgroup members will not defect.  Not distinguishing between those ways and probably not mutually exclusive.

^[Simplest way to think about the problem in game-theoretic terms: one player & one stage game where P1 can cooperate or defect.  P1 has a belief about the type of P2; P2 has some probability of being a complier, conditional complier, or defector.  P1s payoffs for c/d depend on P2 type.  And the intervention increases P1's belief that P2 is conditional complier.  More complicated way is akin to Fearon's comittment problem.  Maybe has P2 signal its type to P1.  Intergroup contact allows for strong signal to P1.]

Negative contact increases prejudice more than positive contact decreases prejudice [@barlow2012contact]

# Notes

### General

Many conflict scholars see intergroup conflict as a bargaining game.  Conflict occurs because of a bargaining failure -- incorrect information [chris:cite], lack of trust that other group will honor comittments [@fearon; @powell].  The solution is a 3rd party -- another group, the state, social institutions like laws and customs -- powerful enough to compel both sides to honor their comittments.  Contracts & law are ways we can trust people without knowing them.  Large costs to defecting on our agreements help everyone trust that agreements will be kept.

But 3rd parties of this sort are not always possible.  Sometimes no state is strong enough to project power onto the conflicting groups.  Projecting power is expensive.  But groups do not necessarily need coercion to solve collective action problems.   Groups can develop social norms that constrain behavior, which are often more efficient than coercive appartus [@ostrom2015governing; @Ostrom2000evolution].  But sometimes social norms to solve conflict are not present or have broken down.

Intergroup contact is a solution to intergroup conflict from the psychological perspective.  Intergroup contact theory hypothesizes that interactions in which group members cooperate to achieve shared goals will reduce prejudice and the likelihood of violence by demystifying the outgroup, presenting the other group's perspective, and replacing imagined stereotypes with firsthand knowledge [@allport1954; @pettigrew2008does].  

Ostrom: grassroots norms. "a social norm, especially in a setting where there is communication between the parties, can work as well or nearly as well at generating cooperative behavior as an externally imposed set of rules and system of monitoring and sanctioning" [@ostrom2000evolution]

Comittment problems are trust problems: "the choice is not to trust, because the expectation is that the other player will not trust" [@ostrom2000evoluation]"

Ostrom on communication: "By devising simple, local mechanisms to get conflicts aired immediately and resolutions that are generally known in the community, the
number of conflicts that reduce trust can be reduced." [@ostrom2000evoluation]

Intergroup contact creates social institutions that affect/constrain behavior.

**It could convince the groups that cooperation is good**
Changing the game: [c,c] payoffs higher than [c,d or d,d] payoffs.  Before contact, could get social benefits to defecting and social costs to cooperating, so cooperating was not in anyone's interest.  After contact, social benefits from cooperating and social costs to defecting. Or something like that.

** It could convince the groups that the other side will cooperate**
Allows costly signaling that my groups type is conditional complier, not defector.  Increases trust that other group will cooperate.  Increase opportunities for group reputations to increase.  In game theory terms, direct reciprocity.

**It could increase the acceptable bargaining space**
Before, both groups would only accept agreements where they got 75% or more, so there was no agreement space.
This is more a story about perceived strength: why would I only accept bargaining where I would receive 75%+ if I thought the alternative to bargaining was you beating me and taking 100%?

**Alternative Mechanisms of Intergroup Contact**
Generalized trust -- no increase to "people of other religions/ethnicities"
Decreased threat -- nope
Ingroup increases to include other group -- intergroup cohesion does not seem to increase.  Probably not that ingroup norms being extended to outgroup.
incresed empathy -- no questions address this, or intergroup cohesion 2?
Perceived benefits of cooperation -- maybe?  But contact does not increase this.

**Limitations**
Most effective for small, cohesive ingroups.

### Pessimist Camp

Some studies suggest that contact in these contexts might increase prejudice.   [Chris: Ryan Enos, Gubler, negative contact guy, Devine et al 2002, Devine 1989, Fiske 1989, Bhavnani et al 2014 is like Gubler, other Scacco theory citations].  Can direct intergroup contact overcome conflict and economic factors to reduce prejudice in places most in need of prejudice reduction?


### Optimist Camp

A notable exception is the @Scacco2016 study in Kaduna, Nigeria, a city with a history of religious riots.  But that context does not mimic many aspects of a conflict context (frequent violence, zero-sum economic goods) that could influence intergroup attitudes and reduce the effects of contact.  That study also showed null effects for intergroup contact but negative effects for intragroup contact.  That was also not a peacebuilding program (social norms) and the intervention sought to diminish group affiliations, rather than highlight them -- salient group affiliations is an important component of intergroup contact.

Allport thought behavioral consequence of prejudice was group violence.

From Scacco: "these interventions are driven by the premise that macrolevel peace and stability can be built from the ground up (Cárdenas 2013; Kuriansky 2007; Gasser and Levinsen 2004;Maoz 2000)."

### General

Gaunt et al - Motivated Reasoning and the Attribution of Emotions to Ingroup and Outgroup
Dhont et al - https://pdfs.semanticscholar.org/76f8/74c6fcc7067332f42ef4848f5878a184c152.pdf

Sidanius and Pratto 1999/2001 - social dominance theory

Violence requires justifying why the violence was okay.  Strong motivation to maintain negative attitudes.


We also want effects of intergroup contact for some ingroup members to diffuse to other ingroup members who have no contact.  The most prejudiced individuals will probably avoid contact, but if effects of contact from other ingroup members diffuse to these very prejudiced individuals -- either through vicarious/imagined contact or through social norm transmission -- intergroup contact could reduce prejudice even for individuals who do not engage in intergroup contact.


## Me

Bridging psychological and rationalist theories: still fundamentally a comittment problem.  But need to increase intergroup trust (belief that group will committ to agreement) and reduce intergroup prejudice (psychological benefit I get from hating the outgroup/feeling superior -- makes cost of conflict lower because adds some psychological benefit to conflict).  Strategic situation equation needs to adjust for psychological variables like trust and prejudice.

Overcoming comittment problem: Community leader involvement is very important -- leaders are often the ones bargaining, _and_ each side may trust that the other groups leaders can prevent/punish defections from his group.  Ingroup Policing.

### Democratic Dilemma: Ways to increase trust between two players

Costly Signals

Penalties for Lying.

Likelihood of Verification of the speaker's words by some other party.

