---
title: "Promoting Peace Amidst Escalating Conflict: An Intergroup Contact Field Experiment in Nigeria - Ekrem Talk"
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Discussion

heart of conflict
1- information problems
	- don't know other side's power; incentives to mislead.
2- comittment problem
	- solution: no standard solution
	- 3rd party guaranteer & 3rd party can punish
		- some research about what a biased mediator can accomplish in other situations. Maybe cite 1-2 things if reviewer wants.

Millions of reasons can make us arrive at one of these problems

indivisibility not important: can trade other things (side-transfers)


Intergroup contact can help solve both problems. 
Contact --> Information exchange --> knowledge that helps overcome.  But still have incentive to mislead.
	- have incentives to mislead if we have a comittment problem. Prisoner's dilemma
	- have no incentive to mislead in a coordination problem.
	- Ekrem: bargaining situation is a coordination game with penalties, not exactly a comittment problem. Want to coordinate, but have incentives to misrepresent.
	- in what situation, and how much, can 
Contact --> trust --> not going to renege, will punish ingroup.
	- axelrod: conditional compliers
	- reputations: take actions that are costly (ingroup policing) during bargaining to signal that you are a conditional complier
		- does not work in completely conflicting interest
If Intergroup Contact is not helping with information transmission, how does it help?
	- constructivists: way I define my own preferences is changing because of the contact.
		- changing how people see the game/change the game people are paying. Change their preferences.  joint identity.

Some of these discussions are similar to IR debates in the 90s.  
US and USSR.  comittment problem, overlapping interests in not blowing up whole world.  IR Constructivists were making arguments that I would like after USSR collapse and Russia came about, and everything worked find.
Two groups with somewhat shared itnerests, but a comittment problem.  Can we make the situation better by working together, talking, etc...
Fearon and Wendt article.



1 - establish that this is comittment problem
2 - establish that comittment problems are very tricky.  don't know how to solve them by talking; need to introduce external actors/mechanisms through which one of two parties can commit.
	- not obvious how intergroup contact would help this situatuation.
3 - talk about why intergroup contact would work. Connections between those mechanisms and intergroup contact: 

Don't call it "rationalist viewpoint", call it conflict scholars or something.