---
title: "Promoting Peace Amid Escalating Conflict: An Intergroup Contact Field Experiment in Nigeria - Overall Outline"
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Intergroup conflict is responsible for many of the worst displays of human nature.  In this paper we test the ability of psychological reconciliation through intergroup contact to contribute to peace between groups involved in violent conflict.  Intergroup conflict often mitigated by groups outside the conflict, like foreign military intervention (peacekeepers), foreign mediation, or 3rd party that enforces bargaining agreements.  However, intervention by outside groups is costly, time-consuming, cannot influence many intergroup conflicts, and not universally successful at reducing violence.  We propose psychological reconciliation through intergroup contact as an alternative to outside factors.  Groups in conflict develop negative attitudes about the other group that make peace impossible.  Outside groups often serve as substitutes for positive intergroup attitudes, but psychological reconciliation could improve intergroup attitudes directly.  Improved intergroup attitudes should allow the conflicting groups to settle disputes even in the absence of outside actors.  We test the ability of psychological reconciliation programs to promote peace between violently conflicting groups with a field experiment in Nigeria, where farmer and pastoralist communities are embroiled in a deadly conflict over land use.  We find that the programs increase intergroup trust and the physical security of group members.  We do not find evidence for alternative mechanisms through which psychological reconciliation could reduce violence, such as reducing outgroup threat or expanding the conception of ingroup to include the former outgroup.  These results suggest that psychological reconciliation can promote peace between groups in conflict.


# Intro

<!--Start concrete with a story so people really understand.  Then zoom out for generalizing/abstraction about conflict and a theory we have about it, then zoom in again on the particular conflict in Nigeria and then zoom out again with what we can learn from it. -->

Story about burnt down village

Story about village defending pastoralists.  Making conflict and contact concrete.

What accounts for the difference?  To prevent this type of intergroup conflict, international community or strong state actors usually intervenes.  Those type of interventions not always successful, not always possible for that type of intervention.

A different approach is grassroots psychological reconciliation based on intergroup contact.  Groups in conflict often hold strong negative attitudes that make peace difficult.  Psych reconciliation can improve intergroup attitudes.  Improving intergroup attitudes can help reduce conflict.

Say what we did in context of farmer-pastoralist conflict.  Some context, some intervention design, some evaluation.

Say what we found.  It seems primarily through intergroup contact.  

Say implications for: (1) conflict resolution, especially intergroup and intercommunal violence.  On the rise, Fulani being massacred in Mali (Economist March 30, 2019).

(2) intergroup contact theory, 

(3) social institutions constraining behavior, 

(4) peacebuilding programs and CDD, 

(5) spillover of effects and social norms/vicarious learning.

Future work should further investigate mechanisms through which grassroots strategies can be successful.  Conditions under which different conflict resolution strategies are successful -- when outside actors needed, when groups can be assisted in solving own conflict.

Roadmap.

# Theory

Typical solutions strive to solve intergroup bargaining problem.  Information and comittment problems.  Define these problems.  3rd parties (peacekeepers, states) solve comittments problems by adding large costs to defecting on agreements.  Mediation works when it solves the information problem.

Not always feasible to do these things, and these things don't always work.  Say why: costly, biased mediators, no state to project power, etc.

Talk about psychological challenges to resolving conflict.  Groups in conflict develop attitudes that make peace difficult.  _The other is innately bad, the other cannot be trusted_.  Might get psychological benefits to positive group differentiation.  Social norms might encourage animosity and punish cooperation. Group members might receive social payoffs for harming the other group.  Outgroup Defense of self becomes violent assault, my violent assault becomes justified retribution. fundamental attribution error, motivated reasoning.

Psychological reconciliation, intergroup contact.  Define what it is, when it should work.

## Psych Reconciliation not working (orthodox view/pessimist group)

- Many reasons contact may not work in this context
    - Intergroup conflict as commitment problem [@fearon1994ethnic; @powell2006war]; contact is not an institution that can enforce commitments
    - Competition for resources [@campbell1965ethno; @Sherif1988robbersCave].  Psych Reconciliation does not change the underlying cause of conflict.
    - Psychological reconciliation can prevent resumption of conflict but requires conflict to already be resolved  [@bar2000intractable]
\pause
\bigskip
    - Active conflict produces many grievances and high prejudice; cognitive dissonance causes backlash for the most prejudiced people [@festinger1962cognitiveDissonance; @gubler2011diss]
    - Negative contact experiences reinforce negative stereotypes [@paolini2010negative]
    - Motivated reasoning for attitudes towards others [@klein1992motivated]
    - Few norms against prejudice <!--Extent that contact activates "norms against prejudice", no good here. -->

## Psych reconciliaiton could work

Talk about ways this type of thing _could_ solve conflict.  Could solve information problem, could solve comittment problem.  Could encourage sharing/bargaining over resources instead of competition/conflict over resources.  Receive information directly, not from a mediator (who may be biased for one side or for peace).  Opportunities for costly signaling and ingroup censuring [@ditlmann2017addressing; @Fearon1996]

Could change stereotypes -- attributes that are applied to the outgroup, focusing on trustworthiness. Solving commit problem. Solve information problem.

Could decrease threat, though in cases of active conflict this might exacerbate rather than solve conflict (information about reduced outgroup threat == higher chance of my group winning).

Could increase empathy.  Seeing the other side's argument, seeing their motivations. Increase empathy/less prejudice helps interpret information in non-biased way. Chris: look for literature on empathy making me interpret information about other people more accurately.  Kertzer?

Could expand ingroup/make group similarities salient.  Seeing our two groups as one, seeing our incentives as aligned.

Chris: in ECPN program, groups work together to gain more material resources, improves us now, makes me think working together in the _future_ would be good.  Also role of leaders in mediating disputes (mediaiton training).

# Context

Conflict bad.  State cannot project power.  No mediators, biased.  Farmer-pastoralist conflict on rise.

"the specific original grievance is forgotten and replaced by general animus toward the other group..  The countryside is littered with the charred ruins of homes, schools, police stations, mosques and churches." [@mcdonnel2017graze]

# Intervention and Experimental Design

- The NGO Mercy Corps implemented a peacebuilding program called Engaging Communities for Peace in Nigeria (ECPN) from 2015-2018
- Sites with (1) farmer-pastoralist conflict and (2) leaders who wanted assistance in reducing the conflict 
- Program engages farmers and pastoralists to work together on projects that benefit both communities
- Each implementation site runs two "conflict forums" where communities discuss grievances


- Randomly assign 10/15 implementation sites to receive the program
- \sout{Randomly assign 50 individuals in each community to participate or not participate in project committees}
- Individuals effectively self-selected into participation or nonparticipation
- Three groups: (1) Participants, (2) Nonparticipants, (3) Control

- Track communities and individuals over time
- Baseline: Randomly select ~50 people per community for the survey
- Endline: (1) Randomly select ~50 people per community for the community-level survey, (2) randomly select 10 respondents from the baseline survey per community for the individual-level survey.

# Results


# Discussion

Future: mechanisms and ways to scale up.  Mechanisms could be many things.  Ways to scale up: cannot have every group in conflict meet.  Scale up with contact between key actors that could diffuse the positive effects of contact & change social norms.  Media programs and observational/vicarious contact.

Some mechanisms of intergrop contact theory clearly will not function here.  Reduced outgroup threat (("Sullivan, Pierson, & Marcus, 1982; Gibson, 2006). If citizens perceive or experience threat from an out-group, they are more likely to be intolerant toward that group)".  Ingroup expands to include outgroup -- no way.  Empathy yes.  Belief that working together will benefit us == yes.

Other Mechanisms: assist intergroup bargaining with opportunities for costly signaling, increased trust.  Increase ingroup policing.  Increase social norms against intergroup violence.  Change interpsonal attitudes?

<!--Scaling up with TV/radio -->
An important question is scaling intergroup contact to larger conflicts.  Intergroup contact is unlikely to deter violence between groups involved in large-scale ethnic war where opposing armies commit atrocities, for example.  It's also unlikely to naturally occur between groups with limited contact to each other, or for people who consciously select out of intergroup contact situations.

Any attempt to scale-up intergroup contact relies on mechanisms of social or vicarious learning.  Research shows that even _observing_ interactions between a member of your group and a member of a disliked group can improve attitudes [@vezzali2014indirect].  Television and radio programs may thus provide intergroup contact between groups with limited exposure to each other [@mazziotta2011vicarious].  @paluck2009 used dramatic radio programs to influence attitudes and behaviors in a post-conflict setting to some effect, and a similar strategy could be used in a conflict setting.