---
title: "Group Conflict, Collective Action Problems, and Intergroup Contact - Abstract"
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

<!--Group conflict of all types plagues humanity's dealings with itself.  -->
There are two major perspectives on group conflict in political science.  One, which I refer to as the _bargaining perspective_, considers group conflict the result of information and commitment problems.  The other, which I refer to as the _identity perspective_, considers group conflict the result of the prejudice and other negative emotions that naturally arise between groups or arise when groups compete for resources.  These two perspectives are rarely combined, but their synthesis could benefit both literature's attempts to understand group conflict and craft policies to reduce it.  In this paper, I apply insights about group biases from the identity perspective to the bargaining perspective's framework of information and commitment problems.  I show how a solution originating from the identity perspective, intergroup contact, alleviates information and and commitment problems.  I then use farmer-pastoralist conflict in Nigeria as an illustrative example of how to understand group conflict using both perspectives.  I close by proposing six policy implications of combining these perspectives and offering five avenues for future research.

<!--
Group conflict can occur because one or both sides prefer fighting to peace, but often conflict occurs despite both side's desire for peace.  In these cases, conflict is caused by an information problem, wherein groups don't know each other's preferences, or a commitment problem, wherein neither side trusts the other to honor agreements.  
-->
