---
title: "Group Conflict and Collective Action: Intro"
author: "Christopher Grady"
date: "May 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro

<!--conflict is bad motivation paragraph -->
Conflict bad.  Lots of interest in resolving conflicts.  Violence between groups, political party competition, sports team competition, teams within organizations.  Conflict makes them all less 

<!--conflict occurs when bargaining fails, bargaining fails because trust.  what does it mean for a group to trust another group?  collective action problem -->
Conflict is a bargaining situation where lack of trust between groups causes violence.  What does it mean to trust a group?  A group is not a homogenous unit; each group is a collection of individuals with their own behavioral incentives.  Peace is a public good so group members have individual-level incentives to defect and enjoy everyone else's contribution to the public good.  Therefore, underlying the Commitment Problem is a Collective Action Problem: cannot trust _all_ members of the other side.  @sambanis2013social "a small but sufficiently potent group of ethnic radicals can derail a peaceful equilibrium."  Knowing that, the key question for each group is if the other can control their most radical members.

- @gambetta_ch13: on defection in a PD: "tragically, it may also be based on the fear that the second player will not trust him to cooperate, and will defect as a direct result of this lack of trust. Thus the outcome converges on a sub-optimal equilibrium, even if both players might have been conditionally predisposed to cooperate."  "It is necessary not only to trust others before acting cooperatively, but also to believe that one is trusted by others."
- @gambetta_ch13: revealed lack of cooperation does not mean lack of desire or capacity to cooperate: "Revealed preference may simply reveal the fact that they are conditional on our beliefs: if the latter change, the former may change accordingly."

<!--Solving collective action problems.
Here or paragraph above prob need to say the typical way to solve commitment problems in conflict literature: strong 3rd party intervention.  But also need to say how (1) it's impractical for many conflicts, and (2) it's costly so the strong third party actor doesn't have an incentive to do it until the conflict becomes a big problem. 1-2 sentences. -->
Typical way to solve commitment problem of conflict is strong 3rd party, and that applies here.  Strong 3rd party monitors and punishes defection.  But that is impractical: 3rd party action is costly to the 3rd party, so 3rd party actor doesn't have incentive until conflict is a big problem for the 3rd party.  Even 3rd party cannot monitor everything all the time.

- @gambetta_ch10: enforcement of a contract builds trust in the enforcer, instead of mutual trust between the two parties.  Crowds out trust needed when the enforcer isn't around.
- @gambetta_ch13: not about trust in others when others' decisions are very constrained/when others have no choices: "if other people’s actions were heavily constrained, the role of trust in governing our decisions would be proportionately smaller, for the more limited people’s freedom, the more restricted the field of actions in which we are required to guess ex ante the probability of their performing them."  
- @gambetta_ch13: coercion "falls short of being an adequate alternative to trust; it limits the extent to which we worry about, but does not increase, trust. On the contrary: coercion...may simultaneously reduce the trust that others have in us.  It introduces an asymmetry which disposes of mutual trust and promotes instead power and resentment"
- @gambetta_ch13 - "Contract shifts the focus of trust on to the efficacy of sanctions, and either our or a third party’s ability to enforce them if a contract is broken."

Other solutions to solving collective action problems will not work here: (1) motivational/other-regarding preferences, but how to increase that? more communication and opportunity to make and keep promises?; (2) strategic / something about reputation/repeated nature of interactions.  not relevant here.  SO we are back to (3) structural / change payoffs. Ingroup policing (replace 3rd party with ingroup), social norms (also replace 3rd party with ingroup).

<!--Groups can solve their ingroup collective action problem through ingroup policing. ingroup policing compels members to obey == collective action problem solved, & is costly cooperative signal == helps solve commitment problem.
Also look at Ostrom for other ways groups solve collective action problems.-->
Can trust members of other side to cooperate if trust other side to punish their own defectors.

<!--commitment problem can remain if signal misinterpreted.  axelrod tit-for-tat with misperceptions. misinterpretation likely for groups in conflict because motivated reasoning.  Things get distorted. Social/psych payoffs for seeing other side badly.  Norms support conflict, self-image can be maintained by a comparison to lesser group, need to justify previous discriminatory behavior and attitudes rather than admit I am a bad person.-->
Groups can send costly signals to the other side about their intention to honor a peace agreement and to punish ingroup defectors.  But how to get that signal across?  And why would Side A not see Side B's "signal" as a cynical attempt to manipulate?  Conflict causes and is caused by prejudice, and prejudice biases perceptions of the other group’s behavior in a way that prevents each side from receiving costly signals or forming accurate beliefs about the other group.  Conflict also creates combative social norms, so group members have social motivation to see other side in bad light. 

- @tajfel1969cognitive: "failure to seek disconfirmation, and an inability to recognize disconfirmation for what it is when it is presented to the individual by chance, are important factors in the maintenance of racial prejudice." from @good2000individuals
- from @good2000 individuals: "Kahneman and Tversky (see Kahneman and Tversky 1973; and Kahneman, Slovic, and Tversky 1982) have examined the strategies that individuals employ when confronted by uncertainty and ambiguity in a variety of situations. They provide much evidence that there is a strong tendency for ambiguous or incomplete information to be interpreted in line with the individual’s preconceptions. Such interpretations will, of course, serve to reinforce those preconceptions."
- @sambanis2013social "conflict and identification patterns reinforce each other." & @bernad2011conflict "intergroup conflict shapes emotional bonds between group members, promotes ingroup and outgroup stereotyping, encourages self-sacrifice for the group, and changes the social structure of the group."
- @declerck2013people cooperation depends on extrinsic incentives to cooperate & how the brain processes trust signals.
- @de2014parochial benefits individuals' within-group reputation/status.
- @declerck2010oxytocin lab/field experimental evidence shows that "cooperation increases when extrinstic incentives are incorporated into the decision-making context, such that the cooperative decision itself becomes rewarding (Bornstein, 2003)""
- @gambetta_ch13 "Pre-commitment, in its various unilateral and bilateral forms, is a device whereby we can impose some restraint on ourselves and thus restrict the extent to which others have to worry about our trustworthiness."  But it may not build trust because it changes the options we have to consider, which may no longer predict what we would do in the absence of pre-commitment.
- @gambetta_ch13: "If one group of soldiers for some reason believes itself to be facing a mob of unrestrained warriors and trusts neither the latter’s time preferences nor their rationality, ‘peaceful’ signals are more likely to be interpreted as a trap."
- @gambetta_ch13 on biased processing of signals: "Trust is a peculiar belief predicated not on evidence but on the lack of contrary evidence...Doubt is far more insidious than certainty, and distrust may become the source of its own evidence."  
    - "deep distrust is very difficult to invalidate through experience, for either it preventspeople from engaging in the appropriate kind of social experiment or, worse, it leads to behaviour which bolsters the validity of distrust itself."  
    - "Once distrust has set in it soon becomes impossible to know if it was ever in fact justified, for it has the capacity to be self-fulfilling, to generate a reality consistent with itself. It then becomes individually ‘rational’ to behave accordingly, even for those previously prepared to act on more optimistic expectations. Only accident or a third party may set up the right kind of ‘experiment’ to prove distrust unfounded (and even so, as Good argues in this volume, cognitive inertia may prevent people from changing their beliefs)." @good2000individuals

<!--important to send clear signals and to reduce motivation to misinterpret those signals.  But how?  Cooperative intergroup contact a method to send clear signals and reduce motivation to misinterpret those signals. Joint "court" institutions so both sides are represented in all cross-group disputes. -->
Contact helps groups send and see costly signals.

<!--ways that contact helps:
(1) Can observe the other side directly.  Can personally see ingroup policing; many group members can send and receive signals directly instead of inferring from observed behavior.
(2) reduce motivated reasoning, provide motivation to see other side positively.
  - material incentive: working with other side beneficial to my group/me vs. we win and take all, or they win and take all.
  - psychological: I think of myself as a good person; i see that other group is not all bad people; I now feel bad for treating them badly. vs previously when I did not feel bad for treating them badly.
  - social: cooperative norms because cross-group cooperation benefitted my group.  I am now punished for holding/expressing negative attitudes.
chris: this one needs to be more clear in my head. -->
Contact can reduce prejudice and provide motivation to view the other side positively.  
    - Psych/material benefits of cooperation change incentive structure of war/peace.  Especially when groups achieve (a goal/something of value) through contact.  Cooperative contact that achieves a goal can also demonstrate to groups the material benefits of cooperation, increasing the expected utility of peace and motivating positive attitude change.
        - @gambetta_ch13: "The importance of interest is twofold: it can be seen to govern action independently of a given level of trust, but it can also act on trust itself by making behaviour more predictable."  "cooperative behaviour does not depend on trust alone" but on interest/incentives.
        - @gambetta_ch13, summarizing Hayek's (1978) Three Sources of Human Values.  trust is "nothing more than trust in the success of previous cooperation."
    - Prejudice provides motivation to view outgroup badly == prejudice causes perceptual biases that distort outgroup intentions.  These perceptual biases prevent one side's costly signals of trustworthiness from being perceived as such by the other side.
    - Contact can create cooperative/non-prejudiced social norm.  The social norm will affect people who weren't exposed to group contact.
        - @de2014parochial: "parochial cooperation (1) emerges especially when it benefits individuals’ within-group reputation, (2) affects one’s withingroup status"

Contact allows groups to build from small cooperation to large.
    - @gambetta_ch13 citing @good2000individuals: "experimental evidence which suggests the fundamental importance of...the lack of ambiguity in what people cooperate about, and of a step by step increase in the risk involved in cooperation".  These things increase the likelihood of cooperation and reinforce trust.  Contact for a joint goal removes ambiguity and can be increased in step-wise fashion.  Costly signaling works in similar way, where initial costly signal has to be costly enough to signal cooperative tendency but not so costly that it will never be sent.
    - @gambetta_ch13 on importance of small to large trust: "trust is not a resource that is depleted through use; on the contrary, the more there is the more there is likely to be...trust may increase through use"

@gambetta_ch13: Contact builds familiarity, which may be necessary for trust to form: "trust may be a by-product, typically of familiarity and friendship, both of which imply that those involved have some knowledge of each other and some respect for each other’s welfare."

- @fearon1996explaining: groups give material and psychological benefits to members (717/p.4).
- @gambetta_ch13: trust not as a precondition to cooperate, but as a consequence of cooperating.  "The soldiers’ belief that they can trust each other results from an inference concerning the effectiveness of their interests as a motive for rational action in initiating and maintaining cooperation. Thus p is raised in the course of cooperation itself, without any assumption being made as to prior levels: ‘The cooperative exchanges of mutual restraint actually changed the nature of the interaction. They tended to make the two sides care about each other’s welfare’ (Axelrod 1984: 85). In the previous section we saw that interest, irrespective of trust, could make cooperation more likely simply by making action more pressing. On closer inspection we find that when that pressure is commonly shared and this fact is known to both sides, then cooperation is motivated and trust itself may increase as a result."  Later, quoting Hume: "'...interest is the first obligation to the
performance of promises. Afterwards a sentiment of morals concurs with interest, and becomes a new obligation upon mankind (1969: 574)."
    - NOTE: Gambetta does not buy this in most cases.  "The optimality of tit for tat as a strategy in playing a repeated Prisoner’s Dilemma and generating a cooperative outcome also suggests that distrust should not be allowed to congeal after defection from the other side. It would be best to have no memory, to forget that past defections may be repeated in subsequent moves. But in the case of individuals who do have some (finite) amount of memory, this is to prescribe as rational the avoidance of unconditional distrust even after the evidence would suggest it to be advisable"

<!--Ways joint "court" institutions helps: each group trusts criminal justice system-->
ingroup policing mechanism: we do not need to punish beyond the formal punishment.  Can be thought of as selective incentive/disincentive [@lichbach1994makes].  Trust in criminal justice system affects something, affected by vicarious experience (cite Mondak vicarious).

- @benard2012cohesion: conflict makes groups more willing to sacrifice for group welfare, enforce norms, and defer to group leader.  To me, answers question of "will groups punish their own", though Benard (and, as far as I can tell, all other authors like Bornstein) consider the situation of costly behavior to defeat an adversary, not compromise with one.
    - "Classic theories suggest that in conflict, individuals encourage contribution to the group through two mechanisms: punishing noncontributors and centralizing authority in the hands of a leader (Simmel [1908] 1955; Sumner and Keller [1906] 1960)."

<!--Implications (1): contact program design: work together for a material benefit, opportunities for ingroup policing -->
Implications for peacebuilding programs.  (1) Contact should provide opportunities for groups to observe the other side sanctioning/policing its own.  Ingroup sanctioning is a costly signal, whereas everything else might be construed as cheap talk.  (2) Contact should show groups how cooperation can be materially good.  Material benefits of cooperation provide more motivation to change attitudes towards other side.

<!--Implications (2): non-contact peacebulding programs: trust in court system by representing both groups -->
Implications for other peacebuilding programs: reinforce joint/formal/public institutions that dispense justice.  Key is to create a feeling of legitimacy/fairness in the other side's court/criminal justice institutions.  For a US analogy, if courts not going to protect black people from KKK and white gangs, need Black Panthers.

<!--Implications for conflict research -->
Implications for conflict research: structural contributors (commitment problem, collective action problem) but also psychological/social contributors to conflict.

Especially relevant to group conflicts where group discipline is relatively low / groups are more heterogeneous / groups are made up of several separate subgroups.  Also relevant when there is no strong third party.

<!--Future research -->
Continuing issues: (1) Getting the ball rolling: how to initiate contact for groups at war/in conflict.  (2) Each groups capacity/ability to accurately perceive the signals from the other side.  Especially given that all sides have an incentive to play as the "cooperative type".  (3) Longevity: nothing structurally has changed, so what prevents these groups from falling back into conflict?

<!--Alternative mechanism for contact: group-heuristic model (Yamagishi and Kiyonari 2000 - the group as the container of generalized reciprocity.  heuristic that "I treat people in my group good way, treat people out of my group bad way.  People I interact with a lot are in my group, people I interact with rarely are in my outgroup".   -->
