---
title: "Group Conflict and Collective Action: Intro"
author: "Christopher Grady"
date: "May 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro

<!--1 – Violence is bad.  Results from commitment/trust problem.  Explain comm/trust problem.-->

Groups fight for the resources -- land, wealth, power, or otherwise -- that fighting destroys.  As such, groups could almost always divide the resources before war in a way that benefits them more than their postwar settlement.  This is the enigma of violent conflict: why do groups engage in violent conflict when violent conflict often destroys the very thing the groups are fighting for?  The general answer is that groups suffer from a commitment problem: both sides are better off negotiating a peaceful agreement, but conflict occurs because neither group trusts the other to abide by negotiated agreements [@fearon1995rationalist; @powell2006war; @reed2016bargaining].  If groups trusted each other to abide by agreements, they would not need to fight and each group would enjoy superior outcomes relative to their outcomes after fighting.  

<!--2 – Comm/trust problems between groups usually solved by 3rd parties or reputations/repeated interactions. Explain how these things solve problem.  -->

One of the most common mechanisms for overcoming commitment problems and resolving group conflict is third-party enforcement of agreements.  Third party enforcement reduces commitment problems by incentivizing each side to honor agreements out of their own interest.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1994ethnic].  Third parties to enforce agreements can often effectively reduce conflict [@doyle2000international; @di2017effectiveness; @walter2002committing; @hartzell2001stabilizing; @gartner2011signs; @wallensteen2014talking], but they also suffer from general limitations. First, third party intervention is costly.  The cost results in intervention only when the third party is biased towards one side of the dispute or when conflict has already escalated into violence, so intervention is rarely used to reduce the persistent, smaller-scale violence that plague many countries [@greig2005stepping; @kydd2006can].  Second, third parties are relatively ineffective at ending ongoing conflicts compared to maintaining peace in a post-conflict setting [@gilligan2008interventions; @doyle2006making; @bratt1996assessing].  And third, third party punishment is exogenous to the conflicting groups and therefore does not create trust between those groups that will last beyond the third party's presence [@gambetta_ch13].  @weinstein2005autonomous estimated that 75% of civil wars resume within 10 years of UN intervention, and @beardsley2008agreement showed that international mediation reduces conflict in the short-term but not the long-term.

<!--3 – reputation/repeated interactions.-->

Rather than rely on third party intervention, groups can also resolve conflicts themselves through repeated interactions and incentives to cultivate a trustworthy reputation.  Like third parties, repeated interactions help overcome commitment problems by providing each group with the incentive to honor agreements out of their own interest.  Here the incentive comes not from fear of punishment but the prospect of better future outcomes from cooperation than defection.  Though each group may have an incentive to defect on an agreement today if the groups will not interact tomorrow, the groups have an incentive to cooperate today if their behavior today will be reciprocated by the other side tomorrow [@ostrom2003trust; @kydd2000trust; @axelrod1981evolution].  Both groups stand to gain more from enduring cooperation than enduring defection.[^reputation]

[^reputation]: I discuss repeated interactions and reputations together, but these mechanisms are subtley different.  The repeated interaction mechanism is generally mobilized for contexts with just two groups.  In those contexts, cooperation in previous interactions assists in obtaining cooperative behavior in the future from the same partner; other potential partners are unnecessary.  The reputation mechanism is generally mobilized for contexts in which many groups observe the behavior of many other groups.  In those contexts a good reputation assists in obtaining _other_ cooperative partners; repeated interactions with the same partner are unnecessary.  I discuss these mechanisms together because both rely on creating cooperative expectations from bargaining partners in future interactions.

<!--4 - general problems with rep/repeated interactions: don't want peace because psych costs; even if want peace, incentive to act tough to get best deal; even if want peace and not acting tough, biased perceptions of outgroup means each group is likely to misinterpret each other's cooperative signals.-->
Solving commitment problems through repeated interactions also faces limitations.  Repeated interactions only solve commitment problems if both groups prefer peace (cooperation) to fighting (defection).  Though peace is in each group's material interest, preferences often deviate from material interest [@fehr2002social].  In the case of conflict, groups may not want peace because they prefer relative gains over the outgroup to absolute gains for themselves [@waltz2010theory; @halevy2010relative; @turner1979social] and because they derive psychological benefit from harming a hated outgroup [@weisel2015ingroup; @cikara2014their].  These psyhological factors add non-material costs to peace agreements.  Even if groups desire peace, they maintain an incentive to act "tough" to get the best deal, and so may not signal their desire for peace [need cite].  And even if groups signal their desire for peace, phenomena like confirmation bias, cognitive dissonance, and motivated reasoning can bias perceptions of outgroup behavior and prevent groups from accurately perceiving peaceful intentions [@de2008motivated; @ward1997naive; @duncan1976differential; @vallone1985hostileMedia; @festinger1962cognitiveDissonance; @kunda1990motivatedReasoning; @tajfel1969cognitive; @nickerson1998confirmation].

<!--5 - Neither 3rd parties nor repeated interaction/reputation often sufficient to build trust between groups. -->
This is a bleak picture.  Often, neither the presence of third parties nor repeated interaction are sufficient to build trust between groups.  Third parties may be unwilling to intervene early enough to prevent violence, rarely intervene with enough force to stop ongoing conflict, and do not necessarily create the trust needed for long-term peace, though they are effective at preventing a relapse into violence in the immediate aftermath of conflict.  Repeated interactions can create the trust needed for long-term peace, but getting cooperation started is difficult because of psychological costs to cooperation, incentives to increase bargaining power by acting uncooperative, and cognitive biases that prevent groups from receiving each other's cooperative signals.

<!--6 - Additional problem arises from trying to answer question: What does it mean to trust a group?  Collective action problem.  3rd party/rep needs not only signal group desire for peace, but willingness to punish group members who do not  Sambanis: “peace can be derailed by a few radicals.” Beyond most members of a group signaling a commitment to peace, they must also signal a willingness and capacity to punish ingroup members who do not contribute to peace.  -->

How, then, can groups build trust and solve commitment problems?  First one must answer the question: what does it mean for one group to trust another group?  Each group is a collection of individual group members with their own behavioral incentives, not cohesive entities.  Peace is a public good that benefits all members of a group.  Contributing to peace is costly for group members, however, because each group member must refrain from engaging in behaviors that benefit them at the expense of the outgroup.  Achieving peace, as with any public good, requires overcoming a collective action problem: the group must compel group members to contribute to peace despite the members' individual incentive to shirk and rely on others to bear its cost.  One group trusting the other to honor an agreement, then, means not only trusting that a high proportion of outgroup members desire peace, but also that those outgroup members can and will compel less cooperative group members to honor the agreement.  Peace, after all, can be derailed by a few radicals [@sambanis2013social].

<!--6 – the solution needs to (1) remove psych costs to peace and psych/social barriers to trusting other side, (2) signal that each group has solved its collective action problem and can compel radical group members to not take aggressive action against outgroup.-->
Groups must both signal their desire for peace and their willingness and capacity to punish their own group members who do not honor the peace agreement.   A solution to group conflict must signal not only a desire for peace but a willingness to punish group members who do not. 



<!--7 – structured intergroup contact to remove psych/social barriers to trust (like prejudice): contact must show the groups that it is in the other side’s interest to cooperate.  H.L. Mencken: “It is hard to believe that a man is telling the truth when you would lie in his place.”  Show that cooperation is in both groups interest: contact helps each group achieve something they desire/achieve a goal.  Groups need a reason to get along.  Contact is Confidence-building measure-->

<!--8 – Once enough trust is developed, Joint criminal justice institutions: outgroup policing defectors is bad because chance that ingroup perceives outgroup punishment as too harsh, causes spiral.  Ingroup policing defectors is bad because chance that outgroup perceives ingroup punishment as too lenient, causes outgroup punishment.-->

Ingroup only punishment: reactive devaluation.

<!--9 – Perspective/Application: Nigeria farmer-pastoralist: pastoralists graze cattle on farmland, farmers attack cattle and sow seeds in grazing lands.  Ingroups not preventing this aggression.  Farmers do not know whose cattle, pastoralists do not know who attacked their cattle.  Attack outgroup generally.  Through a contact intervention, groups established joint criminal punishment institutions when a farmer/pastoralist have grievances.  Representative from each side’s “government” (chiefs) meet and agree on punishment, make sure ingroup abides by ruling.
Perspective/Application: Race Protests/Riots 2020: black people (ingroup) following social rules, punished extremely by cops (outgroup) anyway, no punishment for outgroup defectors, eventually ingroup starts punishing members of outgroup == spiral equilibrium (F&L). Ingroup cannot identify outgroup members who defected so punish any others perceived as outgroup.  Low trust in criminal justice system, low legitimacy, low compliance.
o	Use trials; need members of ingroup and outgroup at trial.-->

<!--10 – Outstanding issues: (1) Onset of these structures: How to get the ball rolling?  A place for 3rd parties? (2) How to keep ball rolling-->

<!--11 - Implications for peacebuilding programs. -->





###

Trust not based on material outcomes would be a + psychological payoff to cooperation/trustworthy behavior.

2nd paragraph about 3rd parties
which deters third parties from intervening before disputes escalate into large-scale violence or unless the third party is biased in favor of one side

2nd paragraph about collective action
This formulation, while true, begs the question: what does it mean for one group to trust another group?  Each group is a collection of individual group members with their own behavioral incentives.  If all group members benefit from peace but contributing to peace is costly, then group members are best off if their group has peace without them contributing to it; peace is a public good and achieving peace requires overcoming a collective action problem.  Peace can be derailed by a few radicals [@sambanis2013social].  To trust a group to honor an agreement, then, is to trust that a sufficiently high proportion of group members want to contribute to peace and can compel other group members to contribute to the public good of peace.<!--To trust a group to honor a peace agreement, then, is to trust that a sufficiently high proportion of group members will honor the agreement.  -->

Why would any group member not honor the agreement when their group's outcome from peace is superior to the group's outcome from fighting?


3rd paragraph
The efficacy of a third party depends on its ability to monitor behavior, detect defection, assign blame, and punish the offender.  This process works well for homogeneous groups like armies, where responsibility for the behavior of any group member can be assigned to the group as a whole.  The same is not true for heterogeneous and decentralized groups, where the third party must observe the behavior of all groups members and cannot identify which group members defected on the agreement.


5th paragraph
psych costs to peace and benefits to conflict might make no agreements mutually acceptable to both sides (no bargaining range).

relative gains citations:  (Gilpin 1981, 1987; Gowa 1986; Grieco
 1988a, 1988b, 1990; Jervis 1988; Kennedy
 1987; Krasner 1987; Lake 1984; Larson  1988; 
Lipson 1984; Stein 1982; Waltz 1979)

Though peace is in each group's material interest, preferences often deviate from material interest [@fehr2002social].  In the case of conflict, groups may not want peace because of psychological costs to peace and benefits to fighting.  Group members are often willing to accept lower absolute gains to increase relative gain over the outgroup [@waltz2010theory; @halevy2010relative; @turner1979social; @festinger1954theory].  Group members may also receive psychological benefit from _harming_ the outgroup [@weisel2015ingroup; @cikara2014their], and a peace agreement prohibits group members from receiving those benefits.