---
title: "Group Conflict and Collective Action: Intro"
author: "Christopher Grady"
date: "May 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--chris: thinking about removing discussion of third parties altogether.  Just saying "short of a third party intervening in the conflict...[repeated interaction stuff]."  Then footnote things about third parties. -->

## Intro

<!--1 – Violence is bad.  Results from information/commitment problem.  Explain information/comm problem.-->

Groups fight for the resources -- land, wealth, power, or otherwise -- that fighting destroys.  As such, groups could almost always divide the resources before war in a way that benefits them more than their postwar settlement.  This is the enigma of violent conflict: why do groups engage in violent conflict when violent conflict often destroys the very thing the groups are fighting for?  One answer is that groups suffer from a bargaining failure when negotiating for peace [@fearon1995rationalist; @powell2006war; @reed2016bargaining].  These bargaining failures can be caused by a lack of trust (a commitment problem) or a lack of information (an information problem).  The commitment problem occurs when both sides are better off negotiating a peaceful agreement but neither group trusts the other to abide by negotiated agreements.  The information problem occurs when neither side knows the other side's power or preferences.  If groups (1) trusted each other to abide by agreements and (2) knew the strength and preferences of the other side, they would not need to fight and each group would enjoy superior outcomes relative to their outcomes after fighting.  I call this the _bargaining perspective_ of group conflict.[^IssueIndivisibility]

[^IssueIndivisibility]: Another common explanation for bargaining failures is _issue indivisibility_: when the thing that groups would gain from fighting cannot be split easily or at all (the throne of a monarchy or control over holy land).  Issue indivisibility is thought to rarely be a problem, however, because almost all things that groups fight for are divisible or can be substituted by something divisibile [@fearon1995rationalist].  For this reason, issue indivisibility is sometimes seen as a commitment problem [@powell2006war].  If the group being given the throne could commit to providing a substantial portion of the spoils to the other side, the group's could make that peace agreement and avoid fighting.  The group given the throne cannot credibly make this commitment, however, because once in power nothing prevents that group from reneging on their agreement.  I do not consider issue indivisibility as a distinct explanation for bargaining failures in this paper.

<!--Also results from individual-level stuff preventing trust and accurate info processing-->
Another answer to the question of why group's fight focuses on the factors that explain individual group members' lack of trust in and lack of accurate information about the other side, as well as why groups might prefer fighting relative to a peace deal even if fighting destroys resources [@campbell1965ethno; @tajfel1971social; @Stephan2000integratedThreat; @allport1954prejudice; @runciman1966relative; @sherif1988RobbersCave; @ross1995psychological; see @bohm2018psychology for a review of psychological theories of conflict].  The lack of trust can occur due to conflicts of interests and competition for scarce resources or as a natural consequence of categorization into ingroup and outgroup.  The lack of accurate information is a consequence of group's perceptual biases, outgroup stereotyping, and limited interaction.  Preferences for fighting over a peace deal the other side would accept stem from self-esteem derived from feelings of group superiority and considerations of relative gains over absolute gains.  If members of opposing groups can identify common interest or a common identity, they can avoid the competition, emotions, and perceptual biases that lead to conflict.  I call this the _identity perspective_ of group conflict.

<!--Compatability. chris: this is super important paragraph and I have not nailed it yet. -->
Though these perspectives are rarely used together, I argue that they are compatible and that their synthesis will help scholars better understand group conflict and help practitioners better develop policies to reduce group conflict.  At their heart, they both focus on preferences, trust, and information, and both consider preferences based on material resources and non-material goods like morals, esteem, values, and norms.  The identity perspective tends to highlight the formation<!--components?--> of preferences and trust and the causes of information asymmetries.  The bargaining perspective highlights the consequences of preferences, mistrust, and information asymmetries.  By considering both perspectives we can better understand the formation and consequences of these factors.^[This characterization necessarily lacks the nuance to describe the entirety of these two perspectives.  There is, of course, work in the identity perspective that considers the consequences of preferences [chris: example.] and work in the bargaining perspective that considers the formation of preferences [chris: cite endogenous preferences].  But I believe this characterization describes the main arguments of each perspective and the seminal articles on which subsequent work has been built.]


<!--Bargaining tends to assume or black-box the formation of preferences, trust, and information asymmetries.  Black-box: reputation can form from costly signaling.  But what will each group see as a costly signal?-->


There is growing interest in bridging political psychology and political economy explanations for concepts that both literatures actively research, like group conflict [@little2017bargaining; @kertzer2018political].  

<!--Compatibility Example: many cognitive biases prevent groups from developing trust.-->
Preferences.  Identity perspective would explain why 

Both perspectives highlight a lack of intergroup trust as one contributor to conflict.  From the bargaining perspective, the lack of trust prevents groups from negotiating peace agreements.  From the identity perspective, numerous cognitive and perceptual baises prevent groups from developing the trust necessary to avoid 

<!--Compatibility Example: Intergroup contact to reduce those biases and help groups develop trust-->


<!--Using both of these perspectives necessary for understanding group conflict and crafting policies to reduce conflict.-->
their synthesis will help scholars better understand group conflict and help practitioners better develop policies to reduce group conflict.
Identifying what the problem is.  A lack of trust?  A lack of information?  Resistance to any peace agreement that is fair to the other side?

<!--Roadmap paragraph -->
I begin by reviewing the bargaining perspective on group conflict, focusing on information problems, commitment problems, and solutions to those problems.  I follow that review by applying the identity perspective to these problems and their solutions, focusing on how group biases and other non-material factors contribute to bargaining failures.  Next I propose intergroup contact as a way to reduce group conflict by providing opportunities for the groups to gain accurate information about each other and to build intergroup trust.  I then apply a synthesis of these perspectives to farmer-pastoralist conflict in Nigeria, describing factors that push groups into conflict, institutions groups have developed to avoid violence, and the consequences when no such institutions exist.  I conclude by describing implications for peacebuilding programs and considering avenues for empirical research.


<!-- 
[^overlap]: There is overlap in idea from these two perspectives.  (1) Realistic group conflict theory from Campbell 1965: group conflict because groups compete for resources and have "incompatible goals".  Bargaining perspective basically assumes that fighting only happens if groups have incompatible goals.  (2) Nisbett and Cohen 1996 about a reputation for toughness.  (3) Bounded generalized reciprocity (Yamagishi et al. 1999) is similar to reputation mechanism.
-->

********************

# Other

<!--citations in identity perspective paragraph separated by claim. -->
Another answer to the question of why group's fight focuses on the factors that explain individual group members' lack of trust in and lack of accurate information about the other group, as well as why groups might prefer fighting relative to a peace deal even if fighting destroys resources [see @bohm2018psychology for a review of psychological theories of conflict].  The lack of trust can occur due to conflicts of interests and competition for scarce resources [@campbell1965ethno; @sherif1988RobbersCave; @sherif1966common; @runciman1966relative] or as a natural consequence of categorization into ingroup and outgroup [@tajfel1971social; @tajfel1979integrative; @turner1987rediscovering].  Lack of accurate information is a consequence of group's perceptual biases, outgroup stereotyping, and limited interaction [@Stephan2000integratedThreat; @riek2006threat; @ward1997naive; @allport1954prejudice].  Preferences for fighting stem from self-esteem derived from feelings of group superiority and considerations of relative gains over absolute gains.  If members of opposing groups can identify common interest or a common identity, they can avoid the competition, emotions, and perceptual biases that leads to conflict.  I call this the _identity perspective_ of group conflict.



Trust not based on material outcomes would be a + psychological payoff to cooperation/trustworthy behavior.

2nd paragraph about 3rd parties
which deters third parties from intervening before disputes escalate into large-scale violence or unless the third party is biased in favor of one side

2nd paragraph about collective action
This formulation, while true, begs the question: what does it mean for one group to trust another group?  Each group is a collection of individual group members with their own behavioral incentives.  If all group members benefit from peace but contributing to peace is costly, then group members are best off if their group has peace without them contributing to it; peace is a public good and achieving peace requires overcoming a collective action problem.  Peace can be derailed by a few radicals [@sambanis2013social].  To trust a group to honor an agreement, then, is to trust that a sufficiently high proportion of group members want to contribute to peace and can compel other group members to contribute to the public good of peace.<!--To trust a group to honor a peace agreement, then, is to trust that a sufficiently high proportion of group members will honor the agreement.  -->

Why would any group member not honor the agreement when their group's outcome from peace is superior to the group's outcome from fighting?


3rd paragraph
The efficacy of a third party depends on its ability to monitor behavior, detect defection, assign blame, and punish the offender.  This process works well for homogeneous groups like armies, where responsibility for the behavior of any group member can be assigned to the group as a whole.  The same is not true for heterogeneous and decentralized groups, where the third party must observe the behavior of all groups members and cannot identify which group members defected on the agreement.


5th paragraph
psych costs to peace and benefits to conflict might make no agreements mutually acceptable to both sides (no bargaining range).

relative gains citations:  (Gilpin 1981, 1987; Gowa 1986; Grieco
 1988a, 1988b, 1990; Jervis 1988; Kennedy
 1987; Krasner 1987; Lake 1984; Larson  1988; 
Lipson 1984; Stein 1982; Waltz 1979)

Though peace is in each group's material interest, preferences often deviate from material interest [@fehr2002social].  In the case of conflict, groups may not want peace because of psychological costs to peace and benefits to fighting.  Group members are often willing to accept lower absolute gains to increase relative gain over the outgroup [@waltz2010theory; @halevy2010relative; @turner1979social; @festinger1954theory].  Group members may also receive psychological benefit from _harming_ the outgroup [@weisel2015ingroup; @cikara2014their], and a peace agreement prohibits group members from receiving those benefits.