---
title: 'Group Conflict and Collective Action: Poli Econ Review'
author: "Christopher Grady"
date: "June 15, 2020"
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
    pandoc_args:
    - -M
    - secPrefix=\S
    template: ../../utils/bowersarticletemplate.latex
  word_document: default
csl: ../../utils/american-political-science-review.csl
bibliography: ../../utils/cdg_references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Bargaining Perspective on Group Conflict

The bargaining perspective considers conflict the result of a bargaining failure.  The two groups both want something and can either fight for it or negotiate over it.  Both groups are better off negotiating pre-war to get their expected outcome post-war, without paying the cost of fighting.  But sides cannot agree to negotiated bargain due primarily to commitment problems and information problems [@fearon1995rationalist].  These problems cause a bargaining failure, and sides resort to fighting.

**Commitment Problem**: One reason sides resort to fighting is that neither group can credibly commit to honor bargained agreements.  This "commitment problem" prevents any agreement from being made because neither group will commit to agreements today that they believe will be broken tomorrow.  Because they cannot reach an agreement, the groups fight.[^commitProblem] Commitment problems are often called trust problems because the problem arises because neither group _trusts_ the other to honor commitments.  Commitment/Trust problems are a common explanation for the ineffeciency puzzle of violent conflict [@fearon1994ethnic; @powell2006war; @fearon1998commitment; @reed2016bargaining; @lake2003international]

[^commitProb]: A commitment problem can occur for many reasons.  It often surfaces due to the potential for bargaining power to shift after an agreement.  If bargaining power shifts after an agreement, one side will have an incentive to renege on that agreement to achieve a better outcome.

The canonical example of a commitment problem is the prisoners' dilemma.  In the Prisoner's Dilemma, two criminals are arrested and interrogated separately.  The law enforcement officers lack the information to convict the criminals for the full extent of their crimes but have enough information to convict each criminal for a lesser charge.  The officers offer each criminal a deal: testify against your partner and you will be set free; your partner will spend three years in prison.  If both criminals stay silent, they will each serve one year in prison.  If they both testify, they will each serve two years in prison.  The prisoners face a dilemma: why stay silent if you are best off testifying regardless of what your partner does?  The problem here is each side's inability to commit to remaining silent -- a commitment problem.  If they could commit, they could get their second favorite outcome; without the ability to commit, they get their second least-favorite outcome.

The Prisoner's Dilemma is formalized in Table \ref{tab:comProb}.  The criminals are referred to as "players".  Staying silent is referred to as "cooperating" with your partner; testifying is referred to as "defecting" against your partner.  Each player wants their highest payoff.

\begin{table}[h!]
\begin{center}
\setlength{\extrarowheight}{2pt}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(2,2)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(1,1)$ \\\cline{3-4}
\end{tabular}
\caption{\label{tab:comProb}\textbf{Example of Commitment Problem.} Numbers represent payoffs to players.  The first number in each cell represents Player 1's payoffs, the second number represents Player 2's payoffs.  Player's want the highest payoff.}
\end{center}
\end{table}

Unless the criminals value cooperation above freedom or have some way of punishing defection -- both of which change the above payoff structure --, both criminals have an incentive to defect regardless of their partners behavior.  If Player 1 defects, Player 2 is best off defecting.  If Player 1 cooperates, Player 2 is also best off defecting.  No one is happy with the resulting outcome.  The two sides would commit to mutual cooperation to avoid mutual defection, but they cannot credibly commit to cooperating because they both prefer to defect regardless of what the other does.

This can be applied to group conflict where "cooperation" is abiding by a peace agreement and "defection" is breaking it.  If one side abides by a peace agreement and disarms, for example, the other side has an incentive to break the agreement by staying armed.  Since neither can trust the other to honor the peace agreement, both sides defect.


**Information Problem**: Another reason groups fight is that neither side knows the preferences of the other.  This "information problem" prevents peace agreements from being made, even if both sides prefer mutual cooperation, because neither side knows that the other would reciprocate cooperation.  Because both sides fear defection if they cooperate, the groups fight.  The information problem of conflict is one of the most common explanations for violent conflict [@fey2011uncertainty; @smith2003mediation; @fearon1995rationalist; @kydd2000trust; @moon2016audience; @rohner2013war; @wolford2011information]

<!--@fey2011uncertainty: information asymmetries cause bargaining failures.  Fighting to gain information: @smith2003mediation. -->

We can observe an information problem by modifying the Prisoner's Dilemma above.  Imagine that each criminal is "honorable" and values reciprocating cooperation.  This bonus to cooperation can be seen as the psychological value that each side places on being honorable; it is represented by adding +2 to the payoff of joint cooperation.  Each criminal wants to cooperate if the other cooperates but wants to defect if the other defects.  Each criminal knows that they are honorable, but neither knows that the other is also honorable.  The problem here is a lack of information -- an information problem.

This modified Prisoner's Dilemma, often called a Trust Game [@kydd2000trust], is formalized in Table \ref{tab:infoProb}.  Each player again chooses whether to cooperate or defect.  Player 1 is honorable and prefers to cooperate if Player 2 will cooperate but defect if Player 2 will defect.  Player 1 is unsure if Player 2 is also honorable.^[In a Trust Game, Player 1 would believe Player 2 is honorable with probability $p$, where $p$ represents Player 1's trust in Player 2.]  World A represents the payoffs if Player 2 is honorable; World B represents the payoffs if Player 2 is not.  In World A there is only an information problem: if groups knew each other's preferences, they have an incentive to cooperate.  In World B there is also a commitment problem: even if groups knew each other's preferences, each still has an incentive to defect.

\begin{table}[h!]
\begin{center}
\setlength{\extrarowheight}{2pt}
\begin{subtable}{0.48\linewidth}
\caption{\label{tab:info_a}\textbf{World A} \\Both sides prefer to cooperate if the other side cooperates but defect if the other side defects.}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(4,4)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(1,1)$ \\\cline{3-4}
\end{tabular}
\end{subtable}%
\hfill
\begin{subtable}{0.48\linewidth}
\caption{\label{tab:info_b}\textbf{World B} \\Player 1 prefers mutual cooperation, but Player 2 prefers to defect regardless of Player 1's Behavior.}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(4,2)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(1,1)$ \\\cline{3-4}
\end{tabular}
\end{subtable}
\caption{\label{tab:infoProb}\textbf{Example of Information Problem.} Numbers represent payoffs to players.  The first number in each cell represents Player 1's payoffs, the second number represents Player 2's payoffs.  Player's want the highest payoff.}
\end{center}
\end{table}

If Player 2 is honorable, Player 1 wants to cooperate.  If Player 2 is not honorable, then Player 1 is in the Prisoner's Dilemma above and wants to defects.  Player 1 cooperates or defects depending on her belief that Player 2 is honorable.  Without a way to for Player 2 to signal honor, Player 1 defects.  Again, no one is happy with the resulting outcome.  The two sides would prefer mutual cooperation even to betraying the other player, but because neither side knows the other's preferences both players defect.

This can again be applied to group conflict where "cooperation" is abiding by a peace agreement and "defection" is breaking it.  In the case where both players are honorable, there is no commitment problem: both players will cooperate if the other player cooperates.  Conflict could still occur due to information problems, however.  Unless both sides know that the other will reciprocate cooperation, both sides may defect to avoid being betrayed.  It is common in group conflict for each group to claim that the other is the barrier to peace.

Another way to represent the information problem in a conflict setting is to say that two groups need to split a resource, but neither knows each other's fighting strength (capacity) or valuation of the resource (willingness).  Without knowing the other side's capacity and willingness to fight, neither side knows what they should offer or receive from a peace agreement.  If, for example, each side believes (incorrectly) that they are stronger than the other, that overconfidence prevent both sides from finding a peace agreement in which they receive more than they expect to receive through fighting [@johnson2009overconfidence].  This information problem can cause bargaining failures even if the two sides communicate.  Both groups have an incentive to portray themselves as stronger, more willing to fight, and less willing to make concessions than they truly are in order to achieve an advantageous bargaining outcome [@fearon1995rationalist].

Groups can suffer from information problems and commitment problems simultaneously. In this example of splitting a resource, groups may fight even if both know each other's fighting strength and valuation of the resource under dispute (i.e. under complete information).  With this complete information, groups could presumably allocate a portion of that resource to each side, with the higher-strength side taking a larger portion.  The problem, however, is that once a group takes a larger portion of the resource, they now have more fighting strength and could renegotiate an even more advantageous deal for themselves.  Knowing this, the weaker side may prefer to fight rather than acquiesce to a series of peace agreements under weaker and weaker bargaining power.


**No bargaining range**: A third reason groups fight is that one or both sides prefers fighting to peace.  In other words, there is no bargaining range: peace agreements acceptable to both sides.  I will refer to this as a "preferences problem".  This preferences problem is not a bargaining failure; if one or both sides prefer fighting to any peace deal, then groups are not bargaining for peace.  Nor is this a "problem" the way as commitment problems and information problems are a problem.  In those problems, conflict is a puzzle because groups end up with outcomes neither group likes and which do not maximize overall utility.  If mutual fighting maximizes overall utility, it is a problem normatively in that we normatively dislike fighting, but it is only a puzzle if we think groups should not prefer fighting.  For these reasons, preferences for fighting over peace are an important reason for group conflict but are discussed less frequently in published literature [but see @coe2012costly, @slantchev2012borrowed, and @chang2013war].

We can observe a preferences problem by again modifying the Prisoner's Dilemma.  Imagine that the criminals hate each other and would regret _not_ ratting out the other guy.  This is represented by adding +1 to the payoff of joint defection and -1 to the payoff of joint cooperation.  Their payoffs would look like Table \ref{prefProb}.  

\begin{table}[h!]
\begin{center}
\setlength{\extrarowheight}{2pt}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(1,1)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(2,2)$ \\\cline{3-4}
\end{tabular}
\caption{\label{tab:prefProb}\textbf{Example of Preferences Problem.} Numbers represent payoffs to players.  The first number in each cell represents Player 1's payoffs, the second number represents Player 2's payoffs.  Player's want the highest payoff.}
\end{center}
\end{table}

This setup, like the Prisoner's Dilemma, results in mutual defection.  Unlike the Prisoner's Dilemma, the players would not commit to cooperation even if they could; nor does knowledge about each other's preferences avoid defection.  Mutual defection is the Pareto-optimal outcome in that it maximizes the total utility of both sides.

Preferences for fighting can also be seen in group conflict.  Each side may prefer to fight because peace is relatively more costly, perhaps because peace entails mounting armament costs [@coe2012costly; @chang2017endogenous] or because of debt payments that a state can only repay if they win the conflict [@slantchev2012borrowed].  Sides may also prefer fighting to peace because fighting is less costly than assumed due limited destruction of resources [@chang2013war].  Sides may also use fighting today to improve their bargaining position with their current adversary [@slantchev2003power] or potential future adversaries [@crescenzi2007reputation]. <!--chris: i don't think I understand slantchev2003 that well. -->^[Lack of information and overconfidence [@johnson2009overconfidence] about likely victory in conflict can cause what looks like a "preferences problem" in that groups may prefer fighting relative to any peace deal the other side is willing to accept.  The difference between an information problem and a preference problem is that the information problem disappears if both sides have complete information about the other, but complete information does not change the preferences problem.]


## Solutions to Group Conflict in the Bargaining Perspective

I will discuss third party intervention and reputation-building as the primary solutions to commitment and information problems in the bargaining perspective.  Third party intervention can solve information problems by providing accurate, credible information to both sides; it can solve commitment problems by punishing defection so that it is in both side's interests to cooperate.  Reputation-building can solve commitment problems and information problem by revealing the preferences of each player and by the prospect of better future outcomes from a cooperative reputation than a noncooperative reputation.^[These problems can also be solved through signaling, where each side sends costly signals of their preferences to the other side.  Because the signals are costly, non-cooperative types do not send costly signals.  In this discussion, I consider signaling as a type of reputation-building.]
<!--Solution is to make cooperation in each group's interest regardless of their base one-off preferences.  Can do that by adding costs to defection so that neither side benefits from defection.  Can also do that through repeated interactions.-->

<!-- Info/Comm problems between groups often solved by 3rd parties or reputations/repeated interactions. Explain how these things solve problem.  -->
Third party intervention is a common mechanism for overcoming information and commitment problems and resolving group conflict.  Third parties can solve information problems by mediating disputes, providing accurate information about the preferences and strength of both sides [@crescenzi2011supply; @gartner2011signs; but see @kydd2003side, @kydd2006can, and @beber2012international for the problem of mediator credibility].  Third parties can solve commitment problems by punishing defection, which incentivizes each side to honor agreements.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1994ethnic].  Third parties that facilitate information flows and enforce agreements often effectively reduce conflict [@doyle2000international; @di2017effectiveness; @walter2002committing; @hartzell2001stabilizing; @wallensteen2014talking].^[Some scholars have noted that third parties do not create trust between those groups that will last beyond the third party's presence [@gambetta_ch13; @rohner2013war; @beardsley2008agreement].]

<!-- many ways, other than 3rd parties, to build trust between groups.  reputation/repeated interactions.-->
In many group conflicts, however, there exists no third party with the capacity and incentive to intervene into the conflict [@fey2010shuttle, p.530].  This situation is common for internal conflicts in weak states, where conflicts are diffuse and the state lacks the capacity to mediate or intervene effectively.  Many group conflicts occur in such states [chris: cite].

In those cases, groups can resolve information and commitment problems without relying on third party intervention.  Groups can resolve those problems by cultivating reputations for trustworthiness in repeated interactions.  Repeated interactions between groups, like third parties, help overcome these problems by providing each group with the incentive to honor agreements.  Here the incentive comes not from fear of punishment by a third party but the prospect of better future outcomes from cooperation than defection.  Though each group may have an incentive to defect on an agreement today if the groups will not interact tomorrow, the groups have an incentive to cooperate now if their behavior today will be reciprocated by the other side in future interactions [@ostrom2003trust; @kydd2000trust; @axelrod1981evolution].[^reputation]  When both groups stand to gain more from enduring cooperation than enduring defection, but information and/or commitment problems would stymie cooperation in one-shot interactions, repeated interactions provide groups with the incentive to cooperate and provide groups with the opportunity to signal their preference for cooperation.

[^reputation]: I discuss reciprocity and reputations together, but these mechanisms are subtly different.  The reciprocity mechanism is generally mobilized for contexts with just two groups.  In those contexts, cooperation in previous interactions assists in obtaining cooperative behavior in the future from the same partner; other potential partners are unnecessary.  The reputation mechanism is generally (though not always) mobilized for contexts in which many groups observe the behavior of many other groups.  In those contexts a good reputation assists in obtaining _other_ cooperative partners; reciprocity from the same partner is unnecessary.  I discuss these mechanisms together because both rely on creating cooperative expectations from bargaining partners in future interactions.

In this section, I reviewed common explanations for and solutions to group conflict under the bargaining perspective.  In the next section, I show how the identity perspective fits with and adds to the bargaining perspective.

