---
title: "Group Conflict and Collective Action: theory outline"
author: "Christopher Grady"
date: "May 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


IIIa: Applying Identity Perspective to Bargaining
-	Make fighting preferable to peace (or at least to the bargains the other side will agree to)
    - Adding costs to peace (preferences problem)
    - Adding value to fighting (preferences problem)
-	Limitations of repeated interactions (info/commit problem)
    - Biasing perceptions (even if groups prefer peace to fighting) (information and commitment problems)
        - Cannot build trust; only in interest to cooperate if 
-	Bleak picture; next section proposes a solution.


<!--chris: bring in relative gains somehow; preference for fighting because expect to win, care about damaging enemy, don't like that cooperation benefits both? Myopia?  What psychological/cognitive biases cause groups to consider relative gains?  Social comparisons/social identity theory?
chris: bring in @bohm2016makes about how perceiving your side as defensive increases outgroup hate and promotes pre-emptive actions to defend ingroup.-->


<!--4 - general problems with rep/repeated interactions: don't want peace because psych costs; even if want peace, incentive to act tough to get best deal; even if want peace and not acting tough, biased perceptions of outgroup means each group is likely to misinterpret each other's cooperative signals.-->
<!--
Solving commitment problems through repeated interactions also faces limitations, however, especially for groups in or with a history of conflict.  Repeated interactions only solve commitment problems if both groups prefer peace (cooperation) to fighting (defection).  Though peace is in each group's material interest, preferences often deviate from material interest [@fehr2002social].  In the case of conflict, groups may not want peace because they derive psychological benefit from feelings of group superiority and from harm to a hated outgroup [@weisel2015ingroup; @cikara2014their; @tajfel2981groups; @fein1997prejudice] and when their animosity leads them to prefer relative gains over the outgroup to absolute gains for themselves [@waltz2010theory; @halevy2010relative; @turner1979social; @tajfel1971social].  Even if groups desire peace, they maintain an incentive to act "tough" to get the best deal, and so may not signal their desire for peace [@ross1995psychological].  And even if groups signal their desire for peace, phenomena like confirmation bias, cognitive dissonance, and motivated reasoning can bias perceptions of outgroup behavior and prevent groups from accurately perceiving peaceful intentions [@de2008motivated; @ward1997naive; @duncan1976differential; @vallone1985hostileMedia; @festinger1962cognitiveDissonance; @kunda1990motivatedReasoning; @tajfel1969cognitive; @nickerson1998confirmation].  These non-material factors can prevent future interactions from solving groups' commitment problem.-->


# Applying the Identity Perspective to Bargaining

<!--Bargaining perspective formalizes the reasons groups can fight: preferences (lack of bargaining range), information problems, commitment problems.  The identity perspective highlights many of the factors that contribute to information problems, commitment problems, and the lack of a bargaining range. -->
The bargaining perspective explains formalizes the reasons groups can fight: preferences (lack of bargaining range), information problems, commitment problems.  I argue that the identity perspective adds to these explanations by describing how psychological and social factors (1) decrease the bargaining range by providing incentives for groups to fight, (2) cause commitment problems by preventing the formation of trust, and (3) cause information problems by biasing information processing about the other group and perceptions of their preferences.  By looking at groups as a collection of individual group members and focusing on individuals' perceptual and cognitive biases, the identity perspective helps explain when and why fighting will occur.

<!--costs to peace:
(1) self-esteem loss
(2) cost of losing justification for past aggressive/discriminatory behaviors
(3) general costs to attitude change: I thought those people were bad, now we're supposed to work with them?
(4) cost of changing norms/institutions that discriminated against the outgroup.
(5) domestic audience costs to leaders?
(6) making peace with an enemy?
(7) sunk cost fallacy / "dissonant...to accept terms today that could have been achieved, without the ensuing costs...,at some earlier point in time."
-->

## Costs of Peace and Benefits of Fighting Reduce the Bargaining Range

<!--chris: be clear that adding costs to peace does not make groups necessarily "prefer fighting to peace", but may make them prefer fighting to the set of bargains the other side will agree to.-->
Psychological and social factors can contribute to group conflict by reducing or erasing the range of peace agreements both sides will accept.  These factors reduce the bargaining range by adding costs to peace and benefits to fighting.  I identify three main ways that psychological and social factors add costs to peace: (1) direct costs of changing attitudes and social norms, (2) loss of self-esteem, and (3) loss of sunk costs.^[These three reasons are not an exhaustive list of the ways that psychological and social factors add costs to peace.  Rather than give an exhaustive list, I seek to demonstrate that explicitly considering psychological and social factors helps explain why groups would find peace costly.]

First, direct costs to attitude change occur to the extent that accepting peace requires individuals in the group to change attitudes about the outgroup.  Individuals use many strategies to maintain existing attitudes -- searching for information that confirms pre-existing beliefs, counter-arguing information divergent with their beliefs -- suggesting that costs to attitude change are not insubstantial [@festinger1962cognitiveDissonance; @nickerson1998confirmation; @kunda1990motivatedReasoning].  Changing negative attitudes towards an enemy may be especially challenging because negative outgroup attitudes are supported by a social norms and justifications that feeds conflict [@bar2007sociopsychological].  At the group-level, a peace agreement requires groups to dismantle the social institutions that fed conflict and encouraged violence against the outgroup [@bornstein2003intergroup].  Those institutions must be reformed to prevent, not encourage, intergroup violence.

Second, peace agreements may cause a loss of self-esteem for individual group members.  Group members derive self-esteem from positively comparing their group to a rival group, and and any agreement in which their side acknowledges the legitimacy of the other challenges this group-based boost to self-esteem [@tajfel1981groups; @wood2000attitude; @tajfel1979integrative; @fein1997prejudice; @martiny2012shall; @brown2019group].  Group members may also pay psychological costs to their self-esteem from losing their rationalization for engaging in discriminatory or aggressive behaviors towards outgroup members.  People rationalize their behavior to maintain a moral self-image [@bandura1999moral; @bandura2014social; @mazar2008dishonesty], and people who harmed the outgroup must come to terms with past behaviors that are now deemed immoral.

Third, individuals are affected by sunk costs and want the gain from a peace deal to make up for the cost of fighting even though those costs were already born [@arkes1985psychology].  The desire to recoup sunk costs induces both sides to demand that the other concede more in a peace agreement.  It would be "dissonant for the disputing parties to accept terms today that could have been achieved, without the ensuing costs, at some earlier point in time" [@ross1995psychological, p.264].  In conjunction with biased perceptions and memories of conflict history (discussed below), each group is also prone to believe that they are morally entitled to more concessions than the other side [@ross1995naive].  Accepting terms that could have been achieved without fighting is also to admit that fighting was a mistake, and people are loathe to admit their mistakes [@tavris2008mistakes].  This partially explains why "emotions stemming from past interethnic violence serve as impediments to peaceful resolutions to present-day conflicts" [@little2017bargaining, p.5; @horowitz2001deadly; @petersen2002understanding]

<!--Example of costs to peace. harm, discrimination. -->
To see how these psychological costs to peace might sabotage peace efforts, imagine that groups fighting over land sign a peace agreement that assigns some land to each group.  This agreement may make material sense in that each group can enjoy the benefits of some land instead of fighting for all of it.  But in addition to the material cost of losing potential access to land granted to the other side, each group must begin punishing violence against outgroup members rather than encouraging it.  Individuals in the group must adjust their behavior to conform to new norms and rethink the status of their group relative to the outgroup; they can no longer "bask in the reflected glory" of their group's superiority [@brown2019group, p.312].  Individuals who felt justified in overcharged outgroup members for services or physically harming outgroup members are now told that such behaviors are wrong and immoral.  Individuals must also accept that their sacrifices to benefit fighting -- dead friends and loved ones, material deprivation, time and energy spent fighting -- were for naught: the sacrifices did not help the group win.  Sustaining conflict against the outgroup allows group members to maintain existing attitudes and behaviors and preserves the possibility that their group will be victorious.

<!--Benefit to fighting-->
Other than avoiding these costs, group members may gain benefits from fighting for two main reasons.  First, group members may feel pleasure in response to outgroup pain [@weisel2015ingroup; @cikara2014their].  This pleasure adds psychological utility to participating in conflict for individual group members.  Second, individuals may like gaining glory and other social rewards for participating in violent conflict.  Societies use various social carrots and sticks to encourage participation in conflict [@gneezy2012conflict], and group members give up those rewards when conflict ends.  These social rewards add social utility to participating in conflict, which could make fighting more attractive than peace.  These benefits to fighting may work in conjunction with each side's desire to signal strength and resolve to future potential adversaries and each side's tendency to overestimate their chances of victory, which can also promote preferences for fighting in the bargaining perspective [@johnson2009overconfidence; @crescenzi2007reputation].

<!--Costs to peace, benefits to fighting: no possible peace agreements -->
As a result of these costs to peace and benefits to conflict, there may exist no peace agreement that both sides prefer to fighting.  Each group may prefer mutual defection and their payoff structure may resemble Table \ref{prefProb}, where fighting occurs because groups have a "preferences problem".  Each side may only accept a peace agreement that materially favor their group because the material gains from peace must overcome its non-material costs; it is difficult for each side to appreciate the non-material costs of the other [@ross1995naive].  Groups may also consider their gains relative to the outgroup, rather than in absolute terms.  Indeed, many group members are willing to accept lower absolute gains to increase relative gain over the outgroup [@turner1970social; @waltz2010theory; @halevy2010relative;].  The preference for gains relative to the outgroup makes any mutually beneficial peace agreement impossible.
<!--In that case, reputations in repeated interactions do not bring peace.  Each side prefers mutual cooperation in repeated interactions only if their utility from mutual cooperation exceeds their utility from mutual defection.   -->


## Biased Perceptions Cause Information and Commitment Problems

<!--Bias perceptions-->
Though the above factors can increase the costs of peace and increase benefits of conflict, the high cost of conflict may be such that both sides still prefer peace.  Even when both sides prefer peace, psychological and social factors can contribute to the information and commitment problems that prevent groups from negotiating peace agreements.  I identify two main ways that these factors contribute to information and commitment problems.  First, cognitive dissonance, motivated reasoning, and confirmation bias[^biasDefs1] cause each side to interpret the other's behavior in a way that supports existing negative attitudes.  Second, loss aversion and reactive devaluation[^biasDefs2] cause the two sides to overvalue concessions they give up and undervalue concessions they receive.  These phenomena introduce significant friction in the ability of groups to accurately perceive the other's preferences and to build trusting relationships.

[^biasDefs1]: _Cognitive dissonance_ is the mental discomfort that occurs when one individual holds two contradictory beliefs.  Individuals resolve this dissonance by rejecting one of the contradictory beliefs [@festinger1962cognitiveDissonance; @tavris2008mistakes].  Individuals tend to resolve this dissonance by rejecting the newer or less central belief because it is costly to reject older and more central beliefs [@schwartz1990towards; @converse1970attitudes; @bryan2019values].  _Motivated reasoning_ and _confirmation bias_ are related concepts.  Motivated reasoning is the tendency for individuals to "reason" in whatever way allows them to reach their desired conclusion [@kunda1990motivatedReasoning].  Confirmation bias is the tendency for individuals to interpret new information and search memory for information to confirm existing beliefs [@nickerson1998confirmation].

[^biasDefs2]: _Loss aversion_ refers to individuals' tendency to prefer avoiding losses more than they attaining equivalent gains [@kahneman2013prospect].  Reactive devaluation is the tendency for individuals to undervalue concessions and proposals from antagonists [@ward1997naive; @ross1991barriers].

Cognitive dissonance, motivated reasoning, and confirmation bias cause group members to interpret and recall outgroup behavior in negative ways.  These phenemona prevent cross-group interactions from accurately revealing each side's preferences because members of different groups experience and interpret the same event differently [@ross1995naive].  Defensive action by outgroup members may be misperceived as belligerent and threatening while belligerent action by one's own group is seen as defensive and justified [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Positive actions by outgroup members may be re-interpreted as negative to avoid cognitive dissonance [@gubler2013humanizing; @paolini2010negative; @good2000individuals].  Unequivocally positive behavior may be dismissed as an exception while negative attributes are believed to define all outgroup members [@hewstone1990ultimate].  These misperceptions can lead each group to believe the other side is untrustworthy or prefers fighting to peace.  And when recalling information about the outgroup from memory, individuals selectively recall events that corroborate their pre-existing negative perceptions [@de2008motivated].

<!--paragraph about loss aversion and reactive devaluation -->
Loss aversion and reactive devaluation can further sabotage the trust-building process.  Individuals tend to weigh losses more heavily than equivalent gains, so anything their group gives up may be magnified in importance [@kahneman2013prospect].  At the same time, individuals tend to undervalue concessions from antagonists [@ward1997naive; @ross1991barriers].  These biased valuations of concessions made and concessions given can prevent groups from reaching a mutually beneficial agreement.  For an abstract example, imagine that Group 1 offers Group 2 a concession that is objectively worth five "negotiation units", but which Group 1 values as six due to loss aversion.  Group 2 may interpret that five as a four due to reactive devaluation, and then offer something that is objectively only worth three but which they perceive as worth four due to loss aversion.  Each group could come away from that encounter believing that the other is unreasonable and that there is no peace agreement mutually satisfactory to both sides.

<!--Example with costly signaling.-->
These phenomena can also interfere with groups sending and receiving costly signals of cooperative intent, one of the main ways groups reveal their preferences and solve commitment problems [@kydd2000trust; @rohner2013war; @gambetta_ch13; @jervis2017perception].  Costly signals are intended to reassure each side of the other's trustworthiness.  A costly signal from Group 1 to Group 2 can allow Group 2 to trust Group 1 because Group 1 would only pay the cost of the signal if Group 1 was trustworthy.  Perceptual biases like reactive devaluation, however, may lower the perceived costliness of any cooperative signal.  Group 2 may perceive the signal as cheap and uninformative of Group 1's preferences or intentions.  Worse, Group 2 may perceive the signal as a cynical attempt to manipulate Group 2 into cooperating so that Group 1 can take advantage of their naivete.

<!--Limited opportunities for interaction -->
Compounding these perceptual problems, accurate information and intergroup trust are hampered by a lack of opportunities to learn about the other side.  Groups in conflict tend to limit contact between the two sides [@bornstein2003intergroup], so most learning must come from observing the outgroup's interactions with other groups.  Even if those opportunities are available, few of the outgroup's interactions will be with groups that are relevant for predicting the outgroup's behavior towards the ingroup, reducing the usefulness of observational learning [@kazdin1974covertModeling; @yang2013similarity]. The main opportunity to observe outgroup behavior and learn their reputation is the ingroup's own interactions with the outgroup, which are limited and hampered by perceptual biases.

## Solutions in the Identity Perspective Applied to the Bargaining Perspective

<!--introduce intergroup contact.  overall goal of section: how intergroup contact helps reducing costs to peace, benefits to fighting, and perceptual biases. -->
I will discuss intergroup contact as the primary solution to group conflict in the identity perspective.  Intergroup contact, interactions between group members in which members of different groups work together to achieve common goals, is not the only solution for group conflict, but I believe it is the most promising solution [see @bohm2018psychology for a summary of others.]   Intergroup contact has the potential to (1) change incentives for fighting and peace, (2) debias perceptions of the outgroup, and (3) provide opportunities for costly signaling.  Put another way, intergroup contact can increase the bargaining range and help solve information and commitment problems.

<!--1-material benefits of cooperation/peace; 2-lowers benefits of fighting if no hate.
Make groups want peace: Goal achievement through cooperation: cooperation in each group’s interest.
perceive that the benefits of peace outweigh the benefits of fighting; a solution should increase the expected payoff of peace (through examples of cross-group cooperation working well) and reduce psychological benefits from harming outgroup.
-->
Intergroup contact can increase the value of peace and decrease the value of fighting, thereby increasing the bargaining range and increasing the likelihood that there are peace agreements both sides prefer to fighting. Intergoup contact does this first by highlighting the material benefits of cooperation.  Few members of groups in conflict are likely to have benefitted from working with the outgroup, so they may associate the outgroup with undesirable outcomes.  When groups achieve a goal through cooperation that is mutually beneficial to both, it adds previously unforeseen benefits to cooperation.  The prospect of benefits through cooperation can motivate individuals to develop more positive attitudes towards cooperation [@grady2020lab; @rohner2013war].  If cooperation is beneficial to the group, the group may develop norms that encourage cooperation [@axelrod1986evolutionary; chris: cite?].  

Along with increasing the perceived value of peace, intergroup contact can also remove benefits to fighting for group members who gain psychological utility or enjoy social rewards from harming the outgroup.  Intergroup contact humanizes and creates positive attitudes towards the other side [@pettigrew1998intergroup; @pettigrew2006meta], and group members only gain utility from harming the outgroup if the outgroup is viewed negatively and without empathy [@bohm2016makes; @weisel2015ingroup; @cikara2014their].  Likewise, groups norms that promote cooperation will give social punishments, not social rewards, for aggressive action towards the outgroup.  When the outgroup is not hated, harming them loses its luster.
<!--More positive individual attitudes and social norms towards the outgroup should also add costs to fighting-->

<!--done: make preferences for peace.  less costs to peace, less benefit to fighting. -->
<!--Next: debias perceptions. -->
<!--Lastly: opportunities for signaling -->

<!--also tells each group that the other side wants to cooperate.  Can trust other side to do what is in their own interest. solves information problem & commitment problem. -->
As well as increasing the utility of cooperation relative to fighting, for intergroup contact to help resolve group conflict it must help solve information and commitment problems.  Intergroup contact can help solve these problems by assuring each group that the other side prefer cooperation to fighting.  It is not enough that each group prefers cooperation, they must have the opportunity to signal that preference to the other side, and the other side must accept the signal.  Without this shared knowledge, groups may remain in conflict because of information and/or commitment problems.  

<!--reduces perceptual biases, greases the gears. -->
The second way that intergroup contact helps reduce conflict is by reducing perceptual biases that prevent groups from accurately perceiving the other side's preferences and building trust.  Removing these perceptual biases helps solve information and commitment problems.  Intergroup contact reduces perceptual biases by dispelling stereotypes, reducing feeling of threat and anxiety, engendering feelings of empathy, and making group commonalities salient [@allport1954prejudice; @pettigrew2008does; @page2008little; @batson1997empathy; @broockman2016durably; @gaertner1993common].  By removing these causes of perceptual biases, groups are more able to form accurate views of each other's preferences.  Without stereotypes and feelings of threat, and with empathy and group commonalities, group members will not be motivated to see the outgroup negatively or feel dissonance after positive experiences with outgroup members.  Groups are also less likely to reactively devalue each other's concessions and more likely to have empathy for each other's positions.  Through these mechanisms, contact builds trust even between members of conflicting groups [@grady2020farmer; @hewstone2006intergroup].

By debiasing perceptions, each group may identify that it is in each group's interest to cooperate with each other.  All of the mechanisms above -- reducing stereotypes and threat, increasing empathy -- also increase the likelihood that group members perceive cooperation to be in their interest and in the interest of the other side. It is unlikely that one side will expect cross-group interaction to be in their group's interest if that side fears the outgroup and holds negative stereotypes about the outgroup's work ethic and honesty.  It is equally unlikely that a group will expect the other side to cooperate with them if the other side believes them to be lazy and dishonest.  Likewise, achieving a joint goal through cooperation reassures each group that the other side also prefers cooperation.  If each side prefers cooperation but neither side is aware of the other side's preferences, groups may not cooperate to avoid the costs of being betrayed.  Each side can trust the other to engage in cooperative behavior when both side's know that it is in each side's interest to do so [@gambetta_ch13].  Removing these perceptual baises helps each side see that cooperation is in the interest of their group _and_ of the other group.  It takes two to mutually cooperate.
<!--@gambetta_ch13: Contact builds familiarity, which may be necessary for trust to form: "trust may be a by-product...of familiarity and friendship, both of which imply that those involved have some knowledge of each other and some respect for each other’s welfare."-->
<!-- @gambetta_ch13: "It is necessary not only to trust others before acting cooperatively, but also to believe that one is trusted by others."
@gambetta_ch13: "The importance of interest is twofold: it can be seen to govern action independently of a given level of trust, but it can also act on trust itself by making behaviour more predictable."  "cooperative behaviour does not depend on trust alone" but on interest/incentives.
        On closer inspection we find that when that pressure is commonly shared and this fact is known to both sides, then cooperation is motivated and trust itself may increase as a result."  Later, quoting Hume: "'...interest is the first obligation to the performance of promises. Afterwards a sentiment of morals concurs with interest, and becomes a new obligation upon mankind (1969: 574)."
-->

<!--done: debias perceptions. -->
<!--next: signal other side's preferences-->

<!--Provides opportunity for costly signaling: groups interact and can directly observe outgroup’s preferences and behavior.
small cooperation helps build large.  Confidence-building measure -->
Along with increasing the utility of cooperation and debiasing perceptions, the third way that intergroup contact can help resolve conflict is by offering opportunities for costly signaling.  Intergroup contact allows groups members to learn about each other based on personal experience, interacting and communicating directly.  Direct cross-group interaction allows group members to signal their trustworthiness through communication with and behavior directly observed by the other side.  This type of direct communication reduces competition and helps solve commitment problems in behavioral games like the Prisoner's Dilemma [@bornstein1989within; @ostrom2006value] and in formal models [@rohner2013war].  These interactions can serve as confidence-building measures and allow groups to start small and low-risk and gradually increasing as groups build trust over time; trust is one of the few resources that increases with use [@gambetta_ch13].  Importantly, intergroup contact gives each group the opportunity to signal willingness to punish their own members if those members jeopardize peace [@fearon1996explaining].

In this section, I showed how the identity perspective works with the bargaining perspective to explain group conflict.  I also demonstrated how a solution proposed by the identity perspective, intergroup contact, works in the bargaining perspective.  Intergroup contact can provide incentives for cooperation, reduce perceptual biases, and provide opportunities for costly signals of trustworthiness.  Through incentives for cooperation, it can give each side a preference for peace over fighting.  By reducing perceptual baises and providing opportunities for costly signaling, contact can help solve information and commitment problems.  In the next section, I apply this joined perspective to farmer-pastoralist conflict in Nigeria and describe the form that institutions to improve intergroup cooperation have taken in that context.




***************



## Problem of Collective Action


<!--Bleak picture; next section potential solution. -->
This is a bleak picture.  Repeated interactions can create the trust needed for long-term peace, but getting cooperation started is difficult because of psychological costs to cooperation, incentives to increase bargaining power by acting uncooperative, and cognitive biases that prevent groups from receiving each other's cooperative signals.  And beyond signaling the intent of the group's majority to abide by peace agreements, groups must go further and signal their willingness and capacity to punish their own group members if a group member defects on the agreement.

<!--7 - Insights from psych on how to change attitudes and relieve biased perceptions.  Intergroup contact to achieve goal. Groups expect the other side to do what is in their interest; if each side recognizes that the other will cooperate out of self-interest, can trust other side to cooperate.

Contact gives groups a reason to get along.  Contact is Confidence-building measure, costly signal. chris: Need to incorporate.

the solution needs to (1) remove psych costs to peace and psych/social barriers to trusting other side, (2) signal that each group has solved its collective action problem and can compel radical group members to not take aggressive action against outgroup.
-->
Despite the bleakness, insights from psychology and political science provide means to overcome the issues that prevent groups from developing trust in repeated interactions.  When repeated interactions help groups cooperate they do so because each group sees that peaceful cooperation is in both their interests; repeated interactions fail to bring about peace when groups prefer fighting or when groups think the other side prefers fighting.  To help groups overcome their commitment problems through repeated interactions, an intervention must shift preferences towards peace and provide an opportunity for each group to observe this preference in the other.  Structured intergroup contact -- cross-group interactions in which groups cooperate to achieve shared goals -- can show groups that peace is in both their interests, remove the psychological barriers to each group identifying that the other wants peace, and provide opportunities for each group to send costly signals of their intent to cooperate and willingness to punish ingroup members who do not.  Achieving a joint goal demonstrates to each group that both their interests are best served through cooperation.  The prospect of benefit through cross-group cooperation motivates cooperation and attitude change [@grady2020lab; @rohner2013war] as well as the adoption of group norms to ensure cooperation, like punishment of ingroup members whose behavior undermines peace [@axelrod1986evolutionary; @fearon1996explaining].  Believing that the other side wants peace also creates the expectation that the other side will solve its collective action problem and police their own because it is in their interest to do so.



************************


<!--Reactive devaluation applies to ingroup policing: "If they are willing to punish X, then the punishment must not be very severe."

@nadler2006intergroup showed that expressions of empathy worsened attitudes towards outgroup unless a basic level of trust was present.-->






<!--
**********

## Problems with 3rd parties specific to heterogeneous groups

Not good when conflict too decentralized for a third party to effectively mediate or intervene.

Third parties should also face specific limitations enforcing agreements among heterogeneous and decentralized groups.  The punishment used by the third party must be applied to those who would defect on the agreement if it is to deter their defection.  This process works better for homogeneous groups like armies, where responsibility for the behavior of any group member can be assigned to the group as a whole, than for heterogeneous groups, where identification and punishment must occur at a much more granular level.  Punishing the entire group for the behavior of a few radicals will likely undermine the third party's credibility, rather than promote peace.^[Many instances of conflict, even those described as wars, are often characterized by small-scale fighting by decentralized groups.  Most of the fighting in what are today called the American Indian Wars took this form, as did the range wars and sheep wars of the American West, present conflicts between farmers and pastoralist in the African Sahel, and many insurgencies involving autonomous insurgent groups.]

specific problems: cannot have repeated interactions with most outgroup members; most of the group can be trusted and thought to have good intentions, but peace can be derailed by a few radicals.
Repeated interactions also face problems specific to heterogeneous groups.  If groups are heterogeneous, repeated action with each outgroup member unlikely.  Reputation.
-->
