---
title: "e_application_outline"
author: "Christopher Grady"
date: "June 8, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

IV: Farmer-pastoralist conflict
-	Describe conflict dynamics (graze, farm)
-	Describe damage (costs of conflict)
- Describe preferences problem (non-material costs/benefits to conflict)
-	Describe commitment problem and information problem
    - Commitment problem can be resolved through information about the other side’s preferences and ability to compel group members
-	Describe how groups solved those problems: joint punishment institutions: adhoc and agreed upon code of laws.
-	Describe typical conflict escalation without: case of poisoned crop residue
-	Describe similar situation with joint-punishment institution: case of captured vigilantes (accidental D).



# Application: Farmer-Pastoralist Conflict

The conflict between farmers and pastoralists in Nigeria looks like a textbook case of a commitment problem preventing peace.  The groups maintain complementary ways of life, making cooperation beneficial for both.  Pastoralists have an excess of protein in the form of meat, milk, and other animal products, but they grow little in the way of grains, tubers and vegetables; the farmers have an excess of grains, tubers, and vegetables but they own few animals and have limited access to animal products.[^chicken]  Farmers also want animals to graze on their lands after harvest season to replenish the soil with animal waste, and pastoralists want to graze their animals on crop residue (stalks, leaves, seed pods, and other inedible parts of the plant) that is left on the fields after harvest.

[^chicken]: This is not to say that farmers have no independent access to protein and pastoralists have no independent access to grain.  Farming villages typically stock chickens for eggs and meat as their main protein source, with a few goats and sheep.  They do not have excess food year round to support large animals like cows.  Most pastoralists are semi-migratory and few stay in one place long enough to cultivate crops.  Those who stay in a "home base" will set aside some land for rice or yams, but most of the land is left for cattle to graze.

By all accounts, farmers and pastoralists benefitted from their complementarity for several generations [@tonah2002fulani; @icg2017nigeria; @thebaud2001sahel].  There were, of course, disagreements between sedentary farmers and mobile pastoralists, but their relationship was characterized more by harmony than conflict.  Recent decades, however, have brought farmers and pastoralists into conflict.  Historically, farming was more common in southern Nigeria and pastoralism more common in the north, but the two ways of life increasingly overlap geographically.  Farmers have moved north into marginal agricultural lands due to the increasing food needs of Nigeria's booming population, which grew from 50 million at Independence in 1960 to 200 million today [@abbass2012no; @kuusaana2015land].  At the same time, pastoralists have been pushed further south by the expansion of the Sahara, which brought them to higher population density areas [@thomas2018sahara; @okpara2015conflicts].  Less land and more people who depend on the land is a recipe for conflict over land and resources.

Farmer-pastoralist conflict has exploded in recent years.  The most recent conflict escalation caused 7,000 deaths from 2014-2019 and displaced hundreds of thousands of people from their homes [@council2019nigeria; @daniel2018anti; @fa2019deadly; @nyt2018nigeria].  The scale of economic damage is unknown, but farmer-pastoralist conflict _before_ this escalation cost Nigeria $13 billion annually in lost economic productivity [@mcdougal2015effect].  This violence has also impeded food production, leading to an impending food crisis [@fa2019deadly; @frontera2018nigeria; @unah2018nigeria].  

The proximate causes of violence are farmers sowing seeds on pastoralists' grazing lands and pastoralists grazing their cattle on farmers' crops.  If either side retaliates -- a farmer by stealing cattle from the pastoralists' herds, a pastoralist by grazing on more farmland -- the scope of the conflict can rapildy expand.  The farmer whose crops were destroyed by cattle does not know which herd grazed on his land; cattle he steals in revenge do not necessarily come from the transgressing herd.  Pastoralists, likewise, do not know which farmer stole their cattle; the crops they destroy in revenge do not necessarily come from the transgressing farm.  From there, a little war often breaks out.  As one reporter noted, "The countryside is littered with the charred ruins of homes, schools, police stations, mosques and churches." [@mcdonnel2017graze].  In one case I witnessed, a farmer took revenge against cattle grazing on his farmland by poisoning the crop residue left on his fields after harvest.  After grazing on the residue, the cattle of dozens of pastoralists became sick and died.  More violence followed. 

<!-- Describe non-material costs/benefits to conflict-->
The land conflict is exacerbated by ethnic and religious differences between groups, which feeds mutual distrust.  The pastoralists are almost all from the Fulani ethnic group and practice Islam; the farmers are from a non-Fulani ethnic groups and practice Islam and Christianity, though the violence is worst where the farmers are homogeneously Christian.  Each group sees the other as biased towards their own side for economic, cultural, and religious reasons.  Each group also sees their way of life as superior.  Farmers see nomadic life as outdated, backwards, and anti-progress; the pastoralists think that sedentary farming makes one weak.  One pastoralist commented to me that if he dropped off a sedentary adult and pastoralist child in the forest, the sedentary adult would depend on the child to survive.

Despite their cultural differences and competition for scarce land, mutual complementarity remains.  Pastoralists still have animal products -- though more farmers have bought animals in recent years, pastoralists still control roughly 90% of Nigeria's livestock [@icg2017nigeria] -- and farmers still have tubers, vegetables, grains, and the resultant crop residue.  The violence is extremely costly to both sides, so both have an incentive to avoid conflict.  Community leaders recognize that peace is in the interest of their communities, but many have been unable to prevent the violence.  In interviews conducted in 2016 and 2019 by @grady2020farmer, community leaders from farming and pastoral communities expressed their desire for peace between the two groups and blamed deviants from the other side for ongoing violence.  Farmers argue that the local pastoralists do not prevent other pastoralists who migrate through from destroying cropland, and pastoralists argue that farmers on the outskirts of the farming village encroach on grazing routes more each year.   <!--Both sides believe only they have a valid claim to the land -- pastoralists because they began grazing it before farmers sowed crops, and farmers because the government recognizes property rights of farmerse over pastoralists.-->

Farmer and pastoralists groups lack the trust needed to make an agreement, and the roots of mistrust -- deviants from both sides -- highlights that the mistrust is driven by a within-group collective action problem, not a general mistrust of all outgroup members.  Peace benefits all members of a group, but contributing to peace is costly for group members because they must refrain from engaging in behaviors that benefit themselves at the expense of the outgroup.  Achieving peace, as with any public good, requires overcoming this collective action problem: the group must compel group members to contribute to peace despite the members' individual incentive to shirk and rely on others to bear its cost.  <!--What does it mean for a group to trust another group?-->One group trusting the other to honor an agreement, then, means not only trusting that a high proportion of outgroup members desire peace, but also that those outgroup members can and will compel less cooperative group members to honor a peace agreement [@fearon1996explaining].  Peace can be derailed by a few radicals who do not reflect the preferences of most group members [@sambanis2013social; @de2009effects].

Peace between many farming and pastoral groups is prevented by a lack of trust (i.e. a commitment problem).  Both sides are better off cooperating peacefully than fighting, but neither side trusts the other to honor agreements that would prevent fighting.  The reasons each group does not trust the other side, however, is not that they believe the other side as a whole will defect on peace agreements, but rather that the farming group cannot credibly commit to preventing all farmers from expanding into grazing lands, and the pastoral group cannot credibly commit to preventing all herders from grazing cattle on croplands.  Their between-group commitment problem is driven by a within-group collective action problem because neither group trusts the other to punish their own.

## Resolving farmer-pastoralist conflict

Though conflict between farming and pastoral groups is common, not all farming and pastoral groups are in conflict.  Many communities overcame their trust problems and enjoy the complementarity of farming and pastoral lifestyles.  Communities that successfully navigated farmer-pastoralist tension generally have a noticeable commonality: an institution comprised of farmers and pastoralists to handle cases that threaten intergroup relations.  This institution can tap into ingroup networks to identify transgressors from each side, much like an ingroup policing institution [@fearon1996explaining].  In addition to the benefit of ingroup networks, these joint institutions have another benefit: since both groups are represented, neither the plaintiff, the defendant, nor their group can credibly claim that the case was decided unfairly due to group bias.  The collaborative nature of the institution helps curtail misperceptions, which can derail cooperative equilibria [@jervis2017misperception; @wu1995cope; @bendor1991doubt].

These joint institutions function much like trial by jury.  Representatives from each group meet, hear from the case's "plaintiff" and "defendant", and decide an appropriate punishment.  For common occurrences -- crop damage, cattle rustling, and the like -- there may also be a code of laws: predecided penalties, such as a set cost per acre of cropland destroyed or head of cattle stolen.  In past decades, agreements between the traditional leaders of each community function similarly, by setting compensation for specific actions.  Conflict is often blamed on the breakdown of such institutions [@tonah2002fulani; @cotula2004land; @kuusaana2015land].

These joint institutions are themselves a peace agreement.  Each group has conceded some local autonomy and agreed to an overarching legal framework that will govern both farmers and pastoralists.  To do so, the groups must agree on several issues, like who serves on the joint institution, how they decide punishmnet, what is the range of acceptable punishments, and how punishments are enforced.  This type of agreement is only possible if both groups share a baseline level of trust.  Each group must also identify that the issue causing conflict between the two sides is a commitment problem, not a preferences problem.  Before an agreement like joint punishment institutions can be reached, the groups first need to learn enough about each other's preferences to establish that each prefers mutual cooperation to mutual fighting.  Put another way, groups need to solve their information problem before they can use joint punishment institutions to solve their commitment problem.  A key challenge, then, is for groups to signal their preferences.  Intergroup contact offers a means through which groups can send and receive those signals.

@grady2020farmer evaluated a contact-based intervention to reduce conflict between farmers and pastoralists.  Though they do not measure the extent to which the intervention affected institutional structures that govern intergroup relations, they describe farmers and pastoralists who had participated in the contact intervention meeting to jointly decide an appropriate punishment for vigilante farmers who intended to harm pastoralists.  The would-be perpetrators, hailing from a nearby village, were noticed and arrested by the hometown farmers while on their way to steal the pastoralists' cattle.  Rather than decide unilaterally how to punish the vigilantes, leaders from the farming community called in leaders from the pastoral community to jointly decide a punishment.  Together the groups decided to disarm the vigilantes and let them go free without further punishment -- a solution proposed by the _pastoralists_.  Had the farmers unilaterally decided to let the vigilantes go free, the pastoralists may have interpreted the punishment as too lenient and accused the farmers of bias.  Since the pastoralists had a say in the decision-making process, however, the group's were able to build trust through cooperation.  The pastoralists appreciated the farmers calling a joint meeting, and the farmers appreciated the pastoralists magnanimity in proposing a lenient punishment.

@grady2020farmer also describe a contrasting situation in which a farmers and pastoralists who had not participated in the contact intervention failed due to the lack of any joint institutions.  In that situation, both sides were participating in a public goods game in which money raised would be jointly administered by both groups.  These groups had no preexisting structure to handle situations that concerned both sides, and neither side trusted the other to hold the money.  The pastoralists claimed that the money would be squandered by the corruption of the farming community's leader if a farmer held it; the farmers claimed that the pastoralists would migrate away with the money if a pastoralist held it.  In the end, the groups agreed that the NGO administering the public goods game would hold the money and disburse it in chunks when the pastoralist leader and the farming leader agreed on its use.

In this section, I discussed farmer-pastoralist conflict in Nigeria, focusing on causes of violence and solutions that groups developed to curtail violence.  In the next section I outline several policy implications that follow from the farmer-pastoralist example and from thinking about group conflict in the bargaining and identity perspectives.

<!--this is not "the state".  I don't know what the state is, but I know it is more than a criminal justice institution.  This serves the same purpose as the state for models of group conflict, but that doesn't make it the state. -->







************

<!--10 – Perspective/Application: Nigeria farmer-pastoralist: pastoralists graze cattle on farmland, farmers attack cattle and sow seeds in grazing lands.  Ingroups not preventing this aggression.  Farmers do not know whose cattle, pastoralists do not know who attacked their cattle.  Attack outgroup generally.  Through a contact intervention, groups established joint criminal punishment institutions when a farmer/pastoralist have grievances.  Representative from each side’s “government” (chiefs) meet and agree on punishment, make sure ingroup abides by ruling.
Perspective/Application: Race Protests/Riots 2020: black people (ingroup) following social rules, punished extremely by cops (outgroup) anyway, no punishment for outgroup defectors, eventually ingroup starts punishing members of outgroup == spiral equilibrium (F&L). Ingroup cannot identify outgroup members who defected so punish any others perceived as outgroup.  Low trust in criminal justice system, low legitimacy, low compliance.
o	Use trials; need members of ingroup and outgroup at trial.-->
I apply this perspective on reducing group conflict through contact and joint-punishment institutions to the domain of conflict between farmers and pastoralists in Africa.  Describe conflict.  @grady2020farmer reports that a contact-based intervention increased trust between groups, reduced insecurity due to violence, and increased non-intervention interaction between farmers and pastoralists.  One of the program's main implementers in conflicting communities, Israel Okpe, identified joint punishment institutions as key for the success of the program.
<!--Chiefs meet adhoc basis.  Pre-agreed upon costs for behaviors (code of laws).  Failed outgroup: spray poison on crop residue to kill cows; burn farmers house; refuse to trade with each other; attack village/ruga; migration; army. -->