---
title: "e_application_outline"
author: "Christopher Grady"
date: "June 8, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

V: Implications for Peacebuilding Programs

The first policy implication is that groups will only cooperate when it is in their interest to do so.  Preferences problem == no amount of information will reduce group conflict.  First need to show groups that peace is in their interest.
- contact good way to do this.
    - achieving a joint goal _that could not be achieved alone_.
    - comparative advantage of each group.

The second policy implication is that preferences for cooperation do not guarantee peace.
- Cooperation is only in a group's interest if the other group also plans to cooperate.
-	Opportunities to observe other side, signal C.

The third policy implication is that groups are collections of individuals, not unitary actors.
-	Reduce psych biases
-	Groups need strength to compel group members.

The fourth policy implication is that misperceptions are a major threat to peace.

The fifth implication is that there is not one solution to group conflict.
- contact does not solve all problems.  ingroup policing does not solve all problems.  

The last implication is that attempts to solve group conflict can easily backfire.
    - benefit one group more == creating a power disparity.  Favoring one group probably makes things worse.
    - try to solve problem by imposing costs to defection but not changing underlying payoff structure that led to violent conflict.  when program ends, conflict resumes.
-	Do not try to solve groups conflict externally; help groups solve own problems.
-	Important for both groups to benefit equally.  


# Policy Implications for Peacebuilding Programs

I will discuss six policy implications from farmer-pastoralist conflict and the bargaining and identity perspectives. I also discuss some consequences of these implications.  The implications are: (1) peace is not intrinsically preferable to fighting; (2) preferences for cooperation over fighting to not guarantee peace; (3) groups are collections of individuals, not unitary actors; (4) Misperceptions are a major threat to peace; (5) there is not one solution to group conflict; and (6) some attempts to alleviate group conflict can backfire.

<!--1-The first policy implication is that groups will only cooperate when it is in their interest to do so. -->
The first policy implication is that peace is not intrinsically preferable to fighting.  Some groups fight because the group members want to fight.  No information or signaling will reduce conflict in these cases because the groups' preferences are misaligned.  In those cases, the first step to peace is each side coming to believe that cooperation is superior to peace.

<!--1a: comparative advantage -->
The best chance for groups to identify that cooperation is in their material interest are distinct group-based comparative advantages.  Farmers and pastoralists each have group-based comparative advantages -- farmers in produce, pastoralists in animals -- that make identifying a shared interest easy.  Though cultural differences may seem like a hindrance to peace, these groups have much to gain from cooperation.  Two groups of farmers have little to offer each other that the group's could not obtain on their own, so there is less room for complementarity.

<!--1b: psych and social value -->
Material interest is not everything, however, and many motivators for preferences are psychological and social.  Groups may prefer fighting due to psychological and social rewards and penalties.  Group members may resist peace if it sacrifices self-esteem and self-image.  Some segment of each group may embrace fighting because it offers them the opportunity to garner social rewards.  These costs and benefits can make it so that there is no peace agreement each sides prefers to fighting.  Changing attitudes and norms can reduce the costs of peace and the benefits of fighting.  Attitude and norm change can potentially be motivated by showing the groups that they can better accomplish their goals through cooperation than conflict [@grady2020lab].


<!--2nd: preferences for cooperation do not guarantee peace -->
The second policy implication is that preferences for cooperation over fighting do not necessarily end group conflict.  Even if both groups prefers mutual cooperation to mutual defection, lack of information about the other side's preferences and an inability to commit to cooperate can prevent peace.  Cooperation is only in a group's interest if the other group also plans to cooperate.  Policies that promote peace must therefore assure each side that the other will cooperate.  The easiest way to assure each side that the other will cooperate is to impose external punishment for defection or external reward for cooperation.  That method of assurance, however, is not available in many contexts and does not build the intergroup trust necessary for cooperation once the external punishment mechanism is removed.  It may nonetheless serve as a short-term solution to reducing group conflict and as a starting point for group cooperation.

In the absence of external rewards and punishment, intergroup contact in which groups work together to achieve a joint goal can show both groups that cooperation is in their interest and that the other side also sees that.  Achieving a joint goal is good for both groups, and both groups see their group and the other side benefitting from cooperation, which helps each side update about the other's preferences -- the other side can be trusted to do what is in their own interest.  Intergroup contact also brings group members into close personal contact, which offers opportunities for learning and costly signaling.

These first two policy implications suggest that contact-based programs where the groups do not work towards a joint goal, like discussion forums, may have no effect on group conflict.  Discussion forums do not directly change preferences; nor do they provide credible information about the other side's preferences.  It is possible that this minimal form of contact could reduce perceptual baises by exposing each group to the other's view points, but they mainly seem to be avenues for "cheap talk" which both sides will discount.


<!--3rd: groups are collections of individuals, not unitary actors -->
The third policy implication is that groups are collections of group members and the preferences of the group should not be taken as the preferences fo each group member.  Group members preferences are likely correlated with the preferences of the amorphous "group", but they also deviate in important ways.  For example, the group as a unitary actor does not face a collective action problem, but the group as a collection of individuals does because each individual wants to rely on others to provide public goods.  An important attribute of a group, then, is its capacity to compel group members to contribute to the public good of peace.  The group is a useful but limited unit of analysis because it can only influence group conflict through its effect on group members.

Thinking of the group as a collection of group members also highlights (1) the psychological and social factors that make conflict attractive and (2) the perceptual and cognitive biases that color groups views of each other.  These type of individual-based factors are not readily apparent when thinking of the groups as homogenous units, but they likely contribute to group conflict.  They may also systematically cause some group members to benefit more from peace than others, so peace as a public good is not equally valuable or desirable to all group members.


<!--4th: misperceptions are a major threat to peace. -->
The fourth policy implication is that misperceptions are a major threat to peace.  It is easy to focus on changes to payoff structure and changes to the value of resources under dispute as the driver of conflict.  In the farmer-pastoralist example, we readily blame population booms and land scarcity for the recent surge in violence, and these factors no doubt precipitated that surge.  However, they do not necessarily result in group conflict unless they reduce the bargaining range to zero.  They may instead cause conflict by creating the misperception that the other side now prefers fighting for the chance to control all of the land to cooperating to share the land between the two groups.

<!--Misperceptions are also a significant cause of information and commitment problems.  Conflict often occurs not because incentives are inherently misaligned but because each group believes that the other will not cooperate.  Inaccurate beliefs about the other side creates the belief that the other side will betray your side's cooperation.-->

<!--5th: there is not one solution to group conflict -->
The fifth policy implication is that there are many ways to resolve group conflict.  Preferences can be aligned, information can be shared, commitments can be made in different ways.  Do not be wed to an ideological idea about reducing group conflict.


<!--6th: attempts to solve group conflict can easily backfire -->

<!--6b- both groups must benefit equally -->
Policy interventions that help groups achieve a joint goal must be sure that both group's benefit equally.  The group's are likely comparing their gains relative to the gains of the outgroup, and any disparity could ruin chances for peace.  Differing gains can _cause_ a commitment problem and violent conflict because the group gaining less has an incentive to fight _now_ before the other side gets stronger.  The side gaining more cannot credibly commit to a deal based on today's balance of power when their power will increase tomorrow.  

<!--other aid programs -->
Changes to payoff structure of each side can make traditional agreements useless.


**************


<!--Consequence of above about "in their interest": do not try to solve group's problems externally.  The benefits of cooperating must be factors that will not chance when a third party leaves. -->
Policy interventions should focus should be on helping groups solve their own problems, rather than the intervention solving the problem.  Third party punishment may be necessary in certain contexts, but it undermines each group learning that the other prefers peace to fighting.  Each group's cooperation might be due to the fear of punishment rather than the benefits of peace.


<!--Groups are composed of individuals with different preferences from the group-->
The second policy implication is that group's should not be considered unitary actors.  Each group is composed of individuals with preferences that may differ from the group's preferences.  

-	Reduce psych biases
-	Groups need strength to compel group members.

<!--consequence of above about "groups made of individuals": different capacity to compel individuals, leads into paragaph about militaries. -->
Group's differ in their capacity to compel group members to behave in the group's interest.  Group's with the power to compel will be better at fighting because they can compel group members to participate in violence [@bornstein2003intergroup] but should also be more able to credibly commit to preventing their own from defecting.

<!--consequence of individuals/collective action causing conflict:  this stuff likely doesn't apply to professional militaries. -->
Conflict between groups with professional armies is unlikely to be caused by collective action problem. Militaries: they solve the collective action problem. that is what army discipline is.  This collective action problem stuff and things about individual preferences for fighting do not apply to wars between hierarchical, professional organizations (like militaries).  To the extent that wars between those organizations are caused by commitment problems, the commitment problem is unlikely to be caused by a collective action problem.  More likely to be caused by factors like overconfidence, commitment problems because power changes over time, desire for tough reputation, goods that are difficult/impossible to divide (holy lands), etc [@fearon1995rationalist; @powell2006war; @reed2016bargaining; @johnson2009overconfidence; chris: need cites for tough reputation].  Could be caused by differing valuations of concessions and other perceptual biases.  Open question how individual psychological and cognitive biases function in the group context.


<!--Cooperation breeds more cooperation; threat to sustainability is accidental defection/misperceptions.  Must avoid misperceptions. -->
Third implication is that misperception is often the greatest threat to enduring peace between groups.  If groups desire peace, the perception that the other side does not desire peace can prevent cooperation.  Once groups are cooperating, misperceiving cooperation as defection can cause a series of defections.  Any institution that limits misperceptions can maintain peace.

Joint-punishment institutions limit misperceptions.  Legitimacy of the institution is paramount.


<!--Fourth: contact programs have promise; other programs can work; all programs can be mismanaged and make things worse. -->
Contact programs promising means to reduce conflict.  
Contact downstream effects: maybe only certain people in each group should participate in contact program, but that's okay.  The contact program can effect other people indirectly if norms shift.  Contact programs likely to backfire for most prejudiced people because they have the most motivation to maintain existing attitudes [@gubler2013harmoniziong].  Vicarious contact through media programs can also affect these people.

<!--contact can backfire -->
Mismanaged contact: one group achieves more from joint goal; bad people participate in contact; relevant authorities not on board with contact or not consulted.  Contact programs are hard and can easily backfire if mismanaged.

<!--other programs can work. -->
Other programs can work.  Groups can see that it is in each other's interest to cooperate without contact.  But difficult to build trust without interaction between groups.

<!--well-meaning programs can exacerbate conflict -->
Programs, if mismanaged, can exacerbate group conflict.  (1) Adding resources to ongoing conflict, those resources can get captured by the conflicting groups.  (2) Programs designed to increase economic status: make land worth fighting for, change traditional agreements that govern cost of messing with land.  (3) When  aid programs end, creating economic instability. removing incentive for groups to work together.  Can crowd out local institutions.














************

<!--11 - Implications for peacebuilding programs. -->
I conclude by discussing implications for peacebuilding programs.  Both groups must want to cooperate and believe the same is true of the other group, even absent the peacebuilding program.  Contact that achieves a goal so that it is in each group's interest to cooperate.  Contact must actually achieve the goal -- contact that does not may cause scapegoating and reinforce the perspective that cooperation with the other side is a waste of time.   Programs that only bring groups into contact (discussion forums) are unlikely to change group relations because they do not affect the fundamental causes of conflict: psychological costs to peace/benefits to fighting and .  Programs should also help groups constrain the behavior of ingroup members whose attitudes are not improved by contact.  I identify joint criminal justice institutions as the best means to 


In this I agree with @rohner2013war that tools to increase gains from interaction, and therefore increase the opportunity cost of fighting, are most likely to deter conflict.