---
title: "e_application_outline"
author: "Christopher Grady"
date: "June 8, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

VI: Avenues for Empirical Research

- More putting together of bargaining and identity perspective; other perspectives on group conflict.
- Collective action problems as potential driver of between-group commitment problems.
- Ingroup policing as potentially unsustainable due to perceptual biases and reactive devaluation?
- Collaborative institutions for ensuring peace, like joint-punishment institutions of Nigerian farmers and pastoralists.
-	Test contact programs with groups in conflict and with history of conflict.
-	Compare contact programs that do and do not (1) work to achieve goal, (2) actually achieve it.
-	Best means to demonstrate material rationality of peace.  Trade, differentiated groups?
- Best means to reduce psych/cognitive biases

-	Need for enforcement at onset to incentivize Cooperation?
-	Role of elites: contact says they must support
-	Difficulty with very decentralized groups
-	Power disparities between groups
-	Contact’s differential effects with these power disparities.
- How to get things started?
- Network graph showing how often poli econ and poli psych stuff cite themselves and not other perspective's articles.


# Avenues for Future Research

This paper sought to show how combining two perspectives on group conflict, the bargaining perspective and the identity perspective, can provide a better understanding of the causes and consequences of group conflict.  Doing so reveals several avenues for future research.  The first avenue is to synthesize models of group conflict from the numerous disciplines that study it.  Group conflict is an interdisciplinary research topic with scholarship in political science [@lopez2017determinants], economics [@kimbrough2017war], psychology [@bohm2018psychology], management science [@mccarter2018models], biology [@rusch2017logic], and evolutionary anthropology [@glowacki2017evolutionary].  Each discipline emphasizes different causes and consequences of group conflict.  A synthesis of perspectives from these distinct viewpoints could provide insights into causes of conflict and more effective methods to reduce it.

The second avenue is to further consider the role that collective action problems play in group conflict.  As we saw with farmer-pastoralist conflict and as has been written about by @fearon1996explaining and @sambanis2013social, among others, peace can be derailed by a small set of group members who refuse to "play ball" with the other side.  Without the ability to compel cooperative behavior from group members, groups cannot credibly commit to honor negotiated agreements.  This points to within-group collective action problems as the driver of some between-group commitment problems.  Peace is a public good: group members must forego behaviors that benefit them individually for peace to be achieved, but once achieved all group members enjoy its benefits whether or not they bore its costs.  

Overcoming collective action problems is notoriously difficult.  In the case of intergroup conflict, collective action problems may be even more difficult to solve because costs must be born before benefits are obtained, and group members may be killed in the meantime and thus never enjoy the benefits of their sacrifice.  Individuals are notoriously bad even at saving for retirement, where they can sacrifice now to benefit themselves later in a low-risk environment [@benartzi2013behavioral; @warner2001personal].  Individuals may rationally discount future payoffs quite significantly in conflict settings where individuals may never see the future and the benefits accrue to a group.

Bornstein (@bornstein1992free and @bornstein2003intergroup) was among the first to consider how groups dealt with the preferences of individual group members in the context of group conflict.  His focus, and the focus of most subsequent scholarship, was how groups encourage group members to participate in violence against the other side, since winning the fight benefits all group members but only group members who fight bear the costs.  Most literature about collective action problems in conflict is thus concerned with each group's attempt to compel group members to _fight_ the other side or resist external pressure; relatively little has been written about each group's attempt to compel group members to _cooperate_ with the other side [@keefer2012follow; @kaplan2010civilian; @rubin2020rebel].

Implicit in the discussion of collective action problems is that groups are made up of individuals with preferences that differ from the group.  Following that logic, war may not be equally costly to all members of society, and peace not equally beneficial.  The public good of peace is more beneficial for some group members than for others.  In the case of farmers and pastoralists, farmers on the outskirts of the community bear the brunt of "defections" during peace time, so peace may not be more costly than war for them.  If group elites bear few costs from conflict and may suffer in prestige from peace, they could resist peace agreements.  Future scholarship should consider who bears the costs of conflict and who stands to benefit from peace.

A third avenue for future research is to study the manner in which groups solve their own commitment problems, with an eye to the within-group collective problem as the driver of the between-group commitment problem.  @fearon1996explaining showed that ingroup policing, an institution wherein groups punish their own miscreants, can help groups avoid an escalation of violence.  They credit the relative paucity of group conflict to such institutions.  Ingroup policing is an excellent example of within-group institutions that prevent violence from escalating and for maintaining peace in many contexts.  

Consideration of perceptual biases and mistrust between groups in or with a recent history of conflict indicates a potential limitation of ingroup policing.  With ingroup policing, groups are restrained from overly lenient punishment of their own people by the threat of violence escalating if either group suspects the other of acting in bad faith.  Since ingroup policing depends on the perceptions of group members, if those perceptions are biased such that members of each group suspect the other is trying to take advantage of the ingroup policing institution, then the institution could break down as each group does not trust the other to allocate sufficient punishment to their own side.  The risk of cooperative behavior being misperceived as uncooperative behavior is one of the main threats to enduring peace [@jervis2017misperception; @wu1995cope; @bendor1991doubt].  Groups could account for the biases of the other side and harshly punish their own to overcome the bias, but overly harsh punishments could reduce the legitimacy of ingroup policing among the ingroup.  Future research should examine how misperceptions caused by biases like motivated reasoning and reactive devaluation affect the ingroup policing equilibrium.
<!--The ingroup could of course account for this bias and assign even harsher punishments to ingroup defectors, but those excessive punishments may reduce support for ingroup policing because group views the punishment as disproportionate to the crime. -->

If ingroup policing is unsustainable due to psychological biases, future research should also consider how to modify that institution to minimize and manage the misperceptions that result from those biases.  A starting point could be the collaborative "joint-punishment" institutions used by some farming and pastoral groups to control their conflict.  These institutions tap into ingroup networks to identify wrongdoers, like ingroup policing, but involve both sides in the punishment decisions to increase transparency.  They may also open up more lenient punishments, as neither group has to worry that the other will misperceive a lenient punishment as defecting from the agreement.  Compared to ingroup policing, however, a joint-punishment institution is likely more difficult to initiate.  Ingroup policing can be implemented by each group alone, whereas a joint structure requires many agreements about the structure's composition, decision-rules, and enforcement capacity.

The fourth avenue for future research is to use the bargaining and identity perspectives to develop mechanisms through which conflict can be resolved, and then to test those mechanisms in lab and field experiments.  One promising method to reduce conflict is intergroup contact, but, to my knowledge, no contact-based intervention has explicitly considered contact as a method to solve information and commitment problems. Contact programs are beginning to be tested between groups in or with a history of conflict, including Nigerian farmers and pastoralists [@grady2020farmer], Christians and Muslims in Iraq [@mousa2018overcome], and Jewish and Arab-Palestinian youth in Israel [@ditlmann2016can], but these programs have thus far focused more on causal inference (does contact work in these contexts) than causal mechanisms (how does contact work in these contexts).  Contact-based interventions would benefit from considering how contact solves information and commitment problems that cause conflict.

Based on the bargaining and identity perspective, intergroup contact may reduce group conflict through the achievement of a joint goal.  From this viewpoint, the key mechanism is goal achievement and without it contact will not improve attitudes or reduce conflict.  Traditionally, goal achievement is thought to "further [the] process" of attitude change, but is not necessarily central to it [@pettigrew1998intergroup, p.66].  To my knowledge, only one lab experiment has tested the effect of intergroup contact when it does or does not achieve a joint goal [@grady2020lab].  More experiments should test this mechanism with different types of group dynamics and in more contexts.

Another mechanism to reduce group conflict is to increase the utility of peace, be it materially (i.e. financial benefit) or non-materially (i.e. alignment with values).  Increasing peace's utility can solve the preference problem if one exists, but it could also solve the information problem if each side believes the preferences of the other group have changed.  I suspect increasing peace's material utility is best for solving information problems because each side is more likely to believe the other is motivated by material outcomes than non-material outcomes ("If they had those values, why are they fighting us now?").  Future research should test the efficacy of different means to increase the utility of peace.  

Interventions that reduce psychological and cognitive biases against the outgroup should also help groups solve information and commitment problems.  Along with testing the efficacy of reducing these biases, further research should test the best means through which such biases can be reduced.  Intergroup contact is one method, but it may be difficult to implement in very violent contexts or in contexts with strict segregation.  Vicarious intergroup contact -- contact in which members of each side observe ingroup members interacting with outgroup members -- could reduce biases in these contexts.

The last avenue for future research I will discuss is how group dynamics moderate the effect of interventions meant to reduce group conflict.  @fearon1996explaining noted that group size changes effective strategies for deterring group conflict: large groups can use the threat of intergroup conflict to incentivize the cooperation of a small group, and small groups use ingroup policing to avoid the wrath of the larger group.  Size and power disparities might influence conflict-reduction interventions in other ways.  The smaller group, for example, is likely to interact more frequently with the larger group than the larger group interacts with the smaller group.  Contact-based interventions may therefore have little effect on members of the smaller group, who have much personal experience with members of the larger group.  Group dynamics other than size and power disparities could similarly change strategies to reduce group conflict, such as the homogeneity and hierarchy of each group and the centralization or decentralization of power within each group.  Future research should investigate how these group dynamics affect the types of institutions that groups develop to alleviate conflict, and should determine which type of interventions are most effective in each context.








************


<!--10 – Outstanding issues: (1) Onset of these structures: How to get the ball rolling?  A place for 3rd parties? (2) How to keep ball rolling.  (3) Limitation: all out war, lack of bargaining range.-->
After considering farmer-pastoralist conflict, I address outstanding issues and avenues for empirical research.  The first issue is how to begin
