---
title: "A collective action problem causes the between-group commitment problem "
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Brainstorm

Group conflict is generally thought of as the consequence of a commitment problem: the two sides cannot make a peace agreement because neither can credibly commit to honor the agreement if a future situation gives them an advantage.  Groups are made of individual group members, peace is a public good, and everyone wants peace without bearing its cost.  Groups can solve their commitment problem by signaling a willingness and capacity to compel their members to abide by a peace agreement.  Conflicting groups have limited opportunities to send those signals and psychological phenomena that bias perceptions cause groups to misinterpret each other's signals.   Intergroup contact is one means by which the groups can receive those signals, and it removes the psychological barriers to receiving those signals.


Thinking of a group as a collection of individuals rather than a monolith.

Thinking of peace as a public good.  A peace agreement requires the cooperation of all group members but can be broken by one.

In many cases, the reason groups cannot credibly commit to honor an agreement is because groups cannot control their members.  If groups could credibly signal to each other their willingness and capacity to control group members -- through a mechanism like ingroup policing -- then groups have solved their commitment problem and a peace agreement is possible. 



