---
title: "Untitled"
author: "Christopher Grady"
date: "April 13, 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Hard test language gets repeated too many times and not explained as well as could be.  "What's at stake" is not clear.  Is the world desperate for a hard test of contact theory?  Is there another solution?

Clear that _active participant in violence_ is a clear feature of what's different about the paper.  Instead of hard test, "unique contribution of paper is that it involves a project where people are involved in ongoing conflict.  Here's why we will learn more about contact theory from this paper than a different one.  The contribution of the paper is _______".
    - not a "hard test", a "different test".  Super important test.  People in confclit not usually in contact with each other.
    - what do we learn from the experiment in the context of an ongoing fight.

Make contribution more clear, and then send it out!
    - not more than a couple of days.
    - what do we learn from the experiment in the context of an ongoing fight.  That adds to the literature.
    - Section 2 lit review kind of takes people away from Nigeria's Middle Belt
    - change how people
    - Section 3.1: could mix what MC did in Nigeria & why they thought it would be successful.  "They did this because of this literature; they did this because of the following mechanisms".  Mixed groups of equal numbers.
    - Don't let peopel forget that you are talking about a real conflict in Nigeria and a field experiment with those people.
    - maybe less on mechanisms not at stake.

