---
title: "Group Conflict and Collective Action: Intro"
author: "Christopher Grady"
date: "May 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--chris: thinking about removing discussion of third parties altogether.  Just saying "short of a third party intervening in the conflict...[repeated interaction stuff]."  Then footnote things about third parties. -->

## Intro

<!--1 – Violence is bad.  Results from information/commitment problem.  Explain information/comm problem.-->

Groups fight for the resources -- land, wealth, power, or otherwise -- that fighting destroys.  As such, groups could almost always divide the resources before war in a way that benefits them more than their postwar settlement.  This is the enigma of violent conflict: why do groups engage in violent conflict when violent conflict often destroys the very thing the groups are fighting for?  The general answer is that groups suffer from a commitment problem: both sides are better off negotiating a peaceful agreement, but conflict occurs because neither group trusts the other to abide by negotiated agreements [@fearon1995rationalist; @powell2006war; @reed2016bargaining].  If groups trusted each other to abide by agreements, they would not need to fight and each group would enjoy superior outcomes relative to their outcomes after fighting.  

<!--2 – Comm/trust problems between groups usually solved by 3rd parties or reputations/repeated interactions. Explain how these things solve problem.  -->

One of the most common mechanisms for overcoming commitment problems and resolving group conflict is third-party enforcement of agreements.  Third party enforcement reduces commitment problems by incentivizing each side to honor agreements out of their own interest.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1994ethnic].  Third parties to enforce agreements can often effectively reduce conflict [@doyle2000international; @di2017effectiveness; @walter2002committing; @hartzell2001stabilizing; @gartner2011signs; @wallensteen2014talking], but they also suffer from limitations. First, third party intervention is costly.  The cost results in intervention only when the third party has an interest in one side winning the dispute or when conflict has already escalated into violence, so intervention is rarely used to reduce the persistent, smaller-scale violence that plague many countries [@greig2005stepping; @kydd2006can; @fey2010shuttle].  Second, third parties are relatively ineffective at ending ongoing conflicts compared to maintaining peace in a post-conflict setting [@gilligan2008interventions; @doyle2006making; @bratt1996assessing].  And third, third party punishment is exogenous to the conflicting groups and therefore does not create trust between those groups that will last beyond the third party's presence [@gambetta_ch13; @rohner2013war].  @weinstein2005autonomous estimated that 75% of civil wars resume within 10 years of UN intervention, and @beardsley2008agreement showed that international mediation reduces conflict in the short-term but not the long-term.

<!--3 – many ways, other than 3rd parties, to build trust between groups.  reputation/repeated interactions.-->

Commitment problems can be overcome and conflict resolved without relying on third party intervention.  Groups can build trust and resolve conflicts by cultivating reputations for trustworthiness in repeated interactions.  Repeated interactions between groups, like third parties, help overcome commitment problems by providing each group with the incentive to honor agreements out of their own interest.  Here the incentive comes not from fear of punishment but the prospect of better future outcomes from cooperation than defection.  Though each group may have an incentive to defect on an agreement today if the groups will not interact tomorrow, the groups have an incentive to cooperate now if their behavior today will be reciprocated by the other side in future interactions [@ostrom2003trust; @kydd2000trust; @axelrod1981evolution].[^reputation]  Both groups stand to gain more from enduring cooperation than enduring defection.

[^reputation]: I discuss repeated interactions and reputations together, but these mechanisms are subtly different.  The repeated interaction mechanism is generally mobilized for contexts with just two groups.  In those contexts, cooperation in previous interactions assists in obtaining cooperative behavior in the future from the same partner; other potential partners are unnecessary.  The reputation mechanism is generally mobilized for contexts in which many groups observe the behavior of many other groups.  In those contexts a good reputation assists in obtaining _other_ cooperative partners; repeated interactions with the same partner are unnecessary.  I discuss these mechanisms together because both rely on creating cooperative expectations from bargaining partners in future interactions.

<!--4 - general problems with rep/repeated interactions: don't want peace because psych costs; even if want peace, incentive to act tough to get best deal; even if want peace and not acting tough, biased perceptions of outgroup means each group is likely to misinterpret each other's cooperative signals.-->
Solving commitment problems through repeated interactions also faces limitations, however, especially for groups in or with a history of conflict.  Repeated interactions only solve commitment problems if both groups prefer peace (cooperation) to fighting (defection).  Though peace is in each group's material interest, preferences often deviate from material interest [@fehr2002social].  In the case of conflict, groups may not want peace because they derive psychological benefit from feelings of group superiority and from harm to a hated outgroup [@weisel2015ingroup; @cikara2014their; @tajfel2981groups; @fein1997prejudice] and when their animosity leads them to prefer relative gains over the outgroup to absolute gains for themselves [@waltz2010theory; @halevy2010relative; @turner1979social].  Even if groups desire peace, they maintain an incentive to act "tough" to get the best deal, and so may not signal their desire for peace [@ross1995psychological].  And even if groups signal their desire for peace, phenomena like confirmation bias, cognitive dissonance, and motivated reasoning can bias perceptions of outgroup behavior and prevent groups from accurately perceiving peaceful intentions [@de2008motivated; @ward1997naive; @duncan1976differential; @vallone1985hostileMedia; @festinger1962cognitiveDissonance; @kunda1990motivatedReasoning; @tajfel1969cognitive; @nickerson1998confirmation].  These non-material factors can prevent future interactions from solving groups' commitment problem.

<!--5 - Challenge not yet identified for building trust between groups: there is a within-group Collective action problem in addition to a between-group commitment problem.  Groups made of individuals.  What does it mean to trust a group?  It means trusting that sufficient number of group members will cooperate and that they can and will compel other group members who do not want to cooperate.  Sambanis: “peace can be derailed by a few radicals.” Beyond most members of a group signaling a commitment to peace, they must also signal a willingness and capacity to punish ingroup members who do not contribute to peace.  -->

An additional challenge with building trust between groups has not received much attention in the literature: each group faces a within-group collective action problem in addition to the between-group commitment problem.  The collective action problem occurs because each group is a collection of individual group members with their own behavioral incentives, not cohesive entities.  Peace benefits all members of a group, but contributing to peace is costly for group members because they must refrain from engaging in behaviors that benefit themselves at the expense of the outgroup.  Achieving peace, as with any public good, requires overcoming this collective action problem: the group must compel group members to contribute to peace despite the members' individual incentive to shirk and rely on others to bear its cost.  <!--What does it mean for a group to trust another group?-->One group trusting the other to honor an agreement, then, means not only trusting that a high proportion of outgroup members desire peace, but also that those outgroup members can and will compel less cooperative group members to honor a peace agreement [@fearon1996explaining].  Peace, after all, can be derailed by a few radicals [@sambanis2013social; @de2009effects].
<!--chris: do I need to say something about third party actors being unable to solve group's internal collective action problem? -->

<!--6 - Neither 3rd parties nor repeated interaction/reputation often sufficient to build trust between groups. -->
This is a bleak picture.  Often, neither the presence of third parties nor repeated interaction are sufficient to build trust between groups.  Third parties may be unwilling to intervene early enough to prevent violence, rarely intervene with enough force to stop ongoing conflict, and do not necessarily create the trust needed for long-term peace<!--, though they are effective at preventing a relapse into violence in the immediate aftermath of conflict-->.  Repeated interactions can create the trust needed for long-term peace, but getting cooperation started is difficult because of psychological costs to cooperation, incentives to increase bargaining power by acting uncooperative, and cognitive biases that prevent groups from receiving each other's cooperative signals.  And beyond signaling the intent of the group's majority to abide by peace agreements, groups must go further and signal their willingness and capacity to punish their own group members if a group member defects on the agreement.

<!--7 - Insights from psych on how to change attitudes and relieve biased perceptions.  Intergroup contact to achieve goal. Groups expect the other side to do what is in their interest; if each side recognizes that the other will cooperate out of self-interest, can trust other side to cooperate.

Contact gives groups a reason to get along.  Contact is Confidence-building measure, costly signal. chris: Need to incorporate.

the solution needs to (1) remove psych costs to peace and psych/social barriers to trusting other side, (2) signal that each group has solved its collective action problem and can compel radical group members to not take aggressive action against outgroup.
-->
Despite the bleakness, insights from psychology and political science provide means to overcome the issues that prevent groups from developing trust in repeated interactions.  When repeated interactions help groups cooperate they do so because each group sees that peaceful cooperation is in both their interests; repeated interactions fail to bring about peace when groups prefer fighting or when groups think the other side prefers fighting.  To help groups overcome their commitment problems through repeated interactions, an intervention must shift preferences towards peace and provide an opportunity for each group to observe this preference in the other.  Structured intergroup contact -- cross-group interactions in which groups cooperate to achieve shared goals -- can show groups that peace is in both their interests, remove the psychological barriers to each group identifying that the other wants peace, and provide opportunities for each group to send costly signals of their intent to cooperate and willingness to punish ingroup members who do not.  Achieving a joint goal demonstrates to each group that both their interests are best served through cooperation.  The prospect of benefit through cross-group cooperation motivates cooperation and attitude change [@grady2020lab; @rohner2013war] as well as the adoption of group norms to ensure cooperation, like punishment of ingroup members whose behavior undermines peace [@axelrod1986evolutionary; @fearon1996explaining].  Believing that the other side wants peace also creates the expectation that the other side will solve its collective action problem and police their own because it is in their interest to do so.

<!--8 - Mistakes happen; need to reduce chances for misinterpretation of other side's signals.  Joint-punishment apparatus. Not ingroup policing-->
Intergroup contact is a good first step to show groups that both benefit from cooperation and help groups send and receive signals of cooperation.  Even if contact reduces biases that cause misperceptions of these signals, however, misperceptions are still possible and can derail cooperative equilibria [@jervis2017misperception; @wu1995cope; @bendor1991doubt].  Members of one group may accidentally engage in action that harms the other or may perceive outgroup behavior as aggressive when it is not.  For long-term peace, institutions must minimize and manage these misperceptions.

One common mechanism for reducing group conflict is ingroup policing in which each side polices its own miscreants [@fearon1996explaining].  Ingroup policing is generally an excellent institution for preventing escalations of violence and for maintaining peace, but I suggest that mistrust between groups in or with a recent history of conflict may make ingroup policing unsustainable as a solution to prevent violence because of the potential for one group to devalue the costs imposed by the ingroup on their defector.  Groups in conflict reactively devalue costly behaviors done by the other side [@ward1997naive; @ross1995psychological; @maoz2002reactive; @millard2018testing] on the logic that "$X$ behavior must not be very costly, since they were willing to do it" (@kahneman1992reference calls a similar phenomenon "concession aversion").  This reactive devaluation causes problems for ingroup policing, since it can create the perception that any ingroup punishment was too lenient.  This can cause the outgroup to exact their own punishment, which may be viewed as too harsh, causing a spiral of violence.  Instead of ingroup policing, I propose that both groups should be involved in the punishment of group members who harm the other side.  The involvement of both groups minimizes the possibility that either side believes the punishment was too lenient or harsh.

<!--Roadmap paragraph -->
I begin by describing how non-material factors can lead to group conflict by preventing each group from trusting the other to cooperate even when it is in each group's material interest to cooperate.  Next I propose intergroup contact and joint-punishment institutions as a way that groups avoid falling into a spiral of violence.  I then apply this perspective to farmer-pastoralist conflict in Nigeria and describe the form that joint-punishment institutions have taken there, as well as consequences for conflict when no such institutions exist.  I conclude by describing implications for peacebuilding programs and considering avenues for empirical research.


********************

# Other

Trust not based on material outcomes would be a + psychological payoff to cooperation/trustworthy behavior.

2nd paragraph about 3rd parties
which deters third parties from intervening before disputes escalate into large-scale violence or unless the third party is biased in favor of one side

2nd paragraph about collective action
This formulation, while true, begs the question: what does it mean for one group to trust another group?  Each group is a collection of individual group members with their own behavioral incentives.  If all group members benefit from peace but contributing to peace is costly, then group members are best off if their group has peace without them contributing to it; peace is a public good and achieving peace requires overcoming a collective action problem.  Peace can be derailed by a few radicals [@sambanis2013social].  To trust a group to honor an agreement, then, is to trust that a sufficiently high proportion of group members want to contribute to peace and can compel other group members to contribute to the public good of peace.<!--To trust a group to honor a peace agreement, then, is to trust that a sufficiently high proportion of group members will honor the agreement.  -->

Why would any group member not honor the agreement when their group's outcome from peace is superior to the group's outcome from fighting?


3rd paragraph
The efficacy of a third party depends on its ability to monitor behavior, detect defection, assign blame, and punish the offender.  This process works well for homogeneous groups like armies, where responsibility for the behavior of any group member can be assigned to the group as a whole.  The same is not true for heterogeneous and decentralized groups, where the third party must observe the behavior of all groups members and cannot identify which group members defected on the agreement.


5th paragraph
psych costs to peace and benefits to conflict might make no agreements mutually acceptable to both sides (no bargaining range).

relative gains citations:  (Gilpin 1981, 1987; Gowa 1986; Grieco
 1988a, 1988b, 1990; Jervis 1988; Kennedy
 1987; Krasner 1987; Lake 1984; Larson  1988; 
Lipson 1984; Stein 1982; Waltz 1979)

Though peace is in each group's material interest, preferences often deviate from material interest [@fehr2002social].  In the case of conflict, groups may not want peace because of psychological costs to peace and benefits to fighting.  Group members are often willing to accept lower absolute gains to increase relative gain over the outgroup [@waltz2010theory; @halevy2010relative; @turner1979social; @festinger1954theory].  Group members may also receive psychological benefit from _harming_ the outgroup [@weisel2015ingroup; @cikara2014their], and a peace agreement prohibits group members from receiving those benefits.