---
title: "Promoting Peace Amidst Group Conflict: An Intergroup Contact Field Experiment in Nigeria - Introduction"
author: "Christopher Grady, Rebecca Wolfe, Danjuma Dawop, and Lisa Inks"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
    pandoc_args:
    - -M
    - secPrefix=\S
    template: ../utils/bowersarticletemplate.latex
  word_document: default
csl: ../utils/american-political-science-review.csl
bibliography: ../utils/cdg_references.bib
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="footnotesize",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132,
  out.width='.9\\textwidth',
  message=FALSE,
  comment=NA)

options(SweaveHooks=list(fig=function(){
			   par(mar=c(3.5, 3, 1.1, 0),
			       pty="s",
			       mgp=c(1.5,0.5,0),
			       oma=c(0,0,0,0))},
			 echo=function(){options(continue=" ") ##Don't show "+" prompts,
			 options(prompt=" ")
			 }),
	digits=4,
	scipen=8,
	width=132
	)
```

<!--
# Thinking

Option1 : zoom in  (current)
- nigeria example
- what accounts for difference?
- intergroup conflict as bargaining failure.




Option2: zoom out first
- intergroup conflict bad; no consistent way to prevent it.
- intergroup conflict as bargaining failure. 


**Intro**

Need to explain why I am doing things more than tell people details of what I am doing.  Only provide broad strokes for what I did.

Field experiment papers often take a couple paragraphs talking about the field experiment, but I don't want to.

*******
-->
## Introduction

<!--chris: New first paragraph about intergroup conflict generally.  ...maybe better to match the new abstract and talk about conflict being (in theory) preventable through bargaining, yet still very common.  And that psych stuff causes deviations from rationality.-->

Violent conflicts are one of most crucial phenomena for humans to overcome.  As of 2018, violent conflicts forcibly displaced over 70 million people from their homes [@unhcr2019], caused 2 million deaths since the year 2000 [@ucdp], threatened food supplies in numerous countries [@verwimp2012food], and extracted a psychological toll on participants and victims.  Despite extensive research, no means of consistently preventing violent conflict between groups is known.  

<!--## Relevant Literature
Intergroup conflict is a bargaining problem exacerbated by lack of intergroup trust.  Groups do not trust each other to honor comittments and worry that the other group is deceiving.   -->

To understand what causes some groups to engage in violent conflict while others maintain peaceful relations, we join many conflict scholars in conceptualizing group conflict as a bargaining failure [@fearon1995rationalist; @fearon1994ethnic; @powell2006war].  In the bargaining framework, both groups want some resource -- land, power, etc -- and must decide how to distribute that resource.  The groups can either bargain and split the resource or groups can fight to claim all of the resource.  Fighting is costly, so both groups are better off finding a bargained solution than fighting.  Though both groups materially benefit from a bargained peace, many peace negotiations fail.  The literature points to a lack of intergroup trust as the primary obstacle to peace: bargaining fails if neither group trusts the other side to be truthful or to honor bargained agreements [@rohner2013war; @kydd2000trust].  Without a reason to trust each other, groups are likely to fight despite the costs to both sides.

<!--chris: If writing old-style intro, would now recap ways to build trust: third party, reputation. -->

<!--How conflict exacerbates trust problems / thwarts intergroup trust.  (1) Low trust due to history of noncooperation & violence.  (2) Disagree about fairness of proposed deal == Disagree about current power / Disagree about which side transgressed and needs to make amends / Disagree about who is likely to hurt more from conflict today/become stronger tomorrow (p.24 of Ross_Ward_1995-NaiveRealism).  (3) internal evaluations and social evaluations == get psychological and social payoffs from beating other side, psychological and social costs from cooperation.  (4) Biased processing of outgroup behavior.  (5) over-generalizing of outgroup.

(A) Biased perceptions: (1) Low trust, (2) perceive fair deals to be unfair.  This is due to (4) perceive outgroup as more threatening/less trustworthy/more in need of making amends.  And due to (5) over-generalizing of outgroup.
(B) Internal Evaluations/non-material payoffs: (3) psychological benefits to beating other side/costs to cooperating with other side, (3) Social benefits to fighting other side / costs to cooperating with other side.  

CHRIS: "Internal Evaluations", "disagreement about fairness of a deal" do not inhibit trust, only biased perceptions of actions and over-generalizing inhibit trust.  Internal evals and disagree about deal fairness make bargaining more difficult but do not work through trust.-->

A number of psychological phenomena complicate trust-building between opposing groups.  First, these groups hold biased perceptions of their own behavior and the behavior of the other side [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Groups perceive their own belligerent actions as defensive and justified, and perceive the defensive actions of the other side as belligerent and gratuitous.  These perceptual biases create and reinforce outgroup mistrust and other negative stereotypes [@hewstone1990ultimate].  Second, groups in conflict derive psychological benefits from feelings of moral superiority over the outgroup [@tajfel1979integrative; @fein1997prejudice; @cikara2013their].  These feelings of moral superiority add costs to improving attitudes about the outgroup and to cooperating with the outgroup.  These two psychological phenomena sabotage intergroup bargaining by causing the groups to have inaccurate beliefs about each other and by limiting peace agreements acceptable to both sides.<!--chris: cite Gubler dissertation page 59, When Humanizing Fails, Self-Image Maintenance Motivation.  Cite Social Identity Theory, self-image maintenance motivation generally. Hogg 2001; Abrams and Hogg 1990. cikara 2013 "their pain" & other articles. -->

<!--Face to face interaction [@bohnet1999social]; overwrite stereotypes with personal interaction [@allport; pettigrew]; opportunities to send costly signals; material benefits of cooperation; form superordinate identity [@gaertner2014reducing]. effects diffuse through vicarious contact and norm changes [@paolini2004; yablon2012we; @crisp2009imagined].  chris: right now this paragraph is a bit too full. -->

Groups in conflict have few natural opportunities to build trust and many to degrade it.  We argue that cooperative intergroup contact provides opportunities to build intergroup trust and can improve the prospects for peaceful negotiation.  Directly, cooperative face-to-face contact provides groups the opportunity to send costly signals about their trustworthiness and preference for peace [@kydd2000trust; @lupia1998democratic; @rohner2013war; @bohnet1999social].  Indirectly, cooperative contact ameliorates the psychological biases that breed mistrust by reducing the anxiety felt from intergroup interaction [@lee2001mere; @page2008little], increasing empathy for members of the other group [@pettigrew2008does; @broockman2016durably], and providing information about the other group that replaces negative stereotypes [@allport1954prejudice; @pettigrew2008does].  Cooperative contact can also demonstrate to groups the material benefits of cooperation [@sherif1958superordinate; @gaertner2000reducing] and can form a superordinate identity that encompasses both groups [@gaertner2014reducing].  Cooperative contact for some group members can diffuse throughout the entire group through the process of indirect contact (knowledge of friendships between ingroup and outgroup members) and changes to social norms [@sen2007emergence; @paolini2004; @yablon2012we; @crisp2009imagined].

<!--Say what we did in context of farmer-pastoralist conflict.  Some context, some intervention design (contact, mediation), some evaluation.-->

To determine if cooperative contact improves intergroup attitudes, we conducted a field experiment with conflicting farmer and pastoralist communities in Nigeria.  More than an occupational difference, farmers who cultivate crops and pastoralists who graze cattle define a major social cleavage in many parts of the world.  These groups conflict over land rights, which define both of their livelihoods.  Farmer-pastoralist conflict has escalated througout the Sahel in recent years, and nowhere more than in Nigeria.  The most recent conflict escalation has caused 7,000 deaths in the past five years, displaced hundreds of thousands of people from their homes, and costs $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria]<!--don't need to cite news articles like this. you can give an address / identifier / link /etc in a footnote -->.

We randomly assigned communities with ongoing farmer-pastoralist violence to receive a contact-based peacebuilding intervention or serve as a control group.  The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.^[The communities built boreholes, market stalls, primary health care facilities, etc.]  The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.  To measure the effects of the intervention, we conducted pre- and post-intervention surveys, a post-intervention natural public goods behavioral game,[^PGG] and twelve months of systematic observations in markets and social events during the intervention.

[^PGG]: In a public goods game (PGG), research subjects are given money and told they can keep the money or donate it to a public fund.  Money donated to the public fund is multiplied by some amount and then shared with all subjects.  Our PGG is _natural_ because it was conducted in a natural setting, rather than a lab.  The funding for the PGG came from the National Science Foundation under Grant No. 1656871.

<!--Say what we found.  It seems primarily through intergroup contact.  -->

We find that the program increased intergroup trust, intergroup contact, and perceptions of physical security.  We see signs of the positive effects in fieldwork as well as in data -- in one of the treatment sites, farmers defended pastoralists from a group of anti-pastoralist vigilantes, rather than assist the vigilantes in removing the pastoralists and claiming their land.  Our results also show that the intervention affected communities as a whole, not just community members directly involved in the intergroup contact.  Individuals who directly engaged in intergroup contact changed the most positively from baseline to endline, but we also observe positive spillovers of trust to group members for whom we did not exogenously increase intergroup contact.

<!--Say implications for: (1) conflict resolution, especially intergroup and intercommunal violence.  On the rise, Fulani being massacred in Mali (Economist March 30, 2019).  <!--(4) peacebuilding programs and CDD, -->

This study expands our knowledge about intergroup conflict in several ways.  First, this study teaches us about the capacity of intergroup contact to improve intergroup relations and reduce conflict.  Peacebuilding organizations implement numerous contact-based interventions in violent contexts each year [@ditlmann2017addressing], but its efficacy to improve intergroup attitudes amid real-world conflict is an open question [@paluck2017contact; @ditlmann2017addressing].  To our knowledge this is the first field experimental test of a contact-based intervention implemented during an active conflict.  Each of the groups in our study were part of an active conflict, with members of each side being killed within one year of the intervention's onset.  We evaluated the program's effects on both attitudinal and behavioral outcomes.  The results suggest that contact-based peacebuilding programs can effectively improve relationships between conflicting groups and is especially relevant to conflict resolution in the cases of intergroup and intercommunal conflicts.

<!--(3) social institutions constraining behavior, intergroup bargaining. Should I also add (5) spillover of effects and social norms/vicarious learning?  Literature about informal structures solving collective action problems.  Some places have formal institutions, some places have do not.  Those places develop informal structures.  This program showed how informal structures can develop through repeated intergroup interaction.-->

Second, we contribute to the literature about informal structures, such as social norms, in solving collective action problems.  In some contexts, formal institutions ensure collective action by punishing groups and individuals who "defect" on agreements.  In many contexts, such as rural Nigeria, no formal institutions exist to encourage such behavior and so groups in those contexts develop informal structures to achieve collective action [@ostrom2000collective].  This peacebuilding intervention showed how informal structures governing interactions between groups can develop through repeated intergroup interaction.  Creating informal structures that diffuse the effects of contact are a way of scaling up peacebuilding interventions.

<!--Fulani getting cleansed -->

Third, this paper teaches us about settling disputes between sedentary peoples and nomadic peoples.  Violent conflict between settled peoples and nomadic peoples is on the rise throughout Africa [@hrc2018farmer; @kuusaana2015land; @mwamfupe2015persistence].  This study focuses on the Fulani, the largest semi-nomadic people on Earth [@fulanisize2017].  Their way of life makes them targets for violence throughout Africa.  Along with this conflict in Nigeria, Fulani in Mali have been the targets of violence so severe that researchers at Armed Conflict Location & Event Data Project called it "ethnic cleansing" [@economist2019militias].  Understanding how to prevent violent conflict between Fulani and settled peoples can help prevent violence that targets other nomadic and semi-nomadic peoples, such as the Tuaregs in West Africa, Uyghurs in Central Asia, Kochi in Afghanistan, and Khoisan of Southern Africa.  Preventing such violence could help preserve a dying way of life.

<!--Fourth, this paper teaches us about bottom-up interventions to encourage peace between groups.  Most interventions use top-down approach.  Bottom-up approach can support top-down or be effective on its own. chris: do I even want to include this? -->

<!--Roadmap.-->

In the next section we provide a theoretical framework for how and why opposing groups struggle to solve their disagreements through bargaining and negotiation, and argue that cooperative contact can help these groups resolve disagreements by improving intergroup trust.  We then discuss Nigeria's farmer-pastoralist conflict, our experimental intervention, and two designs to evaluate the effect of the intervention.  Last we present the results of the study and conclude by discussing their implications for intergroup contact and group conflict. 

<!--chris: I want to add something about how incorporating psychological theories of human behavior into rationalist frameworks of phenomena like conflict provides a better understanding of human behavior. -->

<!--
## Old

## Motivating Example: Story about burnt down village/bad outcomes, then story about village defending pastoralists.

In Nigeria's Middlebelt, intergroup conflict between sedentary farmers and semi-nomadic pastoralists is causing dire consequences: 7,000 deaths in the past five years, 300,000 internally displaces peoples from their homes in 2018, and $13 billion of lost economic productivity annually [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria].  Since the most recent conflict escalation began in 2014, groups of anti-pastoralist vigilantes have mobilized to prevent pastoralists from encroaching on land claimed by farmers [@duru2018court; @mcdonnel2017graze].  These groups, dubbed the "livestock guard", ransack pastoralist settlements and violently drive pastoralists from their homes, often with the assistance of the local farming community.  Likewise, pastoralist groups enact vigilante justice, raiding and burning down farming villages seen to encroach on land claimed by pastoralists.

Though farmer-pastoralist conflict is widespread, mass violence between these groups has not broken out in all Middlebelt communities, and some farmers and pastoralists even defend each other.  When a group of livestock guard came for one pastoralist settlement, the neighboring farming village arrested them to protect the pastoralists.  After the arrest, farmers and pastoralists convened to decide what should be done with the prisoners.  They agreed that the group of livestock guard should not be punished, but should be disarmed and released home -- a proposition proposed by _the pastoralists_.  These same farmers and pastoralists had struggled with conflict, and people on both sides had died in past violence over farmland and grazing land.  But their recent disagreements had not escalated to the point that each side wanted the other removed by any means necessary.  The groups had created structures and relationships that allowed them to settle disputes, and the same structures and relationships allowed them to reach a solution about the livestock guard.

Why were some farmer and pastoralist groups able to keep peace whereas others were consumed by the escalating conflict?  Why were some communities able to overcome their disagreements whereas others were destroyed by them?  

 -->

****************


<!--
## Quotes From Articles

"The problem is bigger than mandates and resources. Above all, it has to do with two strategic choices the UN frequently makes: first, to work with national elites to stop violence from the top down and, second, to push for quick elections as a way to consolidate the peace. The standard UN approach to ending wars is to host large, costly conferences in order to strike agreements between governments and rebel leaders and then organize a national vote and declare victory. Both tendencies are based on faulty assumptions."

The weakness of the top-down approach is that warfare is often the result of not just national or international competition but local competition, too. In many conflict zones, the fight is over such issues as land, water, livestock, and low-level traditional and administrative power.

**Consider the island of Idjwi, in Lake Kivu in eastern Congo. Since war broke out in Congo in 1996, a conflict that has killed anywhere from two million to five million people, Idjwi has avoided the brunt of the violence, even as other islands in nearby lakes have not. Idjwi has all the same factors that have fueled fighting around it: a geostrategic location, mineral resources, ethnic tensions, a lack of state authority, extreme poverty, disputes over land and traditional power. But the island’s residents, including the poorest and least powerful, have set up various grass-roots organizations—religious networks, women’s associations, youth groups, and so on—to help resolve disputes. They also draw on strong traditional beliefs—for example, forming blood pacts through which different families promise never to hurt one another. They have worked to foster what they call a “culture of peace.”**

The UN currently views such bottom-up peace-building efforts as a sideshow. Instead, it should see them as an essential complement to its current top-down efforts to stop fighting.

"bottom-up strategies that [let] the people themselves determine how best to promote peace."

[@autesserre2017international]

"international enforcement can help solve commitment and cooperation problems by imposing order or by directly implement- ing peace agreements or raising the costs of defection from them. Long-term trusteeship may be required to overcome deep distrust and powerful incentives to defect from the peace. As in prisoner's dilemma and mixed motive games (Axelrod and Keohane 1985; Oye 1985), deep hostility, multiple factions, or lack of coherent leadership may complicate the achievement of self-enforcing cooperation. Conscious direction by an impartial agent to guarantee the functions of effec- tive sovereignty become necessary, [@doyle2000international]


@kydd2000trust: opportunity for costly signaling allows groups to build trust and cooperate.  @ostrom2000collective, @Axelrod: conditional cooperators. Need to forgive.

@ostrom2000collective: "if there is a noisy signal about a player’s type that is at least more accurate than random, trustworthy types will survive as a substantial proportion of the population. Noisy signals may result from seeing one another, face-to-face communication, and various mechanisms that humans have designed to monitor each other’s behavior"
"evidence has accumulated that externally imposed rules tend to “crowd out” endogenous cooperative behavior (Frey, 1994)"
"These studies typically find that **a social norm**, especially in a setting where there is communication
between the parties, can work as well or nearly as well at generating cooperative
behavior as an externally imposed set of rules and system of monitoring and
sanctioning." @rohner2013war also says that coercive peace policies do not have enduring effects. @beardsley2008agreement says peacekeeping only works short-term.
@rohner2013war: lack of trust causes civil conflict.  Intergroup trust increases intergroup trade, which increases costs of conflict.


UN peacekeeping not successful at ending _ongoing_ conflicts, but are successful at post-conflict stuff. [@gilligan2008interventions; @doyle2006making]. @bratt1996assessing also questions effectiveness at conflict resolution.  @beardsley2008agreement shows mediation works short-term but not long-term.

@di2017effectiveness good summary of peacekeeping stuff.

@grieg2008they about mediation.
@regan2002third questions effectiveness of international intervention overall.

Studies have not, however, shown how intergroup bargaining is made more difficult by the cognitive and motivational biases of two opposing groups; nor has it shown how those groups can overcome their biases to reduce conflict. 
-->

# References