---
title: "Promoting Peace Amidst Group Conflict: An Intergroup Contact Field Experiment in Nigeria"
author: "Christopher Grady, Rebecca Wolfe, Danjuma Dawop, and Lisa Inks"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  word_document: default
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
    pandoc_args:
    - -M
    - secPrefix=\S
    template: ../../../utils/bowersarticletemplate.latex
csl: ../../../utils/american-political-science-review.csl
bibliography: ../../../utils/cdg_references.bib
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="footnotesize",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132,
  out.width='.9\\textwidth',
  message=FALSE,
  comment=NA)

options(SweaveHooks=list(fig=function(){
			   par(mar=c(3.5, 3, 1.1, 0),
			       pty="s",
			       mgp=c(1.5,0.5,0),
			       oma=c(0,0,0,0))},
			 echo=function(){options(continue=" ") ##Don't show "+" prompts,
			 options(prompt=" ")
			 }),
	digits=4,
	scipen=8,
	width=132
	)
```


\begin{abstract}

Group conflict should be avoidable through intergroup bargaining, yet group conflict is commonplace throughout the world.  We argue that psychological phenomena account for many bargaining failures by inducing barriers to bargaining through two main processes.  First, psychological phenomena prevent groups from developing intergroup trust by biasing interpretations of the behavior of the other side.  Second, psychological phenomena add costs to compromise because group members derive self-esteem from feelings of group superiority.  Interventions that abate these psychological barriers to bargaining should allow the groups to avoid violent conflict.  We test the ability of a contact-based intervention to promote peace between conflicting groups with a field experiment in Nigeria, where farmer and pastoralist communities are embroiled in a deadly conflict over land use.  We evaluate the program with surveys, behavioral observation, and a behavioral game.  We find that the program increases intergroup contact, intergroup trust, and perceptions of physical security of group members.  These results suggest that reducing barriers to bargaining between conflicting groups is possible, and that structured intergroup contact is a promising method to do so.


\end{abstract}


# Introduction

Group conflict is responsible for many of the worst displays of human nature.  It claims lives, threatens food supplies, creates refugees, and extracts a psychological toll on participants and victims.  Despite extensive research, no consistent means of preventing group conflict is known.  To understand why some groups engage in violent conflict and others maintain peaceful relations, we use the framework of group conflict as a bargaining failure, which highlights trust problems as the primary obstacle to peace between groups [@fearon1995rationalist; @rohner2013war; @kydd2000trust].  Groups in conflict have few opportunities to build trust and many to degrade it.  We argue that providing opportunities for trust-building through cooperative intergroup contact improves the prospects for peace.  Intergroup trust ameliorates bargaining problems and increases the likelihood of the groups resolving disputes through bargaining instead of violence.<!--previous sentence really on chopping block. -->

<!--## Relevant Literature
Intergroup conflict is a bargaining problem exacerbated by lack of intergroup trust.  Groups do not trust each other to honor commitments and worry that the other group is deceiving.   -->

Treating intergroup conflict as a bargaining failure is common in conflict studies [@fearon1994ethnic; @powell2006war].  Both groups want some resource -- land, power, etc -- and must decide how to distribute that resource.  Groups can either bargain and split the resource, or groups can fight to claim all of the resource or to increase their later bargaining position.  Fighting is costly, so both groups are better off finding a bargained solution than fighting.  However, bargaining fails if neither group trusts the other side to be truthful or to honor bargained agreements [@rohner2013war; @kydd2000trust].  Without a reason to trust each other, groups are likely to fight despite the costs to both sides.

<!--How conflict exacerbates trust problems / thwarts intergroup trust.  (1) Low trust due to history of noncooperation & violence.  (2) Disagree about fairness of proposed deal == Disagree about current power / Disagree about which side transgressed and needs to make amends / Disagree about who is likely to hurt more from conflict today/become stronger tomorrow (p.24 of Ross_Ward_1995-NaiveRealism).  (3) internal evaluations and social evaluations == get psychological and social payoffs from beating other side, psychological and social costs from cooperation.  (4) Biased processing of outgroup behavior.  (5) over-generalizing of outgroup.

(A) Biased perceptions: (1) Low trust, (2) perceive fair deals to be unfair.  This is due to (4) perceive outgroup as more threatening/less trustworthy/more in need of making amends.  And due to (5) over-generalizing of outgroup.
(B) Internal Evaluations/non-material payoffs: (3) psychological benefits to beating other side/costs to cooperating with other side, (3) Social benefits to fighting other side / costs to cooperating with other side.  

CHRIS: "Internal Evaluations", "disagreement about fairness of a deal" do not inhibit trust, only biased perceptions of actions and over-generalizing inhibit trust.  Internal evals and disagree about deal fairness make bargaining more difficult but do not work through trust.-->

A number of psychological phenomena complicate bargaining amidst conflict.  First, conflicting groups hold biased perceptions of their own behavior and the behavior of the other side [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Groups perceive their own belligerent actions as defensive and justified, and perceive the defensive actions of the other side as belligerent and gratuitous.  These perceptual biases create and reinforce negative outgroup stereotypes [@hewstone1990ultimate].  Second, groups in conflict derive psychological benefits from feelings of moral superiority over the outgroup [@tajfel1979integrative; @fein1997prejudice].  These feelings of moral superiority add costs to improving attitudes about the outgroup and to cooperating with the outgroup.  Together these two psychological phenomena sabotage intergroup bargaining by causing the groups to have inaccurate beliefs about each other and by limiting peace agreements acceptable to both sides.<!--chris: cite Gubler dissertation page 59, When Humanizing Fails, Self-Image Maintenance Motivation.  Cite Social Identity Theory, self-image maintenance motivation generally. Hogg 2001; Abrams and Hogg 1990. cikara 2013 "their pain" & other articles. -->

Many peacebuilding organizations utilize peacebuilding approaches focused on improving intergroup attitudes.  One such approach, intergroup contact theory, hypothesizes that interactions in which group members cooperate to achieve shared goals will improve intergroup attitudes.  Cooperative contact provides positive personal experience with the outgroup, and those experiences reshape outgroup attitudes [@allport1954prejudice; @pettigrew2008does].  This type of structured face-to-face contact also provides groups the opportunity to send costly signals about their trustworthiness and preference for peace [@kydd2000trust; @lupia1998democratic; @rohner2013war].<!--@bohnet1999social increases trust to see other player -->  Intergroup contact is especially good at reducing intergroup conflict when groups cooperate to achieve superordinate goals -- goals that require the cooperation of both groups and benefit both groups -- because groups experience the material benefits of cooperation [@sherif1958superordinate; @gaertner2000reducing].

Although research shows support for intergroup contact theory generally [@pettigrew2006meta], its efficacy to improve intergroup attitudes amid real-world conflict is an open question [@ditlmann2017addressing].  Negative experiences with outgroups worsen intergroup relations, and individuals with the most negative attitudes are most likely to interpret intergroup contact negatively [@paolini2010negative; @gubler2013humanizing; @barlow2012contact].  Its impact on interracial and interethnic attitudes has also been challenged by recent reviews [@paluck2017contact].  Despite a lack of evidence about the effects of contact-based peacebuilding programs in violent contexts, and the risks of programs going badly, peacebuilding organizations implement numerous contact-based interventions in violent contexts each year [@ditlmann2017addressing].  These peacebuilding programs may or may not defuse intergroup conflict.

<!--Say what we did in context of farmer-pastoralist conflict.  Some context, some intervention design (contact, mediation), some evaluation.-->

To determine if contact-based peacebuilding interventions improve intergroup attitudes, we conducted a field experiment with conflicting farmer and pastoralist communities in Nigeria.  More than an occupational difference, farmers who cultivate crops and pastoralists who graze cattle define a major social cleavage in many parts of the world.  These groups conflict over land rights, which define both of their livelihoods.  Farmer-pastoralist conflict has escalated throughout the Sahel in recent years, and nowhere more than in Nigeria.  The most recent conflict escalation has caused 7,000 deaths in the past five years, displaced hundreds of thousands of people from their homes, and costs $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria]<!--don't need to cite news articles like this. you can give an address / identifier / link /etc in a footnote -->.

We randomly assigned communities with ongoing farmer-pastoralist violence to receive a contact-based peacebuilding intervention or serve as a control group.  The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.^[The communities built boreholes, market stalls, primary health care facilities, etc.]  The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.  To measure the effects of the intervention, we conducted pre- and post-intervention surveys, a post-intervention natural public goods behavioral game,[^PGG] and twelve months of systematic observations in markets and social events during the intervention.

[^PGG]: In a public goods game (PGG), research subjects are given money and told they can keep the money or donate it to a public fund.  Money donated to the public fund is multiplied by some amount and then shared with all subjects.  Our PGG is _natural_ because it was conducted in a natural setting, rather than a lab.  The funding for the PGG came from the National Science Foundation under Grant No. 1656871.

<!--Say what we found.  It seems primarily through intergroup contact.  -->

We find that the program increased intergroup trust, intergroup contact, and perceptions of physical security.  We see signs of the positive effects in fieldwork as well as in data -- in one of the treatment sites, farmers defended pastoralists from a group of anti-pastoralist vigilantes, rather than assist the vigilantes in removing the pastoralists and claiming their land.  Our results also show that the intervention affected communities as a whole, not just community members directly involved in the intergroup contact.  Individuals who directly engaged in intergroup contact changed the most positively from baseline to endline, but we also observe positive spillovers of trust to group members for whom we did not exogenously increase intergroup contact.

<!--Say implications for: (1) conflict resolution, especially intergroup and intercommunal violence.  On the rise, Fulani being massacred in Mali (Economist March 30, 2019).  <!--(4) peacebuilding programs and CDD, -->

This study expands our knowledge about intergroup conflict in several ways.  First, this study teaches us about the capacity of contact-based peacebuilding programs to improve intergroup relations.  To our knowledge this is the first field experimental test of a contact-based peacebuilding program implemented during an active conflict.  Each of the groups in our study were part of an active and escalating conflict, with members of each side being killed within one year of the intervention's onset.  We evaluated the program's effects on both attitudinal and behavioral outcomes.  The results suggest that contact-based peacebuilding programs can effectively improve relationships between conflicting groups and is especially relevant to conflict resolution in the cases of intergroup and intercommunal conflicts.

<!--(3) social institutions constraining behavior, intergroup bargaining. Should I also add (5) spillover of effects and social norms/vicarious learning?  Literature about informal structures solving collective action problems.  Some places have formal institutions, some places have do not.  Those places develop informal structures.  This program showed how informal structures can develop through repeated intergroup interaction.-->

Second, we contribute to the literature about informal structures, such as social norms, in solving collective action problems.  In some contexts, formal institutions ensure collective action by punishing groups and individuals who "defect" on agreements.  In many contexts, such as rural Nigeria, no formal institutions exist to encourage such behavior and so groups in those contexts develop informal structures to achieve collective action [@ostrom2000collective].  This peacebuilding intervention showed how those informal structures can develop through repeated intergroup interaction.  Creating informal structures that diffuse the effects of contact are a way of scaling up peacebuilding interventions.

<!--Fulani getting cleansed -->

Third, this paper teaches us about settling disputes between sedentary peoples and nomadic peoples.  Violent conflict between settled peoples and nomadic peoples is on the rise throughout Africa [@hrc2018farmer; @kuusaana2015land; @mwamfupe2015persistence].  This study focuses on the Fulani, the largest semi-nomadic people on Earth [@fulanisize2017].  Their way of life makes them targets for violence throughout Africa.  Along with this conflict in Nigeria, Fulani in Mali have been the targets of violence so severe that researchers at Armed Conflict Location & Event Data Project called it "ethnic cleansing" [@economist2019militias].  Understanding how to prevent violent conflict between Fulani and settled peoples can help prevent violence that targets other nomadic and semi-nomadic peoples, such as the Tuaregs in West Africa, Uyghurs in Central Asia, Kochi in Afghanistan, and Khoisan of Southern Africa.  Preventing such violence could help preserve a dying way of life.

<!--Fourth, this paper teaches us about bottom-up interventions to encourage peace between groups.  Most interventions use top-down approach.  Bottom-up approach can support top-down or be effective on its own. chris: do I even want to include this? -->

<!--Roadmap.-->

In the next section we provide a theoretical framework for how and why opposing groups struggle to solve their disagreements through bargaining and negotiation, and elucidate how contact-based peacebuilding interventions help these groups resolve disagreements by improving intergroup trust.  We then discuss Nigeria's farmer-pastoralist conflict, our experimental intervention, and two designs to evaluate the effect of the intervention.  Last we present the results of the study and conclude by connecting these findings to psychological and economic theories of group conflict.

# Theory

## Intergroup Conflict as a Bargaining Problem
<!--Typical solutions strive to solve intergroup bargaining problem.  Information and commitment problems.  Define these problems.  Bigger versions of "Intergroup conflict is often conceptualized as a bargaining problem" and "How can groups in conflict escape this spiral of distrust and conflict?" paragraphs from intro.-->

Intergroup conflict is most often conceptualized as a bargaining problem [@fearon1994ethnic; @powell2006war], and most solutions to reducing intergroup conflict strive to help the groups overcome barriers to bargaining [@di2017effectiveness] <!--chris: this cite is just for peacekeeping/intervention-->.  Intergroup conflict is a bargaining problem because both groups want some resource -- land, power, etc -- but cannot reach an agreement about how to distribute that resource peacefully.  Because fighting is costly, the groups are better off reaching a bargained compromise than fighting.  However, two problems prevent successful bargaining: information problems and commitment problems [@fearon1995rationalist].  Groups are less likely to successfully bargain without (1) accurate information about each other's strengths and preferences, and/or (2) assurance that each side will abide by its agreements.  

An _information problem_ arises when neither group possesses accurate information about the other.  This problem can occur for many reasons, but often surfaces because independent and accurate information is unavailable and because groups have an incentive to portray themselves as stronger, more willing to fight, and less willing to make concessions than they truly are in order to achieve an advantageous bargaining outcome [@fearon1995rationalist]. An information problem causes bargaining failures because neither group knows what agreements the other side is willing to accept or what their side should receive from bargaining.  

A _commitment problem_ arises when neither group can credibly commit to honor bargained agreements.  This problem can also occur for many reasons, but often surfaces due to the potential for bargaining power to shift after an agreement.  If bargaining power shifts after an agreement, one side will have an incentive to renege on that agreement to achieve a better outcome.  A commitment problem causes bargaining failures because neither group will commit to agreements today that they believe will be broken tomorrow.^[The canonical example of a commitment problem is the prisoners' dilemma: why stay silent if you expect your partner to rat you out?[chris: should I remove this prisoners' dilemma sentence, footnote PD, or ignore PD?]]<!--each group has an incentive to defect from the agreement if the other side complies. -->

Groups in conflict overcome information and commitment problems in two main ways.  The first way is through third-parties.  Third parties can solve information problems by mediating disputes, providing accurate information to both sides [@kydd2006can].  Third parties can also solve commitment problems by intervening to punish defection from agreements.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1995rationalist].

The second way groups solve information and commitment problems is through forming trustworthy reputations and the possibility of future interactions [@kydd2000trust].  Reputations and future interactions can solve information and commitment problems because dishonesty and defection damage a group's reputation, worsening that group's prospects for future bargaining.  Groups with reputations for cooperation are likely to elicit cooperation in future interactions; groups with reputations for defection are likely to elicit defection in future interactions [@ostrom2003trust; @kydd2000trust; @axelrod1981evolution].  Though each group may improve its current outcome by defecting on the current agreement, the groups have less incentive to defect if defection will worsen future bargaining outcomes.  These mechanisms apply to future interactions between the same two groups and to future interactions with other potential bargaining partners.[^reputation]
<!--chris: not talking about information problems at all, really...maybe ask ekrem? -->
<!--Look-back reputation to know player types, and groups having concern for their reputations in future.  Reputations solve information and commitment problems by giving groups an incentive for trustworthy behavior [chris: duh, that is how everything works, even third-parties].  Cultivating a reputation as a trustworthy partner in past interactions gives a bargaining partner confidence that you are trustworthy in the present interaction; cultivating a reputation as an untrustworthy partner does the opposite. Groups concerned with future bargaining are less likely to defect on present agreements because defecting in the present compromises that group's ability to bargain in the future.  Because they do not rely on formal enforcement mechanisms, reputations for trustworthiness improve the prospects for bargaining even in the absence of third parties [@ostrom2003trust].  Groups with poor reputations are also unlikely to attract trustworthy bargaining partners. -->  

[^reputation]: We discuss repeated interactions and reputations together, but these mechanisms are subtly different.  The repeated interaction mechanism is generally mobilized for contexts with just two groups.  In those contexts, cooperation in previous interactions assists in obtaining cooperative behavior in the future from the same partner; other potential partners are unnecessary.  The reputation mechanism is generally mobilized for contexts in which many groups observe the behavior of many other groups.  In those contexts a good reputation assists in obtaining _other_ cooperative partners; repeated interactions with the same partner are unnecessary.  We discuss these mechanisms together because both rely on creating cooperative expectations from bargaining partners in future interactions.

<!--chris: Could move 3rd party discussion here, could move one paragraph about reputations not working well here because groups hate each other.  Then "the following section describes the ways that psychological phenomena prevent peaceful resolution to conflict." -->

## The Persistence of Intergroup Conflict

<!--
First, conflicting groups hold biased perceptions of their own behavior and the behavior of the other side [@ward1997naive].  Groups perceive their own belligerent actions as defensive and justified, and perceive the defensive actions of the other side as belligerent and gratuitous.  These perceptual biases create and reinforce negative outgroup stereotypes [@hewstone1990ultimate].  Second, groups in conflict derive psychological benefits from feelings of moral superiority over the outgroup.  These feelings of moral superiority add costs to improving attitudes about the outgroup and to cooperating with the outgroup.  Together these two psychological mechanisms sabotage intergroup bargaining by causing the groups to have inaccurate beliefs about each other and limiting peace agreements acceptable to both sides.-->

If scholars and practitioners know how to solve the information and commitment problems that cause intergroup conflict, why does conflict persist?  First, it is not possible for third parties to mediate or intervene into every conflict.  Sometimes no third party is willing or able to become involved [@fey2010shuttle, p.530], and sometimes the conflict is too decentralized for a third party to effectively mediate or intervene.  This situation is common for internal conflicts in weak states, where conflicts are diffuse and the state lacks the capacity to mediate or intervene into the conflict.  Second, third party mediation and intervention are not effective in all contexts [@beardsley2008agreement; @beber2012international; @weinstein2005autonomous; @autesserre2017international].

<!--chris: Could merge previous two paragraphs with last section and begin this section as "psychological barriers to peace".  Any attempt at bargaining is likely to be short-circuited by psychological phenomena. -->

<!--Bias perceptions section.
<!--chris:"First, conflicting groups hold biased perceptions of their own behavior and the behavior of the other side [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Groups perceive their own belligerent actions as defensive and justified, and perceive the defensive actions of the other side as belligerent and gratuitous.  These perceptual biases create and reinforce negative outgroup stereotypes [@hewstone1990ultimate]." 
cite Gubler dissertation page 59, When Humanizing Fails, Self-Image Maintenance Motivation.  Cite Social Identity Theory, self-image maintenance motivation generally. Hogg 2001; Abrams and Hogg 1990. Klein and Kunda, brewer1991/1999. -->

Where third parties cannot effectively intervene, conflicting groups could negotiate based on reputation, but reputations are more likely to hinder than to help the bargaining of groups in conflict.  Psychological phenomena introduce significant friction in the ability of groups to build trusting reputations.  Group members interpret the defensive action by outgroup members as belligerent and threatening, while they see their own belligerent actions as defensive and justified [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Even positive actions by outgroup members may be re-interpreted as negative to avoid cognitive dissonance [@gubler2013humanizing; @paolini2010negative].  Group members then attribute those negative outgroup behaviors to internal characteristics that define all outgroup members [@hewstone1990ultimate].  At the same time, they under-generalize positive behaviors as exceptional to the outgroup and selectively remember events that corroborate their pre-existing negative perceptions [@de2008motivated].  These tendencies lead group members to ascribe negative traits, like immorality and untrustworthiness, to outgroups [@tajfel1981groups; @brewer1999ingroupOutgroup; @levine1972ethnocentrism; @eidelson2003dangerous].

Biased perceptions of outgroup members prevent conflicting groups from developing positive reputations, even when both groups are motivated to end the conflict.  The primary way that groups reassure each other of cooperative intentions is through costly signals, but groups in conflict may interpret these costly signals inaccurately and fail to update their perception of the other side's willingness to cooperate [@kydd2000trust; @rohner2013war].  Groups also reactively devalue any compromise the outgroup is willing to concede, lowering the perceived costliness of any cooperative signal [@ward1997naive; @ross1991barriers].  The inability to cultivate positive reputations through costly signals prevents groups from forming the trusting relationships needed to solve commitment problems.  These biases also exacerbate information problems by preventing accurate perceptions of the preferences of the outgroup and by distorting perceptions of which group is in the wrong and should make concessions [@ward1997naive].  These perceptions, once arisen, are very difficult to correct [@nyhan2010corrections; @kunda1990motivatedReasoning].<!--@klein1992motivated might be a better cite, actually -->

Compounding these perceptual problems, reputations for trustworthiness are hampered by a lack of opportunities to learn about the other side from observing their interactions with other groups.  Even if opportunities are available, few of the outgroup's interactions will be with groups that are relevant for predicting the outgroup's behavior towards the ingroup, reducing the usefulness of observational learning [@kazdin1974covertModeling; @yang2013similarity]. The main opportunity to observe outgroup behavior and learn their reputation is the ingroup's own interactions with the outgroup.  For groups in conflict, these opportunities are likely rare and almost always adversarial.

<!--Internal Evaluations section.

"Second, these psychological phenomena increase the costs of cooperation and the benefits of defection.  These costs and benefits limit the number of bargained agreements that each side prefers to fighting."  "They also prevent peaceful resolution of conflict by increasing the costs of cooperation and benefits of defection."

each side is unwilling to accept reasonable bargains because benefits/costs of cooperation.  Even if things set in your favor, with information/commit problems, groups cannot reach a bargain because there is no agreement that both groups will accept.

B) Internal Evaluations/non-material payoffs: (3) psychological benefits to beating other side/costs to cooperating with other side, (3) Social benefits to fighting other side / costs to cooperating with other side. Individuals and leaders (domestic audience costs)

Ekrem: #2 is about psychological modification of payoffs (which increases mistrust, because we now like defecting more and cooperating less).
1) Via social/psychological mechanisms which increase costs of cooperation and benefits of defection (1a personal, 1b social, 1c constraining leaders)
-->

If groups overcome their biased perceptions of the other side and solve information and commitment problems, psychological phenomena provide further barriers to the peaceful resolution of conflict.  From a purely material standpoint, groups should prefer peace to conflict because they expect conflict to be more costly than peace.  However, when forming preferences for conflict or peace, groups also weigh psychological and social factors.  For groups in conflict, these psychological and social factors add costs to cooperation and benefits to conflict.  Factoring in these costs and benefits, groups may be prevented from reaching a bargain because there is no bargain that both groups will accept.

<!--Organized as (1) Individual psychological costs/bene then (2) individual social costs/bene.  Could organize as (1) costs both psych and social, (2) benefits bot psych and social.  Costs to self-esteem.  Benefit from harming other side/opportunity cost of losing those potential benefits.  Perceived deservingness.-->

<!--chris: old paragraph.  Individual group members derive self-esteem benefits from positively comparing their group to a rival group [@tajfel1981groups; @brewer1999ingroupOutgroup; @wood2000attitude; @tajfel1979integrative; @fein1997prejudice].  Members of both groups maintain their group-based self-esteem only from a bargain that benefits their group at the expense of the other; a compromise that acknowledges both groups as equals challenges the positive comparison that provides self-esteem.  As a result, group members may reject bargains that are fair from a material standpoint, as well as leaders who cooperate or compromise with the outgroup [@fearon1994domestic].  Group members prefer to maximize their position relative to the other side rather than maximize their absolute position [@turner1979social], and may even receive psychological benefit from _harming_ the outgroup [@weisel2015ingroup; @cikara2014their].-->

Group members suffer psychological costs from bargains that do not favor their group at the expense of the outgroup.  Group members derive self-esteem from positively comparing their group to a rival group, and any agreement that acknowledges both groups as equals challenges that group-based boost to self-esteem [@tajfel1981groups; @wood2000attitude; @tajfel1979integrative; @fein1997prejudice; @brewer1999ingroupOutgroup].  As a result, group members are willing to accept lower absolute gains to increase relative gain over the outgroup [@turner1979social].  Group members may also receive psychological benefit from _harming_ the outgroup [@weisel2015ingroup; @cikara2014their], and a peace agreement prohibits group members from receiving those benefits.  These psychological phenomena add costs to peace agreements.

<!--Individual social -->
Along with psychological factors that prevent peace, social factors push groups towards conflict.  Group members receive rewards for conforming to group norms and punishments for violating group norms [@bendor2001evolution; @abrams1990knowing; @hogg2006social].[^socialNorms]  In the context of group competition, group norms can encourage aggressive behaviors towards the outgroup and deter intergroup cooperation [@dreu2010social].  Group members and leaders disposed to negotiation may find themselves unable to compromise with the other side due to social pressure [@fearon1994domestic].  Groups in active conflict might also not engage in ingroup policing, a strong, costly signal to the other side that your group will uphold its peace agreements [@fearon1996explaining].[^comProb]  Social sanctions for cooperative behavior, and encouragement for antagonistic behavior, reduce the benefits and increase the costs of peace.

[^socialNorms]: The rewards for following injunctive norms and punishments for violating them can come either internally, from the individual following or violating the norm [@abrams1990social; @onwezen2013norm] or from other members of an individual's group [@bendor2001evolution].  Internal reward/punishment comes in the form of feelings like correctness, pride, and shame; external reward punishment come in the form of material and social status. 

[^comProb]: In addition to reducing the likelihood of ingroup policing, strong anti-outgroup norms might encourage group members to defect on peace agreements that their leaders have agreed to.  This individual-level defection can cause commitment problems because leaders cannot credibly commit to control the aggressive behaviors of group members.

Group conflict is solvable by bargaining.  However, group conflict persists because psychological biases discourage intergroup trust and color each side's perceptions of the facts of the conflict.  Psychological evaluations and social pressures also add non-material costs to peace and non-material benefits to conflict, reducing the number of peace agreements acceptable to both sides.  Together, these psychological barriers to peace reduce the likelihood of successful bargaining and makes violent conflict more likely.  Removing these psychological barriers may be key for reducing group conflict.  The next section proposes structured intergroup contact as a method for removing those barriers and promoting peace.


## Intergroup Contact Interventions to Improve Intergroup Attitudes and Reduce Conflict

<!--intergroup contact.  Define what it is, when it should work.  Then talk about mechanisms: enhance knowledge/increase trust/reduce stereotypes, reduce threat/anxiety, increase empathy, expand ingroup, etc..

Two ways cooperative contact helps reduce conflict.  (1) Increases trust directly, (2) decreases biased information processing.

Provide opportunities for interaction.  Structure interaction in a way that avoids misperceptions -- incidental contact can make things worse (the @enos2014causal cite and the @forbes1997ethnic cite.  Show that working together is possible.-->

If poor relations between groups cause psychological barriers that prevent groups from bargaining successfully, then improving intergroup relations should remove those barriers and allow groups to reach peaceful agreements through bargaining.  One prominent approach to improving relations between groups comes from intergroup contact theory [@allport1954prejudice].  Intergroup contact theory hypothesizes that intergroup relations can be improved through interactions in which group members (1) cooperate (2) with equal status (3) to achieve shared goals (4) with the support of elites.  Improving relations -- especially improving trust -- can help groups overcome information and commitment problems and reduce the likelihood of violence.[^unCon]

[^unCon]:Important to differentiate structured vs unstructured contact.  Contact under other conditions -- such as incidental contact, intergroup competition, interactions in which one group has power over the other, elite disapproval of intergroup contact -- is unlikely to improve intergroup relations [@enos2014causal; @forbes1997ethnic]<!--hhabyarimana et al 2007; vanhanen 1999-->.]  This concern is heightened from groups in conflict, whose incidental interactions are likely antagonistic.

Structured intergroup contact improves intergroup relations for several reasons.[^contactMechs]  First, intergroup contact provides an opportunity for groups to learn about each other and update opinions based on personal experience, thereby dispelling stereotypes [@allport1954prejudice].  <!--Groups often build elaborate myths about the evil of the other to justify their feelings of ingroup superiority.-->  In the context of conflict resolution, the primary barrier to peace is the stereotype that the other group is untrustworthy.  Intergroup contact provides the opportunity to signal trustworthiness and preferences for cooperation to the other group [@kydd2000trust; @rohner2013war] and has been linked with increased trust even in contexts of ongoing conflict [@hewstone2006intergroup].

[^contactMechs]: A full accounting of the mechanisms through which intergroup contact can improve intergroup relations is beyond the scope of this article.  We discuss the mechanisms mostly likely to affect prejudice for groups in active conflict.  For thorough reviews, see @pettigrew2011advances, @pettigrew2008does, or @pettigrew2013groups.]
Second, intergroup contact can change emotional reactions to group members and reduce feelings of threat and anxiety   Feelings of threat and anxiety often arise from fear of the unknown, and feelings of threat and anxiety reduce as familiarity with outgroup members increases [@page2008little; paolini et al 2004; lee 2001]. <!--chris: removed reduce empathy cuz no measure -->

Third, intergroup contact can show that working together is materially beneficial for both groups.  Intergroup contact often entails reciprocal exchanges like trade, which can provide tangible evidence that both groups are materially better off cooperating than fighting, increasing incentives to reach a bargain and avoid conflict [@rohner2013war].  <!--Intergroup contact to achieve a goal that benefits both groups (1) alleviates material deprivation and (2) associates intergroup cooperation with positive material outcomes.  By cooperating for joint benefit in the present groups can see how cooperative behavior in the future will benefit both groups.-->
  
Fourth, intergroup contact can reduce the perceived social distance between the groups and even expand the ingroup to include the former outgroup.  Contact can make salient many similarities between the groups, reducing feelings of social distance and even helping to craft a joint identity that encompasses both groups [@gaertner2014reducing].

The effectiveness of intergroup contact has been demonstrated in a variety of contexts and using a variety of methodological approaches [@paluck2017contact; @pettigrew2006meta].  Notably, intergroup contacted programs improved relations between white people and black people in the U.S. South Africa, and Norway [@marmaros2006friendships; @burns2015interaction; @finseraas2017does; @carrell2015impact], Jews and Arabs [@yablon2012we; @ditlmann2016can], and Hindus and Muslims in India [@barnhardt2009near].  In Nigeria, a recent study found that intergroup contact between Muslims and Christians decreased discrimination relative to a group that experienced _intragroup_ contact, suggesting that intergroup contact can work by countering the adverse effects of ingroup-only experiences [@scacco2018nigeria].
This leads to our main hypothesis:

  - $\mathbf{H_1a}:$ **Intergroup contact will help.**  <!--Specifically, increase trust, decrease animosity, increase physical security.  $\mathbf{H_2a-c}:$ Effect will be mediated by less social distance/more ingroup expansion; decreased threat;  perceptions of economic benefit.-->

But intergroup contact might not change attitudes or reduce conflict.  Group animosity often arises due to the competition for resources that both groups claim or desire [@sherif1958superordinate].  If competition for resources itself causes poor intergroup relations/negative intergroup attitudes, then competition for resources will cause conflict and intergroup contact will have no effect because it doesn't change underlying resource competition.  With or without structured intergroup contact, the groups are still engaged in competition for resources, which breeds conflict [@campbell1965ethno; @Sherif1988robbersCave].

This concern is heightened for groups in active conflict.  Their negative intergroup attitudes come from real conflict, not the type of prejudice that Allport and others theorized about.  Through contact, you might learn that the other group _does_ favor itself.  Contact might show you that the other group _will_ defect on agreements.  Learning about the other side is not going to improve relations if incentives are completely misaligned and the other side _does_ want to harm you.  Additionally, in contexts of ongoing conflict, there may be few norms against prejudice, and possibly group norms that support this particular intergroup prejudice.  If intergroup contact works by activating "norms against prejudice", contact is unlikely to have an effect for groups in conflict.
<!--Relative deprivation theory: the groups still see the other as responsible for ingroup deprivations.-->

This leads to our alternative hypothesis:

- $\mathbf{H_1b}:$ **Intergroup contact will not help.**

The effect may also be conditional on group status.  Intergroup contact may only reduce prejudice from high-status group to low-status group.  @ditlmann2016can contact-based intervention did not affect the disadvantaged, minority group.

- $\mathbf{H_1b}:$ **Intergroup contact will improve attitudes of farmers towards pastoralists but not pastoralists towards farmers.**


# Context

Farmer-pastoralist conflict in Nigeria's Middle Belt provides a context to learn about intergroup conflict.  Nigeria’s Middle Belt divides the country between north and south, and houses a blend of various ethnic groups, with no clear majority. The south comprises primarily Christian farmers from various ethnic groups, while Muslims from the Hausa and Fulani ethnic groups — including the mostly Fulani pastoralists — dominate the north of the country. These religious, ethnic, and occupational identities intersect and create deep fault lines between communities.   Historically, these communities interacted through trade and shared access to land.  However, in recent years, interconnected factors have made these interactions more contentious.  The Middle Belt has been stressed by climate change, population booms, migration, and government policies perceived to favor some groups over others.  These stressors have sparked violent conflict between farmers and pastoralists in recent years.

Climate change contributes to the conflict in two ways.  First, changing climate has reduced available water sources and land conducive to farming or grazing.  As the Sahara expands southward [@thomas2018sahara] and water sources dry [@okpara2015conflicts], farmers and pastoralists have to share fewer resources.  Second, changing climate pushes more pastoralists southward into the Middle Belt.^[In addition to the role of resource scarcity, @hoffmann2004role also suggests that southward transhumance by Tuareg groups pushes Fulani pastoralists further south.]  Their southward migration of pastoralists who formerly resided in northern Nigeria causes even more demand for land and water as those resources are becoming scarce.

Land scarcity is exacerbated by Nigeria's population boom.  Nigeria's population increased from 73 million people in 1980 to an estimated 200 million people in 2019.  The rapidly growing population means increased demand for farming and grazing land, simultaneous with the decreasing supply of farming and grazing land.  The dual pressures of increasing demand and decreasing supply have fueled farmer-pastoralist conflict in recent years [@unah2018nigeria].  Sharing land is easier when people are scarce and land is plentiful; it is not so easy when land is scarce and people are plentiful.

Land scarcity and new migrants jeopardize traditional agreements that have managed farmer-pastoralist interactions for decades.  Farmers and pastoralists residing in Nigeria's Middle Belt developed agreements about seasonal land sharing, exchanges for crop residue and animal manure, compensation for damage to crops by livestock, and other arrangements that helped them share resources and avoid conflict.  As land scarcity increased, these traditional agreements were increasingly broken [@cotula2004land; @kuusaana2015land].  These agreements were also less likely to be implemented by the pastoralists migrating into the Middle Belt, who were unaware of these agreements and not involved in forging them.  Their use of land beyond these traditional agreements has further ignited tensions.

Grievances related to access land and water points are compounded by government policies perceived to favor farmers.  Land privatization enacted in recent decades encouraged farmers to plant crops that occupy land continuously, like orchards, and effectively nullified farmer-pastoralist land sharing agreements [@bassett2009mobile].  Official cattle routes and reserves for moving herds are rarely enforced by the government, leading farmers to plant crops in once-protected areas, which further limits pastoralists’ available grazing space.  The “indigene versus settler” policy limits land ownership and other rights, including political representation, to certain ethnic groups in each state [@nigeria2014freedom].  Certain communities -- often pastoralists, who are seen as “settlers” -- are denied the right to run for public office, limiting the incorporation of their views into local policies.   

Compounding matters, the government of Benue State enacted an anti–open grazing law in November 2017, sparking more violence because many pastoralists reasonably viewed the law as biased against their way of life.  Benue mobilized state-sanctioned vigilante groups called "livestock guard" to enforce the law, but the livestock guard have sometimes sought out pastoralists, rather than guard farmland.[chris: @duru2018court benue police arresting livestock guard and benue courts releasing the guard; cite other news articles about livestock guard]

These factors -- climate change, increasing population, migration, and government policy -- have broken the agreements that previously governed interactions between farmers and pastoralists.  These factors have challenged the interdependence among the groups and the benefits and costs of reaching agreements.  As farmers in Nigeria began to raise their own livestock [@hoffmann2004role], the need for manure from pastoralists decreases.  As governments allocate private property to settled people, pastoralists increasingly destroy crops when using ancestral grazing routes.  And as demand for agriculture products rise, prices for crop destruction must increase to account for lost revenue.  These changes could seem like "defecting" on previous agreements, suggesting to each side that the other is untrustworthy.  Perceived untrustworthy behavior begets a cycle of distrust, culminating in the violent farmer-pastoralist conflict of recent years.

<!--The conflict is primarily _economic_ in nature -- groups fighting for land rights, with goals that are mainly local and territorial.  But these conflicts are exacerbated by ethnic and religious differences.-->

This persistent violence continues to have debilitating effects on Nigerians and the economy. First, it has taken many lives. In 2013 alone, Plateau, Kaduna, Nasarawa, and Benue states registered more than 100 incidents of violent conflict, accounting for more than 1,050 deaths (Mercy Corps 2018). The more recent violence left 300,000 displaced [@nyt2018nigeria] and more than 1,476 dead in 2018 [@council2019nigeria]. The Middle Belt is considered Nigeria’s “food basket” and is central to key value chains throughout the country, including beef, dairy, and cash crops such as cassava. This violence has impeded food production and threatens to create a food shortage [@frontera2018nigeria]. Before the latest surge in violence, the conflict was costing the Nigerian economy $13.7 billion a year [@mcdougal2015effect].  As one reporter noted, "The countryside is littered with the charred ruins of homes, schools, police stations, mosques and churches." [@mcdonnel2017graze].

Farmer-pastoralist conflict in the Middle Belt is not dissimilar from current and past conflicts in other parts of the world.  Throughout Sahel -- farmer-pastoralist clashes are a persistent problem throughout the Sahel and savanna areas of Africa, including Mali, the Ivory Coast (Bassett 1988, 2009), Niger (Thebaud and Batterbury 2001), and Ghana (Tonah 2002).  Farmer-pastoralist clashes are destabilizing to these countries politically, socially, and economically.  In South Sudan, Myanmar, Bosnia.  "Range wars" between farmers and ranchers in 19th and early 20th century American West.  Can learn about intergroup conflict generally from farmer-pastoralist conflict in Nigeria's Middle Belt.  These conflicts are primarily rural and the state does not project power to these areas.  It is often viewed as biased for or against one group.

## Intervention

The intervention formed mixed-group committees with equal numbers of farmers and pastoralists and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.  It started with a series of community meetings, beginning with separate farmer and pastoralist meetings that built up to joint decision-making meetings with the two groups together.  Each joint project committee included an even number of farmers and pastoralists, as well as women and youth representatives, and totaled between 12 and 15 members. Each committee received two grants, one for quick-impact projects, of approximately \$2,000, and one for joint projects, of approximately \$25,000.

The quick-impact projects were conceived as a trust-building initiative, intended to let community members see that cooperation was possible. Projects, managed by both farmers and pastoralists, included hand pumps, construction or rehabilitation of market stalls and schools, rehabilitation of health centers, and construction of fences along grazing routes to protect farmlands. The joint economic development projects aimed to address an underlying issue related to the conflict: sharing of resources that impact livelihoods. Pollution of water, affecting both farming and livestock, was the primary issue people raised. As a result, each site received a new borehole well, with farmer and pastoralist youth helping to construct the wells.  

The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.

These projects were designed with the conditions of Contact Theory in mind.  Groups (1) cooperated with (2) equal status to achieve (3) shared goals with (4) support of local authorities.  These projects were meant to help the groups solve some underlying resource problems that drove conflict.  Collectively, these project give groups the opportunity so send costly signals about their willingness to cooperate [@kydd2000trust; @rohner2013war].

Will these cooperative interactions allow each group to trust the other?



# References