---
title: "Bargaining and Identity Perspectives on Group Conflict"
author:
- affiliation: <cdgrady2@illinois.edu>, University of Illinois at Urbana-Champaign, Department of Political Science.
  name: Chris Grady
date: '`r format(Sys.Date(), "%B %d, %Y")`'
abstract: "There are two major perspectives on group conflict in political science.  One, which I refer to as the _bargaining perspective_, considers group conflict as the result of information and commitment problems.  The other, which I refer to as the _identity perspective_, considers group conflict as the result of the prejudice and other negative emotions that naturally arise between groups or arise when groups compete for resources.  These two perspectives are rarely combined, but their synthesis could benefit both literature's attempts to understand group conflict and craft policies to reduce it.  In this paper, I apply insights about group biases from the identity perspective to the bargaining perspective's framework of information and commitment problems.  I show how a solution originating from the identity perspective, intergroup contact, alleviates information and commitment problems.  I then use farmer-pastoralist conflict in Nigeria as an illustrative example of how to understand group conflict using both perspectives.  I close by proposing six policy implications of combining these perspectives and offering five avenues for future research."
keywords: " political psychology, bargaining, group conflict, intergroup contact"
thanks: "Thanks to Caglayan Baser, Ekrem Baser, Nuole Chen, and Alice Iannantuoni for useful conversations and feedback on earlier drafts of this paper.  Thanks to Jake Bowers, Jim Kuklinski, Justin Rhodes, and Cara Wong for feedback and guidance.  Thanks to Danjuma Dawop, Lisa Inks, Rebecca Wolfe, and the Mercy Corps Nigeria team for granting me the opportunity to work with them on farmer-pastoralist conflict in Nigeria.  Thanks to Tahiru Ahmadu and Israel Okpe for their keen insights and knowledge about group conflict between farmers and pastoralists."
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    number_sections: yes
    template: ../../../utils/bowersarticletemplate.latex
  word_document: default
bibliography: ../../../utils/cdg_references.bib
---

\newpage

# Introduction

<!--chris: NEED to add hameiri2014challenges about difficulties of positive attitude change in ongoing conflict. -->

<!--1 – Violence is bad.  Results from information/commitment problem.  Explain information/comm problem.-->

Groups fight for the resources -- land, wealth, power, or otherwise -- that fighting destroys.  As such, groups could almost always divide the resources before war in a way that benefits them more than their postwar settlement.  This is the enigma of violent conflict: why do groups engage in violent conflict when violent conflict often destroys the very thing the groups are fighting for?  One answer is that groups suffer from a bargaining failure when negotiating for peace [@fearon1995rationalist; @powell2006war; @reed2016bargaining].  These bargaining failures can be caused by a lack of trust (a commitment problem) or a lack of information (an information problem).  The commitment problem occurs when both sides are better off negotiating a peaceful agreement but neither group trusts the other to abide by negotiated agreements.  The information problem occurs when neither side knows the other side's power or preferences.  If groups (1) trusted each other to abide by agreements and (2) knew the strength and preferences of the other side, they would not need to fight and each group would enjoy superior outcomes relative to their outcomes after fighting.  I call this the _bargaining perspective_ of group conflict.[^IssueIndivisibility]

[^IssueIndivisibility]: Another common explanation for bargaining failures is _issue indivisibility_: when the thing that groups would gain from fighting cannot be split easily or at all (the throne of a monarchy or control over holy land).  Issue indivisibility is thought to rarely be a problem, however, because almost all things that groups fight for are divisible or can be substituted by something divisible [@fearon1995rationalist].  For this reason, issue indivisibility is sometimes seen as a commitment problem [@powell2006war].  If the group being given the throne could commit to providing a substantial portion of the spoils to the other side, the groups could make that peace agreement and avoid fighting.  The group given the throne cannot credibly make this commitment, however, because once in power nothing prevents that group from reneging on their agreement.  I do not consider issue indivisibility as a distinct explanation for bargaining failures in this paper.

<!--Also results from individual-level stuff preventing trust and accurate info processing-->
Another answer to the question of why groups fight focuses on the negative attitudes, emotions, and biases that explain individual group members' lack of trust in and lack of accurate information about the other side, as well as why groups might prefer fighting relative to a peace deal even if fighting destroys resources [@campbell1965ethno; @tajfel1971social; @Stephan2000integratedThreat; @allport1954prejudice; @runciman1966relative; @sherif1988robbersCave; @ross1995psychological; see @bohm2018psychology for a review of psychological theories of conflict].  The lack of trust can occur due to conflicts of interests and competition for scarce resources or as a natural consequence of categorization into ingroup and outgroup.  The lack of accurate information is a consequence of group members' perceptual biases, outgroup stereotyping, and limited interaction.  Preferences for fighting (over agreeing to a peace deal acceptable to the other side) stem from feelings of group superiority and considerations of relative gains over absolute gains.  If members of opposing groups can identify common interest or a common identity, they can avoid the competition, emotions, and perceptual biases that lead to conflict.  I call this the _identity perspective_ of group conflict.

<!--Paragraph about bargaining range/preferences for fighting?-->

<!--Compatability. chris: this is super important paragraph and I have not nailed it yet. -->
In this paper, I argue that these perspectives are compatible and attempt to synthesize them by applying the identity perspective to the bargaining perspective.  There is growing interest in bridging political psychology and political economy explanations for phenomena like group conflict, which is a concern for both literatures [@little2017bargaining; @kertzer2018political].  At their heart, both perspectives focus on preferences, trust, and information, and both consider preferences based on material resources and non-material goods like values, esteem, norms, and power.[^material]  The identity perspective tends to highlight the formation<!--components?--> of preferences and trust and the perceptual biases that cause information asymmetries, while the bargaining perspective tends to highlight how preferences, mistrust, and information asymmetries cause conflict.[^perspectives]  Combining these perspectives will help scholars better understand the causes of group conflict and practitioners better develop policies to reduce group conflict.  

[^material]: I use "material" to refer to things that exist in the world, like physical resources and infrastructure.  I use "non-material" to refer to things that exist in the mind but not in the world, like values, emotions, trust, and reputations.

[^perspectives]: This characterization necessarily lacks the nuance to describe the entirety of these two perspectives.  There is, of course, work in the identity perspective that considers how preferences, trust, and information cause conflict and work in the bargaining perspective that considers the formation of preferences and trust.  But I believe this characterization describes the main arguments of each perspective and the seminal articles on which subsequent work has been built.<!--chris: want to cite examples.  for bargaining, reputation and endogenous preferences. -->

<!--Roadmap paragraph -->
I begin by reviewing the bargaining perspective on group conflict, focusing on information problems, commitment problems, and solutions to those problems.  I follow that review by applying the identity perspective to these bargaining problems and their solutions, focusing on how group biases and other psychological factors contribute to bargaining failures.  In doing so, I propose intergroup contact as a way to reduce group conflict by providing opportunities for the groups to gain accurate information about each other and to build intergroup trust, which alleviates information and commitment problems.  I then apply a synthesis of these perspectives to farmer-pastoralist conflict in Nigeria, describing factors that push groups into conflict, institutions groups have developed to avoid violence, and the consequences when no such institutions exist.  I conclude by describing implications for peacebuilding programs and considering avenues for future research.


# Bargaining Perspective on Group Conflict

The bargaining perspective considers conflict a the result of a bargaining failure.  The two groups both want something and can either fight for it or negotiate over it.  Both groups are better off negotiating pre-war to get their expected outcome post-war, without paying the cost of fighting.  But sides cannot agree to negotiated bargain due primarily to commitment problems and information problems [@fearon1995rationalist].  These problems cause a bargaining failure, and sides resort to fighting.\newline

\noindent \textbf{Commitment Problem}: One reason sides resort to fighting is that neither group can credibly commit to honor bargained agreements.  This "commitment problem" prevents any agreement from being made because neither group will commit to agreements today that they believe will be broken tomorrow.  Because they cannot reach an agreement, the groups fight.[^commitProblem] Commitment problems are often called trust problems because the problem arises because neither group _trusts_ the other to honor commitments.  Commitment/Trust problems are a common explanation for the inefficiency puzzle of violent conflict [@fearon1994ethnic; @powell2006war; @fearon1998commitment; @reed2016bargaining; @lake2003international]

[^commitProblem]: A commitment problem can occur for many reasons.  It often surfaces due to the potential for bargaining power to shift after an agreement.  If bargaining power shifts after an agreement, one side will have an incentive to renege on that agreement to achieve a better outcome.

The canonical example of a commitment problem is the Prisoners' Dilemma.  In the Prisoner's Dilemma, two criminals are arrested and interrogated separately.  The law enforcement officers lack the information to convict the criminals for the full extent of their crimes but have enough information to convict each criminal for a lesser charge.  The officers offer each criminal a deal: testify against your partner and you will be set free; your partner will spend three years in prison.  If both criminals stay silent, they will each serve one year in prison.  If they both testify, they will each serve two years in prison.  The prisoners face a dilemma: why stay silent if you are best off testifying regardless of what your partner does?  The problem here is each side's inability to commit to remaining silent -- a commitment problem.  If they could commit, they could get their second favorite outcome; without the ability to commit, they get their second least-favorite outcome.

The Prisoner's Dilemma is formalized in Table \ref{tab:comProb}.  The criminals are referred to as "players".  Staying silent is referred to as "cooperating" with your partner; testifying is referred to as "defecting" against your partner.  Each player wants their highest payoff.

\begin{table}[h!]
\begin{center}
\setlength{\extrarowheight}{2pt}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(2,2)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(1,1)$ \\\cline{3-4}
\end{tabular}
\caption{\label{tab:comProb}\textbf{Example of Commitment Problem.} Numbers represent payoffs to players.  The first number in each cell represents Player 1's payoffs, the second number represents Player 2's payoffs.  Player's want the highest payoff.}
\end{center}
\end{table}

Unless the criminals value cooperation above freedom or have some way of punishing defection -- both of which change the above payoff structure --, both criminals have an incentive to defect regardless of their partners behavior.  No one is happy with the resulting outcome.  The two sides would commit to mutual cooperation to avoid mutual defection, but they cannot credibly commit to cooperating because they both prefer to defect regardless of what the other does.

This can be applied to group conflict where "cooperation" is abiding by a peace agreement and "defection" is breaking it.  If one side abides by a peace agreement and disarms, for example, the other side has an incentive to break the agreement by staying armed.  Since neither can trust the other to honor the peace agreement, both sides defect.\newline

\noindent \textbf{Information Problem}: Another reason groups fight is that neither side knows the preferences of the other.  This "information problem" prevents peace agreements from being made, even if both sides prefer mutual cooperation, because neither side knows that the other would reciprocate cooperation and both sides have an incentive to lie about their preferences to extract more concessions from their opponent.  Because both sides fear defection if they cooperate, the groups fight.  The information problem of conflict is one of the most common explanations for violent conflict [@fey2011uncertainty; @smith2003mediation; @fearon1995rationalist; @kydd2000trust; @moon2016audience; @rohner2013war; @wolford2011information]

<!--@fey2011uncertainty: information asymmetries cause bargaining failures.  Fighting to gain information: @smith2003mediation. -->

We can observe an information problem by modifying the Prisoner's Dilemma above.  Imagine that each criminal is "honorable" and values reciprocating cooperation.  This bonus to cooperation can be seen as the psychological value that each side places on being honorable; it is represented by adding +2 to the payoff of joint cooperation.  Each criminal wants to cooperate if the other cooperates but wants to defect if the other defects.  Each criminal knows that they are honorable, but neither knows that the other is also honorable.  The problem here is a lack of information -- an information problem.

This modified Prisoner's Dilemma, often called a Trust Game [@kydd2000trust], is formalized in Table \ref{tab:infoProb}.  Each player again chooses whether to cooperate or defect.  Player 1 is honorable and prefers to cooperate if Player 2 will cooperate but defect if Player 2 will defect.  Player 1 is unsure if Player 2 is also honorable.^[In a Trust Game, Player 1 would believe Player 2 is honorable with probability $p$, where $p$ represents Player 1's trust in Player 2.]  World A represents the payoffs if Player 2 is honorable; World B represents the payoffs if Player 2 is not.  In World A there is only an information problem: if groups knew each other's preferences, they have an incentive to cooperate.  In World B there is also a commitment problem: even if groups knew each other's preferences, each still has an incentive to defect.

\begin{table}[h!]
\begin{center}
\setlength{\extrarowheight}{2pt}
\begin{subtable}{0.48\linewidth}
\caption{\label{tab:info_a}\textbf{World A} \\Both sides prefer to cooperate if the other side cooperates but defect if the other side defects.}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(4,4)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(1,1)$ \\\cline{3-4}
\end{tabular}
\end{subtable}%
\hfill
\begin{subtable}{0.48\linewidth}
\caption{\label{tab:info_b}\textbf{World B} \\Player 1 prefers mutual cooperation, but Player 2 prefers to defect regardless of Player 1's Behavior.}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(4,2)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(1,1)$ \\\cline{3-4}
\end{tabular}
\end{subtable}
\caption{\label{tab:infoProb}\textbf{Example of Information Problem.} Numbers represent payoffs to players.  The first number in each cell represents Player 1's payoffs, the second number represents Player 2's payoffs.  Player's want the highest payoff.}
\end{center}
\end{table}

Player 1 cooperates or defects depending on her belief that Player 2 is honorable.  If Player 2 is honorable, Player 1 wants to cooperate.  If Player 2 is not honorable, then Player 1 is in the Prisoner's Dilemma above and wants to defect.  Without a way to for Player 2 to signal honor, Player 1 defects.  Again, no one is happy with the resulting outcome.  The two sides would prefer mutual cooperation to betraying the other player, but because neither side knows the other's preferences both players defect.

This can again be applied to group conflict where "cooperation" is abiding by a peace agreement and "defection" is breaking it.  Conflict occurs due to information problems: unless both sides know that the other will reciprocate cooperation, both sides may defect to avoid being betrayed.  It is common in group conflict for each group to claim that the other is the barrier to peace, reflecting their belief that the other group will not reciprocate cooperation.

Another way to represent the information problem in a conflict setting is to say that two groups need to split a resource, but neither knows each other's fighting strength (capacity) or valuation of the resource (willingness).  Without knowing the other side's capacity and willingness to fight, neither side knows what they should offer or receive from a peace agreement.  If, for example, each side believes (incorrectly) that they are stronger than the other, that overconfidence prevent both sides from finding a peace agreement in which they receive more than they expect to receive through fighting [@johnson2009overconfidence].  This information problem can cause bargaining failures even if the two sides communicate.  Both groups have an incentive to portray themselves as stronger, more willing to fight, and less willing to make concessions than they truly are in order to achieve an advantageous bargaining outcome [@fearon1995rationalist].

Groups can suffer from information problems and commitment problems simultaneously. In this example of splitting a resource, groups may fight even if both know each other's fighting strength and valuation of the resource under dispute (i.e. under complete information).  With this complete information, groups could presumably allocate a portion of that resource to each side, with the higher-strength side taking a larger portion.  The problem, however, is that once a group takes a larger portion of the resource, they now have more fighting strength and could renegotiate an even more advantageous deal for themselves.  Knowing this, the weaker side may prefer to fight rather than acquiesce to a series of peace agreements under weaker and weaker bargaining power.\newline

\noindent \textbf{No bargaining range}: A third reason groups fight is that one or both sides prefers fighting to peace.  In other words, there is no bargaining range, no peace agreements acceptable to both sides.  I will refer to this as a "preferences problem".  This preferences problem is not a bargaining failure; if one or both sides prefer fighting to any peace deal, then groups are not bargaining for peace.  Nor is this a "problem" in the way that commitment problems and information problems are a problem.  In those problems, conflict is a puzzle because groups end up with outcomes neither group wants and which do not maximize overall utility (benefit, broadly defined).  If mutual fighting maximizes overall utility, it is a problem normatively in that we normatively dislike fighting, but it is only a puzzle if we think groups should not prefer fighting.  For these reasons, preferences for fighting over peace are an important reason for group conflict but are discussed less frequently in published literature (but see @coe2012costly, @slantchev2012borrowed, and @chang2013war).

We can observe a preferences problem by again modifying the Prisoner's Dilemma.  Imagine that the criminals hate each other and would regret _not_ ratting out the other guy.  This is represented by adding +1 to the payoff of joint defection and -1 to the payoff of joint cooperation.  Their payoffs would look like Table \ref{tab:prefProb}.  

\begin{table}[h!]
\begin{center}
\setlength{\extrarowheight}{2pt}
\begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Player $2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Cooperate$}  & \multicolumn{1}{c}{$Defect$} \\\cline{3-4}
    \multirow{2}*{Player $1$}  & $Cooperate$ & $(1,1)$ & $(0,3)$ \\\cline{3-4}
      & $Defect$ & $(3,0)$ & $(2,2)$ \\\cline{3-4}
\end{tabular}
\caption{\label{tab:prefProb}\textbf{Example of Preferences Problem.} Numbers represent payoffs to players.  The first number in each cell represents Player 1's payoffs, the second number represents Player 2's payoffs.  Player's want the highest payoff.}
\end{center}
\end{table}

This setup, like the Prisoner's Dilemma, results in mutual defection.  Unlike the Prisoner's Dilemma, the players would not commit to cooperation even if they could; nor does knowledge about each other's preferences avoid defection.  Mutual defection is the Pareto-optimal outcome in that it maximizes the total utility of both sides.

Preferences for fighting can also be seen in group conflict.  Each side may prefer to fight because peace is relatively more costly, perhaps because peace entails mounting armament costs [@coe2012costly; @chang2017endogenous] or because of debt payments that a state can only repay if they win the conflict [@slantchev2012borrowed].  Sides may also prefer fighting to peace because fighting is less costly than assumed due limited destruction of resources [@chang2013war].  Sides may also use fighting today to improve their bargaining position with their current adversary [@slantchev2003power] or potential future adversaries [@crescenzi2007reputation]. <!--chris: i don't think I understand slantchev2003 that well. -->^[Lack of information and overconfidence [@johnson2009overconfidence] about likely victory in conflict can cause what looks like a "preferences problem" in that groups may prefer fighting relative to any peace deal the other side is willing to accept.  The difference between an information problem and a preference problem is that the information problem disappears if both sides have complete information about the other, but complete information does not change the preferences problem.]


## Solutions to Group Conflict in the Bargaining Perspective

Third party intervention, reputation-building, and signaling are the primary solutions to commitment and information problems in the bargaining perspective.  Third party intervention can solve information problems by providing accurate, credible information to both sides; it can solve commitment problems by punishing defection so that it is in both side's interests to cooperate.  Reputation-building can solve commitment problems and information problem by revealing the preferences of each player and by the prospect of better future outcomes from a cooperative reputation than a noncooperative reputation.  Each side can also reveal their preferences by sending costly signals of their preferences to the other side.  Because the signals are costly, non-cooperative types do not send costly signals.
<!--Solution is to make cooperation in each group's interest regardless of their base one-off preferences.  Can do that by adding costs to defection so that neither side benefits from defection.  Can also do that through repeated interactions.-->

<!-- Info/Comm problems between groups often solved by 3rd parties or reputations/repeated interactions. Explain how these things solve problem.  -->
Third party intervention is a common mechanism for overcoming information and commitment problems and resolving group conflict.  Third parties can solve information problems by mediating disputes, providing accurate information about the preferences and strength of both sides (see @crescenzi2011supply and @gartner2011signs for this perspective; but see @kydd2003side, @kydd2006can, and @beber2012international for the problem of mediator credibility).  Third parties can solve commitment problems by punishing defection, which incentivizes each side to honor agreements.  Though each group may have an incentive to defect on an agreement after it is made, the groups have less incentive to defect if a strong third party is capable of and willing to punish defection from bargained agreements [@fearon1994ethnic].  Third parties that facilitate information flows and enforce agreements often effectively reduce conflict [@doyle2000international; @di2017effectiveness; @walter2002committing; @hartzell2001stabilizing; @wallensteen2014talking].^[Some scholars have noted that third parties do not create trust between those groups that will last beyond the third party's presence [@gambetta_ch13; @rohner2013war; @beardsley2008agreement].]

<!-- many ways, other than 3rd parties, to build trust between groups.  reputation/repeated interactions.-->
In many group conflicts, however, there exists no third party with the capacity and incentive to intervene into the conflict [@fey2010shuttle, p.530].  This situation is common for internal conflicts in weak states, where conflicts are diffuse and the state lacks the capacity to mediate or intervene effectively.  Many group conflicts occur in such states.<!-- [chris: cite].-->

In those cases, groups can resolve information and commitment problems without relying on third party intervention.  Groups can resolve those problems by cultivating reputations for trustworthiness in repeated interactions.  Like third parties, repeated interactions between groups help overcome these problems by providing each group with the incentive to honor agreements.  Here the incentive comes not from fear of punishment by a third party but the prospect of better future outcomes from cooperation than defection.  Though each group may have an incentive to defect on an agreement today if the groups will not interact tomorrow, the groups have an incentive to cooperate now if their behavior today will be reciprocated by the other side in future interactions [@ostrom2003trust; @kydd2000trust; @axelrod1981evolution].[^reputation]  

When third parties are not present, groups can also solve information and commitment problems through costly signals of cooperative intent [@kydd2000trust; @rohner2013war; @gambetta_ch13; @jervis2017perception].  Costly signals can reassure each side of the other's trustworthiness because only a trustworthy player will pay the cost to send the signal.  The signal must be sufficiently costly to deter noncooperative players from sending it (uninformative signals are referred to as "cheap talk") but not so costly that even cooperative types will not send it.

When both groups stand to gain more from enduring cooperation than enduring defection, but information and/or commitment problems would stymie cooperation in one-shot interactions, repeated interactions and costly signals provide groups with the incentive to cooperate and provide groups with the opportunity to communicate their preference for cooperation.

[^reputation]: I discuss reciprocity and reputations together, but these mechanisms are subtly different.  The reciprocity mechanism is generally mobilized for contexts with just two groups.  In those contexts, cooperation in previous interactions assists in obtaining cooperative behavior in the future from the same partner; other potential partners are unnecessary.  The reputation mechanism is generally (though not always) mobilized for contexts in which many groups observe the behavior of many other groups.  In those contexts a good reputation assists in obtaining _other_ cooperative partners; reciprocity from the same partner is unnecessary.  I discuss these mechanisms together because both rely on creating cooperative expectations from bargaining partners in future interactions.

In this section, I reviewed common explanations for and solutions to group conflict under the bargaining perspective.  In the next section, I show how the identity perspective fits with and adds to the bargaining perspective.


# Applying the Identity Perspective to Bargaining

<!--Bargaining perspective formalizes the reasons groups can fight: preferences (lack of bargaining range), information problems, commitment problems.  The identity perspective highlights many of the factors that contribute to information problems, commitment problems, and the lack of a bargaining range. -->
The bargaining perspective explains formalizes the reasons groups can fight: preferences (lack of bargaining range), information problems, and commitment problems.  I argue that the identity perspective adds to these explanations by describing how psychological and social factors (1) decrease the bargaining range by providing incentives for groups to fight, (2) cause commitment problems by preventing the formation of trust, and (3) cause information problems by biasing information processing about the other group and perceptions of their preferences.  By looking at groups as a collection of individual group members and focusing on individuals' perceptual and cognitive biases, the identity perspective helps explain when and why fighting will occur.

<!--costs to peace:
(1) self-esteem loss
(2) cost of losing justification for past aggressive/discriminatory behaviors
(3) general costs to attitude change: I thought those people were bad, now we're supposed to work with them?
(4) cost of changing norms/institutions that discriminated against the outgroup.
(5) domestic audience costs to leaders?
(6) making peace with an enemy?
(7) sunk cost fallacy / "dissonant...to accept terms today that could have been achieved, without the ensuing costs...,at some earlier point in time."
-->

## Costs of Peace and Benefits of Fighting Reduce the Bargaining Range

<!--chris: be clear that adding costs to peace does not make groups necessarily "prefer fighting to peace", but may make them prefer fighting to the set of bargains the other side will agree to.-->
Psychological and social factors can contribute to group conflict by reducing or erasing the range of peace agreements both sides will accept.  These factors reduce the bargaining range by adding costs to peace and benefits to fighting.  I identify three main ways that psychological and social factors add costs to peace: (1) direct costs of changing attitudes and social norms, (2) loss of self-esteem, and (3) loss of sunk costs.^[These three reasons are not an exhaustive list of the ways that psychological and social factors add costs to peace.  Rather than give an exhaustive list, I seek to demonstrate that explicitly considering psychological and social factors helps explain why groups would find peace costly.]

First, direct costs to attitude change occur to the extent that accepting peace requires individuals in the group to change attitudes about the outgroup.  Individuals use many strategies to maintain existing attitudes -- searching for information that confirms pre-existing beliefs, counter-arguing information divergent with their beliefs -- suggesting that costs to attitude change are not insubstantial [@festinger1962cognitiveDissonance; @nickerson1998confirmation; @kunda1990motivatedReasoning].  Changing negative attitudes towards an enemy may be especially challenging because negative outgroup attitudes are supported by a social norms and justifications that feeds conflict [@bar2007sociopsychological].  At the group-level, a peace agreement requires groups to dismantle the social institutions that feed conflict and encourage violence against the outgroup [@bornstein2003intergroup].  Those institutions must be reformed to prevent, not encourage, intergroup violence.

Second, peace agreements may cause a loss of self-esteem for individual group members.  Group members derive self-esteem from positively comparing their group to a rival group, and any agreement in which their side acknowledges the legitimacy of the other challenges this group-based boost to self-esteem [@tajfel1981groups; @wood2000attitude; @tajfel1979integrative; @fein1997prejudice; @martiny2012shall; @brown2019group].  Group members may also pay psychological costs to their self-esteem from losing their rationalization for engaging in discriminatory or aggressive behaviors towards outgroup members.  People rationalize their behavior to maintain a moral self-image [@bandura1999moral; @bandura2014social; @mazar2008dishonesty], and people who harmed the outgroup must come to terms with past behaviors that are now deemed immoral.

Third, individuals are affected by sunk costs and want the gain from a peace deal to make up for the cost of fighting even though those costs were already born [@arkes1985psychology].  The desire to recoup sunk costs induces both sides to demand that the other concede more in a peace agreement.  It would be "dissonant for the disputing parties to accept terms today that could have been achieved, without the ensuing costs, at some earlier point in time" [@ross1995psychological, p.264].  In conjunction with biased perceptions and memories of conflict history (discussed below), each group is also prone to believe that they are morally entitled to more concessions than the other side [@ward1997naive].  Accepting terms that could have been achieved without fighting is also to admit that fighting was a mistake, and people are loathe to admit their mistakes [@tavris2008mistakes].  This partially explains why "emotions stemming from past interethnic violence serve as impediments to peaceful resolutions to present-day conflicts" [@little2017bargaining, p.5; @horowitz2001deadly; @petersen2002understanding]

<!--Example of costs to peace. harm, discrimination. -->
To see how these psychological costs to peace might sabotage peace efforts, imagine that groups fighting over land sign a peace agreement that assigns some land to each group.  This agreement may make material sense in that each group can enjoy the benefits of some land instead of fighting for all of it.  But in addition to the material cost of losing potential access to land granted to the other side, each group must begin punishing violence against outgroup members rather than encouraging it.  Individuals in the group must adjust their behavior to conform to new norms and rethink the status of their group relative to the outgroup; they can no longer "bask in the reflected glory" of their group's superiority [@brown2019group, p.312].  Individuals who felt justified in overcharged outgroup members for services or physically harming outgroup members are now told that such behaviors are wrong and immoral.  Individuals must also accept that their sacrifices to benefit fighting -- dead friends and loved ones, material deprivation, time and energy spent fighting -- were for naught: the sacrifices did not help the group win.  Sustaining conflict against the outgroup allows group members to maintain existing attitudes and behaviors and preserves the possibility that their group will be victorious.

<!--Benefit to fighting-->
Other than avoiding these costs, group members may gain benefits from fighting for two main reasons.  First, group members may feel pleasure in response to outgroup pain [@weisel2015ingroup; @cikara2014their].  This pleasure adds psychological utility to participating in conflict for individual group members.  Second, individuals may like gaining glory and other social rewards for participating in violent conflict.  Societies use various social carrots and sticks to encourage participation in conflict [@gneezy2012conflict], and group members give up those rewards when conflict ends.  These social rewards add social utility to participating in conflict, which could make fighting more attractive than peace.  These benefits to fighting may work in conjunction with each side's desire to signal strength and resolve to future potential adversaries and each side's tendency to overestimate their chances of victory, which can also promote preferences for fighting in the bargaining perspective [@johnson2009overconfidence; @crescenzi2007reputation].

<!--Costs to peace, benefits to fighting: no possible peace agreements -->
As a result of these costs to peace and benefits to conflict, there may exist no peace agreement that both sides prefer to fighting.  Each group may prefer mutual defection and their payoff structure may resemble Table \ref{tab:prefProb}, where fighting occurs because groups have a "preferences problem".  Each side may only accept a peace agreement that materially favor their group because the material gains from peace must overcome its non-material costs; it is difficult for each side to appreciate the non-material costs of the other [@ward1997naive].  Groups may also consider their gains relative to the outgroup, rather than in absolute terms.  Indeed, many group members are willing to accept lower absolute gains to increase relative gain over the outgroup [@turner1979social; @waltz2010theory; @halevy2010relative].  The preference for gains relative to the outgroup makes any mutually beneficial peace agreement impossible.
<!--In that case, reputations in repeated interactions do not bring peace.  Each side prefers mutual cooperation in repeated interactions only if their utility from mutual cooperation exceeds their utility from mutual defection.   -->


## Biased Perceptions Cause Information and Commitment Problems

<!--Bias perceptions-->
Though the above factors can increase the costs of peace and increase benefits of conflict, the high cost of conflict may be such that both sides still prefer peace.  Even when both sides prefer peace, psychological and social factors can contribute to the information and commitment problems that prevent groups from negotiating peace agreements.  I identify two main ways that these factors contribute to information and commitment problems.  First, cognitive dissonance, motivated reasoning, and confirmation bias[^biasDefs1] cause each side to interpret the other's behavior in a way that supports existing negative attitudes.  Second, loss aversion and reactive devaluation[^biasDefs2] cause the two sides to overvalue concessions they give up and undervalue concessions they receive.  These phenomena introduce significant friction in the ability of groups to accurately perceive the other's preferences and to build trusting relationships.

[^biasDefs1]: _Cognitive dissonance_ is the mental discomfort that occurs when one individual holds two contradictory beliefs.  Individuals resolve this dissonance by rejecting one of the contradictory beliefs [@festinger1962cognitiveDissonance; @tavris2008mistakes].  Individuals tend to resolve this dissonance by rejecting the newer or less central belief because it is costly to reject older and more central beliefs [@schwartz1990toward; @converse1970attitudes; @bryan2019values].  _Motivated reasoning_ and _confirmation bias_ are related concepts.  Motivated reasoning is the tendency for individuals to "reason" in whatever way allows them to reach their desired conclusion [@kunda1990motivatedReasoning].  Confirmation bias is the tendency for individuals to interpret new information and search memory for information to confirm existing beliefs [@nickerson1998confirmation].

[^biasDefs2]: _Loss aversion_ refers to individuals' tendency to prefer avoiding losses more than they attaining equivalent gains [@kahneman2013prospect].  Reactive devaluation is the tendency for individuals to undervalue concessions and proposals from antagonists [@ward1997naive; @ross1991barriers].

Cognitive dissonance, motivated reasoning, and confirmation bias cause group members to interpret and recall outgroup behavior in negative ways.  These phenomena prevent cross-group interactions from accurately revealing each side's preferences because members of different groups experience and interpret the same event differently [@ward1997naive].  Defensive action by outgroup members may be misperceived as belligerent and threatening while belligerent action by one's own group is seen as defensive and justified [@ward1997naive; @duncan1976differential; @vallone1985hostileMedia].  Positive actions by outgroup members may be re-interpreted as negative to avoid cognitive dissonance [@gubler2013humanizing; @paolini2010negative; @good2000individuals].  Unequivocally positive behavior may be dismissed as an exception while negative attributes are believed to define all outgroup members [@hewstone1990ultimate].  These misperceptions can lead each group to believe the other side is untrustworthy or prefers fighting to peace.  And when recalling information about the outgroup from memory, individuals selectively recall events that corroborate their pre-existing negative perceptions [@de2008motivated].

<!--paragraph about loss aversion and reactive devaluation -->
Loss aversion and reactive devaluation can further sabotage the trust-building process.  Individuals tend to weigh losses more heavily than equivalent gains, so anything their group gives up may be magnified in importance [@kahneman2013prospect].  At the same time, individuals tend to undervalue concessions from antagonists [@ward1997naive; @ross1991barriers].  These biased valuations of concessions made and concessions given can prevent groups from reaching a mutually beneficial agreement.  For an abstract example, imagine that Group 1 offers Group 2 a concession that is objectively worth five "negotiation units", but which Group 1 values as six due to loss aversion.  Group 2 may interpret that five as a four due to reactive devaluation, and then offer something that is objectively only worth three but which they perceive as worth four due to loss aversion.  Each group could come away from that encounter believing that the other is unreasonable and that there is no peace agreement mutually satisfactory to both sides.

<!--Example with costly signaling.-->
These phenomena can also interfere with groups sending and receiving costly signals of cooperative intent.  A costly signal from Group 1 to Group 2 can allow Group 2 to trust Group 1 because Group 1 would only pay the cost of the signal if Group 1 was trustworthy.  Perceptual biases like reactive devaluation, however, may lower the perceived costliness of any cooperative signal.  Group 2 may perceive the signal as cheap and uninformative of Group 1's preferences or intentions.  Worse, Group 2 may perceive the signal as a cynical attempt to manipulate Group 2 into cooperating so that Group 1 can take advantage of their naivete.

<!--Limited opportunities for interaction -->
Compounding these perceptual problems, accurate information and intergroup trust are hampered by a lack of opportunities to learn about the other side.  Groups in conflict tend to limit contact between the two sides [@bornstein2003intergroup], so most learning must come from observing the outgroup's interactions with other groups.  Even if those opportunities are available, few of the outgroup's interactions will be with groups that are relevant for predicting the outgroup's behavior towards the ingroup, reducing the usefulness of observational learning [@kazdin1974covertModeling; @yang2013similarity]. The main opportunity to observe outgroup behavior and learn their reputation is the ingroup's own interactions with the outgroup, which are limited and hampered by perceptual biases.

## Solutions in the Identity Perspective Applied to the Bargaining Perspective

<!--introduce intergroup contact.  overall goal of section: how intergroup contact helps reducing costs to peace, benefits to fighting, and perceptual biases. -->
I discuss intergroup contact as the primary solution to group conflict in the identity perspective.  Intergroup contact, interactions between group members in which members of different groups work together to achieve common goals, is not the only solution for group conflict, but I believe it is the most promising solution [see @bohm2018psychology for a summary of others.]   Intergroup contact has the potential to (1) change incentives for fighting and peace, (2) debias perceptions of the outgroup, and (3) provide opportunities for costly signaling.  Put another way, intergroup contact can increase the bargaining range and help solve information and commitment problems.

<!--1-material benefits of cooperation/peace; 2-lowers benefits of fighting if no hate.
Make groups want peace: Goal achievement through cooperation: cooperation in each group’s interest.
perceive that the benefits of peace outweigh the benefits of fighting; a solution should increase the expected payoff of peace (through examples of cross-group cooperation working well) and reduce psychological benefits from harming outgroup.
-->
Intergroup contact can increase the value of peace and decrease the value of fighting<!--, thereby increasing the bargaining range and increasing the likelihood that there are peace agreements both sides prefer to fighting. Intergroup contact does this first--> by highlighting the material benefits of cooperation.  Few members of groups in conflict are likely to have benefited from working with the outgroup, so they may associate the outgroup with undesirable outcomes.  When groups achieve a goal through cooperation that is mutually beneficial to both, it adds previously unforeseen benefits to cooperation.  The prospect of benefits through cooperation can motivate individuals to develop more positive attitudes towards cooperation [@grady2020lab; @rohner2013war].  If cooperation is beneficial to the group, the group may develop norms that encourage cooperation [@axelrod1986evolutionary].  

Along with increasing the perceived value of peace, intergroup contact can also remove benefits to fighting for group members who gain psychological utility or enjoy social rewards from harming the outgroup.  Intergroup contact humanizes and creates positive attitudes towards the other side [@pettigrew1998intergroup; @pettigrew2006meta], and group members only gain utility from harming the outgroup if the outgroup is viewed negatively and without empathy [@bohm2016makes; @weisel2015ingroup; @cikara2014their].  Likewise, groups norms that promote cooperation will give social punishments, not social rewards, for aggressive action towards the outgroup.  When the outgroup is not hated, harming them loses its luster.
<!--More positive individual attitudes and social norms towards the outgroup should also add costs to fighting-->

<!--done: make preferences for peace.  less costs to peace, less benefit to fighting. -->
<!--Next: debias perceptions. -->
<!--Lastly: opportunities for signaling -->

<!--also tells each group that the other side wants to cooperate.  Can trust other side to do what is in their own interest. solves information problem & commitment problem. -->
As well as increasing the utility of cooperation relative to fighting, for intergroup contact to help resolve group conflict it must help solve information and commitment problems.  Intergroup contact can solve these problems by assuring each group that the other side prefer cooperation to fighting.  It is not enough that each group prefers cooperation, they must have the opportunity to signal that preference to the other side, and the other side must accept the signal.  Without this shared knowledge, groups may remain in conflict because of information and/or commitment problems.  Intergroup contact provides opportunities for signals and knowledge sharing.

<!--reduces perceptual biases, greases the gears. -->
The second way that intergroup contact helps reduce conflict is by reducing perceptual biases that prevent groups from accurately perceiving the other side's preferences and building trust.  Removing these perceptual biases helps solve information and commitment problems.  Intergroup contact reduces perceptual biases by dispelling stereotypes, reducing feeling of threat and anxiety, engendering feelings of empathy, and making group commonalities salient [@allport1954prejudice; @pettigrew2008does; @page2008little; @batson1997empathy; @broockman2016durably; @gaertner1993common].  By removing these causes of perceptual biases, groups are more able to form accurate views of each other's preferences.  Without stereotypes and feelings of threat, and with empathy and group commonalities, group members will not be motivated to see the outgroup negatively or feel dissonance after positive experiences with outgroup members.  Groups are also less likely to reactively devalue each other's concessions and more likely to have empathy for each other's positions.  Through these mechanisms, contact builds trust even between members of conflicting groups [@grady2020farmer; @hewstone2006intergroup].

By debiasing perceptions, each group may identify that it is in each group's interest to cooperate.  All of the mechanisms above -- reducing stereotypes and threat, increasing empathy -- also increase the likelihood that group members perceive cooperation to be in their interest and in the interest of the other side. It is unlikely that one side will expect cross-group interaction to be in their group's interest if that side fears the outgroup and holds negative stereotypes about the outgroup's work ethic and honesty.  It is equally unlikely that a group will expect the other side to cooperate with them if the other side believes them to be lazy and dishonest.  Likewise, achieving a joint goal through cooperation reassures each group that the other side also prefers cooperation.  Each side can trust the other to engage in cooperative behavior when both sides know that it is in each side's interest to do so [@gambetta_ch13].  Removing these perceptual biases helps each side see that cooperation is in the interest of their group _and_ of the other group.  It takes two to mutually cooperate.
<!--@gambetta_ch13: Contact builds familiarity, which may be necessary for trust to form: "trust may be a by-product...of familiarity and friendship, both of which imply that those involved have some knowledge of each other and some respect for each other’s welfare."-->
<!-- @gambetta_ch13: "It is necessary not only to trust others before acting cooperatively, but also to believe that one is trusted by others."
@gambetta_ch13: "The importance of interest is twofold: it can be seen to govern action independently of a given level of trust, but it can also act on trust itself by making behaviour more predictable."  "cooperative behaviour does not depend on trust alone" but on interest/incentives.
        On closer inspection we find that when that pressure is commonly shared and this fact is known to both sides, then cooperation is motivated and trust itself may increase as a result."  Later, quoting Hume: "'...interest is the first obligation to the performance of promises. Afterwards a sentiment of morals concurs with interest, and becomes a new obligation upon mankind (1969: 574)."
-->

<!--done: debias perceptions. -->
<!--next: signal other side's preferences-->

<!--Provides opportunity for costly signaling: groups interact and can directly observe outgroup’s preferences and behavior.
small cooperation helps build large.  Confidence-building measure -->
Along with increasing the utility of cooperation and debiasing perceptions, the third way that intergroup contact can help resolve conflict is by offering opportunities for costly signaling.  Intergroup contact allows group members to learn about each other based on personal experience, interacting and communicating directly.  Direct cross-group interaction allows group members to signal their trustworthiness through communication with and behavior directly observed by the other side.  This type of direct communication reduces competition and helps solve commitment problems in behavioral games like the Prisoner's Dilemma [@bornstein1989within; @ostrom2006value] and in formal models [@rohner2013war].  These interactions can serve as confidence-building measures and allow groups to start small and low-risk and gradually increasing as groups build trust over time; trust is one of the few resources that increases with use [@gambetta_ch13].  Importantly, intergroup contact gives each group the opportunity to signal willingness to punish their own members if those members jeopardize peace [@fearon1996explaining].

<!--chris: this paragraph/subsection is a luxury: Not work in all cases.  Where preferences are completely opposed and conflict unlikely to destroy, the benefits of .  Where the conflicting groups are hierarchical armies.  Where peace benefits some group members more than otheres and war hurts some group members more than others.-->

In this section, I showed how the identity perspective works with the bargaining perspective to explain group conflict.  I also demonstrated how a solution proposed by the identity perspective, intergroup contact, works in the bargaining perspective.  Intergroup contact can provide incentives for cooperation, reduce perceptual biases, and provide opportunities for costly signals of trustworthiness.  Through incentives for cooperation, it can give each side a preference for peace over fighting.  By reducing perceptual biases and providing opportunities for costly signaling, contact can help solve information and commitment problems.  In the next section, I apply this joined perspective to farmer-pastoralist conflict in Nigeria and describe the form that institutions to improve intergroup cooperation have taken in that context.


# Application: Farmer-Pastoralist Conflict

The conflict between farmers and pastoralists in Nigeria looks like a textbook case of a commitment problem preventing peace.  The groups maintain complementary ways of life, making cooperation beneficial for both.  Pastoralists have an excess of protein in the form of meat, milk, and other animal products, but they grow little in the way of grains, tubers and vegetables; the farmers have an excess of grains, tubers, and vegetables but they own few animals and have limited access to animal products.[^chicken]  Farmers also want animals to graze on their lands after harvest season to replenish the soil with animal waste, and pastoralists want to graze their animals on crop residue (stalks, leaves, seed pods, and other inedible parts of the plant) that is left on the fields after harvest.

[^chicken]: This is not to say that farmers have no independent access to protein and pastoralists have no independent access to grain.  Farming villages typically stock chickens for eggs and meat as their main protein source, with a few goats and sheep.  They do not have excess food year round to support large animals like cows.  Most pastoralists are semi-migratory and few stay in one place long enough to cultivate crops.  Those who stay in a "home base" will set aside some land for rice or yams, but most of the land is left for cattle to graze.

By all accounts, farmers and pastoralists benefited from their complementarity for several generations [@tonah2002fulani; @icg2017nigeria; @thebaud2001sahel].  There were, of course, disagreements between sedentary farmers and mobile pastoralists, but their relationship was characterized more by harmony than conflict.  Recent decades, however, have brought farmers and pastoralists into conflict.  Historically, farming was more common in southern Nigeria and pastoralism more common in the north, but the two ways of life increasingly overlap geographically.  Farmers have moved north into marginal agricultural lands due to the increasing food needs of Nigeria's booming population, which grew from 50 million at Independence in 1960 to 200 million today [@abbass2012no; @kuusaana2015land].  At the same time, pastoralists have been pushed further south by the expansion of the Sahara, which brought them to higher population density areas [@thomas2018sahara; @okpara2015conflicts].  Less land and more people who depend on the land is a recipe for conflict over land and resources.

Farmer-pastoralist conflict has exploded in recent years.  The most recent conflict escalation caused 7,000 deaths from 2014-2019 and displaced hundreds of thousands of people from their homes [@council2019nigeria; @daniel2018anti; @fa2019deadly; @nyt2018nigeria].  The scale of economic damage is unknown, but farmer-pastoralist conflict _before_ this escalation cost Nigeria $13 billion annually in lost economic productivity [@mcdougal2015effect].  This violence has also impeded food production, leading to an impending food crisis [@fa2019deadly; @frontera2018nigeria; @unah2018nigeria].  

The proximate causes of violence are farmers sowing seeds on pastoralists' grazing lands and pastoralists grazing their cattle on farmers' crops.  If either side retaliates -- a farmer by stealing cattle from the pastoralists' herds, a pastoralist by grazing on more farmland -- the scope of the conflict can rapidly expand.  The farmer whose crops were destroyed by cattle does not know which herd grazed on his land; cattle he steals in revenge do not necessarily come from the transgressing herd.  Pastoralists, likewise, do not know which farmer stole their cattle; the crops they destroy in revenge do not necessarily come from the transgressing farm.  From there, a little war often breaks out.  As one reporter noted, "The countryside is littered with the charred ruins of homes, schools, police stations, mosques and churches." [@mcdonnel2017graze].  In one case I witnessed, a farmer took revenge against cattle grazing on his farmland by poisoning the crop residue left on his fields after harvest.  After grazing on the residue, the cattle of dozens of pastoralists became sick and died.  More violence followed. 

<!-- Describe non-material costs/benefits to conflict-->
The land conflict is exacerbated by ethnic and religious differences between groups, which feeds mutual distrust.  The pastoralists are almost all from the Fulani ethnic group and practice Islam; the farmers are from a non-Fulani ethnic groups and practice Islam and Christianity, though the violence is worst where the farmers are homogeneously Christian.  Each group sees the other as biased towards their own side for economic, cultural, and religious reasons.  Each group also sees their way of life as superior.  Farmers see nomadic life as outdated, backwards, and anti-progress; the pastoralists think that sedentary farming makes one weak.  One pastoralist commented to me that if he dropped off a sedentary adult and pastoralist child in the forest, the sedentary adult would depend on the child to survive.

Despite their cultural differences and competition for scarce land, mutual complementarity remains.  Pastoralists still have animal products -- though more farmers have bought animals in recent years, pastoralists still control roughly 90% of Nigeria's livestock [@icg2017nigeria] -- and farmers still have tubers, vegetables, grains, and the resultant crop residue.  The violence is extremely costly to both sides, so both have an incentive to avoid conflict.  Community leaders recognize that peace is in the interest of their communities, but many have been unable to prevent the violence.  In interviews conducted in 2016 and 2019 by @grady2020farmer, community leaders from farming and pastoral communities expressed their desire for peace between the two groups and blamed deviants from the other side for ongoing violence.  Farmers argue that the local pastoralists do not prevent other pastoralists who migrate through from destroying cropland, and pastoralists argue that farmers on the outskirts of the farming village encroach on grazing routes more each year.   <!--Both sides believe only they have a valid claim to the land -- pastoralists because they began grazing it before farmers sowed crops, and farmers because the government recognizes property rights of farmerse over pastoralists.-->

Peace between many farming and pastoral groups is prevented by a lack of trust (i.e. a commitment problem).  Both sides are better off cooperating peacefully than fighting, but neither side trusts the other to honor agreements that would prevent fighting.  The reasons each group does not trust the other side, however, is not that they believe the other side as a whole will defect on peace agreements, but rather that the farming group cannot credibly commit to preventing all farmers from expanding into grazing lands, and the pastoral group cannot credibly commit to preventing all herders from grazing cattle on croplands.  Their between-group commitment problem is driven by a within-group collective action problem because neither group trusts the other to punish their own.

The cause of mistrust between farmers and pastoralists -- deviants from both sides -- highlights that peace is a public good.  Peace benefits all members of a group, but contributing to peace is costly for group members because they must refrain from engaging in behaviors that benefit themselves at the expense of the outgroup.  Achieving peace, as with any public good, requires overcoming this collective action problem: the group must compel group members to contribute to peace despite the members' individual incentive to shirk and rely on others to bear its cost.  <!--What does it mean for a group to trust another group?-->One group trusting the other to honor an agreement, then, means not only trusting that a high proportion of outgroup members desire peace, but also that those outgroup members can and will compel less cooperative group members to honor a peace agreement [@fearon1996explaining].  Peace can be derailed by a few radicals who do not reflect the preferences of most group members [@sambanis2013social; @de2009effects].

## Resolving farmer-pastoralist conflict

Though conflict between farming and pastoral groups is common, not all farming and pastoral groups are in conflict.  Many communities overcame their trust problems and enjoy the complementarity of farming and pastoral lifestyles.  @grady2020farmer evaluated a contact-based intervention to reduce conflict between farmers and pastoralists.  They find that intergroup contact in which farmers and pastoralists collaborated to build boreholes and small infrastructure projects increased trust, voluntary contact between farmers and pastoralists, and feelings of physical security, relative to a control group.  They also found that the group members in treatment communities who directly participated in the contact intervention benefited more than group members who did not participate, but even the nonparticipants improved relative to the control group.  They speculate that the effects of intergroup contact diffuse to nonparticipants through social norms and social interaction, though they do not test their speculation in that paper.

Along with intergroup contact, communities that successfully navigated farmer-pastoralist tension generally have a noticeable commonality: an institution comprised of farmers and pastoralists to handle cases that threaten intergroup relations.  This institution can tap into ingroup networks to identify transgressors from each side, much like an ingroup policing institution [@fearon1996explaining].  In addition to the benefit of ingroup networks, these joint institutions have another benefit: since both groups are represented, neither the plaintiff, the defendant, nor their group can credibly claim that the case was decided unfairly due to group bias.  The collaborative nature of the institution helps curtail misperceptions, which can derail cooperative equilibria [@jervis2017perception; @wu1995cope; @bendor1991doubt].

These joint institutions function much like trial by jury.  Representatives from each group meet, hear from the case's "plaintiff" and "defendant", and decide an appropriate punishment.  For common occurrences -- crop damage, cattle rustling, and the like -- there may be something akin to a code of laws, such as a set cost per acre of cropland destroyed or head of cattle stolen.  In past decades, agreements between the traditional leaders of each community function similarly, by setting compensation for specific actions.  Conflict is often blamed on the breakdown of such institutions [@tonah2002fulani; @cotula2004land; @kuusaana2015land].

These joint institutions are themselves a peace agreement.  Each group has conceded some local autonomy and agreed to an overarching legal framework that will govern both farmers and pastoralists.  To do so, the groups must agree on several issues, like who serves on the joint institution, how they decide punishment, what is the range of acceptable punishments, and how punishments are enforced.  This type of agreement is only possible if both groups share a baseline level of trust.  Each group must also identify that the issue causing conflict between the two sides is a commitment problem, not a preferences problem.  Before an agreement like joint punishment institutions can be reached, the groups first need to learn enough about each other's preferences to establish that each prefers mutual cooperation to mutual fighting.  Put another way, groups need to solve their information problem before they can use joint punishment institutions to solve their commitment problem.  A key challenge, then, is for groups to signal their preferences.  Intergroup contact offers a means through which groups can send and receive those signals.

@grady2020farmer's evaluation of a contact-based intervention between farmers and pastoralists did not measure the extent to which the intervention affected institutional structures that govern intergroup relations, but they do recount anecdotes that suggest such institutions play an important role in conflict resolution.  They describe farmers and pastoralists who had participated in the contact intervention meeting to jointly decide an appropriate punishment for vigilante farmers who intended to harm pastoralists.  The would-be perpetrators, hailing from a nearby village, were noticed and arrested by the hometown farmers while on their way to steal the pastoralists' cattle.  Rather than decide unilaterally how to punish the vigilantes, leaders from the farming community called in leaders from the pastoral community to jointly decide a punishment.  Together the groups decided to disarm the vigilantes and let them go free without further punishment -- a solution proposed by the _pastoralists_.  Had the farmers unilaterally decided to let the vigilantes go free, the pastoralists may have interpreted the punishment as too lenient and accused the farmers of bias.  Since the pastoralists had a say in the decision-making process, however, the groups were able to build trust through cooperation.  The pastoralists appreciated the farmers calling a joint meeting, and the farmers appreciated the pastoralists magnanimity in proposing a lenient punishment.

They also describe a contrasting situation in which a farmers and pastoralists who had not participated in the contact intervention failed due to the lack of any joint institutions.  In that situation, both sides were participating in a public goods game in which money raised would be jointly administered by both groups.  These groups had no preexisting structure to handle situations that concerned both sides, and neither side trusted the other to hold the money.  The pastoralists claimed that the money would be squandered by the corruption of the farming community's leader if a farmer held it; the farmers claimed that the pastoralists would migrate away with the money if a pastoralist held it.  In the end, the groups agreed that the NGO administering the public goods game would hold the money and disburse it in chunks when the pastoralist leader and the farming leader agreed on its use.

In this section, I discussed farmer-pastoralist conflict in Nigeria, focusing on causes of violence and solutions that groups developed to curtail violence.  In the next section I outline several policy implications that follow from the farmer-pastoralist example and from thinking about group conflict in the bargaining and identity perspectives.


# Policy Implications for Peacebuilding Programs

I will discuss six policy implications from farmer-pastoralist conflict and the bargaining and identity perspectives. I also discuss some consequences of these implications.  The implications are: (1) peace is not intrinsically preferable to fighting; (2) preferences for cooperation over fighting do not guarantee peace; (3) groups are collections of individuals, not unitary actors; (4) misperceptions are a major threat to peace; (5) there is not one solution to group conflict; and (6) some attempts to alleviate group conflict can backfire.

<!--1-The first policy implication is that groups will only cooperate when it is in their interest to do so. -->
The first policy implication is that peace is not intrinsically preferable to fighting.  Some groups fight because the group members want to fight.  No information or signaling will reduce conflict in these cases because the groups' preferences are misaligned.  In those cases, the first step to peace is each side coming to believe that cooperation is superior to peace.

<!--1a: comparative advantage -->
The best chance for groups to identify that cooperation is in their material interest are distinct group-based comparative advantages.  Farmers and pastoralists each have group-based comparative advantages -- farmers in produce, pastoralists in animals -- that make identifying a shared interest easy.  Though cultural differences may seem like a hindrance to peace, these groups have much to gain from cooperation.  Two groups of farmers have little to offer each other that the groups could not obtain on their own, so there is less room for complementarity.  In general, increasing gains from cross-group interaction, and therefore increasing the opportunity cost of fighting, is most likely to deter conflict [@rohner2013war].

<!--1b: psych and social value -->
Material interest is not everything, however, and many motivators for preferences are psychological and social.  Groups may prefer fighting due to psychological and social rewards and penalties.  Group members may resist peace if it sacrifices self-esteem and self-image.  Some segment of each group may embrace fighting because it offers them the opportunity to garner social rewards.  These costs and benefits can modify preferences so that there is no peace agreement each side prefers to fighting.  Changing attitudes and norms can reduce the costs of peace and the benefits of fighting.  Attitude and norm change can potentially be motivated by showing the groups that they can better accomplish their goals through cooperation than conflict [@grady2020lab].


<!--2nd: preferences for cooperation do not guarantee peace -->
The second policy implication is that preferences for cooperation over fighting do not necessarily end group conflict, and therefore policies that promote peace must assure each side that the other will cooperate.  Even if both groups prefer mutual cooperation to mutual defection, lack of information about the other side's preferences and an inability to commit to cooperate can prevent peace.  Cooperation is only in a group's interest if the other group also plans to cooperate.  The easiest way to assure each side that the other will cooperate is to impose external punishment for defection or external reward for cooperation.  That method of assurance, however, is not available in many contexts and does not build the intergroup trust necessary for cooperation once the external punishment mechanism is removed.  It may nonetheless serve as a short-term solution to reducing group conflict and as a starting point for group cooperation.

In the absence of external rewards and punishment, intergroup contact in which groups achieve a joint goal can show both groups that cooperation is in their interest and that the other side also sees that.  The other side can be trusted to do what is in their own interest.  Intergroup contact also brings group members into close personal contact, which offers opportunities for learning and costly signaling.

These first two policy implications suggest that contact-based programs where the groups do not work towards a joint goal, like discussion forums, may have no effect on group conflict.  Discussion forums do not directly change preferences; nor do they provide credible information about the other side's preferences.  It is possible that this minimal form of contact could reduce perceptual biases by exposing each group to the other's view points, but they mainly seem to be avenues for "cheap talk" which both sides will discount.


<!--3rd: groups are collections of individuals, not unitary actors -->
The third policy implication is that groups are collections of group members and the preferences of the group should not be taken as the preferences of each group member.  Group members' preferences are likely correlated with the preferences of the amorphous "group", but they also deviate in important ways.  For example, the group as a unitary actor does not face a collective action problem, but the group as a collection of individuals does because each individual wants to rely on others to provide public goods.  An important attribute of a group, then, is its capacity to compel group members to contribute to the public good of peace.  Group's with the power to compel will be better at fighting because they can compel group members to participate in violence [@bornstein2003intergroup] but should also be more able to credibly commit to preventing their own from defecting.

Thinking of the group as a collection of group members also highlights (a) the psychological and social factors that make conflict attractive and (b) the perceptual and cognitive biases that color groups views of each other.  These types of individual-based factors are not readily apparent when thinking of the groups as homogeneous units, but they likely contribute to group conflict.  They may also systematically cause some group members to benefit more from peace than others, so peace as a public good is not equally valuable or desirable to all group members.  The group is a useful but limited unit of analysis because it can only influence group conflict through its effect on group members.


<!--4th: misperceptions are a major threat to peace. -->
The fourth policy implication is that misperceptions are a major threat to peace.  It is easy to focus on changes to payoff structure and changes to the value of resources under dispute as the driver of conflict.  In the farmer-pastoralist example, we readily blame population booms and land scarcity for the recent surge in violence, and these factors no doubt precipitated that surge.  However, they do not necessarily result in group conflict unless they reduce the bargaining range to zero.  They may instead cause conflict by creating the misperception that the other side now prefers fighting for the chance to control all of the land to cooperating to share the land between the two groups.

Misperceptions are also a significant cause of information and commitment problems.  If groups desire peace, the perception that the other side does not desire peace can prevent cooperation.  Once groups are cooperating, misperceiving cooperation as defection can cause a series of defections.  Any institution that limits such misperceptions should help maintain peace.


<!--5th: there is not one solution to group conflict -->
The fifth policy implication is that there are many ways to resolve group conflict, so practitioners should not be wed to one ideological idea about reducing group conflict.  As long as the solution allows for credible commitments to cooperation, credible sharing of information, and groups' preferences to be aligned, conflict can be resolved.  The means to accomplish each of these goals are likely to differ across contexts and depend on characteristics of the group conflict.  By being wed to one ideological approach instead of assessing the situation, the solution may fail.


<!--6th: attempts to solve group conflict can easily backfire -->
The sixth policy implication is that attempts to resolve group conflict can backfire and cause or exacerbate group conflict if they do not address preferences, commitment problems, and information problems.  Contact programs, for example, could easily be mismanaged in such a way that works against cooperation.  First, the groups may fail to achieve the goal, which could cause scapegoating and reinforce the perspective that cooperation with the other side is a waste of time.  Second, the joint goal may not benefit both sides equally.  <!--The group's are likely comparing their gains relative to the gains of the outgroup, and any disparity could ruin chances for peace.  -->Differing gains can _cause_ a commitment problem and violent conflict because the group gaining less has an incentive to fight _now_ before the other side gets stronger.  The side gaining more cannot credibly commit to a deal based on today's balance of power when their power will increase tomorrow.  Third, contact might be sabotaged by not involving influential members of each group or by involving members of each group who have the least to gain from peace.

Programs that incentivize cooperation by imposing external punishment or reward can also backfire.  Third party punishment could undermine each group learning that the other prefers peace to fighting because each group's cooperation might be due to fear of punishment that disappears when the third party leaves.  Any program imposing external carrots and sticks for cooperation should combine that approach with a way for group's to benefit from cooperation in a way that does not depend on the external incentives.

Programs that do not explicitly seek to reduce group conflict can also cause of exacerbate group conflict.  First, any program that adds resources to an area afflicted by ongoing conflict runs the risks of those resources being captured by the conflicting groups [@findley2011localized].  Second, programs designed to increase economic well-being and increase the value of land can make land worth fighting for; they can also upset traditional agreements that govern punishments for destroying crops, as in the farmer-pastoralist case.  And third, aid programs can crowd out local employment opportunities and local institutions for conflict management, which will be needed when the aid program ends.


# Avenues for Future Research

This paper sought to show how combining two perspectives on group conflict, the bargaining perspective and the identity perspective, can provide a better understanding of the causes and consequences of group conflict.  Doing so reveals several avenues for future research.  The first avenue is to synthesize models of group conflict from the numerous disciplines that study it, as this paper attempts to do.  Group conflict is an interdisciplinary research topic with scholarship in political science [@lopez2017determinants], economics [@kimbrough2017war], psychology [@bohm2018psychology], management science [@mccarter2018models], biology [@rusch2017logic], and evolutionary anthropology [@glowacki2017evolutionary].  Each discipline emphasizes different causes and consequences of group conflict.  More attempts at synthesis of these distinct perspectives could provide insights into causes of conflict and more effective methods to reduce it.

The second avenue is to further consider the role that collective action problems play in group conflict.  As we saw with farmer-pastoralist conflict and as has been written about by @fearon1996explaining and @sambanis2013social, among others, peace can be derailed by a small set of group members who refuse to "play ball" with the other side.  Without the ability to compel cooperative behavior from group members, groups cannot credibly commit to honor negotiated agreements.  This points to within-group collective action problems as the driver of some between-group commitment problems.  Peace is a public good: group members must forego behaviors that benefit them individually for peace to be achieved, but once achieved all group members enjoy its benefits whether or not they bore its costs.  

Overcoming collective action problems is notoriously difficult.  In the case of intergroup conflict, collective action problems may be even more difficult to solve because costs must be born before benefits are obtained, and group members may be killed in the meantime and thus never enjoy the benefits of their sacrifice.  Individuals are notoriously bad even at saving for retirement, where they can sacrifice now to benefit themselves later in a low-risk environment [@benartzi2013behavioral; @warner2001personal].  Individuals may rationally discount future payoffs quite significantly in conflict settings where individuals may never see the future and the benefits accrue to a group.

Bornstein (@bornstein1992free and @bornstein2003intergroup) was among the first to consider how groups dealt with the preferences of individual group members in the context of group conflict.  His focus, and the focus of most subsequent scholarship, was how groups encourage group members to participate in violence against the other side, since winning the fight benefits all group members but only group members who fight bear the costs.  Most literature about collective action problems in conflict is thus concerned with each group's attempt to compel group members to _fight_ the other side or resist external pressure; relatively little has been written about each group's attempt to compel group members to _cooperate_ with the other side [@keefer2012follow; @kaplan2010civilian; @rubin2020rebel].

Implicit in the discussion of collective action problems is that groups are made up of individuals with preferences that differ from the group.  Following that logic, war may not be equally costly to all members of society, and peace not equally beneficial.  The public good of peace is more beneficial for some group members than for others.  In the case of farmers and pastoralists, farmers on the outskirts of the community bear the brunt of "defections" during peace time, so peace may not be more costly than war for them.  If group elites bear few costs from conflict and may suffer in prestige from peace, they could resist peace agreements.  More scholarship should consider who bears the costs of conflict and who stands to benefit from peace.

A third avenue for future research is to study the manner in which groups solve their own commitment problems, with an eye to the within-group collective problem as the driver of the between-group commitment problem.  @fearon1996explaining showed that ingroup policing, an institution wherein groups punish their own miscreants, can help groups avoid an escalation of violence.  They credit the relative paucity of group conflict to such institutions.  Ingroup policing is an excellent example of within-group institutions that prevent violence from escalating and for maintaining peace in many contexts.  

Consideration of perceptual biases and mistrust between groups in or with a recent history of conflict indicates a potential limitation of ingroup policing.  With ingroup policing, groups are restrained from overly lenient punishment of their own people by the threat of violence escalating if either group suspects the other of acting in bad faith.  Since ingroup policing depends on the perceptions of group members, if those perceptions are biased such that members of each group suspect the other is trying to take advantage of the ingroup policing institution, then the institution could break down as each group does not trust the other to allocate sufficient punishment to their own side.  The risk of cooperative behavior being misperceived as uncooperative behavior is one of the main threats to enduring peace [@jervis2017perception; @wu1995cope; @bendor1991doubt].  Groups could account for the biases of the other side and harshly punish their own to overcome the bias, but overly harsh punishments could reduce the legitimacy of ingroup policing among the ingroup.  Future research should examine how misperceptions caused by biases like motivated reasoning and reactive devaluation affect the ingroup policing equilibrium.
<!--The ingroup could of course account for this bias and assign even harsher punishments to ingroup defectors, but those excessive punishments may reduce support for ingroup policing because group views the punishment as disproportionate to the crime. -->

If ingroup policing is unsustainable due to psychological biases, future research should also consider how to modify that institution to minimize and manage the misperceptions that result from those biases.  A starting point could be the collaborative "joint-punishment" institutions used by some farming and pastoral groups to control their conflict.  These institutions tap into ingroup networks to identify wrongdoers, like ingroup policing, but involve both sides in the punishment decisions to increase transparency.  They may also open up more lenient punishments, as neither group has to worry that the other will misperceive a lenient punishment as defecting from the agreement.  Compared to ingroup policing, however, a joint-punishment institution is likely more difficult to initiate.  Ingroup policing can be implemented by each group alone, whereas a joint structure requires many agreements about the structure's composition, decision-rules, and enforcement capacity.

The fourth avenue for future research is to use the bargaining and identity perspectives to develop mechanisms through which conflict can be resolved, and then to test those mechanisms in lab and field experiments.  One promising method to reduce conflict is intergroup contact, but, to my knowledge, no contact-based intervention has explicitly considered contact as a method to solve information and commitment problems. Contact programs are beginning to be tested between groups in or with a history of conflict, including Nigerian farmers and pastoralists [@grady2020farmer], Christians and Muslims in Iraq [@mousa2018overcome], and Jewish and Arab-Palestinian youth in Israel [@ditlmann2016can], but these programs have thus far focused more on causal inference (does contact work in these contexts) than causal mechanisms (how does contact work in these contexts).  Contact-based interventions would benefit from considering how contact solves information and commitment problems that cause conflict.

Based on the bargaining and identity perspective, intergroup contact may reduce group conflict through the achievement of a joint goal.  From this viewpoint, the key mechanism is goal achievement and without it contact will not improve attitudes or reduce conflict.  Traditionally, goal achievement is thought to "further [the] process" of attitude change, but is not necessarily central to it [@pettigrew1998intergroup, p.66].  To my knowledge, only one lab experiment has tested the effect of intergroup contact when it does or does not achieve a joint goal [@grady2020lab].  More experiments should test this mechanism with different types of group dynamics and in more contexts.

Another mechanism to reduce group conflict is to increase the utility of peace, be it materially (i.e. financial benefit) or non-materially (i.e. alignment with values).  Increasing peace's utility can solve the preference problem if one exists, but it could also solve the information problem if each side believes the preferences of the other group have changed.  I suspect increasing peace's material utility is best for solving information problems because each side is more likely to believe the other is motivated by material outcomes than non-material outcomes ("If they had those values, why are they fighting us now?").  Future research should test the efficacy of different means to increase the utility of peace.  

Interventions that reduce psychological and cognitive biases against the outgroup should also help groups solve information and commitment problems.  Along with testing the efficacy of reducing these biases, further research should test the best means through which such biases can be reduced.  Intergroup contact is one method, but it may be difficult to implement in very violent contexts or in contexts with strict segregation.  Vicarious intergroup contact -- contact in which members of each side observe ingroup members interacting with outgroup members -- could reduce biases in these contexts.

The last avenue for future research I will discuss is how group dynamics moderate the effect of interventions meant to reduce group conflict.  @fearon1996explaining noted that group size changes effective strategies for deterring group conflict: large groups can use the threat of intergroup conflict to incentivize the cooperation of a small group, and small groups use ingroup policing to avoid the wrath of the larger group.  Size and power disparities might influence conflict-reduction interventions in other ways.  The smaller group, for example, is likely to interact more frequently with the larger group than the larger group interacts with the smaller group.  Contact-based interventions may therefore have little effect on members of the smaller group, who have much personal experience with members of the larger group.  Group dynamics other than size and power disparities could similarly change strategies to reduce group conflict, such as the homogeneity and hierarchy of each group and the centralization or decentralization of power within each group.  Future research should investigate how these group dynamics affect the types of institutions that groups develop to alleviate conflict, and should determine which type of interventions are most effective in each context.




# References