---
title: "Untitled"
author: "Chris Grady"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--
- Order of paragraphs.  
    - Say contact works in all these contexts.  
    - Say we don't know about contact in violent contexts.
    - Then say conflict poses difficult challenge because might prevent mechanisms + mechanisms & common thread + why they could be prevented.
    - Then say reasons for optimism?

************

chris: Need a paragraph about recent, personal, and heinous grievances both sides have.  That’s the difference between ecpn and other studies.

DIFFERENCE: (1) programmatic intervention using contact in place where people killed.  (2) among active participants and victims of the conflict, not just people who belong to groups in conflict.  Negative and salient personal experiences that define the outgroup.

need more psych mechanisms.  confirmation bias? anchoring? continued examples of the other side being bad.  Have to differentiate the bad/good?  No, have to actually decrease the amount of bad stuff.

Cognitive dissonance: need it for attitude/behavior change (Gubler).  Therefore need experiences that override prior beliefs.  Contact can provide positive experiences that are dissonant with pre-existing beliefs.  But if you continue to have experiences that justify pre-existing negative beliefs, attitude/behavior won't change because it is reinforced.  At best, contact in this environment will lead you to differentiate the "good" members from the wider group; they will be thought of as atypical.  (2) And if the new experiences/attitude change causes us to rethink self-concept/directly challenges us, more likely to reject new experiences to resolve dissonance.  Many of these group members have done things bad, cruel, or harmful to the other side.  Justified if the other side is bad; challenges self-concept if the other group is okay.  Very difficult to change attitudes from negative to positive if I have personally used my negative attitude to justify a bad thing.

cognitive dissonance works in conflict or not, but stronger directly proportional to the motivation.  How central is the attitude that the other side is bad -- strongest when an active participant in conflict.

Behavior changes attitude: once you do something, it's hard to adopt an attitude that your behavior was wrong.  Much easier to change attitudes that you have minimally acted on compared to an attitude when you burned down someone's house based on that attitude.


leads to motivated reasoning, confirmation bias; exacerbated by anchoring.  contact has to JAR someone enough to change their mind.  The amount you need to be JARRED depends on how much value you are deriving from current belief.  Changing mind == + future benefit from accuracy - cost of value from current belief.

Contact good at overriding false information.  You think X about the other group.  You interact with the other group and learn that X is wrong.  But what if you interact with the other group and X is wrong for then, but then you see other members of that group do X to your neighbor.

************

"First study to test contact-based intervention with people actively involved in the conflict.  Not just people who belong to groups in conflict, but with people have recent, personal, and heinous grievances against the other side.  Members of village been killed, etc, neighboring villages have been burned down and abandoned.  Neighboring ruga has been slaughtered.  Many salient grievances attributed to the other side and that define the group.  Would not expect contact to override these personal experiences and redefine whole group.

38% had a family member injured or killed in the conflict.  Only 40% were not personally affected by violence, be it a family member injured or killed, property damaged, or forced to leave home.  Median number killed in last clash was 10.  Also affects attitudes about the entire group: 70% at baseline say trust only 1-2 on 1-5 scale. 61% completely uncomf with intergroup marriage, less than 5% completely comfortable.  Share a meal: 33% comp uncomf, only 6% completely comf. ~75% fearful when farming/grazing/livelihood.

Lots of long-term intractable conflicts have hatred reinforced by social norms.  But in few have so many persons or their close friends/family members been directly harmed.  Something bad has happened to these people and their neighbors."


chris: need to emphasize things necesary for contact to change attitudes towards whole other group.  (1) generalize experiences in positive contact to whole group, (2) disaggregate group.

-->
# Introduction

How can groups in conflict improve intergroup relations?  Violent group conflict has caused 2 million deaths since the year 2000 [@ucdp], forcibly displaced over 70 million people from their homes in 2018 [@unhcr2019], threatens food supplies in numerous countries [@verwimp2012food], and extracts a psychological toll on participants and victims (Schomerus and Rigterink 2018).  Intergroup animosity perpetuates conflict long after the original grievance is immaterial or forgotten [@mcdonnel2017graze; @deutsch1973resolution; @tajfel1979integrative], so improving intergroup relations is vital to stem the human, economic, social, and psychological costs of violent group conflict.

Scholars and practitioners consider _cooperative_ intergroup contact -- contact in which members of two groups work together to achieve common goals -- to be one of the most effective tools for improving intergroup relations.[^coopCon]  Evidence for the hypothesis that contact improves intergroup relations, known as the contact hypothesis [@allport1954prejudice], goes as far back as the 1950s and motivated integrated public housing [@deutsch1951interracial] and workplace and school desegregation [@cook1971race; @cook1985experimenting] in the United States.  More recent studies demonstrated the prejudice-reducing effects of contact by leveraging random assignment to college dorms [@marmaros2006friendships], college roommates [@burns2015interaction; @boisjoly2006empathy; @van2005effect], schools [@rao2019familiarity.], U.S. Air Force groups [@carrell2015impact], mixed sports teams [@ditlmann2016can; @mousa2018overcome], job training programs [@scacco2018nigeria], and medical doctors [@weiss2019curing].  The contact hypothesis also increasingly motivates policy interventions, especially peacebuilding programs [@ditlmann2017addressing; @lemmer2015can].  

[^coopCon]: We will use the term _cooperative contact_ to refer to contact that meets Allport's conditions.  Those conditions are (1) intergroup cooperation (2) with equal status (3) to achieve shared goals (4) with support of local authorities.  Note that _equal status_ does not mean that the groups must have the same status in society, but that the groups share equal status in the cooperative situation.  Cooperative contact stands in contrast to other forms of incidental or unstructured contact that may not have positive effects on intergroup relations.

<!--chris: could combine this paragraph with another.  Also, need to frame differently.  Not quite true that the difference between my study and others is the violent conflict.  Arab/Jew is a violent conflict.  Farmer-pastoralist is different in some other way. -->
Despite contact's many successes, scholars know little about the effects of contact-based interventions for people actively participating in and personally victimized by a violent conflict, or even for interventions directed at improving adults' attitudes towards racial or ethnic groups [@paluck2019contact].  Cooperative intergroup contact has only recently been tested in the field, and never programatically with communities who are currently perpetrating violence against each other.  If one of the goals of cooperative contact is to mitigate violent conflict, then contact-based interventions must be tested between participants and victims in violent conflict.

<!--chris: alternative below paragraph (2-23-2020).
Ongoing violence poses the most difficult test for contact.  Improving attitude requires cognitive dissonance and the rejection of preexisting negative beliefs in favor of the new dissonant positive belief.  Personal participation and victimization in an ongoing conflict provides (1) experiences that confirm rather than refute the existing negative belief and (2) provide strong motivation to maintain negative beliefs to justify unfair or even harmful behavior to the other side.  Very difficult to change outgroup attitudes from negative to positive if outgroup continues to do bad things to me and if I have personally used my negative attitude to justify doing a bad thing.

Contact good at overriding false information.  You think X about the other group.  You interact with the other group and learn that X is wrong.  But what if you interact with the other group and X is wrong for then, but then you see other members of that group do X to your neighbor.
-->

Ongoing violence poses the most difficult test for contact and could interfere with mechanisms through which contact improves relations. The mechanisms through which contact improves relations assume that negative attitudes result from unfamiliarity, and that "familiarity breed[s] liking" [@pettigrew2006meta p.766].  We posit that familiarity through cooperative contact allows groups to identify latent shared interests by providing positive interactions towards achieving a shared interests. Those positive interactions counter existing negative beliefs and create cognitive dissonance.  Attitudes improve when that cognitive dissonance is resolved by rejecting negative beliefs rather than justifying negative beliefs [@gubler2013humanizing].  However, by reinforcing negative beliefs and obscuring shared interests, violent conflict could dull, prevent, or even reverse the predicted positive effects of contact.

<!--chris: whole paragraph too theory-y
Moreover, cooperative contact between some ingroup members and some outgroup members can only meaningfully improve group relations under two conditions.  First, group members must generalize their positive attitudes to the outgroup as a whole and if the effects of contact must diffuse to other ingroup members.  Attitudes generalize when the outgroup members involved in contact are viewed as typical of the outgroup [@hewstone1996contact] and diffusion primarily occurs through changing social norms about cross-group interaction [@paluck2009jsp; @christ2014contextual].  In contexts of ongoing violence, any cross-group interaction may mark an outgroup member as atypical, and social norms may stay staunchly opposed to intergroup cooperation.-->

<!--Something about cognitive dissonance here? -->
Despite these reasons for caution, there are reasons to expect cooperative contact to improve intergroup relations even in contexts of ongoing violence.  Even in contexts of group violence, it is often in each group's shared interest to reach a peaceful compromise because fighting is costly [@fearon1995rationalist].  Cooperative contact to achieve a common goal provides groups with an example of cooperation towards a shared interest, and that experience can make groups imagine future interactions for shared benefit.  Cooperative contact can also remove the psychological barriers to identifying shared interests, such as stereotypes and feelings of threat and anxiety.  Lastly, cooperation that benefits the group should generate group pressure to cooperate, thus creating cooperative social norms.

To learn about whether cooperative contact can improve intergroup relations amidst violent group conflict, we conducted a field experiment with conflicting farmer and pastoralist communities in Nigeria.  More than an occupational difference, farmers who cultivate crops and pastoralists who graze cattle define a major social cleavage in many parts of the world.  These groups conflict over land rights, which define both of their livelihoods.  Farmer-pastoralist conflict has escalated throughout the Sahel in recent years, and nowhere more than in Nigeria.  The most recent conflict escalation has caused 7,000 deaths from 2014-2019, displaced hundreds of thousands of people from their homes, and costs $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria].<!--don't need to cite news articles like this. you can give an address / identifier / link /etc in a footnote -->  In our sample, some members of each community had been killed by members of the other community in the year before the project began.  Ongoing violence, occupational and ethnic differences, and fighting over resources necessary for livelihoods all make this context a hard test for contact theory.  

We randomly assigned communities with ongoing farmer-pastoralist violence to receive a contact-based intervention or serve as a control group.  The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.^[The communities built boreholes, market stalls, and primary health care facilities, for example.]  The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.  To measure the effects of the intervention, we conducted pre- and post-intervention surveys, a post-intervention natural public goods behavioral game,[^PGG] and twelve months of systematic observations in markets and social events during the intervention.

[^PGG]: In a public goods game (PGG), research subjects are given money and told they can keep the money or donate it to a public fund.  Money donated to the public fund is multiplied by some amount and then shared with all subjects.  Our PGG is _natural_ because it was conducted in a natural setting, rather than a lab.  The funding for the PGG came from the National Science Foundation under Grant No. 1656871.

<!-- Findings. -->

We find that the program increased intergroup affect, intergroup contact outside of the intervention, and perceptions of physical security.  We see signs of the positive effects in fieldwork as well as in data: in one of the treatment sites, farmers defended pastoralists from a group of anti-pastoralist vigilantes, rather than assist the vigilantes in removing the pastoralists and claiming their land.  Our results also show that the intervention affected communities as a whole, not just community members directly involved in the intergroup contact.  Individuals who directly engaged in intergroup contact changed the most positively from baseline to endline, but we also observe positive spillovers of trust to group members for whom we did not exogenously increase intergroup contact.

This study expands our knowledge about group conflict in two main ways.  First, this study teaches us about the capacity of intergroup contact to improve intergroup relations and reduce conflict.  Peacebuilding organizations implement numerous contact-based interventions in violent contexts each year, but its efficacy to improve intergroup attitudes amid real-world conflict is an open question [@paluck2019contact; @ditlmann2017addressing].  To our knowledge this is the first field experimental test of a contact-based peacebuilding intervention implemented during an active conflict.  The results suggest that contact-based peacebuilding programs can effectively improve relationships between conflicting groups and is especially relevant to conflict resolution in the cases of intergroup and intercommunal conflicts.

Second, we contribute to the literature about informal structures, such as social norms, in solving commitment problems.  Many scholars have identified group conflict as a commitment problem that is most likely to be solved by an outside actor enforcing commitments [@fearon1994ethnic].  While strong outside actors can resolve confict by solving commitment problems, this study suggests that they are not a necessary condition for resolving conflict.  Many communities in our treatment group significantly improved their relations without a strong actor to enforce commitments.  Our results suggest that cooperative intergroup contact helped groups strengthen their own conflict resolution structures.

<!--chris comments to self:

need to make theory section 1-2 paragraphs, not 3.  a para why it might not work, one para being very general about why it could work by helping groups identify shared interest, helping groups establish joint structures to mitigate conflict, ameliorate psych and social biases against outgroup, others. 

-->