---
title: "Improving Intergroup Relations Amid Group Conflict: An Intergroup Contact Field Experiment in Nigeria - Context"
author: "Christopher Grady"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Key points
<!--
- Brief Nigeria's Middlebelt
    - In recent years, violent conflict between farming and pastoral occupational groups have ravaged the region.  More than an occupational divide: cultural, ethnic, can be religious (Pastoralists are almost universally Muslim, farmers are a mix).  
    - farmers and pastoralists both need access to land for livelihoods.  The most recent conflict escalation, beginning roughly in 2014, has caused 7,000 deaths, displaced hundreds of thousands of people from their homes.  Economic damage unknown, but farmer-pastoralist conflict before the escalation costs Nigeria $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria].  Threatens Nigeria's food supply, since the Middle Belt is Nigeria's "food basket" and a key source of products like beef, dairy, yams, and cassava (https://qz.com/africa/1315749/nigeria-herdsmen-farmer-attacks-are-damaging-agriculture-economy/).  This violence has impeded food production and threatens to create a food shortage (Hailemariam 2018).
    - Before the latest surge in violence, the conflict was costing the Nigerian economy $13.7 billion a year (McDougal et al. 2015).
    - pop booms, migration, gov policy driving conflict
- lots of reasons contact might not be successful; trends pushing groups apart.
    - active & escalating conflict
    - fighting over livelihood resources
    - misaligned incentives with regards to those resources: Pastoralists want to graze, farmers do not want them to graze.
    - different ethnic groups and ways of life, often differ religious values
    - government favors one side
    - dehumanizing effects of killing other group
- Contact not change any of these causes of conflict; things that cause conflict also cause negative intergroup attitudes.
- Not completely misaligned interests.  Some complementarity, formerly working together: 
    - peace is in everyone's interest because fighting is costly.  Destroyed crops, stolen cattle, burned homes, murdered neighbors, constant fear and insecurity.
    - farmers have vegs/grains and need meat/milk.
    - farmers need manure and pastoralists need cow feed
-->
# Context: Farmer-pastoralist conflict in Nigeria's Middle Belt

Nigeria's Middle Belt is plagued by violent conflict over land use.  Farmers, who claim land for agricultural production, and pastoralists, who claim land for animal grazing, increasingly clash over claims to the same land.  Both groups depend on land for their livelihoods, but their divide is also cultural, ethnolinguistic, and, in some locations, religious.  The pastoralists are almost homogeneously of the Fulani ethnic group, speak Fulfulde as their primary language, and practice Islam.  They maintain a semi-nomadic way of life, belonging to a home community but traversing vast distances to secure access to pastureland and water as seasons change.  The farmers live in sedentary villages and exploit land for agriculture.  The ethnic group, language, and religion change by village.  In our study, farmers came from more than a dozen ethnic groups, often residing in the same village.

Historically, these communities cooperated through trade and sharing land that was abundant relative to populations.  Pastoralists would graze their animals on crop residue after harvests and follow migration paths away from farmland during planting seasons.  The groups were complementary: pastoralists gained food for their animals and farmers gained animal manure/urine to replenish soil; farmers bought milk and meat from pastoralists and pastoralists bought grains and vegetables from farmers.  There were tensions, but these were typically overcome by negotiation and violence seems to have been rare.  The Middle Belt came to be known as Nigeria's "food basket" due to the abundance of foodstuffs coming out of the region, like beef, dairy, yam, and cassava^[https://qz.com/africa/1315749/nigeria-herdsmen-farmer-attacks-are-damaging-agriculture-economy/].  

In recent years, this relationship has been stressed by populations booms and climate change.  Nigeria's population at independence in 1960 was about 50 million; Nigeria's population in 2019 is estimated around 200 million.  At the same time, the Sahara's size expanded over 10%, decreasing land available for farming and grazing [@thomas2018sahara; @okpara2015conflicts].  As the number of farmers, pastoralists, and mouths to feed increased, the amount of land available to produce food declined.  These factors also pushed pastoralists southward, towards farming communities with whom the pastoralists had no pre-existing relationship.  Land scarcity and new migrants jeopardize traditional cooperative agreements that have managed farmer-pastoralist interactions for decades [@cotula2004land; @kuusaana2015land].  Sharing land is easier when people are scarce and land is plentiful; it is not so easy when land is scarce and people are plentiful.

Government policies exacerbated the issues caused by demographic and geographic changes.  Land privatization encouraged farmers to plant crops that occupy land continuously, like orchards, and effectively nullified farmer-pastoralist land sharing agreements [@bassett2009mobile].  Official cattle reserves for moving herds are rarely enforced by the government, leading farmers to plant crops in once-protected areas and further limiting pastoralists’ available grazing space.  The “indigene versus settler” policy limits economic and political rights to certain ethnic groups in each state, often denying the "settler" pastoralists the ability to own land and run for political office [@nigeria2014freedom].

These stressors have sparked violent conflict between farmers and pastoralists in recent years [@fa2019deadly]. The most recent conflict escalation, beginning roughly in 2014, has caused 7,000 deaths [@council2019nigeria] and displaced hundreds of thousands of people from their homes [@daniel2018anti; @nyt2018nigeria].  The scale of economic damage is unknown, but farmer-pastoralist conflict _before_ this escalation cost Nigeria $13 billion annually in lost economic productivity [@mcdougal2015effect].  This violence has impeded food production, leading to an impending food crisis [@fa2019deadly; @frontera2018nigeria; @unah2018nigeria].  Compounding matters, state governments' response to the conflict has been to enact anti-grazing laws.  These laws spark more violence because many pastoralists reasonably viewed the law as biased against their way of life.  In the state of Benue, the government mobilized state-sanctioned vigilante groups called "livestock guard" to enforce the law, but the livestock guard have sometimes sought out pastoralists, rather than guard farmland [@duru2018court].

Though we have discussed the conflict as between two large and cohesive groups ("Farmers" and "Pastoralists"), the conflict occurs between numerous small, independent farming and pastoral groups.  The groups typically reside a couple miles from each other -- like people from the next town over.  These independent groups are aware of the broader context of farmer-pastoralist conflict, but their concerns are local and mostly unrelated to what happens in distant villages.  Different versions of the same story initiate and sustain the local conflicts.  First, cattle graze on farmland.^[In past decades, compensation for crop damage would have been standardized, but these traditional agreements have fallen apart in recent years [@cotula2004land; @kuusaana2015land].  With no agreed upon compensation and no authority to punish illegal grazing or illegal cattle rustling, groups take justice into their own hands.]  Next, a farmer retaliates by stealing cattle from the pastoralists (because the farmer does not know _which_ herd grazed on his land, the stolen cattle do not necessarily come from the transgressing herd).  This cycle continues and eventually explodes when a member of one side physically attacks a member of the other side.  From there, a little war often breaks out.  As one reporter noted, "The countryside is littered with the charred ruins of homes, schools, police stations, mosques and churches." [@mcdonnel2017graze].

<!--1-2 paragraphs about this being tough test for contact theory.
- lots of reasons contact might not be successful; trends pushing groups apart.
    - fighting over livelihood resources
        - misaligned incentives with regards to those resources: Pastoralists want to graze, farmers do not want them to graze.
    - active & escalating conflict
        - dehumanizing effects of killing other group
    - different ethnic groups and ways of life, often differ religious values
    - government favors one side
- Contact not change any of these causes of conflict; things that cause conflict also cause negative intergroup attitudes.
- Not completely misaligned interests.  Some complementarity, formerly working together: 
    - peace is in everyone's interest because fighting is costly.  Destroyed crops, stolen cattle, burned homes, murdered neighbors, constant fear and insecurity.
    - farmers have vegs/grains and need meat/milk.
    - farmers need manure and pastoralists need cow feed
-->
Farmer-pastoralist conflict poses a tough test for intergroup contact to improve group relations.  The material, social, and psychological incentives of these groups are opposed.  They want the same land for different purposes and their livelihoods depend on that land.  The groups are involved in a bloody, violent, and escalating conflict for land in which thousands of farmers and thousands of pastoralists have been killed by members of the other group.  Within an individual's community, several people will have been attacked or killed; several others have attacked or killed members of the other side.  To justify killing, groups create collective myths about the retaliatory/defensive nature of their belligerent action and the iniquity and inhumanity of the other side.  Despite their physical proximity, the groups have little to bond over; they are distinct culturally, ethnically, linguistically, and often religiously.  And finally, government favoritism of farmers over pastoralists creates a power disparity between the groups.

<!--One para on why it could still work. -->
Despite the forces pushing these groups into conflict, their interests are not completely misaligned.  Peace is in the interest of both groups because fighting is costly, both materially and psychologically.  The conflict has destroyed billions of dollars in agricultural produce, animal products, and physical infrastructure.  Crops have been destroyed, cattle stolen, homes burned, and neighbors murdered.  Farmers fear violence when working in their fields; pastoralists fear violence when grazing their cattle.  Peace can end the economic, social, and human costs.  Moreover, the groups formerly maintained mutually beneficial trade agreements: farmers trade the crop residue left on their fields for animal manure/urine to replenish soil; farmers traded grains and vegetables in exchange the pastoralists' milk and meat.  Peace rekindles the possibility of these mutually-beneficial trade agreements.  Cooperative intergroup contact should improve group relations by revealing these shared interests.

<!--One paragraph relating Nigerian conflict to other parts of the world conflicts.  Include Roma. -->
Farmer-pastoralist conflict is not confined to Nigeria's Middle Belt.  Farmer-pastoralist clashes are a persistent problem throughout the Sahel and savanna areas of Africa, including Mali, the Ivory Coast (Bassett 1988, 2009), Niger (Thebaud and Batterbury 2001), and Ghana (Tonah 2002).  Farmer-pastoralist clashes are destabilizing to these countries politically, socially, and economically.  Similar group dynamics exist in Europe with Roma, an outgroup viewed as culturally, ethnically, and linguistically distinct and apart from the rest of the polity.  Similar conflict dynamics exist between Jews and Arabs, who also conflict over land that both groups claim.  Scholars can learn about intergroup conflict generally from farmer-pastoralist conflict in Nigeria's Middle Belt.

## Intervention: Engaging Communities for Peace in Nigeria

To address farmer-pastoralist conflict, peacebuilding NGO Mercy Corps implemented a four-year, USAID-funded program titled Engaging Communities for Peace in Nigeria (ECPN) in Middle Belt sites embroiled in violent conflict. The main objective of the program was to foster positive contact between farmers and pastoralists, improve attitudes, improve intergroup relations, and ameliorate conflict.  Mercy Corps implemented the project in two Middle Belt states, Benue and Nassarawa, which have been focal points for farmer-pastoralist conflict. 

The intervention formed mixed-group committees with equal numbers of farmers and pastoralists and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.  It started with separate farmer and pastoralist community meetings to avoid negative contact experiences.  These intra-community meetings eventually built up to joint decision-making meetings with the two groups together.  Each joint project committee included an even number of farmers and pastoralists, as well as women and youth representatives, and totaled between 12 and 15 members. Each committee received two grants, one for quick-impact projects, of approximately \$2,000, and one for joint projects, of approximately \$25,000.

The quick-impact projects were conceived as a trust-building initiative, intended to let community members see that cooperation was possible. Projects, managed by both farmers and pastoralists, included hand pumps; construction or rehabilitation of market stalls, schools, and health centers; and construction of fences along grazing routes to protect farmlands and avoid accidental crop damage. The joint economic development projects aimed to address an underlying issue related to the conflict: sharing of resources that impact livelihoods. Pollution of water, affecting both farming and livestock, was the primary issue people raised. As a result, each site chose to build a new borehole well, with members of both farmer and pastoralist communities helping to construct the wells.  

To ensure support of authorities, the program involved community leaders from both sides in all aspects of the project.  They were involved in the quick-impact projects and joint economic development projects.  We also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.

<!--chris: nuole comment about this paragraph.  i don't understand the comment. -->
These projects were designed with the conditions of Contact Theory in mind.  Groups (1) cooperated with (2) equal status to achieve (3) shared goals with (4) support of local authorities.  These projects were meant to help the groups solve, through intergroup cooperation, problems relevant to both groups.  This would reveal to groups that they shared many of the same struggles and that cooperation could help them overcome these struggles.  Collectively, these project give groups the opportunity so send costly signals about their willingness to cooperate [@kydd2000trust, @rohner2013war].

In the next section we describe the research design to determine the effects of intergroup contact on intergroup attitudes and behaviors.

*******

<!--
Comes after theory.  Intervention Details moved to design.

## Context Outline

- distirbution of the lands: map that shows the regions: Fulani region, farmer region
- The setting: rural, economic
- the background: these populations used to get along, but population booms and climate change reduce land:people ratio
- The conflict: escalating, burnt village/livestock guard, expulsion
-->

<!--
Dehumanization of killing: 
- Conflicting groups dehumanize the outgroup, meaning that they do not acknowledge the outgroup as fully human [@haslam2014dehumanization; @leyens2007infra; @opotow1990moral; @bandura1999moral].  Dehumanized groups are deemed unworthy of moral considerations; they do not deserve empathy, compassion, or fair treatment.  Along with not extending morality to outgroup members, ingroups often view of the outgroup themselves as immoral -- a group without values who cannot be trusted due to their innate moral deficiencies [@weisel2015ingroup; @parker2013lessons; @brewer1999ingroupOutgroup, p.435].  Killing members of the other group causes further dehumanization.

-->
