---
title: "draft2"
author: "Chris Grady"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Switches order of paragraps.  
    - Say contact works in all these contexts.  
    - Then say mechanisms and my "common thread"/overarching understanding.  
    - Then say we know little about contact in violent contexts & maybe violence prevents contact form working. 
    - Then say reasons for optimism?

# Introduction

How can groups in conflict improve intergroup relations?  Violent group conflict has caused 2 million deaths since the year 2000 [@ucdp], forcibly displaced over 70 million people from their homes in 2018 [@unhcr2019], threatens food supplies in numerous countries [@verwimp2012food], and extracts a psychological toll on participants and victims (Schomerus and Rigterink 2018).  Intergroup animosity perpetuates conflict long after the original grievance is immaterial or forgotten [@mcdonnel2017graze; @deutsch1973resolution; @tajfel1979integrative], so improving intergroup relations is vital to stem the human, economic, social, and psychological costs of violent group conflict.

Scholars and policymakers/practicioners consider cooperative intergroup contact -- contact in which members of two groups work together to achieve common goals -- to be one of the most effective tools for improving intergroup relations.  The hypothesis that cooperative contact improves intergroup relations, known as the contact hypothesis [@allport1954prejudice], motivates many policy interventions, from integrated public housing [@deutsch1951interracial] and college dorms [@marmaros2006friendships] to workplace and school desegregation [@cook1971race; @cook1985experimenting; @rao2019familiarity].  The contact hypothesis also increasingly motivates peacebuilding programs [@ditlmann2017addressing; @lemmer2015can].  Through these types of interventions, intergroup contact has improved relations between white people and black people in the U.S. and South Africa [@marmaros2006friendships; @burns2015interaction; @carrell2015impact], Christians and Muslims in Iraq and Nigeria [@mousa2018overcome; @scacco2018nigeria], Jews and Arabs in Israel/Palestine [@yablon2012we; @ditlmann2016can; @weiss2019curing], and Hindus and Muslims in India [@barnhardt2009near].

Scholars theorize that contact improves attitudes mainly through providing information that dispels stereotypes, increasing empathy and perspective-taking, reducing anxiety about interacting with outgroup members, and making salient a superordinate identity that includes both groups [@pettigrew2008does; @dovidio2017reducing; @broockman2016durably; @gaertner2014reducing; @page2008little].  These mechanisms assume that negative attitudes result from unfamiliarity, and that "familiarity breed[s] liking" [@pettigrew2006meta p.766].  We posit that familiarity through cooperative contact allows groups to identify their latent shared interests.  Shared interests may remain latent when groups hold negative stereotypes about each other, feel anxiety when interacting, cannot see from the perspective of the other side, and do not identify any shared similarities or identities.  Cooperative contact should improve attitudes towards the outgroup when there exists a latent shared interest to make salient.

Despite the success of contact to improve relations in many contexts, scholars know little about the effects of intergroup contact for groups engaged in a violent conflict.  Cooperative intergroup contact has only recently been tested in the field with groups who have a recent history of violence [@paluck2017contact; @lemmer2015can], and never with communities who are perpetrating violence against each other.  Historical and ongoing violence pose the most difficult tests for contact and could interefere with mechanisms through which contact improves relations.  By obscuring shared interests and highlighting and reinforcing group differences, violent conflict could dull, prevent, or even reverse the predicted positive effects of contact.  For these reasons, some scholars believe group reconciliation cannot begin until conlict is resolved [@bar2000intractable].

Even when attitudes change for the individuals involved in intergroup contact, contact can only meaningfully improve group relations if the effects of contact diffuse to group members who do not have direct contact with outgroup members.  Diffusion to other group members occurs in two ways.  First is the knowledge that other ingroup members had positive contact with outgroup members, either through word of mouth or through observing positive intergroup interactions [@wright1997extended].  The second is changing social norms about cross-group interaction [@paluck2009jsp; @christ2014contextual].  But historical and ongoing violence may also prevent the effects of contact from diffusing, even if contact improves attitudes for the individuals involved in contact.  Intergroup animosity may bias perceptions of cross-group interaction and social norms may stay staunchly opposed to intergroup cooperation.

<!--
- Provides example of working together for shared interest.  There exists shared interest: fighting often leaves groups worse off than peace.
- Removes psych barriers to identifying a shared group interest: stereotypes, feelings of threat, lack of empathy, and social categorization, etc...
    - Expected behaviors change attitudes [@van2019actions].  Expectation of working with group motivates individuals to see group more positively [@klein1992motivated].
        - currently not saying anything about this.
    - group pressure to cooperate once it is revelaed that cooperation is in the group's interest.
cooperative contact provides opportunities for each group to see that working together helps them achieve their goals.-->

Despite these reasons for caution, there are reasons to expect cooperative contact to improve intergroup relations even in contexts of ongoing violence.  Contact should improve relations when there exists shared group interests.  Even in contexts of group violence, it is often in each group's shared interest to reach a peaceful compromise because fighting is costly [@fearon1995rationalist].  Cooperative contact to achieve a common goal provides groups with an example of cooperation towards a shared interest, and that experience can make groups imagine future interactions for shared benefit.  Cooperative contact can also remove the psychological barriers to identifying shared interests, such as stereotypes and feelings of threat and anxiety.  Lastly, cooperation in that benefits the group should generate group pressure to cooperate, thus creating cooperative social norms.

To learn about whether cooperative contact can improve intergroup relations amidst violent group conflict, we conducted a field experiment with conflicting farmer and pastoralist communities in Nigeria.  More than an occupational difference, farmers who cultivate crops and pastoralists who graze cattle define a major social cleavage in many parts of the world.  These groups conflict over land rights, which define both of their livelihoods.  Farmer-pastoralist conflict has escalated throughout the Sahel in recent years, and nowhere more than in Nigeria.  The most recent conflict escalation has caused 7,000 deaths from 2014-2019, displaced hundreds of thousands of people from their homes, and costs $13 billion annually in lost economic productivity [@council2019nigeria; @daniel2018anti; @mcdougal2015effect; @nyt2018nigeria].<!--don't need to cite news articles like this. you can give an address / identifier / link /etc in a footnote -->  In our sample, members of each community had been killed by members of the other community within the year before the project began.  Past and present violence, occupational and ethnic differences, and fighting over resources necessary for livelihoods all make this context a hard test for contact theory.  

We randomly assigned communities with ongoing farmer-pastoralist violence to receive a contact-based intervention or serve as a control group.  The intervention formed mixed-group committees and provided them with funds to build infrastructure that would benefit both communities; committees then collaboratively chose and constructed infrastructure projects.^[The communities built boreholes, market stalls, primary health care facilities, etc.]  The program also provided mediation training to each community's leaders and held forums where the groups discussed the underlying drivers of conflict.  To measure the effects of the intervention, we conducted pre- and post-intervention surveys, a post-intervention natural public goods behavioral game,[^PGG] and twelve months of systematic observations in markets and social events during the intervention.

[^PGG]: In a public goods game (PGG), research subjects are given money and told they can keep the money or donate it to a public fund.  Money donated to the public fund is multiplied by some amount and then shared with all subjects.  Our PGG is _natural_ because it was conducted in a natural setting, rather than a lab.  The funding for the PGG came from the National Science Foundation under Grant No. 1656871.

<!-- Findings. -->

We find that the program increased intergroup contact, intergroup trust, and perceptions of physical security.  We see signs of the positive effects in fieldwork as well as in data -- in one of the treatment sites, farmers defended pastoralists from a group of anti-pastoralist vigilantes, rather than assist the vigilantes in removing the pastoralists and claiming their land.  Cooperative contact between some ingroup members and some outgroup members can only meaningfully improve group relations if the effects of contact diffuse to group members who do not have direct contact with outgroup members.  Our results also show that the intervention affected communities as a whole, not just community members directly involved in the intergroup contact.  Individuals who directly engaged in intergroup contact changed the most positively from baseline to endline, but we also observe positive spillovers to group members for whom we did not exogenously increase intergroup contact.

This study expands our knowledge about group conflict in several ways.  First, this study teaches us about the capacity of intergroup contact to improve intergroup relations and reduce conflict.  Peacebuilding organizations implement numerous contact-based interventions in violent contexts each year [@ditlmann2017addressing], but its efficacy to improve intergroup attitudes amid real-world conflict is an open question [@paluck2017contact; @ditlmann2017addressing].  To our knowledge this is the first field experimental test of a contact-based intervention implemented during an active conflict.  The results suggest that contact-based peacebuilding programs can effectively improve relationships between conflicting groups and is especially relevant to conflict resolution in the cases of intergroup and intercommunal conflicts.

Second, we contribute to the literature about informal structures, such as social norms, in solving collective action problems.  Conflict between farmers and pastoralists is a collective action problem in that both groups would be materially better off avoiding violence through compromise and cooperation, but each has the incentive to take advantage of the other.  Individuals within each group face the same dilemma: they prefer a compromise, but their incentives are to free-ride and allow others to bear the cost of compromise.  In rural Nigeria, as with many contexts, no formal institutions exist to encourage cooperation and so groups must develop informal structures to achieve collective action [@ostrom2000collective].  This intervention showed how informal structures to solve collection action problems can naturally develop through repeated intergroup interactions.  Our intervention only engaged a small percentage of each community, yet its effects diffused to other community members.  Creating informal structures that diffuse the attitudinal effects of cooperative contact are a way of scaling up contact-based interventions.^[chris: this paragraph is too long and not focused enough.  Would appreciate comments.]

Third, this paper teaches us about settling disputes between sedentary peoples and nomadic peoples.  Violent conflict between settled peoples and nomadic peoples is on the rise throughout Africa [@hrc2018farmer; @kuusaana2015land; @mwamfupe2015persistence].  This study focuses on the Fulani, the largest semi-nomadic people on Earth [@fulanisize2017].  Their way of life makes them targets for violence throughout Africa.  Along with this conflict in Nigeria, Fulani in Mali have been the targets of violence so severe that researchers at Armed Conflict Location & Event Data Project called it "ethnic cleansing" [@economist2019militias].  Understanding how to prevent violent conflict between Fulani and settled peoples can help prevent violence that targets other nomadic and semi-nomadic peoples, such as the Tuaregs in West Africa, Uyghurs in Central Asia, Kochi in Afghanistan, Khoisan of Southern Africa, and Romani of Europe.  Preventing such violence could help preserve a dying way of life.






