---
title: "Untitled"
author: "Chris Grady"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Order of paragraps.  
    - Say contact works in all these contexts.  
    - Say we don't know about contact in violent contexts.
    - Then say conflict poses difficult challenge because might prevent mechanisms + mechanisms & common thread + why they could be prevented.
    - Then say reasons for optimism?

## R Markdown

Scholars and policymakers/practicioners consider cooperative intergroup contact -- contact in which members of two groups work together to achieve common goals -- to be one of the most effective tools for improving intergroup relations.  The hypothesis that cooperative contact improves intergroup relations, known as the contact hypothesis [@allport1954prejudice], motivates many policy interventions, from integrated public housing [@deutsch1951interracial] and college dorms [@marmaros2006friendships] to workplace and school desegregation [@cook1971race; @cook1985experimenting; @rao2019familiarity].  The contact hypothesis also increasingly motivates peacebuilding programs [@ditlmann2017addressing; @lemmer2015can].  Through these types of interventions, intergroup contact has improved relations between white people and black people in the U.S. and South Africa [@marmaros2006friendships; @burns2015interaction; @carrell2015impact], Christians and Muslims in Iraq and Nigeria [@mousa2018overcome; @scacco2018nigeria], Jews and Arabs in Israel/Palestine [@yablon2012we; @ditlmann2016can; @weiss2019curing], and Hindus and Muslims in India [@barnhardt2009near].

<!--chris: could combine this paragraph with another.  Maybe keep first sentence of firsts paragraph only. -->
Despite these successes, scholars know little about the effects of intergroup contact for groups engaged in a violent conflict.  Cooperative intergroup contact has only recently been tested in the field with groups who have a recent history of violence [@paluck2017contact; @lemmer2015can], and never with communities who are perpetrating violence against each other.  If one of the goals of cooperative contact is to mitigate violent conflict, interventions based on cooperative contact must be tested between groups in a violent conflict.

Historical and ongoing violence poses the most difficult test for contact and could interefere with mechanisms through which contact improves relations. Scholars theorize that contact improves relations mainly through providing information that dispels stereotypes, increasing empathy and perspective-taking, reducing anxiety about interacting with outgroup members, and making salient a superordinate identity that includes both groups [@pettigrew2008does; @dovidio2017reducing; @broockman2016durably; @gaertner2014reducing; @page2008little].  These mechanisms assume that negative attitudes result from unfamiliarity, and that "familiarity breed[s] liking" [@pettigrew2006meta p.766].  We posit that familiarity through cooperative contact allows groups to identify their latent shared interests.  By obscuring shared interests and highlighting and reinforcing group differences, violent conflict could dull, prevent, or even reverse the predicted positive effects of contact.  For these reasons, some scholars believe group reconciliation cannot begin until conlict is resolved [@bar2000intractable].

<!--Removed paragraph here about generalizing good attitudes to other outgroup members; about attitudes needing to diffuse to other ingroup members.  But maybe could re-add.  Attitudes likely to generalize because group affiliation very salient.  Likely to diffuse because benefit at group level.  Moving right to why contact will still work.  Associating cooperation with achieving goals provides motivation to improve attitudes [@klein1992motivated] -->

Reasons for optimism.  Contact should work when there is a latent shared interest to activate.  Mechanisms of contact show how shared interest exists.  Hard to believe there is a shared interest while holding negative stereotypes about the other group, such as their lack of trustworthiness and their ingroup favoritism.  Hard to see a shared interest when interacting with the other group causes anxiety due to feelings of threat.  Hard to see a shared interest when you do not identify any shared identities.

Despite these reasons for caution, there are reasons to expect cooperative contact to improve intergroup relations even in trying circumstances.  A key component of contact theory is the groups working together to achieve a common goal.  Humans are goal-oriented, and cooperative contact provides opportunities for each group to see that working together helps them achieve their goals.  This condition of cooperative contact has been underappreciated.  Gives groups reason to be motivated to like each other.  Economic incentives improve attitudes about peace (Jha and Shayo 2019 - Valuing Peace) and @grady2019contact suggests that cooperative contact most effectively improves attitudes towards the outgroup if the cooperation achieve its objective.  Conflict and a history of violence should not interfere with self- and group-interest.  Conflict hard test for contact, important to stick with Allport's conditions.

Even amid conflict, reasons for optimistm.  The common thread of contact's mechanisms is that they allow the groups to see their shared interest.  When there is a latent shared interest to be activated/made salient, contact helps reveal that latent shared interest.  Violent past and present, group differences, group animosity, Something that group animosity is preventing the groups from seeing.  If contact helps groups overcome stereotypes that the other side is untrustworthy or will always favor its own, then mutual benefits from cooperation becomes possible.