---
title: "Improving Intergroup Relations Amid Group Conflict: An Intergroup Contact Field Experiment in Nigeria - Discussion"
author: "Christopher Grady, Rebecca Wolfe, Danjuma Dawop, and Lisa Inks"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    md_extensions: +autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    number_sections: yes
    pandoc_args:
    - -M
    - secPrefix=\S
    template: ../utils/bowersarticletemplate.latex
  word_document: default
csl: ../utils/american-political-science-review.csl
bibliography: ../utils/cdg_references.bib
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="footnotesize",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132,
  out.width='.9\\textwidth',
  message=FALSE,
  comment=NA)

options(SweaveHooks=list(fig=function(){
			   par(mar=c(3.5, 3, 1.1, 0),
			       pty="s",
			       mgp=c(1.5,0.5,0),
			       oma=c(0,0,0,0))},
			 echo=function(){options(continue=" ") ##Don't show "+" prompts,
			 options(prompt=" ")
			 }),
	digits=4,
	scipen=8,
	width=132
	)
```

This paper provides evidence that intergroup contact can improve intergroup relations, even in dire circumstances.  We tested the effects of a programmatic contact intervention in an active and escalating conflict between farmers and pastoralists in Nigeria.  The extreme violence of this context poses a tough test for contact to improve intergroup relations.  The violence provides grievances that feed outgroup animosity and reinforce group differences, provides social and psychological barriers to improving attitudes, and reinforces the perception that groups' material incentives are opposed.  Despite the difficult context, the program improved intergroup affect, fostered more intergroup contact, and decreased feelings of insecurity in these communities.  Methodologically, this study demonstrates the benefits of measuring outcomes at baseline and endline in a treatment group and in a control group as a means of capturing the secular trend.

We believe the program improved group relations and the prospects for peace because groups shared a latent interest that could be activated by contact.  The shared interest was "latent" because it was not being identified by the groups in conflict.  Cooperative contact helped reveal the latent shared interest to both groups by demonstrating how the groups can work together to achieve a common goal and removing psychological and social barriers to identifying the shared interest.  Contact also provides the groups with opportunities to send costly signals of their intent to cooperate, which are important for intergroup cooperation [@kydd2000trust].  More studies need to be conducted to determine the limits of contact and the conditions under which contact can effectively improve intergroup relations.

This study also points to an opportunity for collaboration between scholars of intergroup contact and scholars of conflict.  These literatures are often concerned with the same end goal -- reducing conflict -- but rarely speak to one another.  Conflict scholars often see conflict as a bargaining problem, and violence as a bargaining failure.  The conflict literature points to a lack of trust as the primary cause of conflict and usually posits a strong third party actor as necessary to guarantee peace.  Intergroup contact research hints that intergroup contact can create cooperative norms and institutions that serve the same function as a strong third party.  Improving relations -- especially improving trust -- through psychological interventions like intergroup contact can help groups overcome commitment problems and reduce the likelihood of violence.

Contact could help establish cooperative norms and institutions in a number of ways.  In our fieldwork, we see evidence that contact strengthened existing conflict resolution structures, like leader arbitration.  The leadership of each group convene with the "plaintiff" and "defendant" to arbitrate cross-group disagreements, such as cows caught grazing on farmland.  Our research partners on the ground noted that these structures became more effective in ECPN communities because pastoralists became more aware of the financial value of the crops destroyed by cows and farmers became more aware of the difficulty of controlling and corralling thousands of cows.^[We are especially grateful to Israel Okpe for his observations about farmer-pastoralist conflict dynamics.]  Contact could also encourage ingroup policing: ingroup members punishing other ingroup members who violate the rights of outgroup members [@fearon1996explaining; @ditlmann2016can].  If groups "punish [their own] miscreants" [@fearon1996explaining, p.722], in a way that is visible to the other side, then the other side does not need to retaliate against the transgression.[^ingroupPolice]  Visible ingroup policing shows each side that the other can be trusted, alleviating commitment problems.

<!--need to merge this better with "what we learn about reducing conflict."  Communal, ethnic, sedentary-nomadic/itinerant. -->
This paper also teaches us about settling disputes between sedentary peoples and semi-nomadic peoples.  Violent conflict between settled peoples and semi-nomadic peoples is on the rise throughout Africa [@hrc2018farmer; @kuusaana2015land; @mwamfupe2015persistence].  This study focuses on the Fulani, the largest semi-nomadic people on Earth [@fulanisize2017].  Their way of life makes them targets for violence throughout Africa.  Along with this conflict in Nigeria, Fulani in Mali have been the targets of violence so severe that researchers at Armed Conflict Location & Event Data Project called it "ethnic cleansing" [@economist2019militias].  Understanding how to prevent violent conflict between Fulani and settled peoples can help prevent violence that targets other nomadic, semi-nomadic, and itinerant peoples, such as the Tuaregs in West Africa, Kochi in Afghanistan, Khoisan of Southern Africa, and Romani of Europe.  Preventing such violence could help preserve a dying way of life.

There remain several opportunities to learn about the effects of contact in conflict environments.  First, this study employed a design to test the hypothesis that contact would improve group relations in an active conflict.  It also provided exploratory evidence of the mechanisms through which contact affects group relations, showing that contact may have worked through increased empathy.  Future studies can bring more causal evidence to the question of _how_ contact improves group relations.  Second, our program was designed, implemented, and randomized at the community-level because conflict between farmers and pastoralists occurs at the community level.  Future studies should randomize individual community members' participation in a contact-based intervention.  Such studies could learn much about the affect of contact on individuals, including the dosage of contact necessary to improve attitudes, as well as how social norms and interpersonal discussion diffuse the positive effects of contact to individuals without outgroup contact.

Third, contact interventions, explicitly or implicitly, involve the groups cooperating to _achieve_ a joint goal.  ECPN was designed to benefit all communities by having the conflicting communities cooperate successfully.  But what if contact is not successful and the goal is not achieved?  Does contact itself still improve attitudes, or does contact work because groups begin to associate cross-group cooperation with good outcomes?  In a similar vein, are Allport's conditions necessary for contact to achieve its aims, or are they only needed insofar as they ensure the intergroup cooperation generates positive outcomes for both groups?  Future studies should determine the necessity of Allport's conditions and attempt to differentiate the fact of contact from the outcomes that group cooperation produces.

<!--

# Key points

- Contact mainly tested in lab between minimally different groups. We tested with groups actively fighting.  Toughest test because these groups have most reasons for animosity, trends/forces driving them apart and pushing them towards conflict.  Despite that, we see many positive effects.
- Importance of cooperation == group benefit?
    - Humans are goal-driven.  In a lab experiment, @grady2019contact suggests that cooperative contact only improves attitudes towards the outgroup if the cooperation achieve its objective.
    - Similar to @kydd costly signal: assure other side that working together will be good. Also applies to indirect contact: have to hear about or observe contact going well to want contact with the other side. @jha2013trade: interethnic trade that benefited both parties created norms of interethnic cooperation; those norms continued to have effects centuries later.  Intergroup contact often entails reciprocal exchanges like trade, which can provide tangible evidence that both groups are materially better off cooperating than fighting [@rohner2013war].
    - Reveal latent shared interests by removing barriers to identifying those interests.  Hard to believe there is a shared interest while holding negative stereotypes about the other group, such as their lack of trustworthiness and their ingroup favoritism.  Hard to see a shared interest when interacting with the other group causes anxiety due to feelings of threat.  Hard to see a shared interest when you do not identify any shared identities.  Contact removes these barriers.


### Challenges == Opportunities

- more field experiments; this is only one.
- randomization at individual-level
- groups equally benefiting from intervention
- vary the mechanisms as much as possible
- systematically vary the benefit received from contact (contact itself or contact's success)

### Other future

- why group status affects impact?  Minority group has lots of experience with majority group?  Culture does not assign negative traits to majority group because "culture" is dictated by majority?


## Discussion

need more field experiments; this is only one.  Contact mainly tested in lab between minimally different groups.

Methodological: "baseline/endline + control group as a means of capturing the secular trend".

Contact and Allport's conditions: maybe not about the conditions, but about beliefs that cooperation/interaction with the outgroup will help individuals achieve their goals.  People are goal-oriented, with material, social/status, psychological/internalized moral, and evolutionary goals. People do things to achieve those goals.  People like things that help them achieve their goals.  If intergroup cooperation leads to positive outcomes, I will do more of it and I will like that group.
Interacting with some other group with equal status == likely that my opinions/desires taken into account, whereas unequal status == my opinions/desires are subordinated.  Institutional support == likely that social norms are on my side.  No institutional support == very possible that social norms are not on my side.  Common goals == group working on something that is good for me and good for them; can trust them to work on it, too.  @grady2019contact suggests that cooperative contact most effectively improves attitudes towards the outgroup if the cooperation achieve its objective.  Economic incentives improve attitudes about peace (Jha and Shayo 2019 - Valuing Peace).


Conclusion/summary: Intergroup contact improves intergroup attitudes.  Could contact-based programs effectively improve attitudes amongst groups in conflict?  Take-away: Evidence that this peacebuilding intervention increased trust between conflicting groups.  And group members feelings of physical security increased.

Further research needed to see if improving relations reduces conflict.  One strand of literature sees conflict as a bargaining problem, and violence as a bargaining failure.  In theory, groups should avoid fighting and reach peaceful solution because fighting is costly.  Yet group conflict is common.  This literature points to a lack of trust as the primary cause of conflict.  Improving relations -- especially improving trust -- can help groups overcome commitment problems and reduce the likelihood of violence.

Bridging formal theory and rationalist perspectives with psychological perspectives.  Thinking about psychological implications on games like bargaining, prisoner's dilemma/collective action problems, stag hunt, and trust/trust + reassurance games.  How do psychological conditions like prejudice change preferences and behavior in these games?  Ostrom called for interdisciplinary work about variables affecting likelihood of collective action [@ostrom2003trust]. Cannot always test these variables in a lab -- groups have histories that create trust and distrust, violence occurs in real world, signals of trust are embedded in and can get dwarfed by wider social contexts, my self-conception as a "nice" person is connected to my real world behavior but maybe not my lab behavior, etc...



Mechanism could be "ability to identify local outgroup from non-local outgroup"?

Farmers arresting livestock guard suggests some level of ingroup policing or of viewing the farmer and pastoralist communities as tied together.


We see more market interactions.  @rohner2013war says trade can increase intergroup trust.  More opportunities to signal trustworthiness in trade.  More opportunities to see benefit from cooperating with the outgroup (Realistic group conflict theory).  

Would this happen without NGO?  Presence of outside group encouraging the interaction surely helps.  But the situations that these programs exogenously introduce are often mimicked and inspired by real-life experiences of villages that did not descend into conflict.  Notable in...[chris: I think cites are all in autesserre2017 foreign affairs.  Stuff about Congo? Resisting War: How Communities Protect Themselves.  ].  This program "randomly assigns" what those villages developed endogenously.

Future: mechanisms and ways to scale up.  Mechanisms could be many things.  Ways to scale up: cannot have every group in conflict meet.  Scale up with contact between key actors that could diffuse the positive effects of contact & change social norms.  Media programs and observational/vicarious contact.

Some mechanisms of intergroup contact theory clearly will not function here.  Reduced outgroup threat (("Sullivan, Pierson, & Marcus, 1982; Gibson, 2006). If citizens perceive or experience threat from an out-group, they are more likely to be intolerant toward that group)".  Ingroup expands to include outgroup -- no way.  Empathy yes.  Belief that working together will benefit us == yes.

Other Mechanisms: assist intergroup bargaining with opportunities for costly signaling, increased trust.  Increase ingroup policing.  Increase social norms against intergroup violence.  Change interpersonal attitudes?

An important question is scaling intergroup contact to larger conflicts.  Intergroup contact is unlikely to deter violence between groups involved in large-scale ethnic war where opposing armies commit atrocities, for example.  It's also unlikely to naturally occur between groups with limited contact to each other, or for people who consciously select out of intergroup contact situations.

An attempt to scale-up intergroup contact can use mechanisms of social or vicarious learning.  Research shows that even _observing_ interactions between a member of your group and a member of a disliked group can improve attitudes [@vezzali2014indirect].  Television and radio programs may thus provide intergroup contact between groups with limited exposure to each other [@mazziotta2011vicarious].  @paluck2009jsp used dramatic radio programs to influence attitudes and behaviors in a post-conflict setting to some effect, and a similar strategy could be used in a conflict setting.

From original intro; Future work should further investigate mechanisms through which grassroots strategies can be successful.  Conditions under which different conflict resolution strategies are successful -- when outside actors needed, when groups can be assisted in solving own conflict.

Future work should further investigate mechanisms through which grassroots strategies can be successful.  Conditions under which different conflict resolution strategies are successful -- when outside actors needed, when groups can be assisted in solving own conflict.  Future work should also investigate "scaling up" grassroots interventions, especially those involving intergroup contact.  Not every conflicting group can have contact with the other side.   Contact between key actors that could diffuse the positive effects of contact & change social norms.  And research shows that even _observing_ interactions between a member of your group and a member of a disliked group can improve attitudes [@vezzali2014indirect].  Television and radio programs may thus provide intergroup contact between groups with limited exposure to each other [@mazziotta2011vicarious].

Could be social desirability bias?  Would indicate the program changed social norms -- still valuable.

Could be survey acquiescence bias -- randomization exp "yes" up on all topics.  But other "placebo" outcomes don't go up.

More research needed about using intergroup contact to promote peace between people in conflict.

In many bargaining instances, third-party enforcer is the state (law).

## Limitations

### Small Number of Communities 

The main limitation of the community-level randomized controlled trial is the number of communities we were able to include in the study. With 30 communities clustered at 15 sites, we have relatively low power to detect an effect of ECPN. We try to increase power by testing multiple hypotheses simultaneously (following Caughey, Dafoe, and Seawright 2017) and by using inverse-covariance-weighted outcome indices,  which should measure our outcomes of interest more precisely than indices constructed using other methods.

### Self-Selection at the Individual Level 

We also initially planned to randomize participation on ECPN committees within intervention communities. However, as discussed above, we had low compliance with the individual-level randomization. As a result, many of the people on the committees self-selected into participation. If we see positive change among committee participants, therefore, it is possible that the type of people who participated would have changed more positively even without ECPN, making it difficult to attribute the change to ECPN. It is also possible that ECPN is effective only on the type of people who elected to participate and would not be as effective on people less interested in the program, making it difficult to generalize the effects of ECPN to the wider population in these areas.

We try to address these concerns in three ways. First, we illustrate that the respondents we resurveyed are not statistically different from baseline respondents on baseline measures. Since the people we resurveyed are an as-if-random sample of all baseline respondents, effects we see in this sample should generalize to other respondents. Second, we demonstrate that on most measures, there are no measurable baseline differences between direct participants, indirect participants, and controls. When there are differences, the control sites start out more positively than intervention sites, which would make it more difficult for us to see an effect (i.e., the differences work against us). Third, we present evidence that these groups do not differ in their baseline-to-endline changes on two placebo outcomes,  suggesting that they have similar trajectories in the absence of ECPN. The results of these balance and placebo tests are presented in Appendix 4. 

### Displacement

An additional limitation of both analyses was the significant displacement in Benue state at the time of the endline. Widespread violence between farmers and pastoralists had forced many of the communities in Benue to flee to safer locations. While we chose randomly among the people we could find, we do not know whether the community members we could locate were somehow different from the broader population in these communities.  Appendix 1 presents evidence that on measured variables, resurveyed respondents in the individual-level analysis are representative of all people from the baseline; we are not able to conduct a similar analysis with the community-level sample. In the discussion section, we provide further explanations for how the interpretation of our results would change if our sample is unrepresentative due to displacement. 

### Program Adaptations

Finally, due to the fluid nature of conflict dynamics and the need to adapt the program when necessary, we were not able to maintain separation between intervention and control sites (i.e., there was contamination). For example, the team conducted an intercommunity peace forum in one intervention site, but community leaders requested that leaders from a neighboring site—which happened to be a control site—attend the forum because of a recent conflict event that had spread across the area. The program team decided to risk contamination of the research by including the control site in that one forum, for the sake of the program’s success. This type of contamination was limited as much as possible, and to the extent that it may affect results of the study, it would attenuate the results, working against our hypotheses rather than in favor of them. 

-->



# References
